### ISSUE TITLE
The plan on how to import, develop, test and release charts

### ISSUE THREAD

**Issue by rimusz** [jfrog/charts#1]

**Comment by eldada** [comment]
@rimusz , if we use `--no-install`, do we sill need to install **minikube**?

**Comment by rimusz** [comment]
we can skip minikube and do all in jenkins, but I like to run it in minikube `chart_test.sh --no-install` so the linting is done by travisci.
then jenkins with `chart_test.sh --no-lint` will install/test/remove charts on out k8s cluster

**Comment by rimusz** [comment]
but if we encounter problems of integrating travisci + jenkins, then we can set `chart_test.sh` full testing in jenkins only

**Comment by rimusz** [comment]
we can close this one

**Comment by jainishshah17** [comment]
@rimusz @eldada If it's working with forks then we can close this.
