### ISSUE TITLE
artifactory-nfs-pvc.yaml should use ReadWriteMany instead of ReadWriteOnce

### ISSUE THREAD

**Issue by TJM** [jfrog/charts#1019]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
```
$ helm version
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

```
$ k version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:50:54Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
artifactory-ha (maybe others)

**What happened**:
The artifactory PV is created as RWO (ReadWriteOnce)

**What you expected to happen**:
It should be created as RWX (ReadWriteMany)

**How to reproduce it** (as minimally and precisely as possible):
deploy with nfs

**Anything else we need to know**:
Likely not, pretty simple change

**Comment by chukka** [comment]
@TJM Thanks for reporting ! Would you mind raising a PR with this change for artifactory-ha chart ?

**Comment by gitta-jfrog** [comment]
Not planned, If needed - customers can use create PersistentVolumeClaim and to use customVolumeMounts
