### ISSUE TITLE
[pipelines] Headless Service doesn't work when of type NodePort

### ISSUE THREAD

**Issue by dhdersch** [jfrog/charts#1022]
**Is this a BUG REPORT or FEATURE REQUEST?** BUG REPORT

**Version of Helm and Kubernetes**: 

Helm: v3.2.3
Kubernetes: 

```
dhdersch@MTL-2N7Q9Y2:~/repos/jfrog$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T11:44:51Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.9-gke.6", GitCommit:"14bc8ad5f8c245f1240a8e4eab128c4d51bfeffe", GitTreeState:"clean", BuildDate:"2020-05-30T02:07:03Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: `center/jfrog/pipelines          1.3.4           1.6.2           A Helm chart for JFrog Pipelines  `

**What happened**: I am using the GKE Ingress to route traffic. One of the requirements is that the services it routes to need to be of type `NodePort` and not `ClusterIP`. However, if I set the services for 

* `--set pipelines.api.service.type=NodePort`
* `--set pipelines.www.service.type=NodePort`
* `--set rabbitmq.service.type=NodePort`

Then I get the following error when running `helm install`:

```
Error: Service "pipelines-pipelines-services-headless" is invalid: [spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP', spec.ports[1].nodePort: Forbidden: may not be used when `type` is 'ClusterIP']
```

Perhaps the headless service is not actually needed in this case?

**What you expected to happen**: I expect the helm install command to work

**How to reproduce it** (as minimally and precisely as possible): Described above.

**Anything else we need to know**: I don't think so. This should be a pretty simple fix. Let me know if anything else is needed.

**Comment by rimusz** [comment]
fix in #1026
