### ISSUE TITLE
Metadata service not connecting to AWS RDS database instance

### ISSUE THREAD

**Issue by jdecarvalho** [jfrog/charts#1028]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:

Helm: 3.0.3

Kubernetes: Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}

AWS EKS Platform version eks.2

**Which chart**:
JFrog Artifactory 10.0.5: https://charts.jfrog.io/artifactory-10.0.5.tgz

**What happened**:
Artifactory metadata service cannot connect to AWS RDS PostgresQL database instance.  I see the following error in the logs:

```
2020-07-20T21:38:35.634Z [34;1m[jfmd ][0m [34m[INFO ][0m [2ec0e610b762c334] [database_bearer.go:84         ] [main                ] - Connecting to (db config: {postgresql user='<REDACTED>' password='***' dbname=artifactory host=artifactory.cluster-<REDACTED>.us-east-1.rds.amazonaws.com port=5432 sslmode=disable}) [database]
2020-07-20T21:38:35.641Z [34;1m[jfmd ][0m [31;1m[ERROR][0m [2ec0e610b762c334] [database_bearer.go:68         ] [main                ] - Could not initialize database (db config: {postgresql user='<REDACTED>' password='***' dbname=artifactory host=artifactory.cluster-<REDACTED>.us-east-1.rds.amazonaws.com port=5432 sslmode=disable}): error connecting to database
jfrog.com/metadata/services/common/db.(*databaseBearer).init
	/src/jfrog.com/metadata/services/common/db/database_bearer.go:114
jfrog.com/metadata/services/common/db.NewDatabaseBearer
	/src/jfrog.com/metadata/services/common/db/database_bearer.go:66
main.main
	/src/jfrog.com/metadata/metadata.go:38
runtime.main
	/src/runtime/proc.go:203
runtime.goexit
	/src/runtime/asm_amd64.s:1373
goroutine 1 [running]:
runtime/debug.Stack(0x38, 0xc00061ed80, 0xc00000e9c0)
	/src/runtime/debug/stack.go:24 +0x9d
jfrog.com/jfrog-go-commons/pkg/log.(*standardLogger).Panicfc(0xc000621440, 0x166e420, 0xc0006ff110, 0x13eb133, 0x32, 0xc00000e9c0, 0x2, 0x2)
	/src/jfrog.com/go-commons/pkg/log/standard_logger.go:42 +0x6a
jfrog.com/metadata/services/common/db.NewDatabaseBearer(0x166e420, 0xc0006ff110, 0x166f220, 0xc000109d60, 0x1673460, 0xc0001f17c0, 0x1666260, 0xc0000be060, 0x16489c0, 0xc000621410, ...)
	/src/jfrog.com/metadata/services/common/db/database_bearer.go:68 +0x2d4
main.main()
	/src/jfrog.com/metadata/metadata.go:38 +0x5b7
 [database]
panic: Could not initialize database (db config: {postgresql user='<REDACTED>' password='***' dbname=artifactory host=artifactory.cluster-ca714ef9zjp9.us-east-1.rds.amazonaws.com port=5432 sslmode=disable}): error connecting to database
jfrog.com/metadata/services/common/db.(*databaseBearer).init
	/src/jfrog.com/metadata/services/common/db/database_bearer.go:114
jfrog.com/metadata/services/common/db.NewDatabaseBearer
	/src/jfrog.com/metadata/services/common/db/database_bearer.go:66
main.main
	/src/jfrog.com/metadata/metadata.go:38
runtime.main
	/src/runtime/proc.go:203
runtime.goexit
	/src/runtime/asm_amd64.s:1373
goroutine 1 [running]:
runtime/debug.Stack(0x38, 0xc00061ed80, 0xc00000e9c0)
	/src/runtime/debug/stack.go:24 +0x9d
jfrog.com/jfrog-go-commons/pkg/log.(*standardLogger).Panicfc(0xc000621440, 0x166e420, 0xc0006ff110, 0x13eb133, 0x32, 0xc00000e9c0, 0x2, 0x2)
	/src/jfrog.com/go-commons/pkg/log/standard_logger.go:42 +0x6a
jfrog.com/metadata/services/common/db.NewDatabaseBearer(0x166e420, 0xc0006ff110, 0x166f220, 0xc000109d60, 0x1673460, 0xc0001f17c0, 0x1666260, 0xc0000be060, 0x16489c0, 0xc000621410, ...)
	/src/jfrog.com/metadata/services/common/db/database_bearer.go:68 +0x2d4
main.main()
	/src/jfrog.com/metadata/metadata.go:38 +0x5b7


goroutine 1 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1(0xc0003b6500, 0x4e1)
	/pkg/mod/github.com/rs/zerolog@v1.18.0/log.go:338 +0x4f
github.com/rs/zerolog.(*Event).msg(0xc00007e2a0, 0xc0003b6500, 0x4e1)
	/pkg/mod/github.com/rs/zerolog@v1.18.0/event.go:146 +0x200
github.com/rs/zerolog.(*Event).Msgf(0xc00007e2a0, 0xc000042ac0, 0x35, 0xc00061edc0, 0x3, 0x4)
	/pkg/mod/github.com/rs/zerolog@v1.18.0/event.go:126 +0x83
jfrog.com/jfrog-go-commons/pkg/log.(*standardLogger).logMessage(0xc000621440, 0x166e420, 0xc0006ff110, 0xc00007e2a0, 0xc000042ac0, 0x35, 0xc00061edc0, 0x3, 0x4)
	/src/jfrog.com/go-commons/pkg/log/standard_logger.go:61 +0x197
jfrog.com/jfrog-go-commons/pkg/log.(*standardLogger).Panicfc(0xc000621440, 0x166e420, 0xc0006ff110, 0x13eb133, 0x32, 0xc00061edc0, 0x3, 0x4)
	/src/jfrog.com/go-commons/pkg/log/standard_logger.go:43 +0x1df
jfrog.com/metadata/services/common/db.NewDatabaseBearer(0x166e420, 0xc0006ff110, 0x166f220, 0xc000109d60, 0x1673460, 0xc0001f17c0, 0x1666260, 0xc0000be060, 0x16489c0, 0xc000621410, ...)
	/src/jfrog.com/metadata/services/common/db/database_bearer.go:68 +0x2d4
main.main()
	/src/jfrog.com/metadata/metadata.go:38 +0x5b7
```

I've verified that the database itself is up and running, and accessible from the EKS subnet.  The artifactory service, which uses JDBC for database connections seems to have worked fine.  The database tables are created by it, and some data is even populated at startup.  I also see the following logs for the working Artifactory service:

```
2020-07-20T21:38:29.143Z [1;32m[jfrt ][0;39m [34m[INFO ][0;39m [f9aa2cdf7b7f6c69] [d.i.DbInitializationManager:47] [ocalhost-startStop-2] - Initializing DB Schema initialization manager
2020-07-20T21:38:29.144Z [1;32m[jfrt ][0;39m [34m[INFO ][0;39m [f9aa2cdf7b7f6c69] [.i.DbInitializationManager:174] [ocalhost-startStop-2] - Database: PostgreSQL 10.7. Driver: PostgreSQL JDBC Driver 42.2.12 Pool: postgresql
2020-07-20T21:38:29.145Z [1;32m[jfrt ][0;39m [34m[INFO ][0;39m [f9aa2cdf7b7f6c69] [.i.DbInitializationManager:177] [ocalhost-startStop-2] - Connection URL: jdbc:postgresql://artifactory.cluster-<REDACTED>.us-east-1.rds.amazonaws.com:5432/artifactory
2020-07-20T21:38:29.514Z [1;32m[jfrt ][0;39m [34m[INFO ][0;39m [f9aa2cdf7b7f6c69] [d.i.DbInitializationManager:68] [ocalhost-startStop-2] - ***Creating database schema***
2020-07-20T21:38:30.430Z [1;32m[jfrt ][0;39m [34m[INFO ][0;39m [f9aa2cdf7b7f6c69] [d.i.DbInitializationManager:71] [ocalhost-startStop-2] - ***Database schema created***
2020-07-20T21:38:30.431Z [1;32m[jfrt ][0;39m [34m[INFO ][0;39m [f9aa2cdf7b7f6c69] [d.i.DbInitializationManager:51] [ocalhost-startStop-2] - DB Schema initialization manager initialized
2020-07-20T21:38:30.437Z [1;32m[jfrt ][0;39m [34m[INFO ][0;39m [f9aa2cdf7b7f6c69] [SchemaInitializationManager:48] [ocalhost-startStop-2] - Initializing Post-DB initialization manager
```

**What you expected to happen**:
The metadata service should connect to the database correctly.

**How to reproduce it** (as minimally and precisely as possible):
I've attached the [system.yaml](https://github.com/jfrog/charts/files/4963765/system.yaml.txt) file I used.  Note that I've also tried setting just about every imaginable config option to try to get this to work.  All the different options I tried are also in the file, commented out.

Also attached is the Kubernetes pod ([pod.log](https://github.com/jfrog/charts/files/4954716/pod.log)), service ([service.log](https://github.com/jfrog/charts/files/4954719/service.log)), and statefulset ([statefulset.log](https://github.com/jfrog/charts/files/4954720/statefulset.log)) configurations.  And of course the full Artifactory logs ([artifactory.log](https://github.com/jfrog/charts/files/4954715/artifactory.log)).

**Anything else we need to know**:

We are using Istio on top of AWS EKS.  We don't believe that this is the cause of the problem, since the Artifactory JDBC connection works fine from the same Kubernetes Pod.  It's just the metadata service that is having issues currently.

The remainder of the deployment seems to continue without issues as far as the logs are concerned, but accessing the Console URL gives us a 503 error, attached to this ticket here: [request.txt](https://github.com/jfrog/charts/files/4954717/request.txt)

Thank you for your time and help.

-Juliano DeCarvalho
Infrastructure Architecture

**Comment by chukka** [comment]
@jdecarvalho  Can you please share system.yaml file (I think you missed to attach the file) to debug further

**Comment by jdecarvalho** [comment]
My apologies.  GitHub apparently doesn't support files with the `.yaml` extension.  I've updated the ticket above.

**Comment by chukka** [comment]
@jdecarvalho  Can you  try setting below values in values.yaml (replace all **database_** values with your values)
```
postgresql:
  enabled:false
database:
  type: postgresql
  driver: org.postgresql.Driver
  url: 'jdbc:postgresql://<database_host>:5432/<database_name>'
  user: <database_username>
  password: <database_password>
```
**Note :** No need to edit systemYaml section in values.yaml

**Comment by jdecarvalho** [comment]
When I use that particular configuration, some parts of the log (lines 94-98) refer to the PostGresQL config, while others refer to either derby (lines 192-205), or to sqlite (line 257).  New attachments:

[artifactory.log](https://github.com/jfrog/charts/files/4974378/chukka-1.log)
[system.yaml](https://github.com/jfrog/charts/files/4974380/chukka-1.system.yaml.txt)

**Comment by chukka** [comment]
@jdecarvalho It seems like you have added it in systemyaml which is wrong . I meant above [mentioned values](https://github.com/jfrog/charts/issues/1028#issuecomment-662818194) need to be added in values.yaml ( sample attached) which internally generates systemyaml (as a secret)
[values.yaml.txt](https://github.com/jfrog/charts/files/4974764/values.yaml.txt) 

Generated systemyaml will look like below ( database section will be under `shared` ) . Please verify 

```
shared:
  ...
  database:
    type: postgresql
    driver: org.postgresql.Driver
    url: xxx
    user: xxx
    password: xxx
```

**Comment by chukka** [comment]
@jdecarvalho  you can refer this [blog](https://itsmetommy.com/2020/02/15/jfrog-artifactory-ha-on-gke-with-google-cloud-storage-google-sql/) - FYI, this is on GKE

**Comment by jdecarvalho** [comment]
Sorry for the confusion.  Unfortunately, what you are proposing is exactly what I did before opening this ticket.  Here is the [values.yaml](https://github.com/jfrog/charts/files/4983285/chukka2.values.yaml.txt) file with the requested values set directly, here is the generated [system.yaml](https://github.com/jfrog/charts/files/4983284/chukka2.system.yaml.txt) file, and here is the [artifactory.log](https://github.com/jfrog/charts/files/4983283/chukka2.log) with the same error as on the first post in this thread.

I'll look into the blog post to figure out if I'm missing something.

**Comment by jdecarvalho** [comment]
I also tried to use the configuration found in the above blog where they use `database.secrets.[url|user|password]` instead of `database.[user|password]`, and have gotten the same exact metadata database connection error as before.

**Comment by chukka** [comment]
@jdecarvalho I suspect  issue is with postgresql version 10.7 you are using - can you please upgrade to latest `10.x` - 10.13 and try this ( we have seen some internal issues with postgres version < 10.13)

If it doesn't work  - Can you please create a formal ticket via JFrog Support Channel to have sessions to look at your instance and provide the right guidance - that gives support with SLA. https://jfrog.com/support/

**Comment by jdecarvalho** [comment]
JFrog support was able to help me on this.

For posterity, the JDBC connection defaults to SSL being enabled, while the metadata service defaults to SSL being disabled.  Since our network only allows SSL communications, the metadata database connection was failing.

The fix was to override the metadata database connection string by following [this post](https://jfrog.com/knowledge-base/metadata-service-troubleshooting/), at section #2, and removing the `sslmode=disable` flag.  My system.yaml then looks like this:

```
    metadata:
      database:
        maxOpenConnections: {{ .Values.metadata.database.maxOpenConnections }}
        url: "go:user='<DB_USER>' password='<DB_PSWD>' dbname=artifactory host=<DB_HOST> port=5432"

```

**Comment by chukka** [comment]
@jdecarvalho  Glad that we were able to resolve your issue 👍 . Thanks for sharing the info

**Comment by chukka** [comment]
Closing this issue
