### ISSUE TITLE
Pods never come up

### ISSUE THREAD

**Issue by MrAmbiG** [jfrog/charts#1029]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
1.17. Installed via RKE, on prem.

**Which chart**:
helm 3

**What happened**:
```helm upgrade --install artifactory-ha --set artifactory.masterKey="aaaaaaa" --namespace artifactory-ha center/jfrog/artifactory-ha``` This is the simplest installation you have.

The primary and member pods never come up but stay at 0/1. Since they don't come up I can't check logs for them but only describe the pods.
```
artifactory-ha-artifactory-ha-member-0    0/1     Init:1/5   0          3m35s
artifactory-ha-artifactory-ha-primary-0   0/1     Running    0          3m35s
artifactory-ha-nginx-6b88887bf5-fcr66     0/1     Running    0          3m35s
artifactory-ha-postgresql-0               1/1     Running    0          3m35s
```

We have a default on prem storage class.
**What you expected to happen**:
running pods must be 1/1.

**How to reproduce it** (as minimally and precisely as possible):
`helm upgrade --install artifactory-ha --set artifactory.masterKey="aaaaaaa" --namespace artifactory-ha center/jfrog/artifactory-ha`

**Anything else we need to know**:
Apparently when I describe the member pod it says it is waiting for primary and when I describe the [kubectl describe pod ....] it says 
```
Normal   Created           13m                   kubelet, 10.219.55.110  Created container artifactory-ha
  Normal   Started           13m                   kubelet, 10.219.55.110  Started container artifactory-ha
  Warning  Unhealthy         10m (x9 over 11m)     kubelet, 10.219.55.110  Readiness probe failed: Get http://10.42.209.119:8082/router/api/v1/system/health: dial tcp 10.42.209.119:8082: connect: connection refused
  Warning  Unhealthy         4mneworigins (x19 over 10m)  kubelet, 10.219.55.110  Liveness probe failed: Get http://10.42.209.119:8082/router/api/v1/system/health: dial tcp 10.42.209.119:8082: connect: connection refused
```

**Comment by chukka** [comment]
@MrAmbiG  if I understand correctly, you are using Rancher ? masterKey should be  `-hex 32` implies 64 characters - you can refer [here](https://github.com/jfrog/charts/blob/master/stable/artifactory-ha/README.md#create-a-unique-master-key) and try again

**Comment by chukka** [comment]
@MrAmbiG  is this still an issue ? if not please mark this issue as closed
