### ISSUE TITLE
custom logback.xml does not get copied to member nodes 

### ISSUE THREAD

**Issue by jaymalasinha** [jfrog/charts#1037]
**Is this a request for help?**:
yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
% helm version
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

% kubectl version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:

artifactory-ha chart version 3.0.1

**What happened**:
When I added a custom logback.xml file as descibed in "Create a config map with your logback.xml configuration." https://hub.helm.sh/charts/jfrog/artifactory-ha/3.0.1

**What you expected to happen**:
Apply the custom logback.xml to both primary and member nodes, but the configuration is copied only on the primary node and not on the member node

**How to reproduce it** (as minimally and precisely as possible):
Create a helm release without he custom logback.xml first and apply.  It will have both primary and member nodes running with the default logback.xml.  Then add a  custom logback.xml file as descibed in "Create a config map with your logback.xml configuration."  from https://hub.helm.sh/charts/jfrog/artifactory-ha/3.0.1 and apply the helm release.

**Anything else we need to know**:

**Comment by chukka** [comment]
@jaymalasinha can you share the reproducible  steps (actual helm commands + values.yaml with `custom logback.xml` configuration)

**Comment by jaymalasinha** [comment]
@chukka Sure here are the detailed steps to recreate the issue:

% kubectl create ns artifactory-ha1

% cat kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: artifactory-ha1
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: reaper-json-config
    files:
      - "configs/reaper.json"
  - name: logback-xml-config
    files:
      - "configs/logback.xml"

% kubectl -n artifactory-ha1 apply -k .
configmap/logback-xml-config created
configmap/reaper-json-config created

% cat configs/reaper.json
{
  "artifact_reap_schedule": "0 0 7 * * ?",
  "empty_folder_reap_schedule": "0 30 0/1 * * ?",
  "repo_mapping":{
    "stable-local": {
      "expireOlderThan": 262080
    },
    "unstable-local": {
      "expireOlderThan": 10080
    }
  }
}

[logback.xml.zip](https://github.com/jfrog/charts/files/4990553/logback.xml.zip)


% cat values.yaml
artifactory:
    copyOnEveryStartup:
      - source: /tmp/artifactory-reaper-json/reaper.json
        target: etc/artifactory/
      - source: /tmp/artifactory-logback-xml/logback.xml
        target: etc/artifactory/
    customVolumeMounts: |
      - name: reaper-json
        mountPath: /tmp/artifactory-reaper-json/
      - name: logback-xml
        mountPath: /tmp/artifactory-logback-xml/
    customVolumes: |
      - name: reaper-json
        configMap:
          name: reaper-json-config
      - name: logback-xml
        configMap:
          name: logback-xml-config

% helm upgrade --install artifactory-ha --set artifactory.node.replicaCount=1,artifactory.masterKey=${MASTER_KEY} --namespace artifactory-ha1 jfrog/artifactory-ha -f values.yaml

% helm list
NAME          	NAMESPACE      	REVISION	UPDATED                             	STATUS  	CHART                	APP VERSION
artifactory-ha	artifactory-ha1	1       	2020-07-28 15:24:37.764878 -0400 EDT	deployed	artifactory-ha-3.0.11	7.6.3

% kubectl -n artifactory-ha1 get pods
NAME                                      READY   STATUS    RESTARTS   AGE
artifactory-ha-artifactory-ha-member-0    1/1     Running   0          4m
artifactory-ha-artifactory-ha-primary-0   1/1     Running   0          4m
artifactory-ha-nginx-c5c658ddf-pcd4l      1/1     Running   0          4m
artifactory-ha-postgresql-0               1/1     Running   0          4m

% kubectl -n artifactory-ha1 exec -it artifactory-ha-artifactory-ha-primary-0 -- bash

artifactory@artifactory-ha-artifactory-ha-primary-0:/opt/jfrog/artifactory$ mount |grep logback
/dev/vda1 on /tmp/artifactory-logback-xml type ext4 (ro,relatime)

artifactory@artifactory-ha-artifactory-ha-primary-0:/opt/jfrog/artifactory$ ls -l var/etc/artifactory/logback.xml
-rw-r--r--    1 artifact artifact     13209 Jul 28 19:40 var/etc/artifactory/logback.xml

**As you can see in the following command the custom logback.xml is copied on the primary node**

artifactory@artifactory-ha-artifactory-ha-primary-0:/opt/jfrog/artifactory$ grep Reaper var/etc/artifactory/logback.xml
    <logger name="Reaper" level="info"/>

artifactory@artifactory-ha-artifactory-ha-primary-0:/opt/jfrog/artifactory$ exit

% kubectl -n artifactory-ha1 exec -it artifactory-ha-artifactory-ha-member-0 -- bash
artifactory@artifactory-ha-artifactory-ha-member-0:/opt/jfrog/artifactory$ mount |grep logback
/dev/vda1 on /tmp/artifactory-logback-xml type ext4 (ro,relatime)
artifactory@artifactory-ha-artifactory-ha-member-0:/opt/jfrog/artifactory$ ls -l var/etc/artifactory/logback.xml
-rw-r-----    1 artifact artifact     13168 Jul 28 19:42 var/etc/artifactory/logback.xml

**As you can see in the following command the custom logback.xml is not copied on the member node**

artifactory@artifactory-ha-artifactory-ha-member-0:/opt/jfrog/artifactory$ grep Reaper var/etc/artifactory/logback.xml
artifactory@artifactory-ha-artifactory-ha-member-0:/opt/jfrog/artifactory$

**Comment by chukka** [comment]
@jaymalasinha  Thanks for reporting , Looks like `copyOnEveryStartup` only runs on the master node , we are planning to support `copyOnEveryStartup` on member nodes in upcoming chart releases .

 Feel free to raise a pull request, it will be the best way to make sure your issue gets in the fastest way.
