### ISSUE TITLE
[artifactory-ha] Add support for Artifactory encryption key provisioning

### ISSUE THREAD

**Issue by somaritane** [jfrog/charts#1055]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
Helm: v3.2.0,
Kubernetes: v1.15.3

**Which chart**:
artifactory-ha

**What happened**:

We're looking for possibility to bootstrap Artifactory initial configuration while deploying `artifactory-ha` chart to our k8s cluster.

`artifactory-ha` helm chart supports this with [ConfigMap](https://github.com/jfrog/charts/tree/master/stable/artifactory-ha#bootstrapping-artifactory-configuration) for global and security configuration descriptors.

However there is no possibility to pass [Artifactory Encryption Key](https://www.jfrog.com/confluence/display/JFROG/Key+Encryption) during `artifactory-ha` chart deployment, therefore new encryption key is generated automatically and keys and passwords provided in global config and security descriptors are rendered obsolete.

**What you expected to happen**:

We would like to be able to wire Artifactory encryption key during chart deployment as k8s Secret, same way like it's done for Artifactory admin user and [license](https://github.com/jfrog/charts/tree/master/stable/artifactory-ha#kubernetes-secret).

**Comment by lindhe** [comment]
Definitely an attractive feature!

It seems very easy (just sending a POST request to the `/api/system/encrypt` endpoint), so I would assume this could be done by an init container...

**Comment by chukka** [comment]
@somaritane can you confirm if you are using artifactory 7.x or 6.x ?

**Comment by gitta-jfrog** [comment]
artifactory.key is not relevant anymore.
