### ISSUE TITLE
Postgres dependency chart version has pod label bug

### ISSUE THREAD

**Issue by cheries** [jfrog/charts#1065]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): 
BUG

**Version of Helm and Kubernetes**:
Helm - v3.1.1
K8 - v1.17.0

**Which chart**:
Artifactory HA v3.0.5

**What happened**:
Added a label to postgresql.master.podLabels and got the following error:
`Error: YAML parse error on artifactory-ha/charts/postgresql/templates/statefulset.yaml: error converting YAML to JSON: yaml: line 28: mapping values are not allowed in this context`

**What you expected to happen**:
No Error and a label to be added to the postgresql pod.

**How to reproduce it** (as minimally and precisely as possible):
Add any label to postgresql.master.podLabels

**Anything else we need to know**:
I tested with the v8.7.3 postgresql chart by itself and it gets the same error. The latest version of the postgresql chart, v9.1.4, does not get the error.

**Comment by chukka** [comment]
@cheries Looks like a bug  is with `postgresql` subchart . We have pending PR with postgresql 9.x  update.

**Comment by chukka** [comment]
@cheries  fixed with #1078
