### ISSUE TITLE
Remove runAsUser and fsGroup

### ISSUE THREAD

**Issue by caggles** [jfrog/charts#1075]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature Request

As per ticket #139759 from support.

When running the helm chart, the following lines are show up, no matter what I do:

```
      securityContext:
         runAsUser: 1030
         fsGroup: 1030
```
They show up twice in the resulting manifest.

This is not something that we can do in Openshift - you cannot runAsUser. Removing them is necessary to have the pod even spin up. There is no way to do this using helm values (that I have been able to find). Please add an option to remove these lines.

**Comment by peters95** [comment]
@caggles please look at the openshift helm charts here -> https://github.com/jfrog/JFrog-Cloud-Installers/tree/master/Openshift4/helm

**Comment by caggles** [comment]
Hey! Thanks a lot for the change to allow securityContext to be removed from the artifactory-ha statefulset with the new flag - it works like a charm. It would be amazing if this change were also made to the xray statefulset as well!
