### ISSUE TITLE
Question regarding upgrade strategy

### ISSUE THREAD

**Issue by erick-duran-tfs** [jfrog/charts#1088]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Question

**Version of Helm and Kubernetes**:
Helm 3.2.4
Kubernetes 1.15.11

**Which chart**:
Artifactory HA

**What happened**:
When performing upgrades of a HA cluster with just the primary and one member node, the deployment always terminates both the primary and member pods before deploying the new pods.

**What you expected to happen**:
Wait for new pod before terminating both.

**How to reproduce it** (as minimally and precisely as possible):
Deploy Artifactory HA with 1 member and 1 primary, then perform an upgrade with changes to the Artifactory nodes.

**Anything else we need to know**:
My question is:
Is there any way to prevent this from happening without having to scale up first to more nodes and then scaling down? We have only 2 licenses available for this specific platform deployment, and we want to avoid downtime.

**Comment by chukka** [comment]
@erick-duran is this still an issue , now Artifactory chart supports HA too, please try and share feedback

**Comment by erick-duran** [comment]
Hey @chukka, yes I noticed that, is there any guidance on how to move from the old primary setup to the new member-only based? (e.g. how to clear the pending artifacts for upload when you use a cloud provider as the storage backend).
