### ISSUE TITLE
support different readiness probe pathes for artifactory HA member and primary nodes

### ISSUE THREAD

**Issue by thllxb** [jfrog/charts#1090]
**Is this a request for help?**:
yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature request

**Which chart**:
Artifactory HA

**What happened**:
I cannot specify a different readiness probe to member and primary nodes

**What you expected to happen**:
I should be able to specify a different readiness probe to member and primary nodes

**Comment by chukka** [comment]
@thllxb Can you share more details on this use case

**Comment by thllxb** [comment]
What I mean is, https://github.com/jfrog/charts/blob/master/stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml#L990 and https://github.com/jfrog/charts/blob/master/stable/artifactory-ha/templates/artifactory-node-statefulset.yaml#L875 should be able to be sourced from different configurations to have different values.

In my use case, the primary node can have /artifactory/system/ping to be the liveness prob path, but member nodes needs to have /artifactory/webapp/ to avoid being killed before they are licensed.

**Comment by gitta-jfrog** [comment]
Outdated request, Probes were reimplemented.
