### ISSUE TITLE
Cannot use helm --set to add nginx.service.annotations with bool value "true"

### ISSUE THREAD

**Issue by jing-1strategy** [jfrog/charts#1091]
**Version of Helm and Kubernetes**:
Helm version: "v3.3.1"

**Which chart**:
jfrog/artifactory: 10.1.0

**What happened**:

When I'm trying to add below annotation to the nginx service using --set:

service.beta.kubernetes.io/aws-load-balancer-internal: "true"

Then I got error:

Error: YAML parse error on artifactory/templates/nginx-service.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal object into Go struct field .metadata.annotations of type string

Below Command not working:
helm install artifactory --namespace artifactory center/jfrog/artifactory --set nginx.service.annotations.”service\.beta\.kubernetes\.io\/aws-load-balancer-internal”="true"

**What you expected to happen**:
Below annotation should be added to nginx.service.annotations.

service.beta.kubernetes.io/aws-load-balancer-internal: "true"

**How to reproduce it** (as minimally and precisely as possible):
Execute below command on terminal:
helm repo add center https://repo.chartcenter.io
helm install artifactory --namespace artifactory center/jfrog/artifactory --set nginx.service.annotations.”service\.beta\.kubernetes\.io\/aws-load-balancer-internal”="true"

**Anything else we need to know**:

**Comment by chamoisla** [comment]
@jing-1strategy Create a values.yaml file with [this configuration](https://github.com/jfrog/charts/tree/master/stable/artifactory-ha#install-artifactory-ha-with-nginx-and-terminate-ssl-in-nginx-serviceloadbalancer) (using your own ACM certificate arn).

Then install:
```
helm upgrade artifactory --namespace artifactory -f values.yaml center/jfrog/artifactory-ha
```

I'd be curious to find out if your internal load balancer target groups all report back as healthy once deployed?

**Comment by jing-1strategy** [comment]
Thanks @chamoisla, use values.yaml solves this issue.
and all instance in the target group report back healthy.
