### ISSUE TITLE
Configuring UI session timeout through Helm chart

### ISSUE THREAD

**Issue by jdecarvalho** [jfrog/charts#1101]
**Is this a request for help?**:
Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Which chart**:
10.0.14

**Describe *in detail* the feature/behavior/change you'd like to see.**
Hello,

I've gone through the source for chart version 10.0.14, but was unable to find a way to set the UI session timeout for Artifactory.  There is a guide on how to do this on an on-prem Artifactory deployment, found here https://jfrog.com/knowledge-base/how-to-set-artifactory-ui-session-timeout/ , but I was not able to correlate this to a Helm chart deployment.  Is this possible to do through the chart currently, and if not, what are my options as far as codifying a change to the artifactory.system.properties file?

Thank you for your time,

Juliano DeCarvalho

**Comment by chukka** [comment]
@jdecarvalho  This can be achieved by setting in[ systemyaml  under shared section](https://github.com/jfrog/charts/blob/master/stable/artifactory/values.yaml#L393)

```
shared:
  extraJavaOpts: "... -Dartifactory.ui.session.timeout.minutes=60"
```

**Comment by chukka** [comment]
@jdecarvalho  Now with these latest below charts , you can configure session timeout in [values.yaml](https://github.com/jfrog/charts/blob/master/stable/artifactory/values.yaml#L877)
- artifactory-11.0.3
- artifactory-ha-4.0.4
