### ISSUE TITLE
[artifactory-ha] Add some "verbosity" to the wait-for-db container

### ISSUE THREAD

**Issue by TJM** [jfrog/charts#1117]
**Is this a request for help?**: They always are :)

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**: 3.x; 1.15.4

**Which chart**: artifactory-ha (but it probably applies to others)

**What happened**: container is stuck at "wait-for-db" but no output

**What you expected to happen**: wait-for-db could tell me whats up?

**How to reproduce it** (as minimally and precisely as possible): I am not sure how I got into this state, but I thought it was doing some sort of db migration or whatever, after 30+ minutes, I became suspicious. This is just a request for some useful output, when there are problems.

**Anything else we need to know**:

I exec'd into the container and see that its getting connection refused by adding a couple v's

```
[tmcneely@local ~] (⎈ |sea1sbx:artifactory)$ k exec -it artifactory-artifactory-ha-primary-0 -c wait-for-db -- sh
/ $ ps -ef
PID   USER     TIME  COMMAND
    1 1030      0:00 sh -c until nc -z -w 2 artifactory-postgresql 5432 && echo database ok; do   sleep 2; done;
 1822 1030      0:00 sh
 1828 1030      0:00 sleep 2
 1829 1030      0:00 ps -ef
/ $ sh -c until nc -vvv -z -w 2 artifactory-postgresql 5432 && echo database ok; do   sleep 2; done;
sh: syntax error: unexpected "do"
/ $ sh -c 'until nc -vvv -z -w 2 artifactory-postgresql 5432 && echo database ok; do   sleep 2; done;'
nc: artifactory-postgresql (10.110.9.102:5432): Connection refused
sent 0, rcvd 0
nc: artifactory-postgresql (10.110.9.102:5432): Connection refused
sent 0, rcvd 0
nc: artifactory-postgresql (10.110.9.102:5432): Connection refused
sent 0, rcvd 0
nc: artifactory-postgresql (10.110.9.102:5432): Connection refused
sent 0, rcvd 0
nc: artifactory-postgresql (10.110.9.102:5432): Connection refused
sent 0, rcvd 0
nc: artifactory-postgresql (10.110.9.102:5432): Connection refused
```

**Comment by chukka** [comment]
Yes, This makes sense . Will add this in upcoming releases :)
