### ISSUE TITLE
[xray] xray stateful set should pick up changes to xray-db-creds secret

### ISSUE THREAD

**Issue by TJM** [jfrog/charts#1149]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:

```
[tmcneely@local HelmCharts] (⎈ |sea1sbx:artifactory)$ helm version
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
[tmcneely@local HelmCharts] (⎈ |sea1sbx:artifactory)$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T19:10:21Z", GoVersion:"go1.15.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:55Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: xray

**What happened**: I changed database URL, but the pod did not pick up the change until I manually deleted it

**What you expected to happen**: It should have restarted when the secret was updated

**How to reproduce it** (as minimally and precisely as possible): Deploy XRay with "incorrect" database.url... for example `jdbc:postgresql://xray-db-postgresql:5432/xraydb` ... then try to update it to `postgres://xray-db-postgresql:5432/xraydb?sslmode=disable` ... but it does not pick up the change.

**Anything else we need to know**:
Generally this is handled by an annotation in the statefulset, as you have for system-yaml

**Comment by chukka** [comment]
@TJM let me verify this and come back

**Comment by chukka** [comment]
@TJM Yes, Looks like a valid bug and i assume it affects all other jfrog charts  also. we would like to discuss this internally with our teams and provide a fix in the coming weeks

**Comment by chukka** [comment]
@TJM  Can you try latest xray chart and  check if its all good ?

we will release this fix for all other charts very soon

**Comment by TJM** [comment]
Sure, but admittedly, it was a mistake (bad assumption that Xray used the same DB URL format that everything else does) that led me to find this. I guess I could purposely change it to be wrong then change it back and verify that it restarts appropriately :)

**Comment by TJM** [comment]
I am not sure if its working or not. I do see the new db-secrets annotation....
```
Annotations:    checksum/database-secrets: d965096c0ac89f3e8330c9910062727ac582209b059c463559c9c42c13bd5999
                checksum/systemyaml: ddee6cec38ee8a137075275834d6bcae57ca5bb057b57ed080528af6b61ceea3
```

.. but the pod is still stuck in crash backoff.

~tommy

**Comment by TJM** [comment]
MEH, once the backoff cleared, it worked fine. I am not sure if changing an annotation will bypass a backoff loop :-/
