### ISSUE TITLE
Unable to start XRay from Helm Chart

### ISSUE THREAD

**Issue by ethankhall** [jfrog/charts#1155]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT**

**Version of Helm and Kubernetes**:

```
> helm version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}

> kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-07-04T15:01:15Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

XRay deployed via

```
resource "helm_release" "xray" {
  name       = "xray"
  repository = "https://repo.chartcenter.io"
  chart      = "jfrog/xray"
  version    = "6.0.3"
  namespace  = module.xray_ns.namespace_name

  values = [local.xray_values]

  depends_on = [
    module.xray_sa
  ]
}
```

Values File:

```
postgresql:
  enabled: false

database:
  type: postgresql
  driver: org.postgresql.Driver
  secrets:
    user:
      name: xray-secrets
      key:  username
    password:
      name: xray-secrets
      key:  password
    url:
      name: xray-secrets
      key:  url

serviceAccount:
  create: false
  name: xray-sa

xray:
  joinKeySecretName: xray-secrets
  masterKeySecretName: xray-secrets
  jfrogUrl: http://artifactory-artifactory.artifactory:8081

nginx:
  enabled: false
```

**What happened**:

I'm unable to add XRay to a new deployment of Artifactory.

Here are logs that I pulled from the containers: https://gist.github.com/ethankhall/3fb98deac6852481308fa18352428801

**What you expected to happen**:

The service to start correctly.

**How to reproduce it** (as minimally and precisely as possible):

Deploy the TF from above and see the application not start.

**Anything else we need to know**:

The artifactory instance was imported from another instance and if functional.

**Comment by rahulsadanandan** [comment]
@ethankhall 
It should be the router port 8082 in jfrogUrl.
Can you check this and confirm.

**Comment by chukka** [comment]
Please try with ` jfrogUrl: http://artifactory-artifactory.artifactory:8082` in values.yaml

**Comment by chukka** [comment]
@ethankhall is this still an issue ? Please reopen if it doesn't work
