### ISSUE TITLE
[Xray] Documentation for using external databases other than PostgreSQL

### ISSUE THREAD

**Issue by kristinnardal2** [jfrog/charts#1179]
There is already some documentation for how to do this with Artifactory, see #1013 

I noticed that support for specifying database drivers was added to Xray in #1038 but there is no documentation on how to use this feature or if it's actually supported by Xray.

**Comment by eldada** [comment]
As noted in the [official JFrog Xray installation](https://www.jfrog.com/confluence/display/JFROG/Installing+Xray) docs, currently only PostgreSQL is supported.
