### ISSUE TITLE
[bug]: Shorten charts release name 

### ISSUE THREAD

**Issue by rimusz** [jfrog/charts#12]
The release names generated with charts-testing chart_test.sh script are too long for statefullsets as it comes to 65 for some `metadata.labels`, so pods do not get created:

```
$ helm ls
artifactory-ha-7219pws7otxtcr6g
$ kubectl describe -n artifactory-ha-dmn0miwywb4tcegj statefulset
...
  Warning  FailedCreate      3m (x25 over 8m)  statefulset-controller  create Pod artifactory-ha-dmn0miwywb4tcegj-artifactory-ha-member-0 in StatefulSet artifactory-ha-dmn0miwywb4tcegj-artifactory-ha-member failed error: Pod "artifactory-ha-dmn0miwywb4tcegj-artifactory-ha-member-0" is invalid: metadata.labels: Invalid value: "artifactory-ha-dmn0miwywb4tcegj-artifactory-ha-member-545fd89668": must be no more than 63 characters
...
```

This is why it is failing on https://github.com/helm/charts/pull/7320#issuecomment-416009972

**Comment by rimusz** [comment]
statefulset pod label `controller-revision-hash: artifactory-ha-ehpnodrtdmk9r-artifactory-ha-primary-666664c7dc` name is too long which is failing then

**Comment by jainishshah17** [comment]
@rimusz Fixed.
