### ISSUE TITLE
[jfrog-platform] Initial (Beta) release - Feedback/Suggestions

### ISSUE THREAD

**Issue by chukka** [jfrog/charts#1203]
Dear Folks,

We are just released  `jfrog-platform` chart  available at https://chartcenter.io/jfrog/jfrog-platform and sources [here](https://github.com/jfrog/charts/tree/master/stable/jfrog-platform)

**Few highlights:**

[0.0.3 chart release]
- Single command to install entire Jfrog platform

- Single database(postgresql) for all products

- Use global values to configure  few common parameters like masterKey, JoinKey, etc.,

**Update :**

[0.0.4 chart release]

- Added Migration steps to move existing artifactory/artifactory-ha installations to JFrog platform chart - Refer [here](https://github.com/jfrog/charts/blob/master/stable/jfrog-platform/UPGRADE_NOTES.md)

Please try and share feedback (bug reports or feature requests) :)

Thanks
Ram

**Comment by chukka** [comment]
@TJM

**Comment by chukka** [comment]
@palko444 @TGM

**Comment by TJM** [comment]
Interesting, I was asking about sharing database between the various components and was told not to. It seems completely reasonable to share a single database server between these very related components, but I know that "xray" can be a bit of a connections pig. We are not using several of the included components yet, but it looks like it supports the ability to disable components. Thanks for putting this together, we will try to test this in our environment in the next upgrade cycle.

**Comment by chukka** [comment]
@TJM  We just released a new version supporting Migration steps to move existing artifactory/artifactory-ha installations to JFrog platform chart - Refer [here](https://github.com/jfrog/charts/blob/master/stable/jfrog-platform/UPGRADE_NOTES.md)

Please try and share feedback

**Comment by asanami** [comment]
Some alignment on how secrets are managed would be good.  I _think_ that database passwords are stored in both system.yaml and as secrets in kubernetes.  We tend to use HashicorpVault for injecting secrets in a run time.  E.g.

```apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-database-password-secret
  labels:
    app: {{ template "fullname" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    vault.security.banzaicloud.io/vault-addr: {{ .Values.vault_addr }}
    vault.security.banzaicloud.io/vault-role: {{ .Values.vault_role }}
    argocd.argoproj.io/sync-options: Validate=false
type: Opaque
data:
  postgresql-password: {{ .Values.database_password_secret | b64enc }}
```

Also specifying some of the system configuration for the router without having to override the system.yaml would be nice.  We run artifactory core outside of kubernetes today for reasons, so have a load balancer pre-created to route traffic to k8s.

```
    systemYaml: |
      shared:
        node:
          ip: mission-control-<domain.com>
```
