### ISSUE TITLE
[artifactory-ha] FEATURE: Add support for additional system.yaml configs

### ISSUE THREAD

**Issue by fl-max** [jfrog/charts#1206]
**Is this a request for help?**:
No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
Kubernetes: `v1.17.7`
Helm: `v3.0.3`

**Which chart**:
stable/artifactory-ha

**Feature you would like to see implemented**
Ability to **add** configuration to the `system.yaml` file. Currently this is setup as an override via `.Values.artifactory. systemYaml` ([here](https://github.com/jfrog/charts/blob/master/stable/artifactory-ha/values.yaml#L474)). By default this comes with logic based on other values that I'd rather not touch/maintain.

Ideally, I'd be able to pass **additional** config options and potentially have the ability to override specific elements that are included in the chart. This could be achieved by adding `.Values.artifactory. additionalSystemYaml` and then in the [configMap](https://github.com/jfrog/charts/blob/master/stable/artifactory-ha/templates/artifactory-system-yaml.yaml#L14) having another line for:
`{{ tpl .Values.artifactory.additionalSystemYaml . | indent 4 }}`

This would enable us to set additonal configuration settings without disrupting the logic you already have in place and maintaining that logic as you release updates. The one consideration here is how to handle overrides of elements and/or potential merge conflicts of duplicate keys? Maybe a better approach is to have a `base-system.yaml` and a `user-system.yaml` that Artifactory loads where `user-system.yaml` takes precedence.

**Anything else we need to know**:

**Comment by chukka** [comment]
@fl-max Thanks for this feature request , this feature is already in works  and tracked internally, will be released in next few weeks for all charts 👍

**Comment by chukka** [comment]
I'm closing this - Once we release you can try and share feedback

**Comment by fl-max** [comment]
Shouldn't this be left open until it's released?

**Comment by chukka** [comment]
We are planning to implement this feature little differently from what you proposed but will tag you once released

**Comment by chukka** [comment]
@fl-max This PR has feature to override systemyaml for advanced use cases , Hope you will try and share the feedback
