### ISSUE TITLE
https://github.com/jfrog/charts/blob/master/stable/pipelines/values-ingress-external-secret.yaml has incorrect variables

### ISSUE THREAD

**Issue by asanami** [jfrog/charts#1223]
The values in this file:
https://github.com/jfrog/charts/blob/master/stable/pipelines/values-ingress-external-secret.yaml

Are incorrectly documented.  

For example hostName should be hostname

`rabbitmq.password` should be `rabbitmq.auth.password`

etc.

Please can somebody review these?

**Comment by chukka** [comment]
Yes,Looks like we missed it,will be fixed in next release , please refer  https://github.com/jfrog/charts/blob/master/stable/pipelines/values-ingress.yaml for correct values
