### ISSUE TITLE
[artifactory][artifactory-ha] Allow enabling open metrics API

### ISSUE THREAD

**Issue by KierranM** [jfrog/charts#1232]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**:

**Which chart**: artifactory & artifactory-ha

**What happened**:  As of Artifactory v7.7 it is possible to enable an open metrics API endpoint on Artifactory by adding some configuration to the system.yaml. The required configuration is documented here: https://www.jfrog.com/confluence/display/JFROG/Open+Metrics

**What you expected to happen**: I would like to be able to enable the metrics endpoint using helm values. Either using the existing `metrics.enabled` value, or one that is more specific.

**Anything else we need to know**:

**Comment by donovanmuller** [comment]
@KierranM `.Values.artifactory.openMetrics.enabled` was enabled in `4.7.0` [release](https://github.com/jfrog/charts/blob/master/stable/artifactory-ha/CHANGELOG.md#470---dec-18-2020), happy to close?
