### ISSUE TITLE
[artifactory-ha] Question about able to set multiple ports

### ISSUE THREAD

**Issue by sandy999** [jfrog/charts#1243]
**Is this a request for help?**: yes

---

**Version of Helm and Kubernetes**:
Helm: 3.3.4 and Kubernetes: 1.18.8

**Which chart**: 
artifactory-ha 1.7.3

**What happened**:

We are in the process of moving our existing cluster to AWS. For this, we are using the provided artifactory-ha helm chart. To support backward compatibility, we need to able to accept traffic on multiple ports. Looking at the charts, it seem we can only set one port each type. 

Is there a way for you to be able to configure multiple ports through the charts?  

Apologies in advance for a noob question.   

**What you expected to happen**:
NA

**How to reproduce it** (as minimally and precisely as possible):
NA

**Anything else we need to know**:
NA

**Comment by chukka** [comment]
@sandy999 Sorry didn't understand the question completely, Are you  are  referring using 6.x of artifactory-ha  1.7.3 chart ? Also, what ports do you  want to open , can you be more specific?

**Comment by sandy999** [comment]
Correct, we are setting up artifactory-ha: 6.x  deployed using chart: 1.7.3. 

We are configuring the nginx proxy provided via the chart, deployed on eks. I see the chart provides the option to configure one http and one https port. But we require few more ports to be configured, due to legacy requirements. 

I wanted to check if there is a way to configure nginx deployment with addition ports, before I go down the route to customize it.
