### ISSUE TITLE
Xray parameter indexer.persistence.size doesn't seem to work

### ISSUE THREAD

**Issue by fabiorino** [jfrog/charts#1244]
**Which chart**:
xray

**What happened**:
values-small.yaml, values-medium.yaml and values-large.yaml define the parameter indexer.persistence.size, which doesn't seem to have any effect on the actual deployment. The data-volume PVC size is always set to 50Gi.

**What you expected to happen**:
The PVC size should change accordingly.

**How to reproduce it** (as minimally and precisely as possible):
Deploy the chart with --values values.yaml --values values-*.yaml

**Comment by chukka** [comment]
@fabiorino FYI, persistence size is moved under common, Please check corrected values-*.yaml in PR-#1248
