### ISSUE TITLE
Feature Request: Azure Blob Storage

### ISSUE THREAD

**Issue by agolomoodysaada** [jfrog/charts#125]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature Request

Just like we are able to use S3 and GCS, it would be nice to have Azure blob storage support.
It should accept azure blob storage credentials in the chart itself such as the account name and the access key.

**Comment by eldada** [comment]
@agolomoodysaada - you are more than welcome to test #140 and provide some feedback.

**Comment by felipeac** [comment]
@eldada - I'm gonna test it also :)
