### ISSUE TITLE
[xray] Allow external rabbitmq credentials to come from existing secret

### ISSUE THREAD

**Issue by fabiorino** [jfrog/charts#1257]
This a feature request.

It looks like it's not possible to store external RabbitMQ credentials in a secret, they have to be hardcoded in a variable ("rabbitmq.external.password") or directly in the system yaml. This is inconvenient as we'd rather avoid passing in secrets on the command line or hardcode secrets in the values file.

It is already possible to provide an existing secret for external PostgreSQL, please make the same thing possible for external RabbitMQ.

**Comment by chukka** [comment]
@fabiorino Makes sense, Will try to implement(will be tracking internally)  this in upcoming releases for Xray chart
