### ISSUE TITLE
[xray] 3.11.1 Docker images have been removed from docker.bintray.io

### ISSUE THREAD

**Issue by fabiorino** [jfrog/charts#1258]
"appVersion" in charts/stable/xray/Chart.yaml should be updated to a valid tag, or Docker will fail to pull the image.

Thanks,
Fabio.

**Comment by Vijay5760** [comment]
![image](https://user-images.githubusercontent.com/49961829/99095493-312f1c00-25a3-11eb-8e9b-23043e163c27.png)
looks like registry is moved to new location. someone need to update helm chart with new registry path or move back to orginal location

**Comment by chukka** [comment]
@fabiorino Thanks for reporting ! Will check internally and get back asap
