### ISSUE TITLE
Chart makes tls.crt and tls.key even when Values.nginx.https.enabled = false

### ISSUE THREAD

**Issue by anderm3** [jfrog/charts#1259]
BUG REPORT

**Version of Helm and Kubernetes**: 2.x, 1.13

**Which chart**: artifactory-ha but also artifactory

**What happened**: The generated chart makes a tls.key and tls.crt when Values.nginx.https.enabled is set to false

**What you expected to happen**: It should not make those files

**How to reproduce it** (as minimally and precisely as possible): helm upgrade --install artifactory-ha --dry-run --debug --set nginx.https.enabled=false center/jfrog/artifactory-ha 

**Anything else we need to know**: pr incoming

**Comment by chukka** [comment]
@anderm3 Thanks for the contribution ! we would like to test this internally this week  and merge to master if every thing looks good
