### ISSUE TITLE
Artifactory helm upgrade persistance storage command fails with forbidden error

### ISSUE THREAD

**Issue by eladh** [jfrog/charts#1265]
BUG REPORT

Version of Helm and Kubernetes: 2.x, 1.17 , with rimas tillerless plugin

Which chart: artifactory 8.1.9 (artifactory 6.14.1 rev 61401900)

What happened: As a result of stroage full alert we deleted old binaries and artifacts , performed all GC/Cleanup procedures and sadly the storage still mention full error notification and prevent pushing new artifacts.
although the  **/opt/jfrog/artifactory/data/filestore** seems to be in the right size.

As another countermeasure we wanted to resize our artifactory.persistance.size + and here we got our current problem , running the following command: 

`helm tiller run helm upgrade artifactory jfrog/artifactory  --set postgresql.enabled=false --set artifactory.persistence.size=400Gi --version=8.1.9`

following  @chukka  advice regarding persistence storage change :  
```
> 
> Also, artifactory.persistence.size can't be changed via helm upgrade directly
> 
> Steps to be followed
> 
>     edit PVC size
>     delete statefulset
>     update chart custom-values.yaml
>     do helm upgrade

```

I would love to get more details how to update the persistence storage as manually updating the PVC i got the following error:
`error: persistentvolumeclaims "artifactory-volume-artifactory-artifactory-0" could not be patched: persistentvolumeclaims "artifactory-volume-artifactory-artifactory-0" is forbidden: only dynamically provisioned pvc can be resized and the storageclass that provisions the pvc must support resize`

cc @eldada @chukka

adding

**Comment by eladh** [comment]
@chukka 
Updating the chart values with new storage capacity + delete the statefulset + helm upgrade  , resulting the following error :

`Couldn't find key db-password in Secret default/artifactory-artifactory`

**Comment by chukka** [comment]
@eladh did you pass same value of `.Values.database.password` in values.yaml during upgrade ?

Please check `artifactory-secrets.yaml` file in templates
{{- if .Values.database.password }}
  db-password: {{ .Values.database.password | b64enc | quote }}
  {{- end }}

**Comment by eladh** [comment]
thanks @chukka , i was able to retrieve the db-password secret and complete the artifactory helm upgrade.
