### ISSUE TITLE
[xray] rabbitmq-ha health checks are deprecated

### ISSUE THREAD

**Issue by TJM** [jfrog/charts#1270]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**Version of Helm and Kubernetes**:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:08:32Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

```
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

**Which chart**: xray-6.4.2

**What happened**: while monitoring logs in xray-rabbitmq-ha, I noticed that it is complaining about the health checks being used. Every ~3 seconds it emits an error about the health check being deprecated.

**What you expected to happen**: it not to complain about deprecated health checks

**How to reproduce it** (as minimally and precisely as possible): run xray with rabbitmq-ha enabled

**Anything else we need to know**:

Log messages:
```
2020-11-20 22:08:41.005 [warning] <0.3244.0> rabbitmqctl node_health_check and its HTTP API counterpart are DEPRECATED. See https://www.rabbitmq.com/monitoring.html#health-checks for replacement options.
2020-11-20 22:08:45.980 [warning] <0.3258.0> rabbitmqctl node_health_check and its HTTP API counterpart are DEPRECATED. See https://www.rabbitmq.com/monitoring.html#health-checks for replacement options.
2020-11-20 22:08:48.709 [warning] <0.3269.0> rabbitmqctl node_health_check and its HTTP API counterpart are DEPRECATED. See https://www.rabbitmq.com/monitoring.html#health-checks for replacement options.
```

https://www.rabbitmq.com/monitoring.html#health-checks

~tommy

**Comment by TJM** [comment]
Actually, the whole chart is deprecated: https://github.com/helm/charts/tree/master/stable/rabbitmq-ha

Should we just switch over to the bitnami chart?

**Comment by chukka** [comment]
@TJM We are internally tracking this already , Also #1099 represents the same

Yes, going forward bitnami chart will be default , we are planning to release new chart with this change soon

**Comment by chukka** [comment]
@TJM  You can still use  bitnami's chart in current xray chart by disabling rabbitmq-ha as below

```
rabbitmq-ha:
  enabled: false

rabbitmq:
  enabled: true
  auth:
    username: guest
    password: password 
```

**Comment by TJM** [comment]
I can, indeed. I have converted over to bitnami as you say above... rabbitmq portion of the xray values section

```
    rabbitmq-ha:
      enabled: false
    rabbitmq:
      enabled: true
      replicaCount: 3
      global:
        imageRegistry: bintray.artifactory.company.com
      auth:
        password: censored-of-course
      memoryHighWatermark:
        enabled: true
      pdb:
        create: true
      metrics:
        enabled: true
      resources:
        requests:
          memory: "2Gi"
          cpu: "1"
        limits:
          memory: "4Gi"
          cpu: "2"

```
