### ISSUE TITLE
artifactory-pro stable image 

### ISSUE THREAD

**Issue by vikram383** [jfrog/charts#1292]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature req

**Version of Helm and Kubernetes**: 3.4.1/v1.19

**Which chart**: i want to know about stable chart for deploying without errors like joinkey and msater key 

**What happened**: sometimes Cluster join  fails

**What you expected to happen**: successfully pods should deploy

**How to reproduce it** (as minimally and precisely as possible):
no idea

**Anything else we need to know**:
please provode with stable version woth no errors

**Comment by chukka** [comment]
@vikram383  Its recommended you pass these below values  

# Create a joinKey and masterKey
export JOIN_KEY=$(openssl rand -hex 32)
echo ${JOIN_KEY}

export MASTER_KEY=$(openssl rand -hex 32)
echo ${MASTER_KEY}

# Pass the created these values to helm
`helm upgrade --install artifactory --set artifactory.masterKey=${MASTER_KEY} --set artifactory.joinKey=${JOIN_KEY} --set postgresql.postgresqlPassword=${POSTGRES_PASSWORD} --namespace artifactory center/jfrog/artifactory`

For upgrades ,please follow [here](https://github.com/jfrog/charts/tree/master/stable/artifactory#updating-artifactory)

**Comment by vikram383** [comment]
Hi 
i have tried this couple of times but still problem with join key

**Comment by vikram383** [comment]
Hi chukka 
i can see same master key after deployment succcessfull but not join key it is different
should i give any path for join key in system.yaml 
thanks

**Comment by mreddy93** [comment]
Bootstrap joinKey found in [/opt/jfrog/artifactory/var/bootstrap/access/etc/security/join.key:]. Deleting original
how to rectify path of joinkey?
