### ISSUE TITLE
Joinkey probelm and cluster cant join

### ISSUE THREAD

**Issue by mreddy93** [jfrog/charts#1293]
**Is this a request for help?**: yes

[values.txt](https://github.com/jfrog/charts/files/5638370/values.txt)
[error.txt](https://github.com/jfrog/charts/files/5638371/error.txt)
[error.txt](https://github.com/jfrog/charts/files/5638374/error.txt)

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature req

**Version of Helm and Kubernetes**: 3.4.1/v1.19

**Which chart**: i want to know about stable chart for deploying without errors like joinkey and msater key 

**What happened**: sometimes Cluster join  fails

**What you expected to happen**: successfully pods should deploy

**How to reproduce it** (as minimally and precisely as possible):
no idea

**Anything else we need to know**:
please provode with stable version woth no errors

**Comment by rahulsadanandan** [comment]
@mreddy93 
From the error logs, it seems like 
`failed with error pq: password authentication failed for user "artifactory"`

Can you try installing artifactory in a fresh namespace.

**Comment by mreddy93** [comment]
i tired several times but no luck

**Comment by mreddy93** [comment]
Hi im able to join cluster now but during installation there are couple of WARN like system.yaml failed 
im posting my console output here pls let me know how to get rid of those , if they are not serious for installation do let me know 
thanks 
[output.txt](https://github.com/jfrog/charts/files/5653574/output.txt)

**Comment by rahulsadanandan** [comment]
@mreddy93 
`[WARN ][0m [] [installerCommon.sh:706        ] [main] - System.yaml validation failed` this message can ignored. It is not serious for the installation. we have a ticket to track this internally.

**Comment by mohitreddy93** [comment]
Cluster join: Retry 40: Service registry ping failed, will retry. Error: Failed to ping access, response status: 404 Not Found (returned 404) [startup]

**Comment by mohitreddy93** [comment]
how to resolve above issue?
