### ISSUE TITLE
Binary store as secret 

### ISSUE THREAD

**Issue by adrew183** [jfrog/charts#1295]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
3.4 / v1.19

**Which chart**:
Artifactory

**What happened**:
I just want to know why binary store.xml 
Is stored as secret in templates any aortic reason ?

**What you expected to happen**:
I was expecting to be config map 

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
How to resolve system.yaml failed warning during installation

**Comment by adrew183** [comment]
How to rectify /var/opt/artifactory- could not set the owner

**Comment by rahulsadanandan** [comment]
@adrew183 binary store.xml can contain credentials, so it should be stored as a secret.
