### ISSUE TITLE
[mission-control] Elasticsearch request via router

### ISSUE THREAD

**Issue by donovanmuller** [jfrog/charts#1297]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT / QUESTION

**Version of Helm and Kubernetes**: 

**Which chart**: https://chartcenter.io/jfrog/mission-control?version=5.3.3

**What happened**: Using the provided Elasticsearch container provided by the Chart and _not_ an external cluster. In https://github.com/jfrog/charts/pull/1087 Elasticsearch requests via _router_ were supported. However, I cannot see how to actually make use of the router to route requests to Elasticsearch?

I am expecting that if I use `curl` to make Elasticsearch API requests, that the router will route accordingly. So something like this would be expected to work:

```
curl http://mission-control.mission-control.svc:8082/_cluster/health
404 page not found
```

given a `mission-control` Service in the `mission-control` namespace. The response is a `404` though.

**What you expected to happen**: To enable and configure Filebeat to send to Elasticsearch as per https://www.jfrog.com/confluence/display/JFROG/Dashboard#Dashboard-EnableMetrics I am expecting to use the router port `8082` in the `url`.

**How to reproduce it** (as minimally and precisely as possible): Try `curl` the Elasticsearch API resources using the router Service and port (`8082`)

**Anything else we need to know**: I am probably just not understanding how to use the router properly and am looking for how to correctly use the router to allow requests to the Elasticsearch API/HTTP port (`9200` on the `elasticsearch` container).

**Comment by rahulsadanandan** [comment]
@donovanmuller 
we should use `/elasticsearch` after router port
`curl http://mission-control.mission-control.svc:8082/elasticsearch/_cluster/health`

For filebeat as well, ES URL is `http://mission-control.mission-control.svc:8082/elasticsearch/ `

**Comment by donovanmuller** [comment]
Thanks @rahulsadanandan 👍
