### ISSUE TITLE
[Artifactory-HA] [FEATURE REQUEST] Add Flag for Creating PSP(s)

### ISSUE THREAD

**Issue by mabrikan** [jfrog/charts#1316]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**: Helm (v3.4.2), K8s [client (v1.19), server (v1.18)]

**Which chart**: artifactory-ha

**What happened**: PodSecurityPolicy(s) is/are not created for the release pods 

**What you expected to happen**:  PodSecurityPolicy(s) are created if user wants to.

**How to reproduce it** (as minimally and precisely as possible): 
1. Have a K8s cluster where **RBAC** and **PSP** enabled.
2. Have a default _ClusterRoleBinding_ (for all SAs in all Namespaces) that uses a default "safe" psp (disallowing PVCs)
3. Install the chart

You should encounter validation error, for creating the PVCs. To solve this, you will have to create a new psp for Artifactory.

**Anything else we need to know**:

I suggest adding a flag under `rbac.psp.enabled`. If the user turns this on, the chart will install specific psp(s) for Artifactory PODs

**Comment by rahulsadanandan** [comment]
Hi @mabrikan, Thanks for this feature request. We have created a ticket internally to track this. Will get back to you on this, once we have an update.

**Comment by rahulsadanandan** [comment]
@mabrikan we have discussed this internally, we see that PSPs will be deprecated in the future.
https://github.com/kubernetes/kubernetes/pull/97171.

**Comment by mabrikan** [comment]
Makes sense. Thanks for the reply @rahulsadanandan .
