### ISSUE TITLE
- Cluster join: Retry 35: Service registry ping failed, will retry. Error: Error while trying to connect to local router at address 'http://localhost:8046/access': Get "http://localhost:8046/acces

### ISSUE THREAD

**Issue by mohitreddy93** [jfrog/charts#1334]
**Is this a request for help?**:
yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

**Version of Helm and Kubernetes**:
v3.3

**Which chart**:
artifactory helm chart version:7.11.5

**What happened**:
- Cluster join: Retry 35: Service registry ping failed, will retry. Error: Error while trying to connect to local router at address 'http://localhost:8046/access': Get "http://localhost:8046/acces

**What you expected to happen**:
succesful join of artifactory 

**How to reproduce it** (as minimally and precisely as possible):
i have tried giving node id:artifactory-artifactory-0 in system.yaml

**Anything else we need to know**:
nothing

**Comment by rahulsadanandan** [comment]
@mohitreddy93 Can you please provide the YAML file used to install the chart.?

**Comment by mohitreddy93** [comment]
Sure ,
[values.txt](https://github.com/jfrog/charts/files/5806456/values.txt)

**Comment by mohitreddy93** [comment]
any updates on that rahul

**Comment by mohitreddy93** [comment]
how can i resolve above issue?

**Comment by rahulsadanandan** [comment]
@mohitreddy93 sorry for the delay
did you figure out the issue. From the file shared, i could see you haven’t provided postgresql password 
```
postgresql:
  postgresqlUsername: artifactory
  postgresqlPassword: ""
```

what the logs from the artifactory service.?
