### ISSUE TITLE
We cant update running Artifactory server expired license by updating the license secret

### ISSUE THREAD

**Issue by mohammadtibi** [jfrog/charts#135]
BUG REPORT

Which chart:
artifactory-ha

We mention in the documentation (in the Install Artifactory HA license):

IMPORTANT: You should use only one of the following methods. Switching between them while a cluster is running might disable your Artifactory HA cluster!

However, in case we have installed Artifactory while providing a secret for the license and the license has expired, with the current implementation, we cant update it by updating the license secret and we most update it via the UI ( or REST API).

**Comment by eldada** [comment]
This is actually an issue with the documentation. We'll update it to reflect the right way for managing your Artifactory license.
