### ISSUE TITLE
Data sync from global database server has failed

### ISSUE THREAD

**Issue by jsr57v** [jfrog/charts#1359]
**Is this a request for help?**: Is a request for help

---

**Version of Helm and Kubernetes**:
helm Version:"v3.3.0
kubernetes version 1.18

**Which chart**:
 3.17

**What happened**:
Failed to sync vulnerability database.

**What you expected to happen**:
Message in console: Data sync from global database server has failed
Log: Updates worker id 0 failed to download update from https://jxray.jfrog.io/api/v1/updates/onboarding
Curl to the address https://jxray.jfrog.io/api/v1/updates/onboarding  gives a 401 error

**How to reproduce it** (as minimally and precisely as possible):
When running sync from the console. The database is online. Connectivity exists, but it does not synchronize and gives error: Data sync from global database server has failed

**Anything else we need to know**:
artifactory with license enterprise (is not enterprise plus)

**Comment by chukka** [comment]
@jsr57v  Can you please share reproducible steps ?
