### ISSUE TITLE
How to pass TLS secret to use PostgreSQL with TLS?

### ISSUE THREAD

**Issue by jainishshah17** [jfrog/charts#1361]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

**Version of Helm and Kubernetes**:
```
$kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.12-eks-31566f", GitCommit:"31566f851673e809d4d667b7235ed87587d37722", GitTreeState:"clean", BuildDate:"2020-10-20T23:25:14Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}


$helm version
version.BuildInfo{Version:"v3.2.2", GitCommit:"a6ea66349ae3015618da4f547677a14b9ecc09b3", GitTreeState:"clean", GoVersion:"go1.13.12"}

```

**Which chart**:
Xray 6.10.0

**What happened**:
I am using external database with TLS enabled. 
How to pass created TLS secret to Xray is not clear from documentation provided in [PostgreSQL with TLS](https://github.com/jfrog/charts/tree/master/stable/xray#postgresql-with-tls) 

**What you expected to happen**:
Documented steps to pass TLS secret to Xray to communicate with TLS enabled database.

**How to reproduce it** (as minimally and precisely as possible):
Install Xray with external TLS enabled database.

**Comment by chukka** [comment]
@jainishshah17  Thanks for raising this - Will review internally and update

**Comment by chukka** [comment]
@jainishshah17 [here](https://www.jfrog.com/confluence/display/JFROG/TLS+Certificates#TLSCertificates-SecuringPostgreSQLwithTLSSupportonXray) is the manual documentation of recommended steps , Please try and share feedback .

**Comment by jainishshah17** [comment]
@chukka This documentation does not explain how to mount secret to xray pods.
