### ISSUE TITLE
[Artifactory-ha] Allow to pull images in the postgresql initcontainer from a private registry

### ISSUE THREAD

**Issue by blame19** [jfrog/charts#1374]
FEATURE REQUEST

**Version of Helm and Kubernetes**: 3, 1.18.4

**Which chart**:  Artifactory-ha, v 1.10.1

**What happened**: One initcontainer in the rtedge-postgresql instance is pulling an image from "docker.io/bitnami/minideb:stretch". Apparently this can't be changed or customized in the helm chart, despite we're providing our registry to the line here (https://github.com/jfrog/charts/blob/62eea9e67700ded67142d52c0bd4cc53fc676017/stable/artifactory-ha/values.yaml#L145) in the values.yaml. 

**What you expected to happen**: We're migrating to using an internal registry which mirrors the images from docker.bintray.io. We'd like to customize the registry for all the images provided in the chart, InitContainers included.

**How to reproduce it**: Deploy a rtedge instance with postgresql enabled; use a value in the yaml at line L145 
`postgresql:
  enabled: true
  image:
    registry:<SOME REGISTRY>`

**Anything else we need to know**: //

**Comment by chukka** [comment]
@blame19 You can use this global section (applicable for artifactory, postgresql)

```
global:
  imagePullSecrets:
    - <registrySecret>
  imageRegistry: abc.com
```
