### ISSUE TITLE
[xray] Add priority class support

### ISSUE THREAD

**Issue by cheries** [jfrog/charts#1379]
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): 
Feature

**Version of Helm and Kubernetes**:
k8s: 1.18.9
Helm: 3.1.1

**Which chart**:
stable/xray

**What happened**:
Cannot specify a priority class value in values.yaml and it is required in our cluster.

**What you expected to happen**:
To be able to specify a priority class as we do for the artifactory chart.

**Comment by rahulsadanandan** [comment]
@cheries Thanks
We have created an internal ticket to track this. will plan for this in the upcoming releases.

**Comment by rahulsadanandan** [comment]
@cheries this is available from 103.42.0 chart versions.
