### ISSUE TITLE
How to override property in artifactory.system.properties?

### ISSUE THREAD

**Issue by snaveen** [jfrog/charts#1380]
**Is this a request for help?**:
Yes. 

**Version of Helm and Kubernetes**:
helm3 - v1.15.12-gke.2

**Which chart**:
artifactory-ha

**What happened**:
As part of upgrading to 7.15.3 I want to change value for below property in  artifactory.system.properties
"artifactory.gems.compact.index.enabled=true"

Does chart already supports overriding "artifactory.system.properties"? 
If yes please point me to the documentation. 

If No, Is there any workaround? 

**What you expected to happen**: NA
**How to reproduce it** (as minimally and precisely as possible): NA
**Anything else we need to know**: NA

**Comment by rahulsadanandan** [comment]
@snaveen 
Can you try using the custom config map, custom volume mounts, and then using the preStartCommand to override the file.

**Comment by eldada** [comment]
Another recommended way would be to use the [system.yaml](https://www.jfrog.com/confluence/display/JFROG/Artifactory+System+YAML) to inject extra java options with
```
shared:                                                                                                                                                                                                                                                                  
  extraJavaOpts: "-Dartifactory.gems.compact.index.enabled=true"
```
This will append the property to the final Java command line.

**Comment by snaveen** [comment]
Thanks @eldada. Added extra java opts and it worked as expected.

**Comment by snaveen** [comment]
Thanks @rahulsadanandan I have not tried it. if i try, i will update the result here
