### ISSUE TITLE
Issue with docker port method support

### ISSUE THREAD

**Issue by sandy999** [jfrog/charts#1397]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug

**Version of Helm and Kubernetes**:
kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}

helm version
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"dirty", GoVersion:"go1.15.5"}

**Which chart**:
artifactory-ha:4.7.3

**What happened**:
When using a docker repository that leverages port method support, it is unable to compute the app version correctly. 

**What you expected to happen**:

The app version includes the port and the image name.

**How to reproduce it** (as minimally and precisely as possible):

Use a docker registry with port specified.

artifactory:
    image:
      registry: "\<docker-registry\>:\<docker-port\>"

**Comment by chukka** [comment]
@sandy999 can you please provide more info like registry details and image ? also share the error you encountered
