### ISSUE TITLE
special character "#" is not getting escaped by "\" in database.password value.

### ISSUE THREAD

**Issue by sajjasgit** [jfrog/charts#1408]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**: 
Helm - v3.5.3
Kubernetes - 1.18

**Which chart**: jfrog/xray

**What happened**:
passing "#" as part of database.password value actually striping the content after the password.

**What you expected to happen**:
using escape charecter "\" should include "#" character as it is in the password.

**How to reproduce it** (as minimally and precisely as possible):
helm upgrade --install xray --namespace artifactory --set xray.jfrogUrl=https://xxxxxxx --set xray.joinKey=xxxxx --set xray.masterKey=xxxxxx --set postgresql.enabled=false --set database.url="postgres://<HOST>:<PORT>/<DB_NAME>?sslmode=disable" --set database.user="xxxxx@xxxxx" --set database.password='ll$nE[QX0I2Qz%#]' jfrog/xray

make sure password contains "#" in it.

**Anything else we need to know**:
None

**Comment by chukka** [comment]
Sorry missed this , @sajjasgit is this still an issue ?
