### ISSUE TITLE
[artifactory][artifactory-ha] filebeat-configmap.yaml needs different template

### ISSUE THREAD

**Issue by malagant** [jfrog/charts#1409]
**Is this a request for help?**:
no
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
bug report

Wen activating metrics for artifactory a filebeat-configmap.yaml file will generate a configmap, but with the wrong name.
Changing the lines containing `{{ template "artifactory.name" . }}` to `{{ template "artifactory.fullname" . }}` will fix this (PR will be provided asap.)

**Version of Helm and Kubernetes**:

7.17.5 (1.20)

**Which chart**:

`artifactory` and `artifactory-ha`

**What happened**:

Wrong name for configmap is generated.

**What you expected to happen**:

Expect correct name for configmap to be generated.

**How to reproduce it** (as minimally and precisely as possible):

Just use metrics

**Anything else we need to know**:

I prepared a PR.

**Comment by chukka** [comment]
closing this
