### ISSUE TITLE
[artifactory-ha] Clarification needed on Primary

### ISSUE THREAD

**Issue by andrewhertog** [jfrog/charts#1452]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature Request

It is my understanding from speaking with our account manager, that the Primary no longer serves a unique purpose in an artifactory-ha cluster. The primary now works together with the members to serve requests, and handle tasks. If this is so, could this chart be updated to reflect this? And if not, could I please receive clarification on the different between the primary and member nodes here?

**Version of Helm and Kubernetes**:
Helm 3
Kubernetes 1.20

**Which chart**:
artifactory-HA

**What happened**:
Primary is a distinct node, not serving traffic

**What you expected to happen**:
Primary acts the same as member, and handles nodes

**How to reproduce it** (as minimally and precisely as possible):
Its what the chart does right now

**Anything else we need to know**:

**Comment by neilbeukes** [comment]
Has there been any work done on this that I maybe missed?

**Comment by rahulsadanandan** [comment]
By default artifactory-ha chart will have one primary and 2 member nodes. From artifactory-ha chart version [107.18.6] If you want all nodes to be the primary set these below in values.yaml and primary acts same as the member and handle all requests
```
artifactory:
  primary:
    replicaCount: 3
  node:
    replicaCount: 0
```
