### ISSUE TITLE
System.yaml validation failed for artifactory and xray

### ISSUE THREAD

**Issue by sergiocruzado** [jfrog/charts#1482]
**Is this a request for help?**: no

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): bug report

**Version of Helm and Kubernetes**: 

**Which chart**: jfrog-platform:0.7.1

**What happened**: The system.yaml validation failed for Xray and Artifactory

**What you expected to happen**: yaml validation succeeded

**How to reproduce it** (as minimally and precisely as possible): just deploy the chart and see the logs:
2021-07-25T10:06:42.000Z [shell] [WARN ] [] [installerCommon.sh:714        ] [main] - System.yaml validation failed

Running the command to validate the system.yaml I can see more precise info:

artifactory@jfrog-artifactory-ha-primary-0:/opt/jfrog/artifactory$ app/bin/diagnostics/diagnosticsUtil validate yaml var/etc/system.yaml app/misc/etc/system.basic-template.yaml --uncomment-before-parse;
.access key is misplaced or doesnt apply at this location
.metadata key is misplaced or doesnt apply at this location
.shared.logging key is misplaced or doesnt apply at this location
.artifactory key is misplaced or doesnt apply at this location
.frontend key is misplaced or doesnt apply at this location
yaml validation failed

xray@jfrog-xray-0:/opt/jfrog/xray$ app/bin/diagnostics/diagnosticsUtil validate yaml var/etc/system.yaml app/misc/etc/system.basic-template.yaml --uncomment-before-parse;
.shared.logging key is misplaced or doesnt apply at this location
.shared.rabbitmq key is misplaced or doesnt apply at this location
.server key is misplaced or doesnt apply at this location
yaml validation failed

**Anything else we need to know**:

**Comment by srinivasgowda097** [comment]
@sergiocruzado: try validating system.yaml against system.full-template.yaml

artifactory@jfrog-artifactory-ha-primary-0:/opt/jfrog/artifactory$ app/bin/diagnostics/diagnosticsUtil validate yaml var/etc/system.yaml app/misc/etc/system.full-template.yaml --uncomment-before-parse;

xray@jfrog-xray-0:/opt/jfrog/xray$ app/bin/diagnostics/diagnosticsUtil validate yaml var/etc/system.yaml app/misc/etc/system.full-template.yaml --uncomment-before-parse;

**Comment by sergiocruzado** [comment]
This is the output for artifactory:

artifactory@jfrog-artifactory-ha-primary-0:/opt/jfrog/artifactory$ app/bin/diagnostics/diagnosticsUtil validate yaml var/etc/system.yaml app/misc/etc/system.full-template.yaml --uncomment-before-parse;
.access.tomcat.connector.sendReasonPhrase key is misplaced or doesnt apply at this location
.artifactory.tomcat.connector.sendReasonPhrase key is misplaced or doesnt apply at this location
yaml validation failed

xray@jfrog-xray-0:/opt/jfrog/xray$ app/bin/diagnostics/diagnosticsUtil validate yaml var/etc/system.yaml app/misc/etc/system.full-template.yaml --uncomment-before-parse;
.server.mailServer key is misplaced or doesnt apply at this location
.server.indexAllBuilds key is misplaced or doesnt apply at this location
.router.topology.local.requiredServiceTypes key is misplaced or doesnt apply at this location
yaml validation failed
xray@jfrog-xray-0:/opt/jfr

**Comment by samispurs** [comment]
In my case its
app/bin/diagnostics/diagnosticsUtil validate yaml var/etc/system.yaml app/misc/etc/system.full-template.yaml --uncomment-before-parse;
.artifactory.tomcat.connector.relaxedPathChars key is misplaced or doesnt apply at this location
.artifactory.tomcat.connector.relaxedQueryChars key is misplaced or doesnt apply at this location
yaml validation failed

**Comment by ShirleyZrx** [comment]
@sergiocruzado Did you solve the problem about system.yaml validation failed?  And how?

**Comment by sergiocruzado** [comment]
@ShirleyZrx  still having this type of validation failure

I am now using helm chart jfrog-platform 10.3.2 with MC integrated in Artifactory and using the default systemYaml value in the artifactory chart i get this:

.mc.tomcat.connector.sendReasonPhrase key is misplaced or doesnt apply at this location

Nevertheless, Jfrog Platform is working fine.

**Comment by ShirleyZrx** [comment]
@sergiocruzado thanks for your reply. I have the same problem but JFrog works well too.
