### ISSUE TITLE
Plugins do not propagate to member instances

### ISSUE THREAD

**Issue by ghost** [jfrog/charts#1484]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: Helm 3.x, Kubernetes 1.20.x

**Which chart**: jfrog-platform, specifically artifactory-ha

**What happened**: Plugins are only loaded into the "primary" nodes. When using the cloud native availability there are no "primary" nodes deployed, meaning that we cannot deploy plugins via `artifactory.userPluginSecrets`

**What you expected to happen**: Setting `artifactory.userPluginSecrets` will load plugins into the "member" nodes when using cloud native HA.

**How to reproduce it** (as minimally and precisely as possible): as above

**Anything else we need to know**:

**Comment by chukka** [comment]
@hgoscenski-imanage  can you please check latest GA version of `jfrog-platorm` chart  which uses artifactory chart as default ,

**Comment by hgoscenski-imanage** [comment]
@chukka I no longer have access to the environment however @thomasmRavn may be able to assist.

**Comment by thomasmRavn** [comment]
Working with Jared (our point of contact with Jfrog) we're not ready to test the GA helm chart until next year when we plan to setup a dev environment.
Will post here if we find anything
