### ISSUE TITLE
networkpolicies suppress request

### ISSUE THREAD

**Issue by yiwu1** [jfrog/charts#1488]
**Is this a request for help?**:

Yes

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

This is a FEATURE REQUEST, we want to suppress the networkpolicies resource creation as current cluster don't allow it.

**Version of Helm and Kubernetes**:
helm v3.4.2
kubernets server v1.18.8-342

**Which chart**:
107.21.8

**What happened**:
We have restriction to create networkpolicies in our cluster here as following. Plese check below message:

failed to create resource: networkpolicies.networking.k8s.io is forbidden: User "xxxx" cannot create resource "networkpolicies" in API group "networking.k8s.io" in the namespace "artifactoryha-dev"

**What you expected to happen**:

Which helm command parameters can pass to suppress the networkpolicies resource creation?Otherwise we are blocked here.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
Didn't found out any "enabled" function for networkpolicies resource in values.xml.

**Comment by chukka** [comment]
@yiwu1 Can you try setting in this to  below in values.yaml  

```
networkpolicy: []
```

And  we will plan to address this in upcoming releases

**Comment by yiwu1** [comment]
@chukka thanks for the update. Please keep us updated for new release with this change.

**Comment by chukka** [comment]
Fixed in #1498 , please try 7.25.6 and above charts
