### ISSUE TITLE
[mission-control] Duplicate Resources Key Violates YAML Spec

### ISSUE THREAD

**Issue by isugimpy** [jfrog/charts#1491]
https://github.com/jfrog/charts/blob/f43f88bd2d9cc10f88974cc68594b94f4fa2a1fb/stable/mission-control/templates/mission-control-statefulset.yaml#L419-L420
https://github.com/jfrog/charts/blob/f43f88bd2d9cc10f88974cc68594b94f4fa2a1fb/stable/mission-control/templates/mission-control-statefulset.yaml#L458-L459

It appears that the lines on 458-459 are duplicated.  This causes compliant YAML parsers to fail due to the duplicate key.  Helm itself will simply merge them and use the later value, which makes this work, but that isn't actually to spec and causes problems with some parser implementations.  The same problem will occur if filebeat is enabled, but in a much more insidious way as .Values.missionControl.resources will be applied to the filebeat container via Helm.

**Comment by rahulsadanandan** [comment]
@isugimpy Thanks for reporting this. We will have this fixed in the upcoming releases.

**Comment by chukka** [comment]
will be fixed as part of 4.7.12 release in few weeks

**Comment by chukka** [comment]
Fixed in #1498
