### ISSUE TITLE
best artifactory.persistence.awsS3V3.redundancy value to use for artifactory-ha cluster 

### ISSUE THREAD

**Issue by frankfong0208** [jfrog/charts#1500]
**Is this a request for help?**:
yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
no

**Version of Helm and Kubernetes**:
Helm v3.5.3
Kubernetes versions:
Client Version: v1.19.4
Server Version: v1.18.9-eks-d1db3c

**Which chart**:
https://artifacthub.io/packages/helm/jfrog/jfrog-platform/0.6.0

**What happened**:
We installed artifactory-ha chart with one primary node and two member nodes. For persistence, we choose awsS3V3. Just wondering what would be the best value to set the artifactory-ha.artifactory.persistence.awsS3V3.redundancy. 
In the charts/artifactory-ha/README.md, it states below, but I am still not quite sure what value to use for redundancy(Currently we set this to 3 as we find a default value of 3 in charts/artifactory-ha/values.yaml line 661. Will 3 be a good value for our cluster size?). 
**IMPORTANT:** All storage configurations (except NFS) come with a default `artifactory.persistence.redundancy` parameter.
This is used to set how many replicas of a binary should be stored in the cluster's nodes.
Once this value is set on initial deployment, you can not update it using helm.
It is recommended to set this to a number greater than half of your cluster's size, and never scale your cluster down to a size smaller than this number.

**What you expected to happen**:
NA

**How to reproduce it** (as minimally and precisely as possible):
NA

**Anything else we need to know**:
NA

**Comment by frankfong0208** [comment]
Hi there, could someone please take a look at this for us?

**Comment by frankfong0208** [comment]
Hi there, could someone please take a look at this for us?

**Comment by rahulsadanandan** [comment]
Hey,
you might get some information here
https://www.jfrog.com/confluence/display/JFROG/Filestore+Sharding
https://www.jfrog.com/confluence/display/JFROG/Configuring+the+Filestore#ConfiguringtheFilestore-Sharding-ClusterBinaryProvider

as recommended set this to a number greater than half of your cluster's size, so that in case of a node failure, it is still available from the other
you could also open a support ticket to get the right recommendations based on the actual environment 
cc @chukka @eldada

**Comment by frankfong0208** [comment]
Hi @rahulsadanandan thanks for your reply. If our artifactory-ha cluster has one primary node and two member nodes, what would be the size of our cluster? 2 or 3? (do we only count the member nodes or both member nodes and primary nodes when it comes to cluster size?) 
Will 3 be a good value of redundancy for our cluster size?

**Comment by rahulsadanandan** [comment]
@frankfong0208 the cluster size is 3 here. so redundancy can be 2 and above. we recommend 3 (1 primary +2 member node)

From Artifactory 7.17.4, You could also use CNHA , 3 primary and 0 member nodes
more links here
https://jfrog.com/knowledge-base/how-to-enable-cloud-native-high-availability-feature-for-artifactory-using-helm/
https://www.jfrog.com/confluence/display/JFROG/High+Availability#HighAvailability-Cloud-NativeHighAvailability

**Comment by frankfong0208** [comment]
Thanks @rahulsadanandan
