### ISSUE TITLE
Helm chart and pvc size

### ISSUE THREAD

**Issue by gigi206** [jfrog/charts#1506]
I try to test your helm chart but I can't override the size of PVC :(

2 pvc defined (data and artifactory-volume):
```
$ helm install --dry-run artifactory jfrog/artifactory-jcr | egrep storage                                            
            storage: "200Gi"
          storage: 20Gi
```

I try to override the size of the 2, but only one is changed (data), the 2nd (artifactory-volume) seems to keep the default size:
```
$ helm install --dry-run artifactory jfrog/artifactory-jcr --set artifactory.persistence.size=10Gi --set artifactory.postgresql.persistence.size=5Gi | egrep storage
            storage: "5Gi"
          storage: 20Gi
```

If I try the template artifactory jfrog/artifactory instead of artifactory jfrog/artifactory-jcr, this is the inverse I arrive to change the artifactory-volume size but not the data size.
```
helm install --dry-run artifactory jfrog/artifactory --set artifactory.persistence.size=10Gi --set artifactory.postgresql.persistence.size=5Gi | egrep storage
            storage: "200Gi"
          storage: 10Gi
```

Can someone tell me what I'm doing wrong?

**Comment by normander** [comment]
Hi @gigi206 

You need to be careful to set those parameters. Keep in mind that you have only a couple of values to configure as artifactory-jcr, the rest of them(including persistence) is from a dependency called artifactory so you need to correspond to the dependency(artifactory.artifactory):

`
$ helm install --dry-run artifactory jfrog/artifactory-jcr --set artifactory.artifactory.persistence.size=10Gi --set artifactory.artifactory.postgresql.persistence.size=5Gi
`

**Comment by chukka** [comment]
@gigi206  looks like above answer from @normander solved your issue
