### ISSUE TITLE
jfrog-platform: update chart to use 7.27.3 version

### ISSUE THREAD

**Issue by abhinav-khanna-ib** [jfrog/charts#1517]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
 FEATURE REQUEST

If this is a FEATURE REQUEST, please:
jfrog-platform helm chart is not updated to use latest artifactory helm charts. Can you please update it?

**Comment by chukka** [comment]
@abhinavkhanna-sf Please refer [here](https://www.jfrog.com/confluence/display/JFROG/Installing+the+JFrog+Platform+Using+Helm+Chart) for documentation . 

* Missioncontrol is now part of artifactory (>= 7.27.x) - [Migrating from Missioncontrol to Insight for existing installations](https://www.jfrog.com/confluence/display/JFROG/Migrating+from+Mission+Control+to+Insight)
