### ISSUE TITLE
The artifactory container does not start due to missing wget command

### ISSUE THREAD

**Issue by ccodreanu** [jfrog/charts#1529]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: 
- Helm `version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"dirty", GoVersion:"go1.16.5"}`
- Kubernetes `v1.20.7-eks`

**Which chart**: jfrog/artifactory, version: 107.27.6

**What happened**: `artifactory` container does not start due to `wget` not being available for the `preStartCommand` which installs the JDBC driver.

**What you expected to happen**: `artifactory` container to start.

**How to reproduce it** (as minimally and precisely as possible): Deploy the chart with:

`.Values.artifactory.preStartCommand = "mkdir -p /opt/jfrog/artifactory/var/bootstrap/artifactory/tomcat/lib; cd /opt/jfrog/artifactory/var/bootstrap/artifactory/tomcat/lib && wget -O /opt/jfrog/artifactory/var/bootstrap/artifactory/tomcat/lib/mysql-connector-java-5.1.41.jar https://jcenter.bintray.com/mysql/mysql-connector-java/5.1.41/mysql-connector-java-5.1.41.jar"` (default value in values.yaml)

**Anything else we need to know**: Workaround this by setting  `.Values.artifactory.preStartCommand = "mkdir -p /opt/jfrog/artifactory/var/bootstrap/artifactory/tomcat/lib; cd /opt/jfrog/artifactory/var/bootstrap/artifactory/tomcat/lib && curl -L -o /opt/jfrog/artifactory/var/bootstrap/artifactory/tomcat/lib/mysql-connector-java-5.1.41.jar https://jcenter.bintray.com/mysql/mysql-connector-java/5.1.41/mysql-connector-java-5.1.41.jar"`

**Comment by chukka** [comment]
Fixed in #1554
