### ISSUE TITLE
Suggestion: Allow providing configuration YAML using Helm chart

### ISSUE THREAD

**Issue by pathob** [jfrog/charts#1530]
**Is this a request for help?**: yes

---

Hey, I'm still not an advanced user of Helm and all the templating capabilities related to it and that's why I'd like to ask for help here.

I would like to deploy Artifactory using the `artifactory` Helm chart and directly want to configure an auth provider with it. I'm looking for a way to use the default system yaml and extend it by a block, e.g. `shared.security.ldapSettings`.

I know there are three ways to define custom system yaml and their order: 1. custom init container, 2. external system.yaml and 3. default system.yaml in values.yaml. But none of 1. or 2. is talking about reusing 3. so that the config can be minimized. What I'm thinking of is some kind of merge logic to merge e.g. the `shared.security.ldapSettings` into the default system yaml, but I didn't manage to do it.

I also found the approach described in #1291 but what I don't like here is that this is done AFTER, not WITH actual deployment.

Thanks for your help!

**Comment by pathob** [comment]
Hi @chukka 

I'm dealing with the issue again and noticed that when I opened this issue I had some big misunderstandings about the systemYaml. I thought the systemYaml and the configuration yaml as described [HERE](https://www.jfrog.com/confluence/display/JFROG/Artifactory+YAML+Configuration) are the same.

Anyway, if there was a way to use the configuration yaml from the file system (currently that's only possible via REST API), it would be super easy to build a fully configured Artifactory using the Helm chart. We could just have a `artifactory.configuration` block in the values yaml and configure everything like proxies, auth providers etc.

I think that's something really to consider.

Thank you
Patrick

**Comment by gitta-jfrog** [comment]
The "Artifactory YAML Configuration" is a REST API solution and there are no plans to implement it via file system.
Recently we added "[Access Bootstrap YAML File](https://jfrog.com/help/r/jfrog-installation-setup-documentation/access-bootstrap-yaml-file)" that might be relevant for your needs.
