### ISSUE TITLE
"artifactory" chart needs to handle HA license filename distinction

### ISSUE THREAD

**Issue by patbat95008** [jfrog/charts#1535]
**Is this a request for help?**: No, bug report

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

JFrog's documentation recently was updated [to recommend using the "artifactory" helm chart for HA installations](https://www.jfrog.com/confluence/display/JFROG/Installing+Artifactory#InstallingArtifactory-HelmHAInstallation), as after 7.27 the Artifactory HA system doesn't require a primary node anymore.

This works as intended, increasing the redundancy of the "artifactory" chart creates an HA cluster as it should. However, currently the chart code doesn't handle a filename requirement that is still different between HA and non-HA. 

**Version of Helm and Kubernetes**:  Kubernetes v1.21.3 | Helm 3.7.1

**Which chart**: artifactory (Not artifactory-ha)

**What happened**: 

Attempting to add a cluster license secret to the Artifactory values.yaml file didn't result in the cluster licenses being added automatically. The multiple licenses were saved under /var/opt/jfrog/artifactory/etc/artifactory/artifactory.lic, not the "artifactory.cluster.license" file. 

The cluster license file is a documented requirement of using an Enterprise HA cluster, and [since 7.25.5 it should be used instead of the "artifactory.lic" file](https://www.jfrog.com/confluence/display/JFROG/Artifactory+Release+Notes#ArtifactoryReleaseNotes-Artifactory7.25.5).

**What you expected to happen**:

Using the secret with multiple license files makes the licenses get loaded into the Artifactory system with the proper filename.

**How to reproduce it** (as minimally and precisely as possible):

1] Create a secret in Kubernetes that contains the licenses under a defined key

2] Load the secret in the [artifactory.license.secret field](https://github.com/jfrog/charts/blob/master/stable/artifactory/values.yaml#L462) of the Helm values.yaml file

3] Set the[ replicaCount setting](https://github.com/jfrog/charts/blob/master/stable/artifactory/values.yaml#L250) to be at least 2 to activate HA mode

4] Install an HA cluster using the values.yaml file and the secret, and note that the license loading wizard still appears and Artifactory has no licenses.

**Anything else we need to know**:

I found that in the [artifactory-license-secret.yaml](https://github.com/jfrog/charts/blob/master/stable/artifactory/templates/artifactory-license-secret.yaml) file the system hard-codes the filename to be "artifactory.lic". We can probably update this to be "artifactory.cluster.lic" and it will still work with standalone, non-HA Artifactories given the documented release notes for 7.25.

**Comment by rahulsadanandan** [comment]
@patbat95008 How did you create the secret, can you share the command used?

**Comment by patbat95008** [comment]
`kubectl create secret generic artifactory-lic-test

#Set the Kube_editor Environment Variable - Use your preferred terminal-based text editor
KUBE_EDITOR="vim"

#Directly edit the secret
kubectl edit secret -n <NameSpace> artifactory-lic-test

##artifactory-lic-test##
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: "2021-11-10T23:55:45Z"
  name: artifactory-lic-test
  namespace: default
  resourceVersion: "60401"
  uid: bf931cd2-3fc0-47bd-a407-9147da562df0
type: Opaque
data:
  artifactory-lic: |
<Insert 2 or more base64 encoded licenses here>
`
Creating the secret isn't the issue, let me know if the above command doesn't work.

**Comment by rahulsadanandan** [comment]
@patbat95008 this was fixed in [107.27.6](https://github.com/jfrog/charts/commit/d5110961ad861b1ff1e38c7a64d75edebee1dcbf#diff-ea26e8e261a285b525d4f507037dfbabfaed4d29d51907febf8cff18ad433e5b) chart. Please try and let us know.

**Comment by chukka** [comment]
@patbat95008  Thanks for reporting this , Now we updated  [wiki](https://www.jfrog.com/confluence/display/JFROG/Artifactory+Release+Notes#ArtifactoryReleaseNotes-Artifactory7.25.5)  page with this chart version 

```
This enhancement was added to the Helm Charts from version 107.27.6 and above. 
```

**Comment by chukka** [comment]
@patbat95008 did you get a chance to try with latest chart ? if you don't see any issue, please close this issue
