### ISSUE TITLE
artifactory-ha: elasticsearch url, username and password can't be read from custom secret

### ISSUE THREAD

**Issue by misse** [jfrog/charts#1542]
**Is this a request for help?**: no

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

You should be able to provide the secrets as k8s secrets in all cases where you need to enter them in values.yaml, just like you can for binarystore and database username and password

**Which chart**: 107.27.6

**Comment by chukka** [comment]
related to https://github.com/jfrog/charts/issues/1628

**Comment by gitta-jfrog** [comment]
Not planned to implement,
