### ISSUE TITLE
Update jfrog-platform chart to use latest xray chart (103.37.1)

### ISSUE THREAD

**Issue by geoff-carr-bzy** [jfrog/charts#1549]
Please can the `jfrog-platform` chart be updated to use the latest `xray` chart (`103.37.1`) as there are important fixes in this version that without them the Xray deployment fails due to not being able to copy the custom certificates.

https://github.com/jfrog/charts/blob/79cd7b200579cdc1663dce167679fe23a5afbd11/stable/jfrog-platform/Chart.yaml#L21

**Comment by chukka** [comment]
@geoff-carr-bzy Noted. We are planning for release this week along other fixes
