### ISSUE TITLE
[artifactory] Option to rotate nginx logs in HA setup on GKE with helm

### ISSUE THREAD

**Issue by alejandroLuchador** [jfrog/charts#1555]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**: 
  HELM_VERSION: '3'
  KUBERNETES_VERSION: '1.18.20-gke.901'

**Which chart**:
  ARTIFACTORY_HELM_CHART_VERSION: '4.10.0'
  ARTIFACTORY_VERSION: '7.16.3' 

**What happened**:

At the moment we are running Artifactory HA on GKE. The issue we are facing is that there is no options to enable log rotation for the following nginx log /var/opt/jfrog/nginx/logs/access.log.  We have large number of users and activity, so approximate average log growth is ~2.5GB per day. After about a month the nginx pod get `evicted` by kubernetes. We run 3 pods and this is consistent across all of them. 

When pods get evicted kubernetest spins up new ones. However, the danger is that all 3 get evicted at the same time and we get an outage.

**What you expected to happen**:

We would like to be able to have an option in helm chart to rotate logs.

**How to reproduce it** (as minimally and precisely as possible):

- Deploy Artifactory HA with NginX to k8s.
- Create a script that will continually invoke actions on nginx (e.g. download/upload, etc)
- Watch the /var/opt/jfrog/nginx/logs/access.log grow indefinitely or its pod get evicted by k8s if that option is configured

**Anything else we need to know**:

As a background, we have raised this in JFrog support ticket #[187751](https://support.jfrog.com/s/tickets/5006900003uuR6W/nginx-log-rotation) and support have suggested that this would be a good candidate for feature request.

**Comment by chukka** [comment]
Thanks for reporting ! Would you mind raising a PR for this so that it gets faster to release , Any way we will take this as a feature request

**Comment by gitta-jfrog** [comment]
Not planned to implement.
