### ISSUE TITLE
redundancy is not supported in artifactory chart

### ISSUE THREAD

**Issue by hchiao1** [jfrog/charts#1556]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Critical Feature Request

**Version of Helm and Kubernetes**:

**Which chart**:
artifactory

**What happened**:
Lack of gap between artifactory and artifactory-ha helm chart. To be more specific, binarystore configuration is acting differently. It seems like artifactory-ha have redundancy of 2. But for artifactory chart, the redundancy value is not even supported. 

**What you expected to happen**:
Adding redundancy value as a feature on value.yaml for user to easily migrate from artifactory-ha helm to artifactory helm

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by gitta-jfrog** [comment]
Already implemented.
