### ISSUE TITLE
Template values.yaml - Process enableSignedUrlRedirect for provider id="google-storage-v2"

### ISSUE THREAD

**Issue by kishubhatta** [jfrog/charts#1561]
**Is this a request for help?**: NO

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**: helm3

**Which chart**: artifactory chart 107.29.7

**What happened**: See https://github.com/jfrog/charts/blob/39a10cc59f039c7810e638820f5d3d1958594ad6/stable/artifactory/values.yaml#L890.

**What you expected to happen**: `<enableSignedUrlRedirect>{{ .Values.artifactory.persistence.googleStorage.enableSignedUrlRedirect }}</enableSignedUrlRedirect>`

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by chukka** [comment]
@kishubhatta  can you please describe more details on this issue , can you please confim if this is already fixed on the latest version?

**Comment by kishubhatta** [comment]
Yeah looks addressed. Anyway, we did not end up using it.
