### ISSUE TITLE
Accept log rotation settings (systemYaml) in default values.yaml

### ISSUE THREAD

**Issue by kishubhatta** [jfrog/charts#1568]
**Is this a request for help?**: NO

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**: helm 3

**Which chart**: artifactory chart v107.29.7, app version 7.29.7

**What happened**: Cannot define log rotation settings using default values

**What you expected to happen**: https://github.com/jfrog/charts/blob/e286ca8c3bfa8c5a34683ce265ad66850e588f80/stable/artifactory/values.yaml#L590

**How to reproduce it** (as minimally and precisely as possible):
Use the default values.yaml and try setting just the log rotation settings - you can't. You will have to manually override systemYaml, which makes the other settings like mc, consoleLog, openMetrics pointless.

**Anything else we need to know**: No

**Comment by gitta-jfrog** [comment]
Will be part of https://github.com/jfrog/charts/pull/1842
