### ISSUE TITLE
[Feature] Enable JMX monitoring

### ISSUE THREAD

**Issue by DDSloan96** [jfrog/charts#157]
Would it be possible to enable the chart to expose the JMX monitoring port via a value option for use with Prometheus's JMX exporter

**Comment by satyamag** [comment]
@eldada @jainishshah17  Any updates on this request? We are also looking to export the JMX metrics to stackdriver so that we can keep track of metrics listed here https://www.jfrog.com/confluence/display/RTF/Artifactory+JMX+MBeans.

**Comment by eldada** [comment]
@satyamag - We are a bit low on resources at the moment. You are more than welcome to suggest a PR with initial changes we can start rolling.

**Comment by danielezer** [comment]
@satyamag This should get you started. For your use case, you would just need to enable JMX since the ClusterIP service is enough for because (I'm assuming) the JMX exporter will be inside the cluster.
