### ISSUE TITLE
Recognize iam auth database login

### ISSUE THREAD

**Issue by kishubhatta** [jfrog/charts#1574]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: NA

**Which chart**: jfrog/artifactory

**What happened**: Unused values can crash the artifactory pod

**What you expected to happen**: Values not needed are not required

**How to reproduce it** (as minimally and precisely as possible): Deploy the chart using Google SQL IAM auth

**Anything else we need to know**:

**Comment by kishubhatta** [comment]
@peleduri you don't need to support IAM db auth. You only need to gracefully handle the case where the helm value for password is not specified. Currently, the artifactory application simply crashes if one does not specify password value. One needs to set some `dummy` value, even when using IAM auth and cloud sql proxy sidecar.

**Comment by chukka** [comment]
@kishubhatta  can you please share the reproducible steps

**Comment by johnjelinek** [comment]
This works already. I'm using a `cloud-sql-proxy` sidecar and then just passing in `db-user` (no password) to connect with the IAM GCP service account.
