### ISSUE TITLE
Update jfrog-platform chart to use latest versions of applications

### ISSUE THREAD

**Issue by geoff-carr-bzy** [jfrog/charts#1577]
Please can you confirm when the `jfrog-platform` chart will be updated to use the latest versions of Artifactory and Xray? Currently `jfrog-platform` chart is set to use version  `7.29.8` when Artifactory is at `7.31.10` and Xray is at `3.41.4`

**Comment by chukka** [comment]
@geoff-carr-bzy  This will be done this week with latest versions
