### ISSUE TITLE
Artifactory can't start with fresh install on OKD due to permission denied on /artifactory_bootstrap/binarystore.xml

### ISSUE THREAD

**Issue by beenje** [jfrog/charts#1579]
**Version of Helm and Kubernetes**:
Helm 3.7
Kubernetes: OKD 4.9

**Which chart**:
Chart: artifactory
Version: 107.31.13

**What happened**:
Try to deploy Artifactory using the Helm chart to OKD using a specific uid/gid (we can't use the default artifactory on our cluster):

```yaml
artifactory:
  uid: 1001360000
  gid: 1001360000
```

Following error when trying to start artifactory container:

```
Preparing to run Artifactory in Docker
Running as uid=1001360000(1001360000) gid=0(root) groups=0(root),1001360000
Dockerfile for this image can found inside the container.
To view the Dockerfile: 'cat /docker/artifactory-pro/Dockerfile.artifactory'.
WARN Running with 10% free storage. Consider freeing up space or increasing volume size
Resolved .shared.database.type (postgresql) from /opt/jfrog/artifactory/var/etc/system.yaml
Resolved .shared.database.url (__sensitive_key_hidden___) from /opt/jfrog/artifactory/var/etc/system.yaml
Waiting for DB postgresql to be ready on artifactory-postgresql/5432 for 30 seconds
Copying Artifactory bootstrap files
cp: cannot stat '/artifactory_bootstrap/binarystore.xml': Permission denied
ERROR Unable to copy file, command : cp -f /artifactory_bootstrap/binarystore.xml /opt/jfrog/artifactory/var/etc/artifactory/binarystore.xml
```

**What you expected to happen**:

The container should start.
The permissions on `/artifactory_bootstrap` are `drwxrw-rw-.    1 artifactory artifactory   41 Feb  2 11:17 artifactory_bootstrap`
The directory should be 777 instead to allow any user to copy the file.
That could be fixed in the Dockerfile.

**How to reproduce it** (as minimally and precisely as possible):

Try to deploy a new artifactory with:

```yaml
artifactory:
  uid: 1001360000
  gid: 1001360000
```

**Comment by chukka** [comment]
@beenje  for Openshift based K8s ,please refer - https://github.com/jfrog/JFrog-Cloud-Installers/tree/master/Openshift4/operator/artifactory-ha-operator

**Comment by beenje** [comment]
Thanks for the link.
Looking at the [documentation](https://www.jfrog.com/confluence/display/JFROG/Artifactory+Integration+with+Red+Hat+Certified+OpenShift+Operator), a prerequisite is **Artifactory Enterprise License**

We only have one Artifactory Pro license. Is it possible to use the operator anyway (without HA enabled)?

**Comment by giri-vsr** [comment]
@beenje It is not specifically tested with pro license but you should be able to run with single instance.
