### ISSUE TITLE
mission control command not found

### ISSUE THREAD

**Issue by danielezer** [jfrog/charts#158]
**Is this a request for help?**:

-No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
helm - v2.11.0
kubernetes - 1.11.5-gke.4

**Which chart**:
mission-control

**What happened**:
mission control init containers has error messages that say "command not found"

**What you expected to happen**:
the errorExit function will be executed

**How to reproduce it** (as minimally and precisely as possible):
helm install jfrog/mission-control
look at the mission control pod logs

**Anything else we need to know**:

When I run helm install jfrog/mission-control, I see the following error:

![image](https://user-images.githubusercontent.com/32907193/50251702-99fec100-0399-11e9-861d-96ef4b70399a.png)

**Comment by eldada** [comment]
@amithins - can you take this? It's a small fix to the entrypoint script.

**Comment by amithins** [comment]
This was fixed as part of #217 .
