### ISSUE TITLE
[ERROR] Project update error: rpc error: code = DeadlineExceeded desc = context deadline exceeded [access_client]

### ISSUE THREAD

**Issue by gabo89** [jfrog/charts#1584]
**Is this a request for help?**:
YES
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
bug report 

the problem is to see if is ok to update our helm chart from 107.24.3 to 107.33.8 in production in order to fix the following  error , i saw at internet that upgrading artifactory from 7.24.3 to at least 7.28.0 fix the error since  artifactory older than 7.28 doesnt have the project setting and feature is not enab led yet, i am planing to upgrade helm chart up to 7.33.8 in order to fix this error 

i atach the stackoverflow web related to this issue
https://stackoverflow.com/questions/68951713/artifactory-oss-metadata-service-logs-project-update-error

```
Project update error: rpc error: code = DeadlineExceeded desc = context deadline exceeded [access_client]

```

**Version of Helm and Kubernetes**:
helm version 3
kubernetes 1.20 rancher rke

**Which chart**:
artifactory-oss helm chart 107.24.3 with artifactory version 7.24.3

**What happened**:
log are filling with a error and error is spaming our new relic monitoring tools increase the cost on data ingestion since error spamm eevery 5 second 

**What you expected to happen**:
error should not be happening in artifactory 7.24.3 since projects setting in artifactory are not release yet in artifactory-oss, a fix was introduced in helm chart artifactory-oss 7.33.8 but need to be sure since i cant find in the changelog 

**How to reproduce it** (as minimally and precisely as possible):
install artifactory chart with helm3 using helm chart  for artifactory-oss 107.24.3

**Comment by chukka** [comment]
@gabo89  is this still an issue ?

**Comment by gabo89** [comment]
hello, i updated the helm chart and after it , it solved!
