### ISSUE TITLE
Ability to change timezone before install.

### ISSUE THREAD

**Issue by omlet05** [jfrog/charts#1587]
**Is this a request for help?**:
yes, I deployed latest HELM chart (artifactory-pro) and we noticed that the time was UTC.
Is there any way to change it and deploy it with another Timezone?
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug/ Feature Request.

**Version of Helm and Kubernetes**:
Latest 7.33.12 stable

**Anything else we need to know**:
Is there an option available to change the timezone? From the helm chart?
I can see this in the main pod:
bash-4.4$ cat /etc/localtime
TZif2UTCTZif2?UTC
UTC0

**Comment by chukka** [comment]
@omlet05  please refer - https://www.jfrog.com/jira/browse/RTFACT-21513
