### ISSUE TITLE
Add lifecycle hooks to nginx in the artifactory-ha helm chart

### ISSUE THREAD

**Issue by rkevin-arch** [jfrog/charts#1594]
**Is this a request for help?**:
No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature request

It would be nice to be able to set the `lifecycle` hooks on the pod specs, mostly for nginx. Right now, when we make any changes to nginx that triggers a deployment update, new nginx pods are spun up and all the old pods are terminated. This is sort of done in an HA manner in the sense that there's always a couple nginx pods available, but it does terminate connections on the old pods without waiting, which isn't the HA upgrade we were hoping for. I was going to follow [this article](https://medium.com/codecademy-engineering/kubernetes-nginx-and-zero-downtime-in-production-2c910c6a5ed8) to set up a `preStop` lifecycle hook that runs `nginx -s quit` and waits for a graceful termination before making the pod exit, but we can't do that with the current helm chart.

Bonus: might be useful to have a single flag (maybe `nginx.gracefulStop: true` or something like that?) that sets the `preStop` hook to `["/bin/sh", "-c", "sleep 5; nginx -s quit; while pgrep nginx; do sleep 1; done"]`, but we can set it ourselves if this is too rigid as long as we can set `lifecycle` hooks in general.

**Version of Helm and Kubernetes**:
Helm `3.8.0`, Kubernetes `v1.20.11-eks-f17b81`

**Which chart**:
`artifactory-ha`, although the `artifactory` chart can benefit from it as well. Potentially more charts if you want to expose that option on more than nginx deployments.

**Comment by chukka** [comment]
@rkevin-arch  Thanks ! would you mind raising a PR for this feature request ?
