### ISSUE TITLE
Artifactory-OSS crashed after server restarted.

### ISSUE THREAD

**Issue by sudo-ankitmishra** [jfrog/charts#1597]
**Is this a request for help?**:
yes
---
**Version of Helm and Kubernetes**:
helmv3, k8s=v1.17.9

**Which chart**:
artifactory-107.27.4
we tried even the latset ones, 107.35.x

**What happened**:
after server restarted it stopped on  k8s, redoplyment did not worked.
server restart happened earlier also, but did not faced this issue.

**What you expected to happen**:
Expected artifactory to run normally.

**How to reproduce it** (as minimally and precisely as possible):
This is the template we are using.
[artifactory-template.txt](https://github.com/jfrog/charts/files/8195362/artifactory-template.txt)

**Anything else we need to know**:
Logs that we get.

[logs-from-artifactory-in-nuke-artifactory-0-2.txt](https://github.com/jfrog/charts/files/8195365/logs-from-artifactory-in-nuke-artifactory-0-2.txt)

Thanks need help urgently.

**Comment by sudo-ankitmishra** [comment]
issue solved thanks

**Comment by chukka** [comment]
@sudo-ankitmishra  what was the issue BTW ?
