### ISSUE TITLE
Add an option to set for the pods the value of `schedulerName` field

### ISSUE THREAD

**Issue by lacci** [jfrog/charts#1606]
**Is this a request for help?**:
NO

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
all

**Which chart**:
`artifactory` and `xray`, but can be useful also for others

**What happened**:
Wanted to specify for the artifactory and xray pods the value of the `schedulerName` field, but this is not possible.

**What you expected to happen**:
Find in `values.yaml` a variable to set the value of `spec.template.spec.schedulerName` in the StatefulSets.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by chukka** [comment]
@lacci  Thanks for feature request , we would like to take this in upcoming releases . Would you mind raising a PR  so that it gets quickly

**Comment by chukka** [comment]
This feature is available in xray (>= 103.55.2) via https://github.com/jfrog/charts/pull/1664 and for artifactory, it  will be released with next minor version
