### ISSUE TITLE
Deprecated AWS Classic Load Balancer

### ISSUE THREAD

**Issue by Isakofff** [jfrog/charts#1607]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

Helm creates k8s service which creates AWS Load Balancer. But the type is a CLASSIC load balancer, which will be fully depricated in August 2022 due to retiring the EC2-Classic network. 
So the question is - when do you plan to migrate Classic Load Balancer to Application LB?

**Version of Helm and Kubernetes**:
Helm v3.6.3, Kubernetes v1.20.11

**Which chart**:
artifactory-107.33.12

**What happened**:
It creates depricated AWS Classic Load Balancer

**What you expected to happen**:
It creates AWS Application Load Balancer

**How to reproduce it** (as minimally and precisely as possible):
Just install Helm chart and check the type of AWS Load Balancer which was created.

**Anything else we need to know**:

**Comment by gitta-jfrog** [comment]
According to [deprecation notice](https://docs.aws.amazon.com/elasticloadbalancing/latest/userguide/migrate-classic-load-balancer.html) AWS published this deprecation going to impact customers with  "Classic Load Balancer in [EC2-Classic](https://aws.amazon.com/blogs/aws/ec2-classic-is-retiring-heres-how-to-prepare/)" while JFrog customers with Artifactory deployment in AWS EKS are using "Classic Load Balancer in a VPC" that is not being deprecated (full explanation can be found [here](https://stackoverflow.com/a/70395796))

We are working on working examples for easy deployment of the JFrog Platform on AWS EKS with NLB or ALB. We will publish it soon.

Yarden
JFrog Support
