### ISSUE TITLE
.mc.tomcat.connector.sendReasonPhrase key is misplaced or doesnt apply at this location

### ISSUE THREAD

**Issue by daftping** [jfrog/charts#1609]
**Is this a request for help?**:
BUG REPORT
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
```
helm version --short
v3.7.0+geeac838
```
```
kubectl version --short
Client Version: v1.21.5
Server Version: v1.20.12-gke.1500
```

**Which chart**:
artifactory-107.35.2

**What happened**:
```
2022-04-01T16:27:50.211Z [shell] [INFO ] [] [installerCommon.sh:1603       ] [main] - Current max open processes is unlimited
.mc.tomcat.connector.sendReasonPhrase key is misplaced or doesnt apply at this location
yaml validation failed
2022-04-01T16:27:50.274Z [shell] [WARN ] [] [installerCommon.sh:791        ] [main] - System.yaml validation failed

```

**What you expected to happen**:
Valid system.yaml must be provided to Artifactory. No error messages in the logs.

**How to reproduce it** (as minimally and precisely as possible):
`helm upgrade --install artifactory --set mc.enabled=true jfrog/artifactory`

**Anything else we need to know**:
I don't see in the [docs](https://www.jfrog.com/confluence/display/JFROG/Artifactory+System+YAML) that `.mc.tomcat.connector.sendReasonPhrase` is a valid key. I think we just need to remove it here https://github.com/jfrog/charts/blob/master/stable/artifactory/values.yaml#L1469 and here https://github.com/jfrog/charts/blob/master/stable/artifactory/values.yaml#L673

**Comment by srinivasgowda097** [comment]
Looks like below entry was not added system.full-template.yaml to validate against system.yaml, will fix in upcoming release
<mc: 
      tomcat:
          connector:
              sendReasonPhrase: false>

**Comment by DLivshin** [comment]
sendReasonPhrase was deprecated with tomcat 9 https://tomcat.apache.org/tomcat-8.5-doc/config/http.html#:~:text=regexp%20matching%20disabled).-,sendReasonPhrase,-Set%20this%20attribute

We should not add it to the system.full-template.yaml, and it should be removed from the values.yaml for Artifactory and Access as well
