### ISSUE TITLE
Add an option to provide a secret name for the root certificate

### ISSUE THREAD

**Issue by danielezer** [jfrog/charts#161]
**Is this a request for help?**:

NO

**Is this a BUG REPORT or FEATURE REQUEST?**:

FEATURE REQUEST

**Version of Helm and Kubernetes**:
all versions

**Which chart**:
artifactory-ha and artifactory

I would like to have the option to provide the root certificate for artifactory as a kuberentes secret. This would be very helpful when configuring E+ in regards to access federation and circle of trust.

According to this guide: https://www.jfrog.com/confluence/display/MC/Managing+Access+Federation#ManagingAccessFederation-EstablishingtheCircleofTrust
I need to have the root certificate file in each edge node in order to configure the circle of trust, if I was able to provide it as a parameter/as a secret and reference its name, it would be much easier.

**Comment by eldada** [comment]
@chukka - with the recent changes, are we able to provide a solution for this today?

**Comment by chukka** [comment]
@kaykay88  This is triaged (created a internal ticket for feature request) . @eldada  not yet
