### ISSUE TITLE
StorageClass longhorn instead of local-path

### ISSUE THREAD

**Issue by wopl** [jfrog/charts#1610]
Is it possible to specify StorageClass for jfrog-artifactory helm chart? Just in values.xml?

Would like to change PVC class and name (instead of artifactory-volume-jfrog-artifactory-0)

Thanks, Wolfram

**Comment by chukka** [comment]
@wopl  please share more details like artifactory chart version and use case you are trying solve ?

**Comment by wopl** [comment]
I am using jfrog/artifactory-jcr. As in my K3S cluster I do have multiple StorageClasses, I would like to specify a dedicated storage class for my artifactory persistence (not only the size).

**Comment by yuntsewu** [comment]
Using longhorn running into issues as well

**Comment by abctaylor** [comment]
Also issues with longhorn.

**Comment by abctaylor** [comment]
Let me rather say, issues with Artifactory :) longhorn is stable for everything else but this.

**Comment by gitta-jfrog** [comment]
It is possible to set the storageclass for artifactory-volume
.Values.artifactory.persistence.storageClassName - https://github.com/jfrog/charts/blob/master/stable/artifactory/values.yaml#L858

If there is a specific issue when setting it for longhorn, please add steps to reproduce. 

Thanks!
