### ISSUE TITLE
Insight chart values.yaml - Mapping key "initialDelaySeconds" already defined error

### ISSUE THREAD

**Issue by PKeves** [jfrog/charts#1622]
Is this a request for help?: NO

Is this a BUG REPORT or FEATURE REQUEST? (choose one): BUG REPORT

Version of Helm and Kubernetes: Helm3, k8s 1.20

Which chart: Insight

What happened: Enabling Insight fails with Mapping key "initialDelaySeconds" already defined error

What you expected to happen: helm deployment is successful

How to reproduce it (as minimally and precisely as possible): set enable Insight value to true

Anything else we need to know: To fix the bug remove the duplicated lines on line numbers 705 and 706 (under insightScheduler>startupProbe) in values.yaml under Insight chart

**Comment by itssiri** [comment]
Will be fixed in the upcoming  release. Thanks!

**Comment by srinivasgowda097** [comment]
This is fixed internally and will be released in couple of days - Insight 1.11.x version

**Comment by chukka** [comment]
Fixed as part of https://github.com/jfrog/charts/pull/1651
