### ISSUE TITLE
Artifactory Circle of Trust - Wrong Location for Certificates

### ISSUE THREAD

**Issue by danmanners** [jfrog/charts#1623]
Hey folks! The path referenced in the [JFrog Access Federation Docs](https://www.jfrog.com/confluence/display/JFROG/Access+Federation#AccessFederation-EstablishingtheCircleofTrust) for Circle of Trust setup doesn't actually match where certs are installed via the Helm Chart.

https://github.com/jfrog/charts/blob/1935e070cc7d61274b899dd7d73a06c66d9e489d/stable/artifactory/values.yaml#L33

Currently, the certs are installed into `/opt/jfrog/artifactory/var/etc/security/keys/trusted`, whereas Circle of Trust requires them to be in `/opt/jfrog/artifactory/var/etc/access/keys/trusted`. Due to the difference in location (`security` vs `access`), I need to **manually** copy the files into the other location and bounce the container. It then loads the CoT certs into the database as expected.

Are the Helm charts just not supporting Circle of Trust certificates at this point in time, or is this something that can be resolved?

Thank you in advance!

**Comment by chukka** [comment]
@danmanners Thanks for reacing out ! we are planning to implement this OOB support in helm charts using `circleOfTrustCertificatesSecret` secret name , Planned to release in next version of Artifactory release in coming days
