### ISSUE TITLE
Artifactory OpenMetrics - Allowing passing credentials to Elastic Search through secretKeyRef

### ISSUE THREAD

**Issue by PKeves** [jfrog/charts#1628]
Hi,

I want to use Artifactory Insight service using external Elastic Search however I'm forced to hardcode these credentials into source code as per the current chart.

Would you please allow passing credentials to Artifactory OpenMetrics Elastic Search through  ***valueFrom secretKeyRef***?

Current code:

https://github.com/jfrog/charts/blob/02f892f79a18aff5a0b1be0ca98168d44b1bc6e9/stable/artifactory/values.yaml#L336-L339

Change username and password to be accepted through secretKeyRef, similarly as done here: 

https://github.com/jfrog/charts/blob/02f892f79a18aff5a0b1be0ca98168d44b1bc6e9/stable/artifactory/values.yaml#L596-L600

Otherwise there is a need to hardcore these credentials into source code as mentioned above.

Thank you in advance!

**Comment by chukka** [comment]
Thanks for this feature request , we will create a internal tracking issue for this , will update once we add this change .

**Comment by gitta-jfrog** [comment]
This request is out of our plans. Closing.
