### ISSUE TITLE
Error: template: artifactory-ha/templates/nginx-deployment.yaml:143:24: executing ... at <.Values.nginx.lifecycle>: can't evaluate field Values in type interface {}

### ISSUE THREAD

**Issue by andreaslarfors** [jfrog/charts#1637]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

**Version of Helm and Kubernetes**:
Helm: 
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}
Kubernetes: 
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"a5e4de7e277a707bd28d448bd75de58b4f1cdc22", GitTreeState:"clean", BuildDate:"2021-11-16T01:09:55Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
jfrog/artifactory-ha --version "107.38.10"

**What happened**:
When enabling logging sidecars for nginx, the following error is thrown:
Error: template: artifactory-ha/templates/nginx-deployment.yaml:143:24: executing "artifactory-ha/templates/nginx-deployment.yaml" at <.Values.nginx.lifecycle>: can't evaluate field Values in type interface {}

**What you expected to happen**:
I expected no error to be thrown.

**How to reproduce it** (as minimally and precisely as possible):
`printf "nginx:\n  loggers:\n    - access.log\n    - error.log" > values.yaml`
`helm template foobar jfrog/artifactory-ha --version "107.38.10" -f values.yaml`

**Anything else we need to know**:
This happened when upgrading from 107.33.9 to 107.38.10 with no changes to our custom values files.

**Comment by andreaslarfors** [comment]
The root cause of the error is the context-aware `.` in the file `artifactory-ha/templates/nginx-deployment.yaml` on line 143:
`135:      {{- range .Values.nginx.loggers }}`
`...`
`143:        {{- with .Values.nginx.lifecycle }}`
Because the .Values.nginx.lifecycle value is referenced from within a range, the context `.` is no longer the root context but the range.
The problem can be mitigated by using `$.` instead, i.e.
`143:        {{- with $.Values.nginx.lifecycle }}`

As I'm writing this I'm realising this should be a Pull Request and not an Issue. Will make a PR shortly..

**Comment by lancew-q** [comment]
Running into the same issue, waiting on approval/merge of the PR.

**Comment by chukka** [comment]
Fixed as part of  7.41.x release https://github.com/jfrog/charts/pull/1652
