### ISSUE TITLE
add support for nginx.terminationGracePeriodSeconds

### ISSUE THREAD

**Issue by ns-kbhat** [jfrog/charts#1645]
**Is this a request for help?**: NO

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**:

**Which chart**: artifactory

**What happened**: need control over graceful termination of nginx when large files are being uploaded

**What you expected to happen**: new value nginx.terminationGracePeriodSeconds (artifactory already has it)

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by srinivasgowda097** [comment]
Thanks for the feature request, we will take this internally and will release in next version of Artifactory

**Comment by chukka** [comment]
Added support in #1651
