### ISSUE TITLE
Not possible to use instance credentials for artifactory-ha

### ISSUE THREAD

**Issue by ljupchokotev** [jfrog/charts#1670]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: 3.9.4, 1.21.14

**Which chart**: artifactory-ha

**What happened**: The helm chart forces you to provide a service account key once you set `persistence.googleStorage.gcpServiceAccount.enabled` to `true` in the `persistence.googleStorage.gcpServiceAccount.config` value. We want to use Artifactory with Workload Identity which uses the pod's service account credentials to connect to the GCS bucket without a key. We have to set `persistence.googleStorage.gcpServiceAccount.enabled` to `true` in order to enable the `google-storage-v2` provider which can use the instance credentials (workload identity).

**What you expected to happen**: I expected to not provide a service account key and deploy Artifactory with just the specific service account which would automatically work with Workload Identity.

**How to reproduce it** (as minimally and precisely as possible): Set `persistence.googleStorage.gcpServiceAccount.enabled` to `true`. The helm deploy will fail because you have not provided a key.

**Anything else we need to know**: I have done changes to our copy of the Helm chart and it works with Workload Identity without providing any key.

**Comment by rahulsadanandan** [comment]
@ljupchokotev Could you please let us know what changes you have done in the copy of the charts to make it work?

**Comment by ljupchokotev** [comment]
@rahulsadanandan I introduced a new value under `artifactory.persistence.googleStorage.useInstanceCredentials` which can be set to `true` or `false`.

Then in the templates:
- `artifactory-gcp-credentials-secret.yaml` template - Wrap the whole secret with `{{- if not .Values.artifactory.persistence.googleStorage.useInstanceCredentials }}` to skip it
- statefulset template - Wrap all places with the same check where it tries to mount the gcp credentials secret or use a pre-existing one

**Comment by rahulsadanandan** [comment]
@ljupchokotev thanks.
this seems to be already fixed internally and will be released with 7.46.x versions in the coming weeks.

**Comment by ljupchokotev** [comment]
@rahulsadanandan do you have any date for this?

**Comment by chukka** [comment]
@ljupchokotev  mostly this week (may happen in a day or two)

**Comment by chukka** [comment]
@ljupchokotev  FYI- There are big binarystore changes coming up in 7.46.x release (please check changelog of helm chart for all changes) , before you upgrade

**Comment by chukka** [comment]
Fixed via #1682

**Comment by ljupchokotev** [comment]
A note to other people that might have this problem as well before upgrading, you can actually set any "dummy" value as the gcp config and it will still prefer the instance credentials instead. No changes required
