### ISSUE TITLE
[xray] Allow setting executionServiceAesKey in a secret

### ISSUE THREAD

**Issue by bmanuel** [jfrog/charts#1685]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): feature

**Which chart**:

xray

**Request**:

https://github.com/jfrog/charts/pull/1600 enabled setting the execution service aes key instead of it being randomly generated. It would be nice to be able to securely generate this key outside of the helm run and insert it as a separate secret instead of having the value in plain text in a values file.

**Comment by itssiri** [comment]
Thanks for the feature request. We will try to include this in future releases.

**Comment by bmanuel** [comment]
@itssiri are there any updates on this?

**Comment by rahulsadanandan** [comment]
We have taken this internally and will be released mostly in a couple of weeks.

**Comment by bmanuel** [comment]
@rahulsadanandan any updates on this?

**Comment by rahulsadanandan** [comment]
@bmanuel We have fixed this internally, release is going to happen when xray releases 3.65.x versions.

**Comment by bmanuel** [comment]
@rahulsadanandan any updates on this?

**Comment by chukka** [comment]
Fixed in #1728
