### ISSUE TITLE
Add option to enable/disable proxy_request_buffering and proxy_buffering_off

### ISSUE THREAD

**Issue by EvertonSA** [jfrog/charts#1686]
**Is this a request for help?**:

---

FEATURE REQUEST:

We have an internal ticket with jfrog and the solution provided from support side is very ugly + low maintenance. 

Disable proxy_request_buffering with values.yaml file.

https://github.com/jfrog/charts/blob/30b189c6574f75420b5be98be72663a49432ecfb/stable/artifactory/values.yaml#L1635

we need something like:

```
        {{- if .Values.nginx.disableProxyBuffering}}
        proxy_http_version 1.1;
        proxy_request_buffering off;
        proxy_buffering off;
        {{- end }}
```
and on values.yaml:
```
nginx:
  disableProxyBuffering: true
```

**Version of Helm and Kubernetes**:
all

**Which chart**:
jfrog-platform

**Which product license** (Enterprise/Pro/oss):
Enterprise

**What happened**:
need a lot of customizations on values.yaml to add a simple flag

**What you expected to happen**:
a simple enabled flag on values and templated option on helm chart

**How to reproduce it** (as minimally and precisely as possible):
N/A

**Anything else we need to know**:
Internal ticket 211692

**Comment by itssiri** [comment]
Thanks for the request. We will try to include this in upcoming releases.

**Comment by EvertonSA** [comment]
nice, this can be closed
