### ISSUE TITLE
i am getting the error "Registration with router on URL http://localhost:8046 failed with error: UNAVAILABLE: io exception. Trying again" while installing artifactory in my windows machine

### ISSUE THREAD

**Issue by swatikma** [jfrog/charts#1691]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:

**Which chart**:

**Which product license** (Enterprise/Pro/oss):

**JFrog support reference** (if already raised with support team): 

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by Logeshwarsn** [comment]
Hello @swatikma, Could you please provide which version of helm and kubernetes that you are using ? Which chart are you trying to deploy ? Which product license (Enterprise/Pro/oss) that you're using ? Is any support raised with support team ? Could you tell us what happened  and steps to reproduce it ?

**Comment by chukka** [comment]
Marking this as closed , Please reopen with additional information
