### ISSUE TITLE
Inconsistent user/username keys in database blocks causes trouble

### ISSUE THREAD

**Issue by mattmshell** [jfrog/charts#1692]
[

**Is this a request for help?**: No - complaint

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:

NA

**Which chart**:

artifactory

**Which product license** (Enterprise/Pro/oss):

Pro

**JFrog support reference** (if already raised with support team): 

**What happened**:

database and artifactory.database in values.yaml use different keys for the database username. This causes confusion.

**What you expected to happen**:

Support both user and username keys

**How to reproduce it** (as minimally and precisely as possible):

Read documentation, see username key, use username key in database block, observe failure to login. Cry.

**Anything else we need to know**:
](database:)

**Comment by Logeshwarsn** [comment]
Hello @mattmshell, Thanks !! Are you reffering to the actual [username](https://github.com/jfrog/charts/blob/master/stable/artifactory/values.yaml#L690)  in the values.yaml ? Also , please provide chart name  and version

**Comment by mattmshell** [comment]
Yes - that's correct [L690](https://github.com/jfrog/charts/blob/master/stable/artifactory/values.yaml#L690) and [L1841](https://github.com/jfrog/charts/blob/master/stable/artifactory/values.yaml#L1841)

I'm using 7.46.9

**Comment by Logeshwarsn** [comment]
Thanks for raising this. The username that you mentioned is used under systemYaml section and user is used under database section. This is common across all the Jfrog products and i'm not sure change this at this time.
