### ISSUE TITLE
Xray - All db connections are in use (60/60)

### ISSUE THREAD

**Issue by geoff-carr-bzy** [jfrog/charts#1693]
When deploying the latest version of the Artifactory and Xray Helm charts and then running a Xray DB sync, the following warning is received and Xray becomes unresponsive: -

```
2022-11-04T11:31:53.744Z [jfxr ] [WARN ] [7057b425ba284a30] [connection_pool_holder:238 ] [main ] All db connections are in use (60/60) for 2m0.001338841s.service might not be functioning. Consider increasing the server.database.maxOpenConnections configuration parameter
2022-11-04T11:32:53.745Z [jfxr ] [WARN ] [7057b425ba284a30] [connection_pool_holder:238 ] [main ] All db connections are in use (60/60) for 3m0.00224637s.service might not be functioning. Consider increasing the server.database.maxOpenConnections configuration parameter
```

Where can this value be configured and what is the recommended value for a small to medium sized implementation? This does not seem to be an option within the provided `values.yaml` for the Xray chart. There is `postgresql.postgresqlExtendedConf.maxConnections` but that is set to `1500`

I found the following known issue (possibly related), but not sure how to remediate this: -

<html>
<body>

Xray | Artifacts are not indexed and the persist queue continues to grow when the number of persisted workers is increased without properly updating the max-connections configuration. | The issue has not been resolved but a watchdog was introduced to enable faster detection of the misconfiguration.When the problem occurs, the following warning willl appear in the log file:"All db connections are in use (30/30) for 3m. service might not be functioning. Consider increasing the persist.database.maxOpenConnections configuration parameter".
-- | -- | --

</body>
</html>

**Comment by geoff-carr-bzy** [comment]
So after some digging, does seem to be set to `60` connections by default as you can see this in the `xray-server` log on startup: -
```
[jfxr ] [INFO ] [ ] [connection_pool_holder:189 ] [main ] Setting database max open connections 60
```
In addition, looks like you can set this value in `/opt/jfrog/xray/var/etc/system.yaml` which is populated from the `xray-system-yaml` secret in the following format: -
```
server:
  database:
    maxOpenConnections:
```
The `xray-system-yaml` secret seems to be generated from the contents of `systemYaml: |` in the `values.yaml` file.

I guess iot would be good to understand what the different between this setting, which seems to be the one in use based on the warning I was receiving above, and  the `postgresql.postgresqlExtendedConf.maxConnections` setting.

I am running another DB sync with `maxOpenConnections` set to `500` to see what happens. This may well not be the preferred solution so hopefully someone can advise on what is.

**Comment by chukka** [comment]
@geoff-carr-bzy can you please reach out to [jfrog support team](https://jfrog.com/support/) who can do a one on one session to diagnose and provide an optimal solution

**Comment by geoff-carr-bzy** [comment]
Going to close this as we did engage with support and they have not been able to reproduce the issues we were seeing. I suspect the specific issue above may have been related to clashing `values.yaml` files.
