### ISSUE TITLE
find command not found in ubi-minimal:8.6-902 container

### ISSUE THREAD

**Issue by mikeycmccarthy** [jfrog/charts#1697]
**Is this a request for help?**:

Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
3.7 / 1.21

**Which chart**:
artifactory

**Which product license** (Enterprise/Pro/oss):
Enterprise+

**JFrog support reference** (if already raised with support team): 
N/A

**What happened**:
We attempted an upgrade from 7.35.1 to 7.46.11. An initContainer failed as it attempted to perform an operation related to circle of trust:

```bash
- name: "copy-circle-of-trust-certificates"
        image: "{{ .Values.initContainerImage }}"
        imagePullPolicy: "{{ .Values.artifactory.image.pullPolicy }}"
        command:
        - 'sh'
        - '-c'
        - >
          echo 'Copy custom certificates to /var/opt/jfrog/artifactory/etc/access/keys/trusted';
          find /tmp -type f -name "jfrog*.crt" -exec cp -v {} {{ .Values.artifactory.persistence.mountPath }}/etc/access/keys/trusted \;
        volumeMounts:
          - mountPath: "{{ .Values.artifactory.persistence.mountPath }}"
            name: artifactory-volume
          - mountPath: /tmp
            name: circle-of-trust-certs
            readOnly: true
```

The failure came because the find command is missing from the ubi-minimal:8.6-902 image that is the default initContainerImage.

This seems to be a repeat of https://github.com/jfrog/charts/issues/1548.

**What you expected to happen**:
A nice smooth upgrade!

**How to reproduce it** (as minimally and precisely as possible):
Add an initContainer that uses a find command and the default initContaimer image. The service will not start.

**Anything else we need to know**:
This one is confusing as I was looking at the Red Hat versions of that image to find out at what point find was removed, and it seems that find has not been there for a long time. I managed to make things work by using releases-docker.jfrog.io/jfrog/ubi-minimal:8.5-204 as an image for that specific initContainer but could not see the find binary inside the Red Hat version. I then found https://github.com/jfrog/charts/issues/1548, which has led me to believe that this a a JFrog patched version of a RedHat image of the same name.

**Comment by chukka** [comment]
@mikeycmccarthy  Yes, we removed `find` binary in latest initContainer image  to be in sync with upstream redhat UBI image . please change your command , pls refer [here](https://github.com/jfrog/charts/blob/master/stable/artifactory/templates/_helpers.tpl#L293)

`for file in $(ls -1 /tmp/certs/* | grep -v .key | grep -v ":" | grep -v grep); do if [ -f "${file}" ]; then cp -v ${file} {{ .Values.artifactory.persistence.mountPath }}/etc/security/keys/trusted; fi done;
`

**Comment by chukka** [comment]
This is already documented in  107.41.x [changelog](https://github.com/jfrog/charts/blob/master/stable/artifactory/CHANGELOG.md#107410---june-27-2022)

**Comment by mikeycmccarthy** [comment]
Amazing, thank you @chukka . We switched to this and it worked perfectly!
