### ISSUE TITLE
Deploy Artifactory HA and Xray on disconnected Openshift cluster.

### ISSUE THREAD

**Issue by sriram0721** [jfrog/charts#1704]
**Version of Helm and Kubernetes**:

Openshift 4.11.13 ( Disconnected offline cluster)

**Which chart**:
artifactory HA

**Which product license** (Enterprise/Pro/oss):
Entreprise X

**JFrog support reference** (if already raised with support team): 

**What happened**:
Unable to install using helm chart on openshift cluster as it don't have any internet access

**What you expected to happen**:
Probable solution for this to installation method for disconnected openshift cluster

**Anything else we need to know**:

Hello, we are trying to deploy Jfrog Enterprise X on Openshift. Our cluster is set up in disconnected mode, which means it doesn't have any outbound connectivity to operators or internet. We have a bastion host to connect to the cluster. This bastion has limited internet access.

We tried installing through helm chart from the bastion hosts, though the worker nodes don't have internet it's unable to pull the docker image from the registry!.

Is there any recommended way of installing artifactory and x-ray ?

**Comment by chukka** [comment]
@sriram0721  can you please raise this openshift related issue in [here](https://github.com/jfrog/JFrog-Cloud-Installers/issues)
