### ISSUE TITLE
Publish PDN node chart

### ISSUE THREAD

**Issue by bmanuel** [jfrog/charts#1706]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): feature

**Which chart**:

pdn-node

**Which product license** (Enterprise/Pro/oss):

Enterprise

**What happened**:

JFrog published a PDN node helm chart as documented [here](https://www.jfrog.com/confluence/display/JFROG/Installing+PDN+Node#InstallingPDNNode-InstallingPDNNodeUsingHelm).

**What you expected to happen**:

PDN node chart is available for reference in this git repository.

**Comment by shahiinn** [comment]
@bmanuel : We will check internally regarding this and get back to you soon with an update.

**Comment by shahiinn** [comment]
Currently we do not have plans to make PDN node chart available on our github.
If you have any specific use case with PDN, we would recommend you open a support ticket.

**Comment by bmanuel** [comment]
Can you explain why this particular chart is not being made available so that users are better able to review it and submit issues/fixes?
