### ISSUE TITLE
Purpose of the non HA chart

### ISSUE THREAD

**Issue by mikeycmccarthy** [jfrog/charts#1708]
**Is this a request for help?**:

Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Technically neither!

**Version of Helm and Kubernetes**:
Helm 3.8
K8s 1.21

**Which chart**:
artifactory / artifactory-ha

**Which product license** (Enterprise/Pro/oss):
Enterprise

**JFrog support reference** (if already raised with support team): 
N/A

**What happened**:
We worked with JFrog around a new installation of JFrog and in several places we were going to use HA. We were told at some point that the artifactory-ha chart was going to be deprecated and all functionality moved to the regular artifactory chart. We were shown how we could use the non-ha chart to get an HA installation working.

Apparently JFrog's position has changed on this now and the two charts will continue to be developed simultaneously. We will need to migrate existing instances using the non-ha chart to the ha one ideally, which we haven't yet worked out how to do.

Our question is, what would choose someone to continue to use the non-HA chart vs the HA one with a single node? I can see that if you thought you would never, ever go HA then maybe it isn't necessary, but if there's even a chance you might want to add an HA node later then the pain of migrating would presumably make you seriously consider the HA chart from day one. Or have we missed something?

**What you expected to happen**:

N/A

**How to reproduce it** (as minimally and precisely as possible):

N/A

**Anything else we need to know**:

N/A

**Comment by itssiri** [comment]
Thanks for raising this issue. If you are using existing artifactory HA chart please continue to use it for upgrades.
If it is a fresh installation, you can use artifactory chart also..we support both the charts.
Note: If you are using artifactory chart and wish to increase/move to HA mode we would recommend increasing the replica count in values of artifactory chart via helm. But we don’t support migrating from artifactory chart to artifactory HA chart.

**Comment by mikeycmccarthy** [comment]
Hi all,

Please feel free to close this one up, I had a really good session with @gitta-jfrog who explained why there is a separate HA and non HA chart and how it is going to stay like that for the foreseeable future.

Kind Regards,
Michael

**Comment by nxf5025** [comment]
> Hi all,
> 
> Please feel free to close this one up, I had a really good session with @gitta-jfrog who explained why there is a separate HA and non HA chart and how it is going to stay like that for the foreseeable future.
> 
> Kind Regards, Michael

Hey @mikeycmccarthy - Possible to provide some insight on that discussion? We are about to go through with the new HA setup, but it's not clear which chart to use considering the docs even says you can use either - https://jfrog.com/help/r/jfrog-installation-setup-documentation/install-artifactory-ha-with-helm

**Comment by mikeycmccarthy** [comment]
Hi @nimerb , absolutely, I'll dig out my notes and share them here. I would strongly suggest you use the HA charts based on our experience. We started with them, then we pivoted and started again with the non HA charts as we were told they were to be deprecated, then the decision was made that they would be kept, sadly too late for us.

**Comment by gitta-jfrog** [comment]
Hi All,
Both "artifactory" and "artifactory-ha" charts support deployments of Artifactory High-Availability mode.

Main features that exist exclusively in the 'artifactory-ha' chart:
- [NFS Support](https://github.com/jfrog/charts/blob/master/stable/artifactory-ha/values.yaml#L921) -  Outdated implementation, NFS can be implemented with 'customVolumeMounts' on artifactory chart.
- [existingSharedClaim](https://github.com/jfrog/charts/blob/master/stable/artifactory-ha/values.yaml#L901C7-L901C26) - Mostly relevant when the Filestore located on Artifactory PVCs.

We plan to focus on the 'jfrog-platform' chart as the main chart for JFrog customers. The jfrog-platform chart allows customers to maintain one single chart for all of JFrog products.
**The 'jfrog-platform' chart uses artifactory chart as a dependency.** 

For new deployments, I would suggest picking the 'jfrog-platform' chart. 
Here is an example of how to use the platform chart to install only Artifactory and Xray:

```helm repo add jfrog https://charts.jfrog.io
helm repo update
kubectl create ns jfrog-platform

helm upgrade --install jfrog-platform -n jfrog-platform jfrog/jfrog-platform \
     --set artifactory.mc.enabled=false \
     --set distribution.enabled=false \
     --set redis.enabled=false \
     --set pipelines.enabled=false \
     --set insight.enabled=false
```

Yarden.
