### ISSUE TITLE
Jfrog Platform with Artifactory 7.49

### ISSUE THREAD

**Issue by EvertonSA** [jfrog/charts#1713]
Hello, is 7.49 Artifactory planned to be released on the chart soon?
---
edit:
is 7.49 Artifactory planned to be released on jfrog-platform helm chart soon?

**Comment by Logeshwarsn** [comment]
@EvertonSA  107.49.3 is already available in charts.jfrog.io. And can be consumed.

Note : Sources for this chart will be available soon on github.

**Comment by EvertonSA** [comment]
thanks for the info,

I actually mean to ask for jfrog platform:

helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "runix" chart repository
...Successfully got an update from the "mvisonneau" chart repository
...Successfully got an update from the "hashicorp" chart repository
...Successfully got an update from the "sonarqube" chart repository
...Successfully got an update from the "external-secrets" chart repository
...Successfully got an update from the "gitlab" chart repository
...Successfully got an update from the "prometheus-community" chart repository
...Successfully got an update from the "jfrog" chart repository

helm search repo -l jfrog-platform
NAME                    CHART VERSION   APP VERSION     DESCRIPTION
jfrog/jfrog-platform    10.10.2         7.47.14         The Helm chart for JFrog Platform (Universal, h...
jfrog/jfrog-platform    10.10.1         7.47.12         The Helm chart for JFrog Platform (Universal, h...
jfrog/jfrog-platform    10.10.0         7.47.11         The Helm chart for JFrog Platform (Universal, h...
jfrog/jfrog-platform    10.9.4          7.46.11         The Helm chart for JFrog Platform (Universal, h...
jfrog/jfrog-platform    10.9.3          7.46.10         The Helm chart for JFrog Platform (Universal, h...

**Comment by Logeshwarsn** [comment]
@EvertonSA We are planning to do early release next week.

**Comment by EvertonSA** [comment]
thanks, i will close this them

**Comment by chukka** [comment]
@EvertonSA Published , please try now
