### ISSUE TITLE
Separate chart releases from component releases

### ISSUE THREAD

**Issue by bmanuel** [jfrog/charts#1719]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): feature

**Which chart**:

All

**What you expected to happen**:

Changes to the charts are made available in a timely fashion instead of waiting on component releases. This is especially noticeable for components that are released less frequently like PDN and distribution. On those charts, fixes can take months to arrive, forcing users to manually patch their deployments.

**Comment by TJM** [comment]
Suggestion: Use `-` releases... like 1.2.3-1, 1.2.3-2

I *think* that is still semantic version compatible, and it allows you to release multiple versions of the helm chart for one product version.
