### ISSUE TITLE
[jfrog-platform] Upgrade on UBI Image caused big incident

### ISSUE THREAD

**Issue by EvertonSA** [jfrog/charts#1721]
hello,

we recently upgraded to latest chart available (jfrog-platform 10.11.0)  and all LDAP connections started to fail.

on `copy-custom-certificate` container logs, we have the following:

```
Copy custom certificates to /var/opt/jfrog/xray/etc/security/keys/trusted
bash: grep: command not found
bash: grep: command not found
bash: grep: command not found
```

**Comment by EvertonSA** [comment]
this is the current image: releases-docker.jfrog.io/ubi8/ubi-micro:8.7.1

**Comment by EvertonSA** [comment]
![image](https://user-images.githubusercontent.com/30481051/212460757-20c574f0-30ae-47a0-b70a-8b73999b079e.png)

**Comment by EvertonSA** [comment]
please fix, its a massive bug:
```
docker run -it releases-docker.jfrog.io/ubi8/ubi-micro:8.7.1
Unable to find image 'releases-docker.jfrog.io/ubi8/ubi-micro:8.7.1' locally
8.7.1: Pulling from ubi8/ubi-micro
fdb82fb306d5: Pull complete
Digest: sha256:0dd9ca9a660381758518d7ce0ad340d94606ed28dd1e6bd64d861b2a00c8435b
Status: Downloaded newer image for releases-docker.jfrog.io/ubi8/ubi-micro:8.7.1
sh-4.4# grep
sh: grep: command not found
```

**Comment by EvertonSA** [comment]
internal jfrog support ticket number 231869

**Comment by srinivasgowda097** [comment]
@EvertonSA  Thanks for raising. As a workaround can you please use

**Comment by chukka** [comment]
Please try latest  jfrog-platform chart -`10.11.1`  and share feedback

**Comment by EvertonSA** [comment]
@chukka will try, unfortunately, needs to be done on weekends.

**Comment by EvertonSA** [comment]
confirm its working now
