### ISSUE TITLE
init containers for postgres setup have incorrect address in commands

### ISSUE THREAD

**Issue by humzam96** [jfrog/charts#1726]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

-->

**Version of Helm and Kubernetes**:
Helm v3.8.0
OpenShift 4.10 (Kubernetes v1.23.5)

**Which chart**:
10.11.1 jfrog-platform

**Which product license** (Enterprise/Pro/oss):
Enterprise 

**JFrog support reference** (if already raised with support team): 
n/a

**What happened**:
init containers on non artifactory pods are stuck on loop waiting for artifactory because the service name cannot be customized and is incorrect. Under stable/jfrog-platform/templates/_helpers.tpl line 82 we cannot change the nc command to match what the name of the service is. When manually editing out "-artifactory" it works fine.

**What you expected to happen**:
The init container should be able to have a custom command. 

**How to reproduce it** (as minimally and precisely as possible):
Change the jfrogUrl, and the expected behavior is the init containers find artifactory. 

**Anything else we need to know**: n/a

**Comment by chukka** [comment]
@humzam96 Can you please share your values.yaml  and also share logs which you encountered

**Comment by chukka** [comment]
I'm marking this as closed, feel free to reopen if its still an issue
