### ISSUE TITLE
Jfrog Helm Repository Not Returning Charts

### ISSUE THREAD

**Issue by TheRealDwright** [jfrog/charts#1727]
**Version of Helm and Kubernetes**:
Helm:
```
version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.19"}
```
Kubernetes:
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.12", GitCommit:"b058e1760c79f46a834ba59bd7a3486ecf28237d", GitTreeState:"clean", BuildDate:"2022-07-13T14:52:41Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.13-eks-fb459a0", GitCommit:"55bd5d5cb7d32bc35e4e050f536181196fb8c6f7", GitTreeState:"clean", BuildDate:"2022-10-24T20:35:40Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
```
**Which chart**:
Artifactory 107.33.12

**Which product license** (Enterprise/Pro/oss):
OSS

**JFrog support reference** (if already raised with support team): 
Install artifactory (reference chart renderer)
```
apiVersion: khelm.mgoltzsche.github.com/v2
kind: ChartRenderer
metadata:
  name: artifactory
repository: https://charts.jfrog.io
chart: artifactory
version: 107.33.12
valueFiles:
  - values.yaml

```

kustomization.yaml:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generators:
  - chart-renderer.yaml
```

**What happened**:
Starting today https://charts.jfrog.io started throwing chart "artifactory" version "107.33.12" not found in repository https://charts.jfrog.io

**What you expected to happen**:
The chart to be downloaded.

**How to reproduce it** (as minimally and precisely as possible):
kustomize build . --enable-alpha-plugins using the above kustomization and chart renderer.

**Anything else we need to know**:

**Comment by chukka** [comment]
@TheRealDwright Thanks for raising this issue ! we are working with concerned team on high priority ! we will share an update soon .

**Comment by zagaria** [comment]
Have the same issue - charts are not available and block upgrade process.

Physically chart exists but https://charts.jfrog.io/index.yaml is empty

**Comment by chukka** [comment]
@zagaria @TheRealDwright can you please verify if every thing is good now ?

**Comment by zagaria** [comment]
@chukka works, thanks!

**Comment by TheRealDwright** [comment]
LGTM
