### ISSUE TITLE
Distribution Redis container shuts down every minute

### ISSUE THREAD

**Issue by dennisheller-nokia** [jfrog/charts#1729]
### Is this a request for help?:
no

### Is this a BUG REPORT or FEATURE REQUEST? (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Kubernetes v1.23.14
Helm v3.8.1

**Which chart**:
distribution

**Which product license** (Enterprise/Pro/oss):
Enterprise

**JFrog support reference** (if already raised with support team): 

**What happened**:
Distirbution pod randomly gets restarted

**What you expected to happen**:
Distribution pod running forever without manual interaction

**How to reproduce it** (as minimally and precisely as possible):
Dont know, occurs randomly

**Anything else we need to know**:
We had the same problem already: #1655 
Was fixed by increasing the readiness and liveliness timeout from 1 to 5 seconds.
Now we are starting to face the same issue again under high load. 

▶️  **_would it be possible to make the timeout configurable?_**

**Comment by kammathavaran** [comment]
Thanks for reporting this issue. I will get back to after investigating the case.
