### ISSUE TITLE
Existing PVC Name in Artifactory-HA is incorrect

### ISSUE THREAD

**Issue by sanjeevkarani** [jfrog/charts#173]
Existing PVC Name in values.yaml shows the following:

## If true, you must prepare a PVC with the name e.g `artifactory-ha-member`

We have noticed the "Existing PVC Name" as following:
volume-artifactory-ha-artifactory-ha-primary
volume-artifactory-ha-artifactory-ha-member

This is not Documented anywhere and causes issue when mapping the artifactory-ha deployment to existing claims.

**Comment by jainishshah17** [comment]
@sanjeevkarani Artifactory selects PVC which matches the label `app: artifactory-ha-primary` and `app: artifactory-ha-member`.  Which means when you create PVC manually you will need to create it with the following labels.

I will change documentation to 
**If true, you must prepare a PVC with the name e.g `app: artifactory-ha-primary`**
**If true, you must prepare a PVC with the label e.g `app: artifactory-ha-member`**

**Comment by eldada** [comment]
@jainishshah17 - was this done?
