### ISSUE TITLE
Artifactory Intermittently throws Http 500 error on openshift

### ISSUE THREAD

**Issue by sriram9707** [jfrog/charts#1731]
**Is this a request for help?**:

---

** BUG REPORT ** :

**Version of Helm and Kubernetes**: Openshift 4.11 , Helm 3

**Which chart**: Artifactory

**Which product license** Enterprise

**JFrog support reference** : 236806 

**What happened**: 

We have installed jfrog on openshift cluster ( artifactory chart with 2 replicas )  which serves as our dependency management. When we pull/push images, we intermittently face HTTP Internal Sever 500 error on the console. And the same image is getting pulled after few hours. THis is causing a huge impact for us as its not stable. 

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
`###########################################################

###########################################################
ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
ssl_certificate  /var/opt/jfrog/nginx/ssl/artifactory-nginx-jfrog.apps.non-prod-dmz.ncbnpr.local.crt;
ssl_certificate_key  /var/opt/jfrog/nginx/ssl/artifactory-nginx-jfrog.apps.non-prod-dmz.ncbnpr.local.key;
ssl_session_cache shared:SSL:1m;
ssl_prefer_server_ciphers   on;
## server configuration

server {
    listen 443 ssl;
    listen 80;

    server_name ~(?<repo>.+)\.artifactory.jfrog.svc.cluster.local:443 artifactory.jfrog.svc.cluster.local:443;

    if ($http_x_forwarded_proto = '') {

        set $http_x_forwarded_proto  $scheme;

    }

    ## Application specific logs

    access_log /var/log/nginx/artifactory-access.log timing;

    error_log /var/log/nginx/artifactory-error.log;

    rewrite ^/$ /ui/ redirect;

    rewrite ^/ui$ /ui/ redirect;

    proxy_buffer_size          128k;

    proxy_buffers              4 256k;

    proxy_busy_buffers_size    256k;

    chunked_transfer_encoding on;

    client_max_body_size 0;

    location / {

    proxy_read_timeout  4200s;

    proxy_pass_header   Server;

    proxy_cookie_path   ~*^/.* /;

    proxy_pass          http://artifactory:8082;

    proxy_set_header    X-JFrog-Override-Base-Url $http_x_forwarded_proto://$host;

    proxy_set_header    X-Forwarded-Port  $server_port;

    proxy_set_header    X-Forwarded-Proto $http_x_forwarded_proto;

    proxy_set_header    Host              $http_host;

    proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;

        location ~ ^/artifactory/ {

            proxy_pass    http://artifactory:8081;

        }

    }

}`

**Comment by kammathavaran** [comment]
Please reach out to support and provide more details on this issue.
