### ISSUE TITLE
[artifactory-jcr] add preStartCommand

### ISSUE THREAD

**Issue by TJM** [jfrog/charts#1733]
**Is this a request for help?**: no

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**:
helm 3.11.1
kubernetes 1.25.3

**Which chart**: `artifactory-jcr`

**Which product license** (Enterprise/Pro/oss): N/A

**JFrog support reference** (if already raised with support team): 238182

**What happened**: tried to use `preStartCommand` (per support) to create initial admin token as documented:
* https://www.jfrog.com/confluence/display/JFROG/Helm+Charts+for+Advanced+Users
* https://www.jfrog.com/confluence/display/JFROG/Managing+Keys#ManagingKeys-CreatinganAutomaticAdminToken

**What you expected to happen**: prestartCommand should run, but it is not part of the artifactory-jcr chart

**How to reproduce it** (as minimally and precisely as possible):
```
helm upgrade --install artifactory jfrog/artifactory --version 107.49.8 --set "artifactory.preStartCommand=touch /var/opt/jfrog/artifactory/bootstrap/etc/access/keys/generate.token.json"
```

**Anything else we need to know**:

This should just be copy/paste from the artifactory chart to the artifactory-jcr chart.
It wold also be nice if the `NOTES.txt` were updated to be more like the stable/artifactory chart.

**Comment by eldada** [comment]
Hi @TJM . 
Since this is a wrapper chart, you need one level deeper in to get to artifactory chart (`artifactory.artifactory`).
```
helm upgrade --install artifactory jfrog/artifactory --version 107.49.8 --set "artifactory.artifactory.preStartCommand=touch /var/opt/jfrog/artifactory/bootstrap/etc/access/keys/generate.token.json"
```

Try it and let us know.

**Comment by TJM** [comment]
Yep, sorry!
