### ISSUE TITLE
Loadbalancer service not being deployed "internally"

### ISSUE THREAD

**Issue by BJWRD** [jfrog/charts#1747]
**Is this a request for help?**:

Yes

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
Helm: v3.10.1
Kubernetes: v1.25

**Which chart**:
artifactory

**Which product license** (Enterprise/Pro/oss):
Pro

**JFrog support reference** (if already raised with support team): 
N/A

**What happened**:
Loadbalancer is deployed as internet-facing despite the annotation entry

**What you expected to happen**:
Loadbalancer to be deployed internally facing

**How to reproduce it** (as minimally and precisely as possible):
helm install artifactory jfrog/artifactory --set nginx.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-scheme"="internal"

**Anything else we need to know**:

**Comment by BJWRD** [comment]
Also, it's worth mentioning I've tried multiple variations of the annotation which should provision an internally facing Loadbalancer, but it seems the following annotation is the correct one to use at this current moment - **service.beta.kubernetes.io/aws-load-balancer-scheme:**

**Comment by Logeshwarsn** [comment]
@BJWRD Can you try as suggested as below ,
https://stackoverflow.com/questions/37869727/kubernetes-support-for-internal-load-balancers-in-aws ?

**Comment by BJWRD** [comment]
@Logeshwarsn If you see the latest comment in the StackOverflow question, you can see that the updated annotation to use in this instance is - **service.beta.kubernetes.io/aws-load-balancer-scheme:** 

Which is what I have previously used, as suggested above.

**Comment by BJWRD** [comment]
Apologies, I have been customising the values.yaml file (see below). Are you suggesting that the annotations should be included within nginx block, opposed to the LoadBalancer block? At this moment in time a classic load balancer is being provisioned -

```    
nginx:
  enabled: true
  tlsSecretName: foo
## LoadBalancer
service:
  ssloffload: true
  type: LoadBalancer
  annotations:
   service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: "true"
   service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
   service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
   service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"

**Comment by gitta-jfrog** [comment]
Yes, This 'service' block should be under the 'nginx' block.
As you can see in [nginx-service.yaml](https://github.com/jfrog/charts/blob/master/stable/artifactory/templates/nginx-service.yaml#L14) template, the annotations are taken from '.Values.nginx.service.annotations '

`
nginx:
  enabled: true
  tlsSecretName: foo
  service:
    ssloffload: true
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"`

**Comment by BJWRD** [comment]
@gitta-jfrog Thanks for the clarification.

I have since applied this to my values.yaml file, however it seems that once deployed the annotations are not being applied to the Loadbalancer service. This is what I see once I edit the service directly using kubectl -

![image](https://user-images.githubusercontent.com/83971386/233776212-c50344b5-b2f5-496c-ae17-ea88b1dc21c5.png)


If I add the annotations while editing the running service the majority of them are applied, but it seems that the **service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"** annotation is not updating the Loadbalancer to an **Internal** Scheme -

![image](https://user-images.githubusercontent.com/83971386/233776080-78d2ac0b-e562-4fb6-bf2e-18c00996cace.png)

To make things easier, here's my complete values.yaml file contents -

 ``` # This chart is based on the main artifactory chart with some customizations.
# See all supported configuration keys in https://github.com/jfrog/charts/tree/master/stable/artifactory
## Role Based Access Control
rbac:
  create: true
  role:
    ## Rules to create. It follows the role specification
    rules:
    - apiGroups:
      - "*"
      resources:
      - "*"
      verbs:
      - "*"
      subjects:
      - kind: User
        name: artifactory
        api_group: rbac.authorization.k8s.io
        namespace: artifactory-oss
## Service Account
serviceAccount:
  create: true
  name: artifactory
  annotations: 
    kubernetes.io/service-account.name: artifactory
## Artifactory
artifactory:
    ## SSL Certificate
## certificates added to this secret will be copied to $JFROG_HOME/artifactory/var/etc/security/keys/trusted directory
  customCertificates:
    enabled: true
    certificateSecretName: foo
  image:
    registry: releases-docker.jfrog.io
    repository: jfrog/artifactory-pro
  persistence:
    size: 50Gi
  resources: 
    requests:
      memory: "4Gi"
      cpu: "2"
    limits:
      memory: "8Gi"
      cpu: "6"
    ## The following Java options are passed to the java process running Artifactory.
  javaOpts: 
    xms: "4g"
    xmx: "6g"
## Nginx
nginx:
  enabled: true
  service:
    ssloffload: true
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
      service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "Environment=Foo"
  externalTrafficPolicy: Local
  http:
    enabled: true
    externalPort: 80
    internalPort: 80
  https:
    enabled: true
    externalPort: 443
    internalPort: 443
  labels:
    app: artifactory-nginx
  tlsSecretName: foo-secret
## Ingress
ingress:
  enabled: false
## Autoscaling
#autoscaling:
#  enabled: true
#  minReplicas: "1"
#  maxReplicas: "3"
## PostgreSQL
postgresql:
  enabled: true
  image:
    registry: releases-docker.jfrog.io
    repository: bitnami/postgresql
    tag: 13.9.0-debian-11-r11
  labels:
    app: artifactory-postgresql
  ## This key is required for upgrades to protect old PostgreSQL chart's breaking changes.
  databaseUpgradeReady: "yes"
  ## If NOT using the PostgreSQL in this chart (artifactory.postgresql.enabled=false),
  ## specify custom database details here or leave empty and Artifactory will use embedded derby.
  # database:
  jfconnect:
    enabled: false

**Comment by BJWRD** [comment]
@gitta-jfrog 
Update: The other Loadbalancer annotations are now being passed to the Loadbalancer service upon deployment. But the **service.beta.kubernetes.io/aws-load-balancer-scheme: "internal** annotation is still not being passed to the Loadbalancer.

Have you been able to replicate this?

**Comment by gitta-jfrog** [comment]
Hi @BJWRD , I managed to provision an Internal Classic LB by adding the following annotation
`service.beta.kubernetes.io/aws-load-balancer-internal: "true"`

![image](https://user-images.githubusercontent.com/69511528/233993789-77edbf9a-5410-4689-86e9-e4c96317d215.png)

Looks like you can use the annotation "aws-load-balancer-scheme" only as part of "[aws-load-balancer-controller](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.5/deploy/installation/)" in your EKS cluster.

You can find [here](https://github.com/gitta-jfrog/kubernetes/blob/main/eks/alb/ingress-nginx/README.md) an example of how to implement JFrog Artifactory with AWS ALB based on the 'aws-load-balancer-controller'.

**Comment by BJWRD** [comment]
Thanks @gitta-jfrog - that seems to have done the trick! 

I appreciate your help on this 👍
