### ISSUE TITLE
[platform] Update xray chart to 3.71.6

### ISSUE THREAD

**Issue by bmanuel** [jfrog/charts#1750]
**Is this a request for help?**: no

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): feature request

**Which chart**:
platform

**Which product license** (Enterprise/Pro/oss):
enterprise

**What you expected to happen**:
Xray subchart in the platform chart is updated to the latest version (3.71.6)

**Comment by Logeshwarsn** [comment]
@bmanuel We are planning to release a new patch version with xray 3.71.6 on next week.

**Comment by bmanuel** [comment]
@Logeshwarsn any updates on this?

**Comment by Logeshwarsn** [comment]
@bmanuel There is a small change in xray 3.71.6 ,how it handles non default vhosts .Please refer to this [release notes ](https://jfrog.com/help/r/jfrog-release-information/xray-3.71.6). We are currently testing that change in the platform chart. Hence the delay. We would be releasing new version in coming days (day or two).

**Comment by chukka** [comment]
@bmanuel Here we go , jfrog-platform `10.12.2` chart has this change
