### ISSUE TITLE
Service is healthy; there are missing services: jfmd

### ISSUE THREAD

**Issue by AliyevH** [jfrog/charts#1752]
**Is this a request for help?**: YES
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**Version of Helm and Kubernetes**:
HELM: v3.11.2
KUBERNETES: v1.24.8+k3s1

**Which chart**:
[Artifactory](https://github.com/jfrog/charts/tree/master/stable/artifactory)

**Which product license** (Enterprise/Pro/oss): Pro

**What happened**:
Router readiness on URL http://localhost:8046/router/api/v1/system/readiness failed with error: Router readiness failed with status 503. Trying again

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
Just install helm chart with default options.

**Anything else we need to know**:
Response message :

"state": "UNHEALTHY_PEER",
"message": "Service is healthy; there are missing services: jfmd"

But first error i got in logs is:
Failed to decrypt license: last block incomplete in decryption (although the given license seems to be correct when decoding it)

Is is possible that jfmd not starts because of license?
What does these services are doing?

**Comment by oumkale** [comment]
Hi @AliyevH,

Will you please share the full logs? to analyze further.

**Comment by alfred-stokespace** [comment]
I resolved my problem.
It turns out this was all because I was trying to use PostGres 15 and apparently 13 is highest supported.
