### ISSUE TITLE
Multiple existingClaims support for Distribution

### ISSUE THREAD

**Issue by mikeycmccarthy** [jfrog/charts#1754]
**Is this a request for help?**:

This is a feature request.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

In terms of persistence, specifically the Redis persistence I believe, Distribution has the following options from what I can gather:

1. No persistence
2. Bring your own claim
3. Let the chart create the PVC based on the Volume Claim Template within the StatefulSet template

What we're looking for I believe is a fourth option - the ability to bring your own claim but with support for ordinal numbers. As far as I can see the artifactory-ha chart has support for this but the Distribution chart doesn't. If you provide an existingClaimName, that same claim is used for each replica, and no ordinal number is appended.

**Comment by gitta-jfrog** [comment]
Distribution is running by default without persistence and we are not planning to add support for existingClaims for Distribution or Artifactory Chart.
