### ISSUE TITLE
Custom ports S3 compatible storage for Artifactory

### ISSUE THREAD

**Issue by Sura34** [jfrog/charts#1767]
We are using Artifactory enterprise plus. As a backend storage, we are using S3-compatible storage which is deployed in our on-premise environment. 

Our environment is set up as per [this ](https://jfrog.com/help/r/jfrog-installation-setup-documentation/amazon-s3-official-sdk-template) documentation and our s3-compatible storage is accepting traffic in ports **other than** 443 and 80. 

Even though the parameter `port` is supported in `s3-storage-v3` it's not actually working from values in helm. We confirmed this with JFrog support as well. 

We recommended to bootstrap the whole binarystore.xml file from values but this is not the convenient way going forward. Cause it will not be possible for instance to use secrets for credentials. 

So, we need a new feature to be able to support `port ` for S3-compatible backend storage.

**Comment by Logeshwarsn** [comment]
@Sura34 Thanks for reaching us. We will discuss this internally and do the needful.
