### ISSUE TITLE
Artifactory logo is broken

### ISSUE THREAD

**Issue by cyrilc-pro** [jfrog/charts#1768]
**Is this a request for help?**: no

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT 

**Version of Helm and Kubernetes**: N/A

**Which chart**: Artifactory

**Which product license** (Enterprise/Pro/oss): N/A

**JFrog support reference** (if already raised with support team):  N/A

**What happened**: Chart has a broken logo image file

**What you expected to happen**: Chart should have a valid logo

**How to reproduce it** (as minimally and precisely as possible): Check out `stable/artifactory/logo/artifactory-logo.png` on `master`

**Anything else we need to know**:

**Comment by Logeshwarsn** [comment]
@cyrilc-pro Thanks for reporting this. We will look into this and do the needful

**Comment by gitta-jfrog** [comment]
Issue fixed, will be part of next Self-Hosted Minor Release.
