### ISSUE TITLE
Overwrite artifactory.system.properties with helm values

### ISSUE THREAD

**Issue by AliyevH** [jfrog/charts#1769]
**Version of Helm and Kubernetes**: K3s

**Which chart**: https://github.com/jfrog/charts/tree/master/stable/artifactory

**Which product license** (Enterprise/Pro/oss): Pro

**What happened**: RubyGems.org has deprecated the dependency API (api/v1/dependency), moving to the “Compact Index” API mechanism. How can i add directives in artifactory.system.properties file with helm values? Or how can i change existing options?

**Comment by eldada** [comment]
The **artifactory.system.properties** are just a list of system properties passed to the JVM.
You can pass custom java system properties with the values.yaml's `artifactory.javaOpts.other` key.
So I'd recommend keeping a special `values-system-properties.yaml` files with the following format
```
artifactory:
  javaOpts:
    other: >
      -Dartifactory.property.a=value-a
      -Dartifactory.property.b=value-b
```
and install with
```
helm upgrade --install artifactory jfrog/artifactory -f values-system-properties.yaml
```

**Comment by AliyevH** [comment]
@eldada Thanks for response
