### ISSUE TITLE
Limited size S3-compatible backend storage

### ISSUE THREAD

**Issue by Sura34** [jfrog/charts#1780]
We are using custom S3-compatible backend storage which is based on Dell ECS. This storage is deployed in our on-prem infrastructure. 

Unlike Amazon S3, this backend storage has of course limited size. 

Our environment is set up as per [this ](https://jfrog.com/help/r/jfrog-installation-setup-documentation/amazon-s3-official-sdk-template)documentation and it uses `s3-storage-v3`. 

Even though the storage has a limited size, Artifactory assumes the backend is "Amazon S3" with infinite size. 

![image](https://github.com/jfrog/charts/assets/24653853/3c11d465-52a3-484b-bc55-dda3a61ff692)

This makes it difficult to know the size of the backend storage and be alerted when it reaches the threshold. Thus, we require a feature improvement for Artifactory to identify the size of the backend and possibly create max storage for backend s3-compatible storage.

**Comment by kammathavaran** [comment]
Whats the artifactory version and license you are using? Also can you describe your filestore configuration ?

**Comment by shahiinn** [comment]
@Sura34 : Thanks for the details. The issue/feature needs to be implemented in the product side rather than on the helm chart. Can you please open a support ticket with JFrog for the requesting same.
