### ISSUE TITLE
Jfrog Platform wrong update

### ISSUE THREAD

**Issue by EvertonSA** [jfrog/charts#1784]
New jfrog-platform chart supposed to upgrade artifactory but it doesn't...

https://github.com/jfrog/charts/blob/master/stable/jfrog-platform/Chart.yaml#L19C12-L19C20

https://github.com/jfrog/charts/blob/master/stable/artifactory/Chart.yaml#L24C10-L24C19

**Comment by EvertonSA** [comment]
We trust upstream provided jfrog chart. but looks like it's not tested. I hope this does not happen again, otherwise my trust on upstream charts is broken

**Comment by chukka** [comment]
Sorry for that , Fixed and [released](https://github.com/jfrog/charts/commit/ae5a56bfd5fc36a113bce13023ef9c2e8420af2e) as part of  jfrog-platform  release `10.3.3`
