### ISSUE TITLE
[jfrog-platform] chart doesn't work with just `rabbitmq:enabled: false`

### ISSUE THREAD

**Issue by kmorkans** [jfrog/charts#1794]
**Version of Helm and Kubernetes**:

Testing on minikube v1.30.1 and Helm v3.12.2

**Which chart**:

jfrog-platform

**What happened**:

jfrog-platform chart doesn't work with just `rabbitmq:enabled: false`. Needed to provide `rabbitmq:migration:enabled: false` and       `rabbitmq:rabbitmqUpgradeReady: true` as well.
Got error - `Helm install failed: template: jfrog-platform/templates/migration-hook.yaml:80:16: executing "jfrog-platform/templates/migration-hook.yaml" at <.Values.rabbitmq.podSecurityContext.enabled>: nil pointer evaluating interface {}.enabled`

Possible fix was added to `stable/jfrog-platform/templates/migration-hook.yaml` in [10.12.3 release](https://github.com/jfrog/charts/commit/4e3a62662f546fe7b2190614b913bafaab0aa908) but that was reverted in [10.13.0 release](https://github.com/jfrog/charts/commit/f418d0484a80e640a113642154e86fe84b902515)

**What you expected to happen**:

As per default values file I expected just to be able to set  `rabbitmq:enabled: false`.

**How to reproduce it** (as minimally and precisely as possible):

Try and install jfrog-platform chart with just `rabbitmq:enabled: false`.

**Anything else we need to know**:

**Comment by chukka** [comment]
@kmorkans Thanks for reporting , this will be fixed ASAP
