### ISSUE TITLE
[artifactory] values.yaml needs fixing

### ISSUE THREAD

**Issue by dfgrosso** [jfrog/charts#1800]
**Is this a request for help?**: 
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

DESCRIPTION

The "values.yaml" file on stable/artifactory-oss has 2 errors.

The last property group, router, is misplaced. Needs a tab.

The property group before that, postgresql, is duplicated.

Tried to PR the fix myself but I couldn't. My PR failed (I'm bit newbie on Github) :p

**Version of Helm and Kubernetes**:

N/A

**Which chart**:

Artifactory 107.63.7

**Which product license** (Enterprise/Pro/oss):

OSS

**JFrog support reference** (if already raised with support team): 

N/A

**What happened**:

N/A

**What you expected to happen**:

N/A

**How to reproduce it** (as minimally and precisely as possible):

N/A

**Anything else we need to know**:

**Comment by srinivasgowda097** [comment]
@dfgrosso  Thanks for raising the issue, we have already identified and have a tracking ticket, will be fixed in upcoming releases
