### ISSUE TITLE
binarystore.xml is not updateable after initial helm install of artifactory-ha

### ISSUE THREAD

**Issue by CarpathianUA** [jfrog/charts#181]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG

**Version of Helm and Kubernetes**: Helm v2.11.0, Kubernetes v1.10.11

**Which chart**: artifactory-ha:8.7.0

**What happened**: binarystore.xml is not updateable after initial ```helm install``` command

**What you expected to happen**: binarystore.xml is propagated from /artifactory_extra_conf to /var/opt/jfrog/artifactory/etc on ```helm upgrade``` if it's changed

binarystore.xml is not updateable after initial ```helm install```

I see that binarystore.xml is mounted from configMap in the chart and Docker image ```docker.bintray.io/jfrog/artifactory-pro``` has an entrypoint-artifactory.sh which should propagate the file from a mentioned folder, but it never happen:
```
addExtraConfFiles () {
    logger "Adding extra configuration files to ${ARTIFACTORY_HOME}/etc if any exist"

    # If directory not empty
    if [ -d "${ARTIFACTORY_EXTRA_CONF}" ] && [ "$(ls -A ${ARTIFACTORY_EXTRA_CONF})" ]; then
        logger "Adding files from ${ARTIFACTORY_EXTRA_CONF} to ${ARTIFACTORY_HOME}/etc"
        cp -rfv ${ARTIFACTORY_EXTRA_CONF}/* ${ARTIFACTORY_HOME}/etc || errorExit "Copy files from ${ARTIFACTORY_EXTRA_CONF} to ${ARTIFACTORY_HOME}/etc failed"
    fi
}
```
Obviously it's happen becauase of next test in entrypoint-artifactory.sh
```
# In case data dirs are missing or not mounted, need to create them
setupDataDirs () {
    logger "Setting up Artifactory data directories if missing"
    if [ ! -d ${ARTIFACTORY_DATA}/etc ]; then
        mkdir -pv ${ARTIFACTORY_DATA}/etc || errorExit "Failed creating ${ARTIFACTORY_DATA}/etc"

        # Add extra conf files to a newly created etc/ only!
        addExtraConfFiles
    fi
    [ -d ${ARTIFACTORY_DATA}/data ]        || mkdir -pv ${ARTIFACTORY_DATA}/data        || errorExit "Creating ${ARTIFACTORY_DATA}/data failed"
    [ -d ${ARTIFACTORY_DATA}/logs ]        || mkdir -pv ${ARTIFACTORY_DATA}/logs        || errorExit "Creating ${ARTIFACTORY_DATA}/logs failed"
    [ -d ${ARTIFACTORY_DATA}/backup ]      || mkdir -pv ${ARTIFACTORY_DATA}/backup      || errorExit "Creating ${ARTIFACTORY_DATA}/backup failed"
    [ -d ${ARTIFACTORY_DATA}/access ]      || mkdir -pv ${ARTIFACTORY_DATA}/access      || errorExit "Creating ${ARTIFACTORY_DATA}/access failed"
    [ -d ${ARTIFACTORY_HOME}/run ]         || mkdir -pv ${ARTIFACTORY_HOME}/run         || errorExit "Creating ${ARTIFACTORY_HOME}/run failed"
    [ -d ${ARTIFACTORY_HOME}/etc/plugins ] || mkdir -pv ${ARTIFACTORY_HOME}/etc/plugins || errorExit "Creating ${ARTIFACTORY_HOME}/etc/plugins failed"
    [ -d ${REPLICATOR_DATA} ]              || mkdir -pv ${REPLICATOR_DATA}              || errorExit "Creating ${REPLICATOR_DATA} failed"
}
```
After initial ```helm install``` persistent volume is created and populated with ${ARTIFACTORY_DATA}/etc so the bash test above will never happen on subsequent ```helm update```s

**How to reproduce it**:
Steps to reproduce:
1. Initially deploy artifactory-ha with ```helm install``` and with operator provided helm values, e.g. -f values.yaml
2. Update binarystore.xml related values in values.yaml, e.g. change IAM role
3. Update Artifactory workload using ```helm upgrade``` with operator provided values, e.g. -f values.yaml and ```--recreate-pods``` parameter
4. ```diff /artifactory_extra_conf/binarystore.xml /var/opt/jfrog/artifactory/etc/binarystore.xml``` - files will be different and binarystore.xml isn't propagated from /artifactory_extra_conf to /var/opt/jfrog/artifactory/etc

**Comment by CarpathianUA** [comment]
Any updates?

**Comment by eldada** [comment]
@CarpathianUA - your observation is correct, and is behaving as designed. The `/artifactory_extra_conf/` was originally meant for bootstrapping and not for updating.
We are discussing the correct behaviour here as some files should not be updated on an upgrade/restart.
Your request is valid.

**Comment by CarpathianUA** [comment]
@eldada thanks for an update!
We really need to have a possibility to update config without full chart redeployment :)

**Comment by eldada** [comment]
@CarpathianUA I have an idea on this. I'm looking into keeping this backwards compatible. Hope to share it in a few days.

**Comment by CarpathianUA** [comment]
Hello JFrog, is there any updates?

**Comment by eldada** [comment]
Sorry @CarpathianUA . No updates yet.

**Comment by danielezer** [comment]
@eldada how about moving binarystore.xml out of the /artifactory_extra_conf/ directory and copying it over to the etc/ directory on startup?
I can implement that if you think that's a valid solution

**Comment by eldada** [comment]
@danielezer , @CarpathianUA - I'm thinking of the following solution that will keep backwards compatibility (this is critical).
- Keep mounting files to `/artifactory_extra_conf/` as before
- Keep a list of files that should also be copied from `/artifactory_extra_conf/` to `ART_DATA/etc/` on every start
- Run over this list and copy the set files right before the `preStartCommand` execution
```
...
        command:
        - '/bin/sh'
        - '-c'
        - >
          {{- if .Values.artifactory.configMapName }}
          echo "Copying bootstrap configs";
          cp -Lrf /bootstrap/* /artifactory_extra_conf/;
          {{- end }}
-----> ADD HERE <------
          {{- if .Values.artifactory.preStartCommand }}
          echo "Running custom preStartCommand command";
          {{ .Values.artifactory.preStartCommand }};
          {{- end }}
          /entrypoint-artifactory.sh
...
```

This way, you must specify exactly what files you want to copy beyond current logic.

Until then, this copy can be added to the `artifactory.preStartCommand`, which is there for exactly such needs.
WDYT?

**Comment by danielezer** [comment]
ok, sounds good. Where would you want that list to be? In the helm chart/as an environment variable?etc...

**Comment by danielezer** [comment]
What do you think about moving the binarystore to another directory instead of using /artifactory_extra_conf? I think that there's no downside to copying the binarystore on each Artifactory startup. I agree that for some of the other files in that directory it could be an issue, but I think that for the binarystore it should be ok

**Comment by eldada** [comment]
That would work but I'm worried about customers that might have already tied an automated process to the current location. This is why I suggested the extra move. Keep existing functionality and add on top of it.

> Where would you want that list to be?

In the `values.yaml` as a commented out block + documentation in README

**Comment by CarpathianUA** [comment]
Hi @eldada, it works for us.
Actually we started to use preStart command to be able to achieve required result. 
But if it's possible, I would rather go with more native way of sysncing binarystory.xml, e.g. move it to another location as @danielezer suggested.

**Comment by danielezer** [comment]
ok @eldada. I'll start working on that when I have some time
