### ISSUE TITLE
[Xray] RabbitMQ migration hook should respect global.imageRegistry

### ISSUE THREAD

**Issue by Atchuu** [jfrog/charts#1816]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug

**Version of Helm and Kubernetes**:

Helm 3.11.0 / Kubernetes 1.24.9

**Which chart**:

Xray 103.81.8

**Which product license** (Enterprise/Pro/oss):

Enterprise

**JFrog support reference** (if already raised with support team): 

**What happened**:

Inside our air-gapped network, an upgrade of Xray with mostly default settings attempts to trigger the pre-upgrade-hook. That template has a hardcoded value for the hooks image's registry path. This is a problem for environments where the Kubernetes nodes cannot reach releases-docker.jfrog.io.

**What you expected to happen**:

The setting for global.imageRegistry (or something else) should be respected and the pre-upgrade-hook container can pull and start

**How to reproduce it** (as minimally and precisely as possible):

- Block network access to releases-docker.jfrog.io
- Trigger upgrade of Xray's rabbitmq
- Notice the ImagePullBackOff

**Anything else we need to know**:

**Comment by chukka** [comment]
Yes, it's fixed internally, will be released in next few weeks (103.83.x mostly)

**Comment by rahulsadanandan** [comment]
This fix is available in the latest onprem charts
103.95.7
