### ISSUE TITLE
[xray] Unable to set log levels

### ISSUE THREAD

**Issue by bmanuel** [jfrog/charts#1821]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature

**Which chart**:

xray

**What you expected to happen**:

There are times that it would be helpful to run xray services with different log levels, especially when trying to debug issues. The chart does not currently support setting the log levels for those services. Ideally, it would be possible to set a global level and then override it for each service individually if necessary.

**Anything else we need to know**:

It is possible to override the system yaml and add the logging, so that is a usable short term fix. Needing a custom system yaml is not ideal since updates in this chart no longer are used, increasing the burden during upgrades.

**Comment by rahulsadanandan** [comment]
@bmanuel We have introduced a new feature that allows overriding the system YAML with the extraSystemYaml section. The entries specified under ‘xray.extraSystemYaml’ will be merged with files/system.yaml to generate the final system.yaml.

https://github.com/jfrog/charts/blob/master/stable/xray/values.yaml#L192-L202

Let us know if this works for you.
