### ISSUE TITLE
changing report row limit for xray chart

### ISSUE THREAD

**Issue by thecloudgeek** [jfrog/charts#1826]
how does one change the report row limit for the xray helm chart? I couldn't quite figure out how the set system.yaml file for xray according to this:
https://jfrog.com/help/r/xray-how-to-bypass-reports-row-limit

**Comment by dortam888** [comment]
On the official [values.yaml](https://github.com/jfrog/charts/blob/master/stable/xray/values.yaml) line 202 you have system.yaml server.
Under it you can insert reports.rowLimits as explained in the article and redeploy.

**Comment by rahulsadanandan** [comment]
@thecloudgeek  Recently have merged a feature (https://github.com/jfrog/charts/pull/1842) that allows overriding the system YAML with the `extraSystemYaml` section. The entries specified under ‘xray.extraSystemYaml’ will be merged with files/system.yaml to generate the final system.yaml. 
This change is available from Xray version 103.95.x onwards.
