### ISSUE TITLE
Azure blob storage needs to be cluster-azure-blob-storage in HA chart

### ISSUE THREAD

**Issue by patbat95008** [jfrog/charts#183]
**Is this a request for help?**:
No. It is an bug report.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
This is a bug report, as one of the chart files is not correctly configured.

**Version of Helm and Kubernetes**:
N/A - The issue is with the Artifactory configuration settings

**Which chart**:
charts/stable/artifactory-ha/

**What happened**:
The Azure storage provider configuration in [charts/stable/artifactory-ha/templates/artifactory-binarystore.yaml](https://github.com/jfrog/charts/blob/master/stable/artifactory-ha/templates/artifactory-binarystore.yaml#L162) is set to use azure-blob-storage, but for artifactory HA this needs to be [cluster-azure-blob-storage ](https://www.jfrog.com/confluence/display/RTF/Configuring+the+Filestore#ConfiguringtheFilestore-AzureBlobStorageClusterBinaryProvider).

Without the sharding implementation in this binary provider, downloads from other nodes will not succeed. This is because Cloud Storage provider binarystore templates assume that a shared NFS mount is used instead of the cluster-sharding system implemented in Artifactory 5.X.

**What you expected to happen**:
When a file is uploaded to Artifactory, other nodes should be able to download the file.

**How to reproduce it** (as minimally and precisely as possible):
Set the filstore type as Azure blob storage, observe that the configuration deployed will not work for an Artifactory HA cluster.

This is located on the primary Kubernetes pod under /var/opt/jfrog/artifactory/etc/binarystore.xml.

**Anything else we need to know**:

This is the template that should be used instead, note it is very similar to the already implemented cluster-google-cloud-storage template:

<config version="2">
    <chain template=“cluster-azure-blob-storage”>
       <provider id=“cache-fs-eventual-azure-blob-storage” type=“cache-fs”>
           <provider id=“sharding-cluster-eventual-azure-blob-storage” type=“sharding-cluster”>
               <sub-provider id=“eventual-cluster-azure-blob-storage” type=“eventual-cluster”>
                   <provider id=“retry-azure-blob-storage” type=“retry”>
                       <provider id=“azure-blob-storage” type=“azure-blob-storage”/>
                   </provider>
               </sub-provider>
               <dynamic-provider id=“remote-azure-blob-storage” type=“remote”/>
           </provider>
       </provider>
   </chain>
 
    
    <provider id="sharding-cluster-eventual-azure-blob-storage" type="sharding-cluster">
        <readBehavior>crossNetworkStrategy</readBehavior>
        <writeBehavior>crossNetworkStrategy</writeBehavior>
        <redundancy>2</redundancy>
        <lenientLimit>1</lenientLimit>
        <property name="zones" value="local,remote"/>
    </provider>
 
    <provider id="remote-azure-blob-storage" type="remote">
        <zone>remote</zone>
    </provider>
 
    <provider id="eventual-cluster-azure-blob-storage" type="eventual-cluster">
        <zone>local</zone>
    </provider>
 
    
    <provider id="azure-blob-storage" type="azure-blob-storage">
        <accountName>XXXXXX</accountName>
        <accountKey>XXXXXX</accountKey>
        <endpoint>https://<ACCOUNT_NAME>.blob.core.windows.net/</endpoint>
        <containerName><NAME></containerName>
    </provider>
</config>

**Comment by felipeac** [comment]
Hi @patbat95008 . It's Felipe here. We've discussed about this issue earlier.
I can create a PR with this change.
Thank you for opening the issue.

**Comment by eldada** [comment]
@felipeac - you are very welcome to submit a PR. We encourage it! 😄

**Comment by jainishshah17** [comment]
@felipeac We are looking forward to getting PR from you.
