### ISSUE TITLE
[Xray] Add ability to configure defaultRetentionDaysForIndexedRepo for Xray

### ISSUE THREAD

**Issue by gregoryboue** [jfrog/charts#1832]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

Currently the Xray indexing default retention period can be [defined in Xray System yaml](https://jfrog.com/help/r/jfrog-security-documentation/indexing-xray-resources) with `server.repo.defaultRetentionDaysForIndexedRepo` settings.

If we want to configure this settings, we have to override xray system yaml (see [systemYamlOverride](https://github.com/jfrog/charts/blob/master/stable/xray/values.yaml#L78)), so it would be great to be able to configure this setting via a value in the chart's values.yaml file.

**Comment by rahulsadanandan** [comment]
@gregoryboue Recently have merged a feature (https://github.com/jfrog/charts/pull/1842) that allows overriding the system YAML with the `extraSystemYaml` section. The entries specified under ‘xray.extraSystemYaml’ will be merged with files/system.yaml to generate the final system.yaml.

https://github.com/jfrog/charts/blob/master/stable/xray/values.yaml#L192-L202

Let us know if this works for you.
