### ISSUE TITLE
Missing docker image

### ISSUE THREAD

**Issue by texn0id** [jfrog/charts#1834]
Is this a BUG REPORT or FEATURE REQUEST? (choose one):
BUG REPORT

DESCRIPTION
When trying to get an image using the following path
docker.bintray.io/jfrog/artifactory-cpp-ce:**7.6.2**
I encounter an error: 

> Error response from daemon: unauthorized: The client does not have permission for manifest: Upstream repository is not configured properly

But at the same time, you can safely get artifactory-cpp-ce:**7.6.1** and artifactory-cpp-ce:**7.6.3**

Version of Helm and Kubernetes:

N/A

Which chart:

Artifactory 2.5.0

Which product license (Enterprise/Pro/oss):

OSS

JFrog support reference (if already raised with support team):

N/A

What happened:

N/A

What you expected to happen:

N/A

How to reproduce it (as minimally and precisely as possible):

N/A

Anything else we need to know:

**Comment by oumkale** [comment]
Hi @texn0id,

Thank you for reporting this issue, it is available now. Please test and let us know.
```
docker pull docker.bintray.io/jfrog/artifactory-cpp-ce:7.6.2
7.6.2: Pulling from jfrog/artifactory-cpp-ce
25e46ad006a2: Already exists
06ea0fb6fd44: Already exists
ec5405997a44: Already exists
c163ef759c66: Already exists
1def433748d7: Already exists
6d52baa3c62f: Already exists
a95ebc011e8e: Already exists
86baa659ab42: Pull complete
ce78eb25c553: Pull complete
0665d7a5a389: Pull complete
1c18ca65bc51: Pull complete
Digest: sha256:704056e9beffb955160fac91a0cb711a9e4cbfbdfd123c685e8e8fb2d6d27419
Status: Downloaded newer image for docker.bintray.io/jfrog/artifactory-cpp-ce:7.6.2
docker.bintray.io/jfrog/artifactory-cpp-ce:7.6.2
```

**Comment by texn0id** [comment]
@oumkale thanks for the solution
