### ISSUE TITLE
Maintaining logs by days

### ISSUE THREAD

**Issue by Nathan770** [jfrog/charts#1843]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**:
Helm: v3.11.0
Kubernetes: v1.26.3
**Which chart**:
Jfrog-platform: 10.16.2

**Which product license** (Enterprise/Pro/oss): Enterprise+

**JFrog support reference** (if already raised with support team): 

**What happened**:
The logs were deleted after 10 files, and we have many users using the platform, so we want to keep 30 days of logs.

**What you expected to happen**:
Maintaining at least 30 days of logs by default.

**How to reproduce it** (as minimally and precisely as possible):
Create a lot of traffic on the JFrog platform.

**Anything else we need to know**:

**Comment by shahiinn** [comment]
The log rotation configuration of jfrog applications are configurable through [system.yaml](https://jfrog.com/help/r/jfrog-installation-setup-documentation/artifactory-system-yaml-configuration-topics)(The default value is set to rotate on 10 files).
For example, if you need to configure the rotation to 50 files, you can set it by

```
shared:
  logging:
    rotation:
      maxFiles: 50
```

Further, this configuration can be set per micro-services as well.
For example, if you need to apply it only for the application log of frontend microservice :

```
frontend:
  logging:
    application:
      rotation:
        maxFiles: 50
```
Hence you can define a custom system.yaml with your requirements and use it in the chart.
