### ISSUE TITLE
 7.71.5

### ISSUE THREAD

**Issue by EvertonSA** [jfrog/charts#1844]
Hi,

We are users of jfrog platform and we have runned into huge issues on the terraform bug after 1.6 terraform release. We assume jfrog artifactory 7.71.5 will fix this jfrog bug. but it's not released yet.

Can you release jfrog-platform with artifactory  7.71.5? our next deployment windows is this weekend, so I appreciate if you can release till Thursday.

**Comment by chukka** [comment]
@EvertonSA  Planning for a release today

**Comment by chukka** [comment]
released via #1846
