### ISSUE TITLE
artifactory-ha helm chart has problem with join key

### ISSUE THREAD

**Issue by ahmadgh9** [jfrog/charts#1850]
**Is this a request for help?**: no

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: 3.13.2 and 1.27

**Which chart**: artifactory-ha

**Which product license** (Enterprise/Pro/oss): Pro

**JFrog support reference** (if already raised with support team): 

**What happened**: copy joinKey somewhere and looks for it somewhere else

**What you expected to happen**: containers going to be not ready

**How to reproduce it** (as minimally and precisely as possible): use artifactory ha small values and just run it!

**Anything else we need to know**: I tried with artifactory helm chart and small values and worked well but not working with artifactory ha chart and values

**Comment by ahmadgh9** [comment]
```
kubectl logs -f artifactory-ha-artifactory-ha-primary-0 copy-system-configurations 

Copy system.yaml to /var/opt/jfrog/artifactory/etc
'/tmp/etc/system.yaml' -> '/var/opt/jfrog/artifactory/etc/system.yaml'
Copy binarystore.xml file
'/tmp/etc/artifactory/binarystore.xml' -> '/var/opt/jfrog/artifactory/etc/artifactory/binarystore.xml'
Copy access.config.patch.yml to /var/opt/jfrog/artifactory/etc/access
'/tmp/etc/access.config.patch.yml' -> '/var/opt/jfrog/artifactory/etc/access/access.config.patch.yml'
Copy joinKey to /var/opt/jfrog/artifactory/bootstrap/access/etc/security
Copy masterKey to /var/opt/jfrog/artifactory/etc/security
```

```
kubectl logs -f artifactory-ha-artifactory-ha-primary-0 jfconnect 

2023-12-13T07:50:46.961Z [jfcon] [INFO ] [3c8be7b382a64a14] [bootstrap.go:245              ] [main                ] - JFConnect (jfcon) service initialization started. Version: 7.71.0 (revision: ba746121c9, build date: 2023-10-03T07:13:47Z) PID: 1 Home: /opt/jfrog/artifactory
2023-12-13T07:50:46.961Z [jfcon] [DEBUG] [                ] [file_resolver.go:72           ] [main                ] - Resolved system configuration file path: /opt/jfrog/artifactory/var/etc/system.yaml
```

**Comment by gitta-jfrog** [comment]
Hi @ahmadgh9 

Please describe the issue with more details and exact steps to reproduce. We are not aware of any issue with the JoinKey implementation which didn't change for a while. 

Thanks
Yarden.
