### ISSUE TITLE
artifactory-oss router does not start, reports 'Missing required services: [jfrt jfob jffe]'

### ISSUE THREAD

**Issue by ToniA** [jfrog/charts#1852]
**Is this a request for help?**: yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: Helm v3.12.3, Kubernetes 1.27.3

**Which chart**: artifactory-oss

**Which product license** (Enterprise/Pro/oss): oss

**JFrog support reference** (if already raised with support team): 

**What happened**: artifactory-oss does not start

**What you expected to happen**: artifactory-oss should start

**How to reproduce it** (as minimally and precisely as possible):

I have a working artifactory-oss installation on version 107.68.14, fairly basic installation with 
```
kubectl create namespace artifactory-oss

helm upgrade --install artifactory-oss --set artifactory.postgresql.postgresqlPassword=*** --namespace artifactory-oss -f values-oss.yaml jfrog/artifactory-oss --version 107.68.14
```

Due to the security issue email from JFrog, I tried to upgrade my installation to 107.68.19:
```
helm upgrade artifactory-oss --set artifactory.postgresql.postgresqlPassword=***--namespace artifactory-oss -f values-oss.yaml jfrog/artifactory-oss --version 107.68.19
```

artifactory-oss never comes online. Looking at `kubectl logs -n artifactory-oss artifactory-oss-0 router -f`, I can see it complains about `Missing required services: [jfrt jfob jffe]`

**Anything else we need to know**:

`helm rollback` to chart version 107.68.14 always works. I tried to upgrade to every currently available newer version on 107.68.* and 107.71.*, I get the same problem on every one of those.

**Comment by gitta-jfrog** [comment]
Hello @ToniA 

I wasn't able to reproduce the issue you described. I managed to upgrade artifactory-oss without an issue from 7.68.14 to 7.68.19, and also managed to complete a new installation of artifactory-oss 7.71.9.

I would encourage you to check the service logs (i.e. artifactory-service.log) located under the var/log folder to identify the failure reason. 

Yarden.

**Comment by ToniA** [comment]
It was a problem with my values-oss.yaml file. You should really have a better way to configure custom mime types. I need a mapping for *.svg, so that they render correctly on a static website published by my private Artifactory installation.
