### ISSUE TITLE
Deploying Artifactory Pro with Helm Chart on GKE - HTTP 405 Docker

### ISSUE THREAD

**Issue by Coopyrightdmin** [jfrog/charts#1854]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: 
Helm 3.10.2 
Kubernetes v1.27.3-gke.100
Docker 24.06

**Which chart**: artifactory-107.71.11

**Which product license** (Enterprise/Pro/oss): Pro

**JFrog support reference** (if already raised with support team): None

**What happened**:
We have setup JFrog Artifactory on GKE. We are able to access to the UI part and publish packages to R CRAN, archives to Generic, Login and Pull images from a virtual docker repository. Unfortunately, we cannot push images to the local repository using `docker push`and `jfrog rt dp`. 

When checking logs, it appears that `docker push` send first a HEAD with a 404, then a POST with a 202 and a location and finally a GET with 405 METHOD NOT ALLOWED. 

**What you expected to happen**:

We expect to push an initial docker image into the local repository without any issue.

**How to reproduce it** (as minimally and precisely as possible):

1) Vanilla setup of Artifactory pro on GKE with Helm (having defined a DNS and attaching certificates to the ingress)
2) Create a Docker Local Repository "test"
3) docker login artifactory.example.com
3) docker push artifactory.example.com/test/hello-world:latest

Login Succeeded
The push refers to repository [artifactory.example.com/test/hello-world]
12660636fe55: Pushing  10.75kB
unknown: Method Not Allowed

**Anything else we need to know**:

**Comment by Logeshwarsn** [comment]
@Coopyrightdmin Could you please raise this issue with Jfrog support team ? So that they can help you on this.

**Comment by gitta-jfrog** [comment]
Closing as no response. Please reach out to JFrog Support or[ JFrog community support ](https://stackoverflow.com/questions/tagged/artifactory) to investigate and find the root cause of the issue. Thanks
