### ISSUE TITLE
[FATAL] Cluster join: Failed resolving join key: failed resolving 'shared.security.joinKey' key; file does not exist: /opt/jfrog/router/var/etc/security/join.key

### ISSUE THREAD

**Issue by juparog** [jfrog/charts#1859]
**Is this a request for help?**: Yes

---

**Version of Helm and Kubernetes**:
```bash
kubectl version -o yaml
clientVersion:
  buildDate: "2023-07-19T12:20:54Z"
  compiler: gc
  gitCommit: fa3d7990104d7c1f16943a67f11b154b71f6a132
  gitTreeState: clean
  gitVersion: v1.27.4
  goVersion: go1.20.6
  major: "1"
  minor: "27"
  platform: windows/amd64
kustomizeVersion: v5.0.1
serverVersion:
  buildDate: "2024-01-02T20:34:38Z"
  compiler: gc
  gitCommit: 3f8ed3d5017d988600f597734a4851930eda35a6
  gitTreeState: clean
  gitVersion: v1.27.9-eks-5e0fdde
  goVersion: go1.20.12
  major: "1"
  minor: 27+
  platform: linux/amd64
```

**Which chart**: `artifactory-ha-107.71.5.tgz`

**Which product license** (Enterprise/Pro/oss): Enterprise

**JFrog support reference** (if already raised with support team): No

**What happened**: It is intensive to deploy artifactory using the above mentioned chart on an aws eks cluster using the command `helm upgrade --namespace jfrog-artifactory-dev --install --values ./values.yaml --wait --debug devops ./artifactory-ha-107.71.5.tgz`

Failed pod `artifactory-ha-primary`:
<img width="371" alt="image" src="https://github.com/jfrog/charts/assets/58745412/6b2fb0f7-b4b6-4ec2-ac33-1baf20b1af6a">

Error in container `router`:
<img width="811" alt="image" src="https://github.com/jfrog/charts/assets/58745412/7e3c9c61-97f8-4102-bfb5-bbbb63002192">

full log: 
[error.log](https://github.com/jfrog/charts/files/14193409/error.log)

Attached you will find the values.yaml file [artifactory.zip](https://github.com/jfrog/charts/files/14182550/artifactory.zip).

**What you expected to happen**: Being able to have a functional instance of the artifactory-primary pod

**How to reproduce it** (as minimally and precisely as possible): 
- Download the attached [artifactory.zip](https://github.com/jfrog/charts/files/14182550/artifactory.zip) zip which will contain the values file and the artifactory chart (or download the official helm repo chart).
- Create a clean namespace on your k8s cluster.
- Run the command `helm upgrade --namespace jfrog-artifactory-dev --install --values ./values.yaml --wait --debug devops ./artifactory-ha-107.71.5.tgz`
- - Be sure to change the namespace name in the commands and the paths of the values and chart to your own.

**Anything else we need to know**: The installation being attempted is clean, that is, it is not trying to migrate from another version.

**Comment by kammathavaran** [comment]
Can you kindly reach out to a customer support engineer ?
