### ISSUE TITLE
 StatefulSet artifactory-ha-jfrog-deployme-artifactory-ha-member failed. Not found: "gcpcreds-json"

### ISSUE THREAD

**Issue by abhisheksama** [jfrog/charts#1873]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Version of Helm and Kubernetes**:
107.77.6 

**Which chart**:
artifactory-ha

**Which product license** (Enterprise/Pro/oss):
Enterprise

**JFrog support reference** (if already raised with support team): 

**What happened**:
I was trying to upgrade the artifactory HA version to 107.77.6 chart version using Argo CD.  The artifactory-ha-member
 throwed an error saying "gcp-cred.json" not found and so I deleted the pv and tried to recreate it to resolve the error but it throws the same error again. Upon looking I found that the gcp-cred.json is not being defined under spec.volumes [here](https://github.com/jfrog/charts/blob/master/stable/artifactory-ha/templates/artifactory-node-statefulset.yaml#L1145) unlike the primary sts [here.](https://github.com/jfrog/charts/blob/master/stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml#L1276-L1280) After manually [2] under "volumes" I was able to resolve the error.
 
 
[1]:
 create Pod artifactory-ha-jfrog-deployme-artifactory-ha-member-0 in StatefulSet artifactory-ha-jfrog-deployme-artifactory-ha-member failed error: Pod "artifactory-ha-jfrog-deployme-artifactory-ha-member-0" is invalid: [spec.containers[6].volumeMounts[2].name: Not found: "gcpcreds-json", spec.initContainers[3].volumeMounts[5].name: Not found: "gcpcreds-json"]

[2]
- name: gcpcreds-json
          secret:
            defaultMode: 420
            secretName: artifactory-gcp-storage-creds-csi-managed-secret

**What you expected to happen**:

I expect it to create [2] under volumes so that the secret can be used through mountpath

**How to reproduce it** (as minimally and precisely as possible):
 deploy artifactory HA with persistence enabled and using a custom google service account.

**Anything else we need to know**:

**Comment by oumkale** [comment]
Hi @abhisheksama ,

Thank you for your issue, we have already taken this internally and it will be released in upcoming release 7.84.x

Will keep you updated

**Comment by oumkale** [comment]
This has been fixed in Artifactory version: 7.84.10, closing this issue.
