### ISSUE TITLE
Circle of Trust certificates gets deleted after the pods are up

### ISSUE THREAD

**Issue by sharvesh06** [jfrog/charts#1874]
**Is this a request for help?**: Yes

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: 
Helm Version: 107.77.9
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3+rke2r2

**Which chart**: Atrifactory-HA

**Which product license** (Enterprise/Pro/oss): Enterprise

**JFrog support reference** (if already raised with support team): N/A

**What happened**: 
One of the non-init containers is removing the circle of trust certificate from /var/opt/jfrog/artifactory/etc/access/keys/trusted. The certificate is initially in place after the init container transfers the file to the correct location, but subsequently, another container deletes it.

**What you expected to happen**:
Expected circle of trust certs in /var/opt/jfrog/artifactory/etc/access/keys/trusted

**How to reproduce it** (as minimally and precisely as possible):
cat /var/opt/jfrog/artifactory/etc/access/keys/trusted/filename.crt

**Comment by gitta-jfrog** [comment]
Hi @sharvesh06 

This is not a bug. It’s the expected behavior of Access Trusted folder. The CRT file will be removed and will be store in Access DB.

https://jfrog.com/help/r/jfrog-platform-administration-documentation/how-to-establish-a-circle-of-trust

Yarden.

**Comment by sharvesh06** [comment]
Thank you
