### ISSUE TITLE
Invalid RabbitMQ credentials.

### ISSUE THREAD

**Issue by r0fls** [jfrog/charts#188]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): 
Bug Report

**Version of Helm and Kubernetes**:
helm 2.12.0
kubernetes 1.12.3

**Which chart**:
stable/xray

**What happened**:
RabbitMQ reports `PLAIN login refused: user 'guest' - invalid credentials`

**What you expected to happen**:
The helm chart to work out of the box.

**How to reproduce it** (as minimally and precisely as possible):
I deployed the helm chart in a new namespace called xray. That is all, no custom configuration.

**Comment by eldada** [comment]
@r0fls
- Does any of the Xray services report it's unable to connect to RabbitMQ (check pods logs)?
- Does the system keep running?

**Comment by r0fls** [comment]
@eldada all of the xray pods are crashlooping. Here for instance are the logs from one of the xray-analysis pods:

```
[15:30:22 UTC 2019/01/24] [EROR] (jfrog.com/xray/xqueue/connector.connectToRabbitMQ:79) Error connecting to rabbit message queue check mq settings
[15:30:27 UTC 2019/01/24] [INFO] (jfrog.com/xray/xqueue/connector.connectToRabbitMQ:75) connecting to RabbitMq
```

The system has not started running successfully.

**Comment by r0fls** [comment]
Seeing similar problems with postgres and mongodb. When I exec into the postgres container and try to update the password I get:

```
$ kubectl exec -n xray -it release-name-postgresql-69f55d7b76-jt6bb /bin/sh
# psql
psql: FATAL:  database "xray" does not exist
```

**Comment by jainishshah17** [comment]
@r0fls Do you have RBAC enabled? Where is your K8S cluster hosted (On-Prem/AKS/GKE)?

**Comment by r0fls** [comment]
We have RBAC enabled on the cluster but I did not provide any flags to helm when initializing the chart. Our clusters are deployed with kops on AWS, not AKS.

**Comment by r0fls** [comment]
The values.yaml were from here: https://www.jfrog.com/confluence/display/EP/Installing+on+Kubernetes#InstallingonKubernetes-Xray.1

I've created a repo with the manifests that are installed here:
https://github.com/r0fls/xray-k8s-manifests

**Comment by Kasre** [comment]
@r0fls - Can you please share the full CLI command used for deploying this chart?

**Comment by r0fls** [comment]
After switching to the chart from the official jfrog release, this is working. Thanks!

**Comment by eldada** [comment]
Good idea. Stick with the official charts 😄 
Thx for the update.
