### ISSUE TITLE
wrong copy-circle-of-trust-certificates imagePullPolicy configuration

### ISSUE THREAD

**Issue by Kebree** [jfrog/charts#1881]
**Version of Helm and Kubernetes:**
All

**Which chart:**
Since 107.84.10

**Which product license (Enterprise/Pro/oss):**
All

**What happened:**

Following the release of the latest update, the ha statefulset went from :

 ```
     - name: copy-circle-of-trust-certificates
        image: {{ include "artifactory-ha.getImageInfoByValue" (list . "initContainers") }}
```

to :

 ```
  - name: copy-circle-of-trust-certificates
        image: "{{ .Values.initContainerImage }}"
        imagePullPolicy: c

```

**What you expected to happen:**

The image pull policy cannot be 'c'

**Comment by Kebree** [comment]
Sorry, wrong paste from my part, the stable/artifactory-ha/templates/artifactory-primary-service.yaml file went from 

```
 - name: copy-circle-of-trust-certificates
       image: "{{ .Values.initContainerImage }}"
```
to

```
 - name: copy-circle-of-trust-certificates
       image: {{ include "artifactory-ha.getImageInfoByValue" (list . "initContainers") }}
       imagePullPolicy: c
```

but anyway, the issue is not on the "image" part but on the "imagePullPolicy" part.

The reproducible step is setting the `circleOfTrustCertificatesSecret` value.

**Comment by chukka** [comment]
Thanks

**Comment by chukka** [comment]
This has been fixed internally and will be available for next patch release

**Comment by chukka** [comment]
@Kebree  Please try `107.84.11` chart for the fix  and share feedback

**Comment by Kebree** [comment]
Services are starting now. Thank you for the resolution of this issue.
