### ISSUE TITLE
Add support of specifying resources constraints for pre-upgrade-hook job

### ISSUE THREAD

**Issue by se-kai** [jfrog/charts#1894]
**Is this a request for help?**: 
NO

**Is this a BUG REPORT or FEATURE REQUEST?** : 
BUG REPORT

**Version of Helm and Kubernetes**:
Helm Version: v3.11.2
Kubernetes Version: v1.27.11+ec42b99

**Which chart**:
Xray 103.96.1

**Which product license** (Enterprise/Pro/oss):
Enterprise

**JFrog support reference** (if already raised with support team): 
No

**What happened**:
When a **ResourceQuota** is configured in the namespace, the pre-upgrade-hook job with is not able to deployed
because resources requests and limits must be specified. Currently there is no way to configure the resource constraints in chart.

**What you expected to happen**:
I need to define the resource constraints in the values.yaml file

**How to reproduce it** (as minimally and precisely as possible):
Deploy the xray chart on a cluster where the resource quota is needed.

**Anything else we need to know**:
No

**Comment by rahulsadanandan** [comment]
@se-kai  Thanks for reporting this. We have an internal ticket and it will be fixed in the upcoming versions of Xray.

**Comment by megha1906** [comment]
@se-kai Thank you for reporting this. We've incorporated it internally rolled it out with the 3.102.x versions of xray.
