### ISSUE TITLE
Scaling multiple shards for each cluster-node

### ISSUE THREAD

**Issue by sanjeevkarani** [jfrog/charts#191]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:

**Which chart**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by sanjeevkarani** [comment]
Currently, Artifactory HA charts are limited to single shard per pod and would require additional pods to scale the sharding redundancy.

For example, Currently, setting a redundancy of 6 would also require to scale the 3 node-cluster to 6.

**Comment by danielezer** [comment]
@sanjeevkarani you can just what you are looking for with `artifactory.persistence.fileSystem.existingSharedClaim.numberOfExistingClaims` which was kindly contributed by @zendril with PR #263

**Comment by danielezer** [comment]
@sanjeevkarani you would have to create the PVCs beforehand but in this way you can achieve having more shards than the amount of nodes in you cluster. Does that make sense?
