### ISSUE TITLE
JFrog HA 7.90.10 Update issue

### ISSUE THREAD

**Issue by DGJ89QK** [jfrog/charts#1924]
**Version of Helm and Kubernetes**:  AKS 1.27.7 Helm Provider Terraform 2.13.1

**Which chart**:  107.90.10

**Which product license** (Enterprise/Pro/oss): Enterprise

**JFrog support reference** (if already raised with support team): 

**What happened**:  template: artifactory-ha/templates/artifactory-primary-statefulset.yaml:657:32: executing "artifactory-ha/templates/artifactory-primary-statefulset.yaml" at <{{template "artifactory.fullname" .}}>: template "artifactory.fullname" not defined

During Helm deploy I get this error.

**What you expected to happen**: Deploy Helm Chart

**How to reproduce it** (as minimally and precisely as possible): Every runs pipeline

**Anything else we need to know**:

**Comment by RobinDuhan** [comment]
Hi @DGJ89QK, please share the values.yaml being used for us to be able to help.

**Comment by DGJ89QK** [comment]
[values.zip](https://github.com/user-attachments/files/17026895/values.zip)

**Comment by RobinDuhan** [comment]
This isn't accurate, will you please follow the instructions [here](https://jfrog.com/help/r/jfrog-installation-setup-documentation/install-artifactory-single-node-with-helm-charts) and try?

**Comment by DGJ89QK** [comment]
I already try, same issue.

**Comment by RobinDuhan** [comment]
Can you please share the steps/commands that you ran?

**Comment by gitta-jfrog** [comment]
Please disable the evidence service. 
```
evidence:
  enabled: false
```
The issue fixed in latest version 7.98.9
