### ISSUE TITLE
Chart updates not being committed in this repo?

### ISSUE THREAD

**Issue by 9numbernine9** [jfrog/charts#1927]
Hello,

Recently I've been noticing that there's been new versions of JFrog product Helm charts being published, but there doesn't seem to be any changes in this repo that correspond to those releases. For example, the Artifactory Helm chart was [recently bumped to `107.90.14`](https://charts.jfrog.io/artifactory-107.90.14.tgz) but the changes in this repo show `Chart.yaml` as [still at `107.90.10`](https://github.com/jfrog/charts/blob/master/stable/artifactory/Chart.yaml#L24). 

Just wondering if something has changed in the build/deploy process for Helm chart updates, or whether or not this repo is still the source of truth for those charts?

**Comment by chukka** [comment]
@9numbernine9 done via #1928

**Comment by 9numbernine9** [comment]
@chukka Thanks for looking into this! I'm slightly confused by some aspects of PR #1928 though - it seems like some of the `CHANGELOG.md` files are having their release versions _replaced_ instead of just appending new entries to the files? (e.g. in commit f4dd370dab46eefae1e027acb69f6748c397d6da `stable/artifactory-cpp-ce/CHANGELOG.md` has replaced `107.90.10` with `107.90.14` but the release _date_ of `Feb 20, 2024` has been kept the same.)

**Comment by chukka** [comment]
This is a known issue , our internal automation doesn't update dates , but updates only required versions . Hope this helps
