### ISSUE TITLE
Adding Custom Labels

### ISSUE THREAD

**Issue by pltkrt** [jfrog/charts#1937]
I install jfrogf-platform via helm and I miss the possibility to set a custom label to all its components.

```
    helm repo add jfrog https://charts.jfrog.io
    helm repo update

    # Install Artifactory via Helm
    helm upgrade --install jfrog-platform jfrog/jfrog-platform \
        -f resources/values-artifactory.yaml \
        -n "jfrog-platform" \
        --create-namespace
``` 

In the values-file I don't see any flag indicating such.

**Comment by ashraf-kherbawy** [comment]
Hi!

The JFrog Platform chart is simply an aggregation of our product's charts. All of our sub-charts can have labels configured, you will just have to access it through it's parent keys.

For example, if you are using the Artifactory chart, you would add labels like the following to Artifactory and Nginx:

artifactory:
    labels: {}
nginx:
    labels: {}

But under the JFrog Platform chart, you need to have one extra Artifactory parent key, as a reference to the Artifactory chart:

artifactory:
    artifactory:
        labels: {}
    nginx:
        labels: {}

This same logic applies to the rest of the chart.

**Comment by pltkrt** [comment]
would be nice to set it at a single place, but yes, that worked. Thanks for that.

```
artifactory:
  nginx:
    labels: {"key": "value"}
  artifactory:
    labels: {"key": "value"}
```
