### ISSUE TITLE
Error when multiple Nginx (replicaCount > 1)

### ISSUE THREAD

**Issue by bsemperlotti** [jfrog/charts#21]
**Version of Helm and Kubernetes**:
NA

**Which chart**:
artifactory-ha

**What happened**:
When setting nginx.replicaCount=2, and nginx.persistance.enabled=true, The second instance of Nginx fails to start because volume claim is already bound to first instance:

```
kubectl get pods | grep artifactory

artifactory-artifactory-ha-member-0                    1/1       Running    0          9m
artifactory-artifactory-ha-member-1                    1/1       Running    0          7m
artifactory-artifactory-ha-primary-0                   1/1       Running    0          9m
artifactory-nginx-69f8d97768-kmpjd                     0/1       Init:0/2   0          9m
artifactory-nginx-69f8d97768-l95vs                     1/1       Running    0          9m
```

```
kubectl get pvc | grep artifactory

artifactory-nginx                                                Bound     pvc-e899f622-ab99-11e8-b520-0a9fd9e2d170   5Gi        RWO            standard       10m
volume-artifactory-artifactory-ha-member-0                       Bound     pvc-e8b40093-ab99-11e8-ac7b-1237bc16f1bc   200Gi      RWO            standard       10m
volume-artifactory-artifactory-ha-member-1                       Bound     pvc-4291763c-ab9a-11e8-ac7b-1237bc16f1bc   200Gi      RWO            standard       7m
volume-artifactory-artifactory-ha-primary-0                      Bound     pvc-e8bb615f-ab99-11e8-ac7b-1237bc16f1bc   200Gi      RWO            standard       10m
```

```
kubectl describe pod artifactory-nginx-69f8d97768-kmpjd

[...]
Events:
  Type     Reason                 Age                From                                 Message
  ----     ------                 ----               ----                                 -------
  Warning  FailedScheduling       47s (x3 over 48s)  default-scheduler                    PersistentVolumeClaim is not bound: "artifactory-nginx" (repeated 12 times)
  Normal   Scheduled              45s                default-scheduler                    Successfully assigned artifactory-nginx-69f8d97768-kmpjd to ip-10-80-2-89.ec2.internal
  Normal   SuccessfulMountVolume  44s                kubelet, ip-10-80-2-89.ec2.internal  MountVolume.SetUp succeeded for volume "artifactory-artifactory-ha-token-6wv9c"
  Warning  FailedMount            44s                attachdetach-controller              AttachVolume.Attach failed for volume "pvc-e899f622-ab99-11e8-b520-0a9fd9e2d170" : "Error attaching EBS volume \"vol-0c875b4587a4178e4\"" to instance "i-04aaaeb9a03b14d7d" since volume is in "creating" state
  Warning  FailedAttachVolume     33s                attachdetach-controller              Multi-Attach error for volume "pvc-e899f622-ab99-11e8-b520-0a9fd9e2d170" Volume is already exclusively attached to one node and can't be attached to another
```

**What you expected to happen**:

It is not clear if and why persistent volumes should be used for NGinx. 
Can you precise the use of these volumes and when they should be used or not ?

What should be the expected behaviour ? Should multiple persistent volumes and persistant volume claims must be created or the same volume should be shared with appropriate accessMode ?

**How to reproduce it** (as minimally and precisely as possible):

helm install --name artifactory --set nginx.replicaCount=2 jfrog/artifactory-ha

**Anything else we need to know**:

**Comment by bsemperlotti** [comment]
Sure, I will let you know the result but can you explain what is the usage of this persistent volume ? Is it required to persist configuration through restart ? What is the drawback of not using them ?

**Comment by eldada** [comment]
The idea was to optionally allow advance setup for persisting logs and config. For having multiple replicas with PVC, you'll have to use no PVC, or switch to a StatefulSet.

**Comment by bsemperlotti** [comment]
It works when disabling persistent volume for nginx.

**Comment by jainishshah17** [comment]
@eldada Good Idea. Will add note.

**Comment by danielezer** [comment]
@eldada I think it would be a good idea to either remove the option for persistence in the artifactory-ha chart or to use a StatefulSet instead to avoid issues like this one - especially if we couple the artifactory.node.replicaCount with the number of nginx containers. WDYT?

**Comment by eldada** [comment]
We will not allow persistency if nginx replica count > 1. We will not couple the number of replicas with Artifactory to provide control and flexibility to users. #243 should fix this.
