### ISSUE TITLE
Implement logging sidecars for all of the services (Distribution, Xray, Artifactory Edge and Mission Control).

### ISSUE THREAD

**Issue by nihalreddy28** [jfrog/charts#224]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

  Implement logging sidecars for all of the services (Distribution, Xray, Artifactory Edge and Mission Control). This is similar to what has been already implemented for Artifactory in the following pull request https://github.com/jfrog/charts/pull/206

**Comment by eldada** [comment]
JFMC pull request #226
