### ISSUE TITLE
Move `securityContext` to container level

### ISSUE THREAD

**Issue by rimusz** [jfrog/charts#233]
Currently all charts `securityContext` have in deployment/statefulset spec level which breaks Istio proxy injection container work., moving `securityContext` to container level will sort the problem.
```
        securityContext:
          runAsUser: {{ .Values.xxx.uid }}
          fsGroup: {{ .Values.xxx.uid }}
```

**Comment by rimusz** [comment]
awesome!

**Comment by zendril** [comment]
@danielezer I don't see any context, why is this re-opened?

**Comment by danielezer** [comment]
@zendril I moved the securityContext to container level and it broke the permissions on the volumes so I reverted it. Now it is back to how it was before, which is at the pod level
