### ISSUE TITLE
Mission control chart can't be installed using the --wait flag

### ISSUE THREAD

**Issue by danielezer** [jfrog/charts#239]
**Is this a request for help?**:
NO
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

**Version of Helm and Kubernetes**:
all versions

**Which chart**:
mission-control

**What happened**:
When installing mission-control using the helm chart, the resources will never be stable because the hook that created the mongo users does not run. That happens because, according to the helm documentation:
`Tiller loads the resulting resources into Kubernetes. Note that if the --wait flag is set, Tiller will wait until all resources are in a ready state and will not run the post-install hook until they are ready.`
 
Which means that the hook that creates users before the mission control pods start will not run, and the mission control pods will never be healthy because they can't access the db
**What you expected to happen**:
mission control to be healthy

**How to reproduce it** (as minimally and precisely as possible):
`helm install --wait --name mission-control jfrog/mission-control --set mongodb.db.adminPassword=passw0rd --set mongodb.db.mcPassword=passw0rd --set mongodb.db.insightPassword=passw0rd`

**Comment by danielezer** [comment]
Never mind, I see that the hook is already not used. Closing this issue

**Comment by eldada** [comment]
This was one of the reasons we remove the hook 😉
