### ISSUE TITLE
Add support to allow the import of SSL certs to Artifactory Helm chart

### ISSUE THREAD

**Issue by nimerb** [jfrog/charts#242]
FEATURE REQUEST

Add support to the Artifactory Helm chart to allow users to use Java trustStore to perform SSL handshake (CA trusted) between Artifactory and different applications. 

For example:
Implement a SSL between Artifactory and LDAPS using self signed certificates that are imported to Java trust store using keytool.

**Comment by eldada** [comment]
We are working to add this functionality in the Docker image and then add support for it in the helm chart.

**Comment by zendril** [comment]
It looks like there is addCertsToJavaKeystore in the entrypoint now, but it it trying to copy from /artifactory_extra_certs which doesn't exist and can't be created by the 'artifactory' user given that / is owned by /.

Is that accurate or am I missing something here?

**Comment by palko444** [comment]
Currently im doing this with preStartCommand:
default password for javakeystore is "changeit"

<pre>
preStartCommand: "/java/jdk-11.0.2+9/bin/keytool -importcert -keystore /java/jdk-11.0.2+9/lib/security/cacerts -storepass YourPass -file /usr/local/share/ca-certificates/all.crt -alias YourAlias -noprompt
</pre>

this is customVolumes and customerVolumeMounts:
<pre>
customVolumes: |
    - name: all-ca-mount
      configMap:
        name: all-ca
</pre>

<pre>
customVolumeMounts: |
    - name: all-ca-mount
      mountPath: "/usr/local/share/ca-certificates/all.crt"
      subPath: all.crt
</pre>

**Comment by zendril** [comment]
Thanks! That's exactly what I did on my side as well.

I notice that the implementation in the helm charts won't work for
importing a store.. it assumes multiple single certs.

Maybe I can contribute a patch in a bit.

**Comment by eldada** [comment]
The suggested configuration that @palko444  proposed is the correct way to implement this.
As for importing a full store (@zendril) - we'll be happy to get a pull request. I think it can also be done with a combination of `customVolumeMounts`, `customVolume` and `preStartCommand`.

**Comment by TJM** [comment]
If anyone finds this in the future, it looks like (at least in 7.2.x) that you can just mount the certs into `/var/opt/jfrog/artifactory/etc/security/keys/trusted` and artifactory will take care of trusting them for you...

```
artifactory:
  customVolumes: |
    - name: trusted-certs
      configMap:
        name: trusted-certs
  customVolumeMounts: |
     - name: trusted-certs
       mountPath: /var/opt/jfrog/artifactory/etc/security/keys/trusted
```

And, of course the requisite:

```
helm create configmap trusted-certs --from-file myCa.pem
```

**Comment by ankurdhiman328** [comment]
> importcert

I am getting a permission denied error with the preStartCommand:

Chart Version: artifactory-7.13.2
App Version: 6.9.0

Error:

`Running custom preStartCommand command
Warning: use -cacerts option to access cacerts keystore
Certificate was added to keystore
keytool error: java.io.FileNotFoundException: /java/jdk-11.0.2+9/lib/security/cacerts (Permission denied)
`

Can someone help?
