### ISSUE TITLE
support existingclaim for artifactory-ha again

### ISSUE THREAD

**Issue by zendril** [jfrog/charts#253]
**Is this a request for help?**:
No. I can submit PR to put back in if necessary.
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT 

**Version of Helm and Kubernetes**:
Helm: 0.11.11

**Which chart**:
stable/artifactory-ha

**What happened**:
between 0.11.3 and 0.11.11 the existing claim concept was removed.

**What you expected to happen**:
This should remain in addition to the dynamic creation options.

Our firm does not allow us to dynamically create NFS so we have to pre-provision them and then pass that into the kubernetes manifest.

**How to reproduce it** (as minimally and precisely as possible):
Look at the templates (primary, member and nginx) all refer to something like:
`{{- if not .Values.artifactory.primary.persistence.existingClaim }}`

However it doesn't actually do anything with or account for when existingClaim has a value.

**Anything else we need to know**:

**Comment by eldada** [comment]
@danielezer actually submitted a fix to this in #237. Can you check? Isn't it working as expected?

**Comment by danielezer** [comment]
@eldada @zendril this is supported and should work. There are instructions in the README of the artifactory-ha chart. You can create claims beforehand with specific names and they will be used

**Comment by zendril** [comment]
@eldada @danielezer Reading through the code I'm not seeing where this is honored. I only see the volumeclaimtemplate being populated when .existingClaim is false. I can't find where the volumeclaim is specified or a selector used when .existingClaim is set to true. Can you link to the code line?

Either way I'll give it a try tomorrow.

Also,

I think there is also conflicting information in the readme vs the code:
Readme says:

> Create a persistent volume claim by the name volume-<release-name>-artifactory-ha-primary-0

but the values.yaml has different value examples:

>      ## Set existingClaim to true or false
>      ## If true, you must prepare a PVC with the name e.g `artifactory-ha-primary`
>      existingClaim: false
https://github.com/jfrog/charts/blob/master/stable/artifactory-ha/values.yaml#L348-L350

I'll be happy to PR if it isn't right.

**Comment by zendril** [comment]
I do see it still explicitely supported in the non-ha chart:
https://github.com/jfrog/charts/blob/master/stable/artifactory/templates/artifactory-statefulset.yaml#L302-L306

**Comment by danielezer** [comment]
@zendril you are right, there's a contradiction between the values file and the README. The example you should follow is this one - https://github.com/jfrog/charts/blob/master/stable/artifactory-ha/README.md#existing-volume-claim. 

The implementation for using an existing volume claim is different in the artifactory-ha chart and in the artifactory chart.

The artifactory chart implementation is pretty straight forward - mounting an existing claim by name.
The artifactory-ha chart implementation is done by creating volume claims by the same name as they would have been created by the chart. Those claims are picked up by the statefulset and used by it. The reason for that is that using existing volume claims for stateful sets with more than one replica is impossible (or very complicated) since you can't use selectors for claims in the volumeClaimTemplates, the selector is for persistentVolumes (and not persistentVolumeClaims). That's the reason we implemented it with naming conventions instead of selectors. 

Hope that answers you question. I will issue a PR for fixing the example in the values.yaml

**Comment by zendril** [comment]
@danielezer Thanks for the more detailed description. 

Ok, I see where you were heading with the default naming (magic).

This still presents a problem for us.

The setup we were envisioning:
- Semi-persistent rbd (ceph) storage and pvc for each primary & member to hold the artifactory instance, masterkey, logs, etc.. (artifactory.persistence.mountPath) 
- NAS attached via a PV and PVC (precreated) to attach across all instances as the HA_DATA_DIR

Issues:
- Multiple PVC -> PV isn't allowed.
- We can get around the limitation above by creating multiple PV all pointing to same NAS, however this still doesn't work because we can't attach all primary/member pods to the same PV because then they would be clobbering each other at the artifactory.persistence.mountPath location
    - We also don't really want to be running the artifactory instance itself on a NAS, much more prefer the ceph storage.

The solution I am proposing:
- Allow the existing PVC name to be passed in and used for artifactory-ha-data and artifactory-ha-backup (similar to what is done for nfs type, but without the dynamic provisioning)

Ex (just showing the output, i can work on the template after this):
```
      - name: artifactory-ha-data
        persistentVolumeClaim:
          claimName: existing-artifactory-containers-data-pvc
      - name: artifactory-ha-backup
        persistentVolumeClaim:
          claimName: existing-artifactory-containers-data-bk-pvc
```

There is another option (where multiple volumes can be created in the volumeClaimTemplate), but this means that we would need to know how many primary/member pods will be running and manually create a PV/PVC for it ahead of time. With the solution above we can just re-use the same PVC across any/all pods (even as we scale up) so they can share the same Data.

I'll submit PR and we can discuss on that?

**Comment by danielezer** [comment]
@zendril That's the way it works in the artifactory chart. In the artifactory-ha chart its impossible because there's more than one replica. Since there's more than one replica, you can't use names for the persistent volume claims because they would usually be different volumes claims for each pod in the StatefulSet

**Comment by zendril** [comment]
Are you saying it isn't possible (in artifactory-ha chart) to have:
- dynamic PVC for each replica to host artifactory.persistence.mountPath
- existingClaim to share across all replicas to host artifactory-ha-data

**Comment by danielezer** [comment]
@zendril Dynamic PVC for each replica is supported now. Using the same existing claim for all the nodes in the cluster is also supported in artifactory-ha by using the nfs option by not with a predefined claim. We can add that capability if you feel you need that

**Comment by danielezer** [comment]
This will of course have to be a volume with readWriteMany access. Is that what you mean? @zendril

**Comment by zendril** [comment]
@danielezer Yes, that's correct.

We tested this (limited testing of course) with 1primary/2member setup today and it seems to work fine.
Basically we used the nfs implementation, but plugged in a predefined claim.

Even this part will be acceptable (to follow convention, vs having to pass in a custom claim name)
```
      - name: artifactory-ha-data
        persistentVolumeClaim:
          claimName: {{ template "artifactory-ha.fullname" . }}-data-pvc
      - name: artifactory-ha-backup
        persistentVolumeClaim:
          claimName: {{ template "artifactory-ha.fullname" . }}-backup-pvc
```

Unless you think its faster for you to do it, I can raise a PR for it.

You have a preference?
- put a flag on the nfs type to indicate dynamic vs predefined claim
- copy/pasta artifactory.persistence.type=nfs to another new one like 'predefined' or 'existing' or 'other'
- other idea?

**Comment by danielezer** [comment]
I think the best way to achieve that is to use a pre-defined PVC with readWriteMany access. Doesn't have to be NFS. I would start digging in to that today

**Comment by zendril** [comment]
Correct. The intention is to use a pre-defined PVC with readWriteMany access.

So since it doesn't have to be NFS that means we probably go with another entry for
```
artifactory:
  persistence:
    type: pre-defined
```
and essentially implement the semantics of `artifactory.persistence.type.nfs` without a corresponding `artifactory-nfs-pvc.yaml`.

I love it when a plan comes together. :smile:

**Comment by zendril** [comment]
@danielezer @eldada @jainishshah17 
I submitted a PR for this, but before we merge it there may be another change we'd like to put in.

This will support a single, pre-existing claim.

In our case, we can only provision ~20TB of nas at a time. We would like to provision multiple of these (because in one instance we have ~100TB of artifacts). How would this work with binarystore and sharding?  There can only be one HA_DATA_DIR and that is done via a single volumeMount to that dir. How would/could we attach multiple PVCs and have them all used by binarystore and the single HA_DATA_DIR limitation?  I opened a support ticket to ask the same thing (101515) in case you all aren't sure either.

**Comment by danielezer** [comment]
@zendril the default binarystore configuration is sharding. If you create the PVCs before deploying with the expected names. Artifactory will use those and shard your data

**Comment by zendril** [comment]
@danielezer Sorry for being dense, trying to get up to speed on the sharding but want to make sure I understand and can implement and test it before finishing the PR.

If I have 2 PVC for the data, I can have something like this in the binarystore:
```
        <provider id="state-aware" type="state-aware">
            <fileStoreDir>shard-fs-1</fileStoreDir>
            <zone>local</zone>
        </provider>
        <provider id="state-aware" type="state-aware">
            <fileStoreDir>shard-fs-2</fileStoreDir>
            <zone>local</zone>
        </provider>
```

But where do I actually point the HA_DATA_DIR and the volumeMount for each PVC?

I can't just volumeMount  2 different PVCs at the same `/var/opt/jfrog/artifactory-ha`

Would I keep HA_DATA_DIR pointed at `/var/opt/jfrog/artifactory-ha`
and then have volumeMounts:
```
- name: artifactory-ha-data-1
   mountPath: "/var/opt/jfrog/artifactory-ha/shard-fs-1"
- name: artifactory-ha-data-2 
   mountPath: "/var/opt/jfrog/artifactory-ha/shard-fs-2"
```

**Comment by danielezer** [comment]
@zendril no problem. Each replica in your StatsulSet will have a different PVC, that's the default behaviour using the volumeClaimTemplates. The binarystore is already configured by default for sharding the three PVCs. If you create the PVCs with the appropriate names in advance, the release will pick it up and use those for the storage. The binary data will be sharded across the nodes, since it is preconfigured in the binarystore.xml

Hope that helps

**Comment by zendril** [comment]
@danielezer It did. That and some other digging helped and I have it all
working as of yesterday. I'll clean up and update the PR most likely
tomorrow.
