### ISSUE TITLE
[Feature] Support custom sidecar containers

### ISSUE THREAD

**Issue by eldada** [jfrog/charts#257]
As a user, I'd like to be deploy a custom sidecar container in the Artifactory pod to be used for cases like log collection, proxy, monitoring etc.

Add an option to create a custom sidecar by using the `values.yaml` configuration. Similar to what we did by adding `customInitContainers` and `loggers`.

**Comment by jainishshah17** [comment]
Please add support to overwrite user for sidecar containers as well.
