### ISSUE TITLE
502 bad gateway error when pulling the image

### ISSUE THREAD

**Issue by rihtak06** [jfrog/charts#261]
When i do` helm install jfrog/xray`  I got 
Failed to pull image "docker.bintray.io/jfrog/xray-analysis:2.7.3": rpc error: code = Unknown desc = error pulling image configuration: received unexpected HTTP status: 502 Bad Gateway
 and when i try `docker pull docker.bintray.io/jfrog/xray-server:2.7.3` , 
I got

>  pulling image configuration: received unexpected HTTP status: 502 Bad Gateway

**Comment by eldada** [comment]
@rihtak06 this is related to issues with Bintray. Not related to the helm charts. Working on it.

**Comment by eldada** [comment]
See https://status.bintray.com/
