### ISSUE TITLE
Upgrade Xray with Helm from 2.6.0 to 2.7.3 fails

### ISSUE THREAD

**Issue by majwang** [jfrog/charts#274]
Upgrading Xray with helm fails with authentication failures against the databases.

Steps to reproduce:
-install Xray: helm install --set common.xrayVersion=2.6.0 xray jfrog/xray
-upgrade Xray: helm upgrade --set common.xrayVersion=2.7.4 --set xray jfrog/xray
-see that the xray-server fails to connect to mongo with invalid credentials

To resolve this issue, you have to exec into each container, grab the password for Mongo/Postgres with printenv, then set it with --set. Note that there is also an issue with rabbitmq connecting, so you have to exec into the rabbitmq container, and set the password to whatever you've set with --set (rabbitmqctl change_password guest ).

helm upgrade --set common.xrayVersion=2.7.4 --set mongodb.mongodbPassword=uyjQvTA0n5 --set postgresql.postgresPassword=uTHbrU3GzP --set rabbitmq.rabbitmqPassword=fDGRicPDOHGd3ZUSoXPUwwfW xray3 jfrog/xray

Notes:
-upgrading with --reuse-values does not help
-installing xray initially with all the passwords set via --set, and then upgrading with all the same passwords set with --set will allow the upgrade to proceed for mongo/postgres, but fail at rabbitmq.

**Comment by eldada** [comment]
@majwang - this seems like it's a documentation gap.
For upgrading a release that was deployed with the auto generated password, you must extract them before running the upgrade. 
See [decoding-a-secret](https://kubernetes.io/docs/concepts/configuration/secret/#decoding-a-secret).

**Comment by eldada** [comment]
@danielezer - can you test this, try to resolve the RabbitMQ issue and fix the documentation and add the need to get passwords before an upgrade (if auto generated passwords were used).

**Comment by majwang** [comment]
I think figured it out. I was setting the password with --set during the upgrade for rabbitmq, not rabbitmq-ha.

**Comment by danielezer** [comment]
> @majwang - this seems like it's a documentation gap.
> For upgrading a release that was deployed with the auto generated password, you must extract them before running the upgrade.
> See [decoding-a-secret](https://kubernetes.io/docs/concepts/configuration/secret/#decoding-a-secret).

@eldada still want me to take a look?

**Comment by majwang** [comment]
I think we still need to update our documentation. There have been a few cases of issues related to the DB passwords on upgrades so far.

**Comment by danielezer** [comment]
This should fix this issue, when merged: https://github.com/helm/helm/pull/5290

**Comment by eldada** [comment]
@danielezer - can you just suggest a documentation fix?

**Comment by danielezer** [comment]
@eldada sure I’ll start working on that tomorrow

**Comment by danielezer** [comment]
@eldada @majwang this is more than a documentation fix. I will work on that. For example in mission control, I think it would be cool if when the passwords for the mission control users in the secret change, we will update the user with that new password. Currently this is not supported since the script checks if the user exists, and if so, it does not do anything. Anyway, I will work on fixing those issues and submit a pull request soon
