### ISSUE TITLE
Install More than one artifactory on the same K8s namespace using the same DB

### ISSUE THREAD

**Issue by eladh** [jfrog/charts#280]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Gcp
**Which chart**:
Artifactory 7.13.0

**What happened**:
Install More than one artifactory on the same K8s namespace and was trying to register the services in JFMC resulting license duplication 

**What you expected to happen**:
Separated env 

**How to reproduce it** (as minimally and precisely as possible):
Install More than one artifactory on the same K8s namespace 

**Anything else we need to know**:
As a workaround install the artifactory instances in a separate namespaces

**Comment by eldada** [comment]
@danielezer - this is easy to reproduce.
```
helm install --name aaa jfrog/artifactory
helm install --name bbb jfrog/artifactory
```
Setup the first Artifactory and you'll see the second one is also set...

Can you take it with @eladh ?

**Comment by danielezer** [comment]
@eldada sure

**Comment by danielezer** [comment]
@eladh @eldada I can't reproduce this issue. Installing two Artifactory releases in the same namespace works for me. Can you please provide me with some more details?

**Comment by jainishshah17** [comment]
@eladh Are you using same artifactory license in both Artifactory releases? AFAIK that's the only case when you will get `JFMC resulting license duplication`.

**Comment by eldada** [comment]
I was able to reproduce this with just one license that I installed to `aaa`. Then, after installing `bbb`, the UI of `bbb` pointed to `aaa`'s Artifactory.
Once you go to Admin -> System Info, you'll see the same DB.

**Comment by eladh** [comment]
@jainishshah17 So the same behaviour as @eldada mention - same when added a new repository on artifactory x saw the same repo on artifactory y

**Comment by jainishshah17** [comment]
> I was able to reproduce this with just one license that I installed to `aaa`. Then, after installing `bbb`, the UI of `bbb` pointed to `aaa`'s Artifactory.
> Once you go to Admin -> System Info, you'll see the same DB.

I am not able to reproduce it either.

**Comment by jainishshah17** [comment]
> @jainishshah17 So the same behaviour as @eldada mention - same when added a new repository on artifactory x saw the same repo on artifactory y

@eladh Can you describe psql deployments of both releases?

**Comment by danielezer** [comment]
@eldada @eladh I'm not able to reproduce this issue. I followed your procedure, but everything looks ok.

**Comment by eladh** [comment]
@eldada  @danielezer  @jainishshah17  - I'm unable to reproduce this issue
