### ISSUE TITLE
Configuring userPluginSecrets causes initialization issue due to artifactory_extra_conf not loaded

### ISSUE THREAD

**Issue by properpanda** [jfrog/charts#287]
a bug was introduced with PR#278 (https://github.com/jfrog/charts/pull/278/)  specifically commit:
https://github.com/jfrog/charts/pull/278/commits/cb2316d1985a58999faf126aca67a1dbab6d2572

We have seen behaviour when using userPluginsSecrets such that when configuring a userPluginSecret, a command gets added to the template that creates an /var/opt/jfrog/artifactory/etc folder.

during initialization running entrypoint-artifactory.sh, the script sees that an etc folder exists and DOES NOT add the extra conf files needed in a fresh installation causing faulty installations is undesired effects

from entrypoint-artifactory.sh
```
# In case data dirs are missing or not mounted, need to create them
setupDataDirs () {
    logger "Setting up Artifactory data directories if missing"
    if [ ! -d ${ARTIFACTORY_DATA}/etc ]; then
        mkdir -pv ${ARTIFACTORY_DATA}/etc || errorExit "Failed creating ${ARTIFACTORY_DATA}/etc"

        # Add extra conf files to a newly created etc/ only!
        addExtraConfFiles
    fi
```

We believe that the userPluginsSecrets code should stage plugins from secrets in /tmp/plugins and allow the entrypoint-artifactory.sh to copy them appropriatly.  I can work this bug fix and supply a PR.

**Comment by properpanda** [comment]
I looked at a couple fixes, the most straight forward fix would be to be able to write to the /tmp/plugins directly, but unfortunately that directory on the artifactory-pro:6.9.0 image is drwxr-xr-x root/root.  If we can open the permissions to allow non-root groups to write to it, then the userPluginsSecrets will work with minor adjustments

the alternative solution was to mount a volume on top of /tmp/plugins - either with an emptyDir (and copy files over) or a projected volume that contained all the secrets.  however, the issue was that we lost the prepackaged internalUser.groovy script that exists in /tmp/plugins as part of the artifactory-pro:6.9.0 image.  If people were dependent on this script then it would no longer be there (that's why the initial solution seems simplest and ideal)

**Comment by jainishshah17** [comment]
@properpanda How about mount pluginSecrets to `/tmp/plugin` and then copy them to `/tmp/plugins` using preStartCommand so that Entrypoint can move it over to `ART_HOME/etc/plugins`?

**Comment by properpanda** [comment]
> @properpanda How about mounting pluginSecrets to `/tmp/plugin` and then copy them to `/tmp/plugins` using preStartCommand. Which will allow entrypoint can move it over to `ART_HOME/etc/plugins`?

as mentioned above, /tmp/plugins is not writable, unless you mount a volume on it but then you lose internalUser.groovy plugin that exists in there from the image

**Comment by zendril** [comment]
@jainishshah17 @eldada Who or what team has the access to modify the Dockerfile (or whatever you all are using to build the artifactory_pro image)? Would like to discuss getting this small change (chown /tmp/plugins to artifactory) in that build.

I assume that part isn't open sourced anywhere is it?

**Comment by eldada** [comment]
@zendril - I have access to it and I already added this fix to an internal branch we have. Will be released with one of the coming versions.

**Comment by jainishshah17** [comment]
@properpanda @zendril This fix removed `internalUser.grovvy`.

**Comment by danielezer** [comment]
@zendril @properpanda in the mean time you can use the copyOnEveryStartup feature for that. an example values file would be:
```
artifactory:
  copyOnEveryStartup:
    - source: /tmp/plugins/*
      target: etc/plugins/
```

**Comment by JfrogPrasanna** [comment]
Closing this.
