### ISSUE TITLE
Update ReverseProxyConfiguration.md documentation with customization steps

### ISSUE THREAD

**Issue by patbat95008** [jfrog/charts#293]
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
This is a "Bug" Report for the information contained within the GitHub repo's documentation.

**Version of Helm and Kubernetes**:
N/A

**Which chart**:
Artifactory-HA

**What happened**:
Spinning up a Kubernetes cluster with a standard Artifactory-ha Helm chart did not allow a user to customize the Nginx reverse proxy, even after following the current documentation.

**What you expected to happen**:
The documentation steps would work if defaults were used, or mention next steps to try.

**How to reproduce it** (as minimally and precisely as possible):

1. Spin up a Helm artifactory-ha chart by following the GitHub documentation

2. Attempt to customize the Nginx reverse proxy pod [as per the documentation](https://github.com/jfrog/charts/blob/master/stable/artifactory-ha/ReverseProxyConfiguration.md), using [one of the example Nginx configurations](https://github.com/jfrog/artifactory-docker-examples/blob/master/files/nginx/conf.d/ha/artifactory.conf)

3. Encounter errors on the Nginx pod related to the proxy_pass line used

**Anything else we need to know**:
To solve the problem, you need to get the Artifactory pod's Service Namespace by running the following command:

kubectl get svc -n k8s-ns-cicd

This will output a list of the pod names, the "artifactory-ha" name needs to be used in the Nginx configuration instead of "node-1" or "artifactory-ha-primary". It was unclear where those names were coming from in the examples.

The documentation should include the above example command as a part of the ["Steps to use static configuration for reverse proxy in nginx." step ](https://github.com/jfrog/charts/blob/master/stable/artifactory-ha/ReverseProxyConfiguration.md#steps-to-use-static-configuration-for-reverse-proxy-in-nginx)

**Comment by eldada** [comment]
@jainishshah17 - can you update the examples with templates and add instruction on extracting the names as @patbat95008 noted?
