### ISSUE TITLE
Google storage provider with existing bucket

### ISSUE THREAD

**Issue by satyamag** [jfrog/charts#303]
**Is this a request for help?**:
YES

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

possibly a BUG

**Version of Helm and Kubernetes**:
1.11.7

**Which chart**:
0.4.4 artifactory-ha

**What happened**:

We are trying to activate google storage binary provider. As part of the setup we provision the bucket via terraform and then deploy artifactory ha helm chart.  I have set the <bucketExists> field to true in the artifactory-binarystore.yaml as suggested [here](https://www.jfrog.com/confluence/display/RTF/Configuring+the+Filestore#ConfiguringtheFilestore-GoogleStorageBinaryProvider). However when I deploy the pod in the primary statefulset does not stabilise. The following messages are in the logs

[art-init] [INFO ] (o.a.a.f.t.j.g.GoogleJets3tBinaryProvider:94) - Bucket exists = false
[ERROR] (o.a.a.f.t.j.g.GoogleJets3tBinaryProvider:274) - Failed to create bucket bucket-name on GCS --> BucketNameUnavailable:The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.

**What you expected to happen**:

Should respect the bucketExists flag and not try to recreate it

**How to reproduce it** (as minimally and precisely as possible):

Enable google-storage provider and pass it existing bucket name and interoperability API credentials and try to deploy it

**Comment by eldada** [comment]
@satyamag - You are using an old version of the `artifactory-ha` chart (0.4.4). We already have `0.12.13`. Can you test this with the new chart and come back with results?

**Comment by satyamag** [comment]
@eldada based on a quick review (please correct me if I am mistaken) looks like the artifactory-binarystore.xml section related to google-storage has not been modified since the initial releases. Have there been other changes between 0.4.4 and 0.12.13 that would affect this issue? If bumping the version is a dependency to fixing this error that would be good to know. It is hard for me to test with the new version and ideally we would like to have the GCS integration working before we bump the version.

**Comment by eldada** [comment]
@jainishshah17 - can you hop in and have a look here?

**Comment by jainishshah17** [comment]
@satyamag I see that you are on an older version which did not have this flag in `binarystore.xml`. I see that even in our new chart we will need to add this (flag)[https://github.com/jfrog/charts/blob/master/stable/artifactory-ha/templates/artifactory-binarystore.yaml#L115]. 
As a workaround you can manually change configmap and add this entry and restart all your pod one by one starting with the primary.

**Comment by jainishshah17** [comment]
Meanwhile, I will work on adding this flag to our helm charts.
