### ISSUE TITLE
use a configmap for nginx configuration

### ISSUE THREAD

**Issue by danielezer** [jfrog/charts#312]
**Is this a request for help?**:
NO
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
ALL

**Which chart**:
artifactory and artifactory-ha

**What happened**:
When installing the artifactory and artifactory-ha charts, nginx will fail to start one time because there's a sort of race conditions between the nginx startup and the postStart command.

**What you expected to happen**:
nginx to start properly without restarting

**How to reproduce it** (as minimally and precisely as possible):
helm install jfrog/artifactory

**Anything else we need to know**:
I think that if we start using a configmap for the nginx configuration and mount it directly onto /etc/nginx/nginx.conf it would remove the need to use sed and copy to generate the nginx configuration, thus removing the need for the postStart container lifecycle.

**Comment by danielezer** [comment]
@jainishshah17 @eldada @rimusz I created this issue to start a discussion, WDYT?

**Comment by jainishshah17** [comment]
@danielezer I fixed this in https://github.com/jfrog/charts/pull/307

**Comment by jainishshah17** [comment]
@danielezer Documentation for that feature https://github.com/jfrog/charts/tree/master/stable/artifactory-ha#use-custom-nginxconf-with-nginx

**Comment by danielezer** [comment]
@jainishshah17 what I mean is to use this as the default behaviour. I think its more elegant than the current solution which copies the files from /tmp and uses sed to change the configuration file embedded in the nginx docker image

**Comment by jainishshah17** [comment]
If you mean `artifactory.conf` file then we can not directly mount it to `/etc/nginx/conf.d/artifactory.conf`. Because ConfigMap/Secrets are not writable. Which will fail our updateConf logic.

**Comment by danielezer** [comment]
Yes, I understand that, but is that a deal breaker? I think that using a configmap as it was intended to be used is better than the current implementation. That’s only my opinion of course. I opened this issue to have a discussion. In my opinion the upside of using a configmap directly mounted
to the target path outweighs the downside of loosing the auto conf update feature

**Comment by jainishshah17** [comment]
@danielezer I am open for discussion. Let's wait to hear from @eldada and @rimusz

**Comment by eldada** [comment]
Best practice wise - we should use the direct configMap mount, as this is the recommended way to manage application config in K8s.
The copy and edit in **postStart** using `sed` does look like a hack or a workaround rather than a proper setup.
If we move to using the configMap as the default solution, we'll have to disable the auto config (`nginx.env.skipAutoConfigUpdate=true`). The question is how many customers actually use this in the K8s setup?
@jainishshah17 - how would a customer setup multiple sub domains for Docker?

**Comment by danielezer** [comment]
@eldada what does the auto update really do? I mean, when I change the configuration, the chart itself changes the configuration and there’s logic in the dicker image for reloading? 
If that’s the case, we can just update the configuration using the configmap and let the logic in the docker image reload Nginx. We can even add a watchdog for checking the checksum of the nginx configuration and reload when it changes. WDYT? that way we can use the configmap and keep all the features

**Comment by eldada** [comment]
That would require writing the config changes to the configMap directly? How would you automate this?

**Comment by danielezer** [comment]
No, because the all changes to the configuration will be done directly on the configmap. I was thinking about exposing the configuration in values.yaml and when a user wants to change the nginx configuration they will simply provide a different value to the nginx.configuration for example. Since it would be directly mounted to the nginx folder, all we would need to do is reload instead of changing the content of the configmap. They say, the users would also have better visibility into the nginx configuration directly from the configmap instead of having to exec into the pod and read the file

**Comment by eldada** [comment]
I think we can add this as an additional option. Backward compatibility is important here.

**Comment by danielezer** [comment]
I think it would be backward compatible as I see it

**Comment by eldada** [comment]
Go ahead and raise a PR.

**Comment by danielezer** [comment]
Cool, will start working on that soon. Thanks @eldada @jainishshah17

**Comment by jainishshah17** [comment]
> Best practice wise - we should use the direct configMap mount, as this is the recommended way to manage application config in K8s.
> The copy and edit in **postStart** using `sed` does look like a hack or a workaround rather than a proper setup, but are well justified by the auto update feature.
> If we move to using the configMap as the default solution, we'll have to disable the auto config (`nginx.env.skipAutoConfigUpdate=true`). The question is how many customers actually use this in the K8s setup?
> @jainishshah17 - how would a customer setup multiple sub domains for Docker?

@eldada User will have to create DNS record with `*.domain` pointing to External IP of nginx service. In terms of configuration for configmap it will look like https://github.com/jfrog/artifactory-docker-examples/blob/master/files/nginx/conf.d/ha/artifactory.conf#L15
