### ISSUE TITLE
way to alter context root of tomcat?

### ISSUE THREAD

**Issue by scphantm** [jfrog/charts#316]
**Is this a request for help?**:
yes

running the latest helm chart, is there the ability to use helm to alter the context root?  I would like my system to use `/` instead of `/artifactory/webapp`.  Because we have our own router and other systems, my OKD install doesn't install NGNix, and we just create a route right to the tomcat server (simplicity, resources, etc).  It doesn't appear that i can use the route to do this, but i was wondering if i could change something in the helm that would allow me to alter that server.xml file and change the context root of tomcat.

**Comment by jainishshah17** [comment]
@scphantm See the comment from @KierranM  https://github.com/jfrog/charts/pull/264
