### ISSUE TITLE
Artifactory primary/nodes must have at-least 4 cpu

### ISSUE THREAD

**Issue by arielkv** [jfrog/charts#318]
All Artifactory servers should have minimum 4cpu by default.
As mentioned in the [Artifactory System Requirements](https://www.jfrog.com/confluence/display/RTF/System+Requirements) the minimum number of cores to run Artifactory is 4.

This is highly important in HA clusters. Without having the minimum number of cores unexpected issues will occur.

**Comment by danielezer** [comment]
I'm not sure this is a good idea since it could prevent users from installing this helm chart on testing environment like their computer with docker-for-mac or minikube

**Comment by arielkv** [comment]
@danielezer This is not a matter of an idea, having 4cpu is a requirement by Artifactory.
Artifactory HA doesn't work properly with less than 4cpu. 

I have submitted this issue following a situation where an Artifactory deployment wasn't working due to the fact is was running only with 2cpu (although the load on them was very low).

**Comment by danielezer** [comment]
@arielkv helm’s best practice is to not set default resources requirements...

**Comment by rimusz** [comment]
As I proposed before, we should have extra values files for different use cases, in this case add e.g. `prod-values-ha.yaml` with only set resources there which then can be passed with `-f prod-values-ha.yaml` for helm install/upgrade commands

**Comment by eldada** [comment]
To mitigate this, we will do the following:
1. Add a config key `artifactory.async.corePoolSize` in values.yaml. See [How do I tune Artifactory for heavy loads?](https://jfrog.com/knowledge-base/how-do-i-tune-artifactory-for-heavy-loads/).
2. Set default value to 8 for `artifactory` and 16 for `artifactory-ha`.
3. Add this to the `EXTRA_JAVA_OPTIONS` block.
4. Document this feature.
