### ISSUE TITLE
Use newer rabbitmq-ha >= 1.13.1 in xray

### ISSUE THREAD

**Issue by jonasrutishauser** [jfrog/charts#331]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm 2.12.3
Kubernetes 1.10.11

**Which chart**:
xray

**What happened**:
As we need to change the image registry, it could not pull image busybox in rabbitmq-ha. The image name is hardcoded in this old version.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
Please use a newer version of rabbitmq-ha.

**Comment by eldada** [comment]
@jonasrutishauser - did you try using a newer chart version for `rabbitmq-ha`?
Your request is valid, but we need to verify two things:
1. Support upgrade over existing deployments
2. Use supported Xray RabbitMQ version (3.7.x)

If you did test it, and it supports these two requirements, you are welcome to submit a pull request.
