### ISSUE TITLE
Support 'artifactory.persistence.cacheProviderDir' for on-premise cluster

### ISSUE THREAD

**Issue by sanjeevkarani** [jfrog/charts#333]
Currently, support for 'artifactory.persistence.cacheProviderDir' is limited to cloud storage providers.
It is also required for 'file-system' persistence of on-premise k8s platform

**Comment by eldada** [comment]
@sanjeevkarani - can you also submit a pull request with this change?

**Comment by danielezer** [comment]
Fixed at #336
