### ISSUE TITLE
providing customArtifactoryConfigMap will result in nginx crashloop

### ISSUE THREAD

**Issue by ypan887** [jfrog/charts#352]
custom nginx config can be provided via customArtifactoryConfigMap option. However, enable this option right now will result in crashed nginx pod. 

When describing the pod, the following error can be found:

```
Warning  FailedPostStartHook     1m (x3 over 1m)  kubelet, gke-nutanix-nginx-default-pool-91516bba-qwfw  Exec lifecycle hook ([/bin/sh -c if [ -f /tmp/replicator-nginx.conf ]; then cp -fv /tmp/replicator-nginx.conf /etc/nginx/conf.d/replicator-nginx.conf; fi; if [ -f /tmp/ssl/*.crt ]; then rm -rf /var/opt/jfrog/nginx/ssl/example.*; cp -fv /tmp/ssl/* /var/opt/jfrog/nginx/ssl; fi; sleep 5; nginx -s reload; touch /var/log/nginx/conf.done
])
```
And from the container logs:

`nginx: [emerg] host not found in upstream "artifactory" in /etc/nginx/conf.d/artifactory.conf:31`

It looks like the cause of the issue is that:

1. We expect artifactory.conf that passed with config map to be mounted to /etc/nginx/conf.d/artifactory.conf (which it do). But the entrypoint script in the nginx container took the template under /var/opt/jfrog/nginx/artifactory.conf and replace the one we passed in when the container starts.

2. when 'customArtifactoryConfigMap' is not false, the following script is skipped during poststart life cycle, which didn't point to the correct service if you are installing with release name other than 'artifactory'. This script is expected to be skipped but, since what's under /etc/nginx/conf.d/ didn't get replaced by the custom artifact.conf passed in, it causes the "host not found in upstream" error

sed -i -e 's,proxy_pass.*http://artifactory.*/artifactory/\(.*\);,proxy_pass       http://{{ $serviceName }}:{{ $servicePort }}/artifactory/\1;

A possible fix is to modify nginx template to mount customArtifactoryConfigMap to a tmp folder first and use script to copy it to the right location just like the ssl secret. 

```
lifecycle:
          postStart:
            exec:
              command:
              - '/bin/sh'
              - '-c'
              - >
                {{- if (not .Values.nginx.customArtifactoryConfigMap) }}
                until [ -f /etc/nginx/conf.d/artifactory.conf ]; do sleep 1 ; done;
                if ! grep -q 'upstream' /etc/nginx/conf.d/artifactory.conf; then
                sed -i -e 's,proxy_pass.*http://artifactory.*/artifactory/\(.*\);,proxy_pass       http://{{ $serviceName }}:{{ $servicePort }}/artifactory/\1;,g' \
                    -e 's,server_name .*,server_name ~(?<repo>.+)\\.{{ $serviceName }} {{ $serviceName }};,g' \
                    /etc/nginx/conf.d/artifactory.conf;
                fi;
                {{- end }}
                **cp -fv /tmp/nginx/artifactory.conf /etc/nginx/conf.d/artifactory.conf;**
                if [ -f /tmp/replicator-nginx.conf ]; then
                cp -fv /tmp/replicator-nginx.conf /etc/nginx/conf.d/replicator-nginx.conf;
                fi;
                if [ -f /tmp/ssl/*.crt ]; then
                rm -rf /var/opt/jfrog/nginx/ssl/example.*;
                cp -fv /tmp/ssl/* /var/opt/jfrog/nginx/ssl;
                fi;
                sleep 5; nginx -s reload; touch /var/log/nginx/conf.done
```

```
{{- if .Values.nginx.customArtifactoryConfigMap }}
        - name: artifactory-nginx-config
          mountPath: "/tmp/nginx/artifactory.conf"
          subPath: "artifactory.conf"
{{- end }}
```

**Comment by danielezer** [comment]
@ypan887 This issue happened to me as well, the way to solve it is adding these parameters to helm install/upgrade:
```
--set nginx.env.skipAutoConfigUpdate=true
--set nginx.env.ssl=false
--set nginx.customArtifactoryConfigMap=<CONFIGMAP_NAME>
```

This is not ideal, but as a temporary workaround it should be good enough

**Comment by KierranM** [comment]
I've experienced this as well, but ours was also combined with the fact that quite often it would start with missing or no artifactory.conf at all. I've been messing around directly with the deployment and I think it's an issue with the fact that the `/etc/nginx/conf.d` folder (i.e where kubernetes is trying to mount the custom configmap) is a symlink to `/var/opt/jfrog/nginx/conf.d` which is also a mounted volume as an `emptyDir`.

Removing the `nginx-volume` from the deployment fixed everything. The containers now start every time without issue.

I'm considering PRing in a flag to disable the volume mount entirely.

**Comment by nsabernierdev1** [comment]
I'm facing this issue also when migrating to chart artifactory-ha-0.13.3.
Previously it was working, and now it fails.

I will give a try to Kierran solution, and will give an eye on a best solution.

Thanks,

**Comment by nsabernierdev1** [comment]
Hi,

I have managed to make it work by reverting the changes in the nginx-deployment.yaml file done byt the 0.13.3 chart version.

I have done two changes :
1. change the Nginx PodStart script:
replacing:
{{- if (not .Values.nginx.customArtifactoryConfigMap) }}
by
{{- if .Values.nginx.customArtifactoryConfigMap }}
cp -Lrf /tmp/conf.d/artifactory*.conf /etc/nginx/conf.d/artifactory.conf;
{{- else }}
2. replacing:
mountPath: "/etc/nginx/conf.d/artifactory-ha.conf"
subPath: "artifactory-ha.conf"
by:
mountPath: "/tmp/conf.d"

Waiting for the right solution ;-)

Thanks,

**Comment by danielezer** [comment]
@nsabernierdev1 I’m planning to change the way the nginx deployment works and that should fix this issue. In the mean, please try to use the workaround I suggested, since moving back to copying the file from /tmp can cause other issues and introduce complexities we are trying to move away from.
