### ISSUE TITLE
xray helm chart update

### ISSUE THREAD

**Issue by shayfisher** [jfrog/charts#356]
FEATURE REQUEST

**Version of Helm and Kubernetes**: 
Helm version - 2.13.1
Kubernetes - 1.12.8

**Which chart**:
xray-0.12.10

**What happened**:
feature request

**What you expected to happen**:
Please add a "flag" (i.e nginx.enabled) on the chart so It will set the service type for
xray server correctly.
When installing using helm, the default behavior creates xray-server service of type LoadBalancer.
On Azure this makes the environment spin up a load balancer.
We would like the chart to check if the flag is set, if it isn't set the service type to be of type ClusterIP and also set the externalPort field to be 8000 instead of 80.
Then we define our own Ingress routes to be able to access the xray-server.

**How to reproduce it** (as minimally and precisely as possible):
not relevant

**Anything else we need to know**:

**Comment by danielezer** [comment]
@shayfisher you can change the service type with:
```--set server.service.type=ClusterIP```

You can also change the external port with:
```--set server.externalPort=8000```

That should solve your problem. Changing the default value to ClusterIP would break backward compatibility and can cause issues to some of our customers who use the chart.

**Comment by shayfisher** [comment]
This is what I did.
I wanted this "logic" to be handled by the chart.
I will continue setting those two values.
Thank you

**Comment by eldada** [comment]
@shayfisher - do you have a suggestion on how you would like to see it? You can submit a pull request and we'll go over it.
