### ISSUE TITLE
Mission Control - Elasticsearch permission denied

### ISSUE THREAD

**Issue by angegar** [jfrog/charts#392]
**Is this a request for help?**:
 Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Don't know if it is a bug a miss configuration

**Which chart**:

Mission Control

**What happened**:

The elasticsearch container fails with the following error :

```Shell
 Warning  FailedPostStartHook  95s                  kubelet, ip-10-165-14-79.ec2.internal  Exec lifecycle hook ([/bin/sh -c sleep 5; mkdir -p /var/log/elasticsearch; bash /scripts/setup.sh > /var/log/elasticsearch/setup-$(date +%Y%m%d%H%M%S).log 2>&1
]) for Container "mission-control-elasticsearch" in Pod "mission-control-elasticsearch-bd5f7697f-dp6l4_ms(f8e47883-968c-11e9-a21d-0e548f39e9dc)" failed - error: command '/bin/sh -c sleep 5; mkdir -p /var/log/elasticsearch; bash /scripts/setup.sh > /var/log/elasticsearch/setup-$(date +%Y%m%d%H%M%S).log 2>&1
' exited with 1: mkdir: cannot create directory '/var/log/elasticsearch': Permission denied
/bin/sh: /var/log/elasticsearch/setup-20190624143356.log: No such file or directory
, message: "mkdir: cannot create directory '/var/log/elasticsearch': Permission denied\n/bin/sh: /var/log/elasticsearch/setup-20190624143356.log: No such file or directory\n"
```

Do i need to make something particular to be able to create the directory /var/log/elasticsearch ?

Here is the command i use to deploy :

```
build: create-namespace
	helm upgrade -f values.yaml -f values-small.yaml \
		--install \
		--namespace  mc \
		--set missionControl.mcKey='' \
		--set missionControl.missionControlUrl='' \
		 mission-control jfrog/mission-control
```

Thank you for the help you may bring

**Comment by danielezer** [comment]
@angegar it seems to me that you are using an old version of the chart. Can you please tell me what's the version you're trying to use? The part where we had `mkdir /var/log/elasticsearch` is quite old and is not in the current version of the chart

**Comment by angegar** [comment]
Here is the chart details :

![image](https://user-images.githubusercontent.com/5628764/60086538-82830500-973b-11e9-9781-126298628a6f.png)

**Comment by angegar** [comment]
jfrog repo is in my repo list

**Comment by danielezer** [comment]
@angegar the current chart version is 1.4.4 and is very different for the one you have, please try to run
helm repo update 
And try to install again

**Comment by angegar** [comment]
ok i am trying thank you

**Comment by angegar** [comment]
The chart version is good now, however i don't see the elasticsearch container whereas i enabled it. May be something i did not clean up.

**Comment by angegar** [comment]
arfff it is now a part of the pod mission-control.

**Comment by angegar** [comment]
ok i managed to make it works. Thank you for your quick help.

![image](https://user-images.githubusercontent.com/5628764/60087488-641e0900-973d-11e9-9e99-5ba3a5aff71a.png)

**Comment by danielezer** [comment]
Great @angegar. Glad it worked out
