### ISSUE TITLE
Nginx automatic configuration broken

### ISSUE THREAD

**Issue by ljupchokotev** [jfrog/charts#397]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: 
Kubernetes:
* Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"archive", BuildDate:"2019-06-08T16:22:01Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
* Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-gke.10", GitCommit:"f53039cc1e5295eed20969a4f10fb6ad99461e37", GitTreeState:"clean", BuildDate:"2019-06-19T20:48:40Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}

Helm: Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}

**Which chart**: artifactory-ha

**What happened**: It seems that the PR #376 has made quite some changes to the artifactory-ha charts. It is not possible to use the auto configuration of nginx anymore since that PR overrides the command for the nginx pod. And for some reason that broke our docker repositories (can't login), while it was working before updating the chart.

**What you expected to happen**: Expected that the auto-configuration of Nginx as explained in ReverseProxyConfiguration.md to work. Even the script updateConf.sh references some env variables that were deleted in that PR. Also expected to see logs in the nginx pod.

**How to reproduce it** (as minimally and precisely as possible):
1. Deploy chart
2. Update reverse proxy configuration following ReverseProxyConfiguration.md
3. Check nginx config file for artifactory

**Anything else we need to know**:
I don't mind the change to use a config map for nginx, but at least we need a better message in the changelog that the previous setup is not working anymore.

**Comment by eldada** [comment]
@ljupchokotev - thanks for the feedback. Indeed - this changes is removing functionality and should have been better communicated.
The automatic update of nginx config in the kubernetes setup bypassed the k8s artifactory service and went directly to the pods, which is against k8s best practices.
Managing the config in a config map aligns better with "configuration as code" and is able to better provide stability and reliability of the Artifactory application.

**Comment by ljupchokotev** [comment]
I agree that this way should be better. 

Have you tested the new way to check if it works with a Docker repository? Previously, following the ReverseProxyConfiguration.md documentation (needs to be removed since it adds confusion now) made it work using the `Repository Path` access method for Docker. With the new configuration, what needs to be configured in the reverse proxy settings of Artifactory to make it work with `Repository Path`? I will have more time to debug this today and come back with more information.

**Comment by danielezer** [comment]
@ljupchokotev The reason this is not working for you as expected is because, as you said, the nginx update config feature is gone. Your nginx config is now only redirecting repo.<artifactory-service-name> to the proper repository path. In order to achieve the same behaviour as before, you will need to create a configmap external to the chart, and provide its name as a parameter to helm install/upgrade:
`kubectl create configmap art-nginx-conf --from-file=artifactory-ha-nginx.conf`
and:
`helm upgrade --install artifactory --set nginx.customArtifactoryConfigMap=art-nginx-conf`

I will add some documentation for that to replace the old reverse proxy guide. Thanks for pointing that out.

**Comment by ljupchokotev** [comment]
Thanks for the response @danielezer. I will try out the documentation for static configuration in ReverseProxyConfiguration.md and see if that fixes my problem. Also, I don't see any way to customize the default nginx configuration through values.yaml. Is that something that plan to add?

**Comment by danielezer** [comment]
@ljupchokotev Something like this? ☝️

**Comment by ljupchokotev** [comment]
@danielezer yes, thank you for the PR! Now it's even easier since the server names, ports, etc. are templated out. Also, I think you forgot to remove `blabla.com` from https://github.com/jfrog/charts/pull/399/files#diff-06cf735a4b8cadafa965817b102afb07R484.

**Comment by danielezer** [comment]
Lol, you’re right! Thanks. I’ll remove that
