### ISSUE TITLE
PRs from forks fail on GKE step

### ISSUE THREAD

**Issue by rimusz** [jfrog/charts#41]
PRs from forks fail on GKE step as:
```
Pull requests sent from forked repositories do not have access to encrypted variables or data.
```
https://docs.travis-ci.com/user/pull-requests  

So we need to rethink this integration part.

**Comment by eldada** [comment]
We'll move to use [GCP cloud build](https://cloud.google.com/cloud-build/) for this.

**Comment by rimusz** [comment]
minikube is now set to test PRs from forks and GKE for forks form the main repo.
