### ISSUE TITLE
Support of additional S3 Configuration Options (httpsOnly, httpsPort, httpPort)

### ISSUE THREAD

**Issue by AlexanderDenk-EE** [jfrog/charts#425]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST

Support for custom http/https port and httpsOnly flag for AWS-S3 provider. The underlying S3 provider would allow to be configured to use an arbitrary S3 (even with non-default and non-https ports).

**Version of Helm and Kubernetes**: n/a

**Which chart**: artifactory / artifactory-ha

**What happened**: The "AWS-S3"-implementation is more restrictive than it needs to be. This leads us to forks of the charts that could be avoided.

**What you expected to happen**: Introduce parameters for these settings (httpsOnly, httpPort, httpsPort).

**How to reproduce it** (as minimally and precisely as possible): see above.

**Anything else we need to know**: If the request is supported I'm willing to add the three flags myself :) It shouldn't be that complex.

**Comment by eldada** [comment]
@AlexanderDenk-EE - you are more than welcome to submit a pull request!

**Comment by eldada** [comment]
PRs #435 and #436 now provide the option to fully control the binarystore.xml and you can change it to fit your needs.
If you would like this see these options as part of the default template, you can submit a pull request.
