### ISSUE TITLE
Providing custom binarystore.xml to the chart

### ISSUE THREAD

**Issue by mikaelhachaturian** [jfrog/charts#432]
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
all versions

**Which chart**:
artifactory

**What happened**:
As of writing this issue, the artifactory chart creates a general binarystore.xml based on persistence storage type. We use cachefs with filesystem and right now the filesystem type creates a default binarystore without cachefs.

**What you expected to happen**:
option to provide the chart a custom binarystore.xml to use

**Comment by eldada** [comment]
@mikaelhachaturian - This is a valid request. We'll provide a pull request in the near future.

**Comment by eldada** [comment]
Will close once `artifactory-ha` is also updated with the change.
