### ISSUE TITLE
Artifactory and Docker repositories

### ISSUE THREAD

**Issue by MichaelVL** [jfrog/charts#455]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Bug report.

**Version of Helm and Kubernetes**:

Helm:
Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}

Kubernetes:
1.15.3

**Which chart**:

stable/artifactory

**What happened**:

I want to use Artifactory for hosting docker repositories. Specifically the sub-domain method with a reverse proxy in front of Artifactory. I didn't work - more details below.

**What you expected to happen**:

Docker operations like 'login' and 'push' should work.

**How to reproduce it** (as minimally and precisely as possible):

As a test, i wanted to deploy Artifactory using a hostname (DNS) of
'artifactory.example.com' and I wanted to test with a Docker repository named
'repo1', hence with the sub-domain method, the docker repository should be
located at 'repo1.artifactory.example.com'

I deployed Artifactory with Helm - below is the essential part of the installation:

VIP = IP address from DNS of 'artifactory.example.com'
HOST0 = "repo1.artifactory.example.com"
HOST1 = "artifactory.example.com"

helm upgrade artifactory jfrog/artifactory --install --version 7.16.11 \
               --set nginx.service.loadBalancerIP=$VIP \
               --set ingress.hosts[0]=$HOST0 \
               --set ingress.hosts[1]=$HOST1 \

This generated a Helm release called 'artifactory' and a ConfigMap called
'artifactory-artifactory-nginx-artifactory-conf' which has the following
'server_name' specification:

      server_name ~(?<repo>.+)\.artifactory-artifactory artifactory-artifactory ~(?<repo>.+)\.artifactory.example.com repo1.artifactory.example.com ~(?<repo>.+)\.example.com artifactory.example.com;

This 'server_name' spec is important since this is how the repository path is mapped to the Artifactory URLs.

I believe this 'server_name' spec have some problems:

1. The dots '.' in the regular expressions should be escaped - only the first dot is properly escaped.

2. The full names are also included here (e.g. 'repo1.artifactory.example.com')
and this will effectively mask the regular expressions since Nginx give higher
precedence to exact names than wildcards.

Manually changing the 'server_name' spec to the following (escaping dots, removing exact names for docker repos) made docker repositories work properly:

      server_name ~(?<repo>.+)\.artifactory-artifactory artifactory-artifactory ~(?<repo>.+)\.artifactory\.example\.com ~(?<repo>.+)\.example\.com artifactory.example.com;

I.e. commands like 'docker login repo1.artifactory.example.com' now works.

**Anything else we need to know**:

I didn't find any documenation on how the chart should be used with docker
repositories. The above procedure was kind of reverse-engineered from other
documentation and Nginx knowledge. It might be good with some specific
documentation on how docker repositories should, i.e. is it the intention that
ingress' should be defined for each repository?

**Comment by danielezer** [comment]
@MichaelVL I was actually not able to reproduce this issue. I deployed artifactory with the sub-domain docker method and added the repositories to the ingress hosts. It actually did work as expected. Can you please share the error messages you saw when trying to run `docker login` or `docker pull` before you made changes to the nginx config map?

**Comment by MichaelVL** [comment]
artifactory-artifactory-nginx-artifactory-conf ConfigMap:

  server_name ~(?<repo>.+)\.artifactory-artifactory artifactory-artifactory ~(?<repo>.+)\.artifactory.example.com repo1.artifactory.example.com ~(?<repo>.+)\.example.com artifactory.example.com;

Docker login to the repository is done with:

  docker login repo1.artifactory.example.com

and it results in 400 error codes. Investigating the traffic between the Nginx POD and the artifactory POD I see:

    GET /artifactory/api/docker/v2/ HTTP/1.1
    X-Artifactory-Override-Base-Url: https://repo1.artifactory.example.com:443/artifactory
    X-Forwarded-Port: 443
    X-Forwarded-Proto: https
    Host: repo1.artifactory.example.com
    X-Forwarded-For: 10.244.0.1
    Connection: close
    User-Agent: docker/18.09.7 go/go1.10.1 git-commit/2d0083d kernel/4.15.0-45-generic os/linux arch/amd64 UpstreamClient(Docker-Client/18.09.7 \(linux\))
    Accept-Encoding: gzip

    HTTP/1.1 400 Bad Request
    Server: Artifactory/6.11.6
    X-Artifactory-Id: 6e921143e3a9e856:-2c5c96d7:16cb7f6d82a:-8000
    Content-Type: application/json;charset=ISO-8859-1
    Content-Length: 116
    Date: Thu, 22 Aug 2019 07:18:01 GMT
    Connection: close

    {
      "errors" : [ {
	"status" : 400,
	"message" : "Unsupported docker v2 repository request for 'null'"
      } ]
    }

Here we see the original host was 'repo1.artifactory.example.com' and the rewritten URL was '/artifactory/api/docker/v2/'.

To investigate the regular expression and the setting of the 'repo' variable, I
added the following additional header to the
artifactory-artifactory-nginx-artifactory-conf ConfigMap:

        proxy_set_header    X-Artifactory-Repo REPO-VALUE:$repo;

Tracing the traffic between the Nginx POD and the artifactory POD show the additional header not containing any repo value:

  X-Artifactory-Repo: REPO-VALUE:

With the 'server_name' spec change to:

  server_name ~(?<repo>.+)\.artifactory-artifactory artifactory-artifactory ~(?<repo>.+)\.artifactory\.example\.com ~(?<repo>.+)\.example\.com;

the 'docker login' succeeds, and tracing the traffic between the Nginx POD and the artifactory POD shows correct parsing of the regex and the repo value now containing 'repo1':

    GET /artifactory/api/docker/repo1/v2/ HTTP/1.1
    X-Artifactory-Override-Base-Url: https://repo1.artifactory.example.com:443/artifactory
    X-Forwarded-Port: 443
    X-Forwarded-Proto: https
    Host: repo1.artifactory.example.com
    X-Forwarded-For: 10.244.0.1
    X-Artifactory-Repo: REPO-VALUE:repo1
    Connection: close
    User-Agent: docker/18.09.7 go/go1.10.1 git-commit/2d0083d kernel/4.15.0-45-generic os/linux arch/amd64 UpstreamClient(Docker-Client/18.09.7 \(linux\))
    Authorization: Bearer XXXXXXXXXXXXXXXX
    Accept-Encoding: gzip

    HTTP/1.1 200 OK
    Server: Artifactory/6.11.6
    X-Artifactory-Id: 6e921143e3a9e856:-2c5c96d7:16cb7f6d82a:-8000
    Docker-Distribution-Api-Version: registry/2.0
    Content-Type: application/json
    Transfer-Encoding: chunked
    Date: Thu, 22 Aug 2019 07:48:28 GMT
    Connection: close

    {}

**Comment by MichaelVL** [comment]
With the default deployment shown above, resulting in the following line in the
artifactory-artifactory-nginx-artifactory-conf ConfigMap:

  server_name ~(?<repo>.+)\.artifactory-artifactory artifactory-artifactory ~(?<repo>.+)\.artifactory.example.com repo1.artifactory.example.com ~(?<repo>.+)\.example.com artifactory.example.com;

Docker login to the repository is done with:

  docker login repo1.artifactory.example.com

and it results in 400 error codes. Investigating the traffic between the Nginx POD and the artifactory POD I see:

    GET /artifactory/api/docker/v2/ HTTP/1.1
    X-Artifactory-Override-Base-Url: https://repo1.artifactory.example.com:443/artifactory
    X-Forwarded-Port: 443
    X-Forwarded-Proto: https
    Host: repo1.artifactory.example.com
    X-Forwarded-For: 10.244.0.1
    Connection: close
    User-Agent: docker/18.09.7 go/go1.10.1 git-commit/2d0083d kernel/4.15.0-45-generic os/linux arch/amd64 UpstreamClient(Docker-Client/18.09.7 \(linux\))
    Accept-Encoding: gzip

    HTTP/1.1 400 Bad Request
    Server: Artifactory/6.11.6
    X-Artifactory-Id: 6e921143e3a9e856:-2c5c96d7:16cb7f6d82a:-8000
    Content-Type: application/json;charset=ISO-8859-1
    Content-Length: 116
    Date: Thu, 22 Aug 2019 07:18:01 GMT
    Connection: close

    {
      "errors" : [ {
	"status" : 400,
	"message" : "Unsupported docker v2 repository request for 'null'"
      } ]
    }

Here we see the original host was 'repo1.artifactory.example.com' and the rewritten URL was '/artifactory/api/docker/v2/'.

To investigate the regular expression and the setting of the 'repo' variable, I
added the following additional header to the
artifactory-artifactory-nginx-artifactory-conf ConfigMap:

        proxy_set_header    X-Artifactory-Repo REPO-VALUE:$repo;

Tracing the traffic between the Nginx POD and the artifactory POD show the additional header not containing any repo value:

  X-Artifactory-Repo: REPO-VALUE:

With the 'server_name' spec change to:

  server_name ~(?<repo>.+)\.artifactory-artifactory artifactory-artifactory ~(?<repo>.+)\.artifactory\.example\.com ~(?<repo>.+)\.example\.com;

the 'docker login' succeeds, and tracing the traffic between the Nginx POD and the artifactory POD shows correct parsing of the regex and the repo value now containing 'repo1':

    GET /artifactory/api/docker/repo1/v2/ HTTP/1.1
    X-Artifactory-Override-Base-Url: https://repo1.artifactory.example.com:443/artifactory
    X-Forwarded-Port: 443
    X-Forwarded-Proto: https
    Host: repo1.artifactory.example.com
    X-Forwarded-For: 10.244.0.1
    X-Artifactory-Repo: REPO-VALUE:repo1
    Connection: close
    User-Agent: docker/18.09.7 go/go1.10.1 git-commit/2d0083d kernel/4.15.0-45-generic os/linux arch/amd64 UpstreamClient(Docker-Client/18.09.7 \(linux\))
    Authorization: Bearer XXXXXXXXXXXXXXXX
    Accept-Encoding: gzip

    HTTP/1.1 200 OK
    Server: Artifactory/6.11.6
    X-Artifactory-Id: 6e921143e3a9e856:-2c5c96d7:16cb7f6d82a:-8000
    Docker-Distribution-Api-Version: registry/2.0
    Content-Type: application/json
    Transfer-Encoding: chunked
    Date: Thu, 22 Aug 2019 07:48:28 GMT
    Connection: close

    {}

**Comment by danielezer** [comment]
Thanks @MichaelVL, that's very good info. I also had the same line in the nginx configmap, and interestingly the docker commands worked for me. I'll try to reproduce your error and will keep you updated

**Comment by danielezer** [comment]
@MichaelVL do you have any values file you use to install the chart?

**Comment by MichaelVL** [comment]
With these shell variables:

  VIP = IP address from DNS of 'artifactory.example.com', e.g. 192.168.122.220
  HOST0 = "repo1.artifactory.example.com"
  HOST1 = "artifactory.example.com"

and a previously created secret 'artifactory-license' containing the license
file, I use the following helm command (I also have a few settings related to
persistence, which I have removed):

helm upgrade artifactory jfrog/artifactory \
               --install \
               --version 7.16.11 \
               --set nginx.service.loadBalancerIP=$VIP \
               --set ingress.enabled=false \
               --set ingress.hosts[0]=$HOST0 \
               --set ingress.hosts[1]=$HOST1 \
               --set artifactory.license.secret=artifactory-license,artifactory.license.dataKey=art.lic \
               --namespace=xxxx

Note that the 'ingress.enabled=false' is the chart default and thus
unnecessary. Specifying 'ingress.hosts' while having 'ingress.enabled=false'
might seem strange, but the chart use 'ingress.hosts' independently of
'ingress.enabled'.

**Comment by danielezer** [comment]
@MichaelVL When I disabled ingress I was able to reproduce your issue, this PR should fix your issue :)

**Comment by MichaelVL** [comment]
I can confirm, that the PR solves the issue.

Thanks!
