### ISSUE TITLE
stable/artifactory/values.yaml have a typo  that cannot be used

### ISSUE THREAD

**Issue by pythonton** [jfrog/charts#459]
**BUG REPORT?**:

**Version of Helm and Kubernetes**:  v2.10.0 ；  1.10

**Which chart**: artifactory

**What happened**:

### Bug 1 : split typo

![image](https://user-images.githubusercontent.com/50493427/63694829-e617d480-c849-11e9-9f5d-8909c33e41ca.png)
via. https://github.com/jfrog/charts/blob/master/stable/artifactory/values.yaml

![image](https://user-images.githubusercontent.com/50493427/63694985-355e0500-c84a-11e9-99ba-fc7557c7945b.png)

### Bug 2 : StatefulSet:artifactory ：Repeatedly mount to  /var/opt/jfrog/artifactory

![image](https://user-images.githubusercontent.com/50493427/63695180-adc4c600-c84a-11e9-8407-ec2fbd3e1ba4.png)

```
create Pod artifactory-artifactory-0 in StatefulSet artifactory-artifactory failed error: Pod "artifactory-artifactory-0" is invalid: spec.containers[0].volumeMounts[1].mountPath: Invalid value: "/var/opt/jfrog/artifactory": must be unique
```

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by danielezer** [comment]
@pythonton This is not a typo, it just requires helm version `2.11.0`.
Anyway, this is going away soon, PR #458 and #457 will remove the usage of this function

**Comment by pythonton** [comment]
thx! 

suggest that write Prerequisites about #helm  Version# in _README.md_
