### ISSUE TITLE
nginx as (optional) sidecar container

### ISSUE THREAD

**Issue by AlexanderDenk-EE** [jfrog/charts#460]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Description:**

We are running AF with a cluster of 1 master node and 2 worker nodes in an OpenShift environment using an OpenShift LB. For enabling AF to be used as docker registry we use nginx as reverse proxy in front of AF. So nginx is basically used only for rewriting URLs. Therefore inbound and outbound traffic currently needs to get over two network hops from the LB to nginx and from nginx to an AF instance. This causes internal traffic that could be avoided if the nginx hop would be removed. This should be possible if nginx is executed as sidecar of an AF instance instead as standalone container in front of AF. We are thinking that this is a common use case and the option to execute nginx as sidecar would be beneficial for multiple users. Also it would enable us to stick to the official chart versions. 

**Version of Helm and Kubernetes**: latest stable

**Which chart**: latest stable

**What happened**: we are running in network bottlenecks

**What you expected to happen**: we try to avoid all unnecessary traffic

**How to reproduce it** (as minimally and precisely as possible): just use the default setup

**Anything else we need to know**: n/a

**Comment by danielezer** [comment]
@AlexanderDenk-EE This is available using the `nginx.enabled=false` to disable nginx. This way Artifactory will be deployed without the sidecar nginx.

**Comment by AlexanderDenk-EE** [comment]
Sorry, I think the ticket was misunderstood. Currently NGINX is **NOT** deployed as sidecar of Artifactory but deployed as standalone deployment beside the stateful set. The request is the enhance the setup to support NGINX **as** sidecar of the Artifactory Primary/Member stateful set.

**Comment by danielezer** [comment]
@AlexanderDenk-EE The idea behind separating the two is so that you would be able to scale each of them independently. For example, something you would want 3 Artifactory nodes but only one or two nginx server, so that’s why we didn’t couple them together. The extra network hop shouldn’t be significant, but if it is I can suggest you would rewrite the URLs for docker using your other LB

**Comment by eldada** [comment]
As an added note - you can still add a custom sidecar as you wish with the `nginx.enabled=false` and writing your own `artifactory.customSidecarContainers` is a dedicated values file.
