### ISSUE TITLE
Helm charts won't launch

### ISSUE THREAD

**Issue by evannorstrand** [jfrog/charts#464]
Very simply, the standard low availability helm chart when launched with default settings fails to launch successfully.

This is not the case with the deprecated version in helm which we are looking to migrate away from.

**Comment by eldada** [comment]
Can you provide the command used and the errors you see?

**Comment by eldada** [comment]
We have also fixed a potential helm rendering issue with #463 that might help. You are welcome to test the latest versions.

**Comment by evannorstrand** [comment]
The error is: Wait helm template failed. Error: found in requirements.yaml, but missing in charts/ directory: postgresql : exit status 1

**Comment by eldada** [comment]
When using the helm chart from local sources, you need to first pull in the dependencies.
```
helm dependency update <path to chart>
```
Does this solve your error?

**Comment by danielezer** [comment]
@evannorstrand did that fix your problem?

**Comment by evannorstrand** [comment]
Apologies for not getting back to this sooner, I had the wrong URL referenced. I was pointing at the github charts url, not the jfrog url.
