### ISSUE TITLE
Need way to turn off `wait-for-db` completely

### ISSUE THREAD

**Issue by maguro** [jfrog/charts#479]
**FEATURE REQUEST**

**Version of Helm and Kubernetes**:

Helm: v2.14.3
Kubernetes: 1.14.3-gke.11

**Which chart**:
`jfrog/artifactory`
`7.17.4`

**What happened**:

I am using Cloud SQL and I intend to access it via the Cloud SQL proxy, which is [installed as a sidecar](https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine).  This means that there is no SQL connectivity until the sidecar is run.

The problem is that the init container, `wait-for-db`, sits and waits for a DB connection which cannot be accomplished until the sidecar is running.

**What you expected to happen**:

Have the ability to disable the `wait-for-db` init container.

**Comment by eldada** [comment]
Good, valid request.Will pick it up.
