### ISSUE TITLE
Adding Support for SSL mode in mission control chart for external postgresql

### ISSUE THREAD

**Issue by ypan887** [jfrog/charts#487]
right now, it seems that there are no way to pass ssl options to external postgresql databse in mission control chart. 

1. We do have an options for bundled postgresql:

postgresql.db.sslmode

Which sets the env variable 

$DB_SSLMODE

However, it is not being honoured by JFMC 3.5

2. The sslmode properties are not available for extern database, and we can not directly pass the full url with ssl options. This should be added.

3.  JFMC_DB_URL defined in mission control stateful set does not honor $DB_SSLMODE option

value: 'jdbc:postgresql://{{ .Release.Name }}-postgresql:{{ .Values.postgresql.service.port }}/{{ .Values.postgresql.db.name }}?currentSchema={{ .Values.postgresql.db.jfmcSchema }}'

**Comment by JfrogPrasanna** [comment]
No relevant anymore.

**Comment by sponte** [comment]
Hello, why is this irrelevant no more? I came across a use case for MC deployment and would like to enable that option
