### ISSUE TITLE
Nginx config update error

### ISSUE THREAD

**Issue by mgstep** [jfrog/charts#488]
I ran into an error upgrading the Nginx config 

helm upgrade --install artifactory jfrog/artifactory -f nginx-values.yaml
UPGRADE FAILED
Error: render error in "artifactory/templates/nginx-service.yaml": template: artifactory/templates/nginx-service.yaml:1:14: executing "artifactory/templates/nginx-service.yaml" at <.Values.nginx.enabled>: nil pointer evaluating interface {}.enabled
Error: UPGRADE FAILED: render error in "artifactory/templates/nginx-service.yaml": template: artifactory/templates/nginx-service.yaml:1:14: executing "artifactory/templates/nginx-service.yaml" at <.Values.nginx.enabled>: nil pointer evaluating interface {}.enabled

**Comment by mgstep** [comment]
helm version v2.14.3

**Comment by eldada** [comment]
1. What was the config used in the initial install?
2. What are the values in `nginx-values.yaml`?

**Comment by mgstep** [comment]
Initial install was a vanilla helm install jfrog/artifactory —name artifactory (tried with artifactory-ha with same results). The config file was first a modified version of the one specified on the readme, then even using the exact readme threw the error. All it takes to throw the error is the first two lines of the .yaml file, however, that reference Nginx 

I.e. the nginx-values.yaml from the docs as:
nginx:
  artifactoryConf: |
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_certificate  {{ .Values.nginx.persistence.mountPath }}/ssl/tls.crt;
    ssl_certificate_key  {{ .Values.nginx.persistence.mountPath }}/ssl/tls.key;
    ssl_session_cache shared:SSL:1m;
    ssl_prefer_server_ciphers   on;
    ## server configuration...

**Comment by danielezer** [comment]
@mgstep From what you posted here, you have an indentation issue. It should look something like the following:
```

**Comment by danielezer** [comment]
@mgstep can you also share which version of the just you are trying to use and the output from trying to install without any values? When I try to install `artifactory-ha` without values, it works as expected..

**Comment by mgstep** [comment]
The indents were just from the paste, with them indented properly I still get the error.
The install works but updating the nginx values fails.

**Comment by danielezer** [comment]
@mgstep I am still not able to reproduce this issue... Can you please explain your full process and send all of your values files?

**Comment by danielezer** [comment]
@mgstep From looking at your values and your error message, it seems like it happens because you have an indentation issue in values.
instead of:
```
nginx: 
artifactoryConf: |
  ...
```

You need:
```
nginx:
  artifactoryConf: |
    ...
```
Please notice the two spaces before the `artifactoryConf` keyword.

When I use the values you use as is, I get the same error you get:
```
Release "artifactory-ha" does not exist. Installing it now.
Error: render error in "artifactory-ha/templates/nginx-service.yaml": template: artifactory-ha/templates/nginx-service.yaml:1:14: executing "artifactory-ha/templates/nginx-service.yaml" at <.Values.nginx.enabled>: nil pointer evaluating interface {}.enabled
```

When I fix the indentation for the `artifactoryConf` keyword, it works as expected.

Also, if you examine the error message, you can see that it says `nil pointer evaluating interface {}.enabled`. This basically means that the `nginx` map is `nil`, since you have in your values file: 
`nginx:` without `artifactoryConf` properly indented, it means you set two top level keys: `nginx: ""` and
`` `artifactoryConf: | 
  ...
```

Please let me know if that solves your issue

**Comment by mgstep** [comment]
Can't believe I didn't see that. Thank you for your help. The error had me wrapped around the axle,  especially because I have done this before without issue (its the little things). Whoops!

**Comment by danielezer** [comment]
Happy to help :)
