### ISSUE TITLE
Putting chart version in spec.VolumeClaimTemplate.metadata.labels of a StatefulSet prevents ANY future upgrade of existing Release

### ISSUE THREAD

**Issue by robjcrowston** [jfrog/charts#495]
BUG REPORT 

See below for full details:
https://github.com/helm/charts/issues/7803

It seems that the jfrog helm charts also have this bug, for example:

https://github.com/jfrog/charts/blob/45c9c8e138f8ce94e80d638653ab08ae810b1738/stable/artifactory/templates/artifactory-statefulset.yaml#L7

**Comment by danielezer** [comment]
Hey @robjcrowston Thanks for the issue. I don't see the chart label in `spec.VolumeClaimTemplate.metadata.labels`. The link you sent is to labels set on the statefulset itself and not on the volumeClaimTemplate. From looking at the code, I see that the only label we set on the volumeClaimTemplate is `name: artifactory-volume`
https://github.com/jfrog/charts/blob/45c9c8e138f8ce94e80d638653ab08ae810b1738/stable/artifactory/templates/artifactory-statefulset.yaml#L453

**Comment by danielezer** [comment]
Unless I'm missing something @robjcrowston ?

**Comment by danielezer** [comment]
Closing this issue. Doesn't seem to be relevant
