### ISSUE TITLE
helm install fails every time

### ISSUE THREAD

**Issue by imorti** [jfrog/charts#499]
Been trying to use the artifactor-ha helm chart using 
`helm install --name artifactory-ha jfrog/artifactory-ha`. All pods fail except `artifactory-ha-postgresql`. 
Error in nginx pod is:
```nginx: [emerg] host not found in upstream "artifactory" in /etc/nginx/conf.d/artifactory.conf:27```

**Comment by danielezer** [comment]
Hey @imorti, sounds like you’re using an old version of the chart. Please try to run:
helm repo update
And try to install the chart again

**Comment by imorti** [comment]
oh I did that about 3-4 times already and still fails literally every time.

**Comment by danielezer** [comment]
Can you please share the version which you are using and any values files/parameters you provide for the chart upon installation?

**Comment by imorti** [comment]
`artifactory-ha-0.17.1`

`nginx: docker.bintray.io/jfrog/nginx-artifactory-pro:6.13.1`

**Comment by imorti** [comment]
`artifactory-ha          	1       	Fri Oct 11 12:24:13 2019	DEPLOYED	artifactory-ha-0.17.1    	6.13.1     	default `

**Comment by imorti** [comment]
apiVersion: v1
appVersion: 6.12.2
description: Universal Repository Manager supporting all major packaging formats,
  build tools and CI servers.
home: https://www.jfrog.com/artifactory/
icon: https://raw.githubusercontent.com/jfrog/artifactory-dcos/master/images/jfrog_med.png
keywords:
- artifactory
- jfrog
- devops
maintainers:
- email: amithk@jfrog.com
  name: amithins
- email: daniele@jfrog.com
  name: danielezer
- email: eldada@jfrog.com
  name: eldada
- email: rimasm@jfrog.com
  name: rimusz
name: artifactory-ha
sources:
- https://bintray.com/jfrog/product/JFrog-Artifactory-Pro/view
- https://github.com/jfrog/charts
version: 0.16.7

**Comment by danielezer** [comment]
Thanks @imorti. Can you please share the logs from the artifactory pod?

**Comment by eldada** [comment]
@imorti - is this still relevant?

**Comment by imorti** [comment]
Sorry. I rolled off the project so no access to logs. Will try again on a new cluster.

**Comment by danielezer** [comment]
@imorti any is this still relevant? Are you able to provide the logs from the Artifactory pod?
