### ISSUE TITLE
xray - add secrets for DBs credentials

### ISSUE THREAD

**Issue by palko444** [jfrog/charts#501]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):  FEATURE REQUEST
Please allow credentials for rabbitmq, postgress and mongodb, to be set from secrets. Currently credentials are directly in values.yaml file. This will probably require update of dependent charts also.

**Version of Helm and Kubernetes**:
k8s: v1.14.3
helm: v2.14.0

**Which chart**:
NAME            CHART VERSION   APP VERSION 
jfrog/xray      1.2.1           2.10.1      

**What happened**:
All credentials for mongodb, postgres and rabbitmq are stored in chart values.yaml file.

**What you expected to happen**:
Have possibility to load credentials from secrets

**How to reproduce it** (as minimally and precisely as possible):
N/A

**Anything else we need to know**:

**Comment by sp3nx0r** [comment]
Also looking for this functionality. Utilizing Helm in a CI/CD environment is incompatible with current Xray chart due to the lack of secrets support. Rabbitmq appears to allow existing secret, but postgres/mongo do not have that option in chart currently.

**Comment by JfrogPrasanna** [comment]
Closed in 7.x
