### ISSUE TITLE
xray - add wait for dependent services

### ISSUE THREAD

**Issue by palko444** [jfrog/charts#502]
**Is this a request for help?**: NO

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):FEATURE REQUEST
Add options for mongodb, postgress, rabbitmq to be able to wait for instances to be accessible. Currently this is implemented only if Dbs are installed by chart
```
{{- if .Values.mongodb.enabled }}
    echo "Waiting for Mongo..."
    until nc -z -w 2 {{ .Release.Name }}-mongodb 27017 && echo mongodb ok; do
      sleep 2;
    done;
    {{- end }}
    {{- if .Values.postgresql.enabled }}
    echo "Waiting for Postgres..."
    until nc -z -w 2 {{ .Release.Name }}-postgresql {{ .Values.postgresql.service.port }} && echo postgresql ok; do
      sleep 2;
    done;
    {{- end }}
    echo "Waiting for Rabbit..."
    {{ if index .Values "rabbitmq-ha" "enabled" }}
    until nc -z -w 2 {{ .Release.Name }}-rabbitmq-ha {{ index .Values "rabbitmq-ha" "rabbitmqNodePort" }} && echo rabbitmq ok; do
    {{- end }}
    {{ if index .Values "rabbitmq" "enabled" }}
    until nc -z -w 2 {{ .Release.Name }}-rabbitmq {{ index .Values "rabbitmq" "rabbitmqNodePort" }} && echo rabbitmq ok; do
    {{- end }}
      sleep 2;
    done;
```
This can be done same way as in artifactory-ha `waitForDatabase: true`
E.g.:
waitForMongo: true|false
waitForRabbitmq: true|false
waitForPostgres: true|false

**Version of Helm and Kubernetes**:
k8s: v1.14.3
helm: v2.14.0

**Which chart**:
NAME CHART VERSION APP VERSION
jfrog/xray 1.2.1 2.10.1

**What happened**:

**What you expected to happen**:
I want xray to wait for dependent services, even if those are not deployed by xray chart.

**How to reproduce it** (as minimally and precisely as possible):
N/A

**Anything else we need to know**:

**Comment by JfrogPrasanna** [comment]
@palko444 Thanks for raising this issue. However,  the services themselves wait and retry for RabbitMQ and PosgreSQL in unified platform. Given this retry mechanism by application services, this request is no more relevant and hence will be closing it.
