### ISSUE TITLE
xray - add rabbitmq url in global section

### ISSUE THREAD

**Issue by palko444** [jfrog/charts#503]
**Is this a request for help?**:NO

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):FEATURE REQUEST
Add `rabbitmqurl` to xray global section as this is only one missing. Mongo and postges are both in global section.

**Version of Helm and Kubernetes**:
k8s: v1.14.3
helm: v2.14.0

**Which chart**:
NAME CHART VERSION APP VERSION
jfrog/xray 1.2.1 2.10.1

**What happened**:
For xray chart rabbitmq can be only installed via chart, there is no option to use already installed rabbitmq.

**What you expected to happen**:
To be able to use existing installation of rabbitmq

**How to reproduce it** (as minimally and precisely as possible):
N/A

**Anything else we need to know**:

**Comment by chukka** [comment]
@palko444  is this still a requirement  in Xray 2.x charts ?

**Comment by chukka** [comment]
@palko444  Reminder ! If this is not a requirement - We can close this issue

**Comment by palko444** [comment]
Hello, im currently using Xray3, and there is option to specify this in systemYaml in values file.
So for me this one can be closed

**Comment by chukka** [comment]
Thanks for update.
