### ISSUE TITLE
xray - allow global.*urls to be loaded from secrets 

### ISSUE THREAD

**Issue by palko444** [jfrog/charts#504]
**Is this a request for help?**:NO

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):FEATURE REQUEST
Currently all credentials in `global.*url` are put as string to values.yaml file. Please move those to secrets, as `postgresqlTlsSecret` is already secret.

**Version of Helm and Kubernetes**:
k8s: v1.14.3
helm: v2.14.0

**Which chart**:
NAME CHART VERSION APP VERSION
jfrog/xray 1.2.1 2.10.1

**What happened**:
Config urls contains sensitive data (credentials) for dependent services and are configured directly in values.yaml file. 

**What you expected to happen**:
Allow these credentials to be passed as secret.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by jaysiee** [comment]
@palko444  Any plans to implement this? 

This is a critical issue for people trying to implement gitops as having these values at the current location keeps us from using SealedSecrets and similar workflows.

**Comment by palko444** [comment]
I guess i will wait for helm chart for xray 3.0

**Comment by JfrogPrasanna** [comment]
Closed in 7.x charts.
