### ISSUE TITLE
Add JMX Exporter to helm chart

### ISSUE THREAD

**Issue by DDSloan96** [jfrog/charts#508]
Feature Request:

When JMX is exposed include the jmx exporter (https://github.com/prometheus/jmx_exporter) and associated service monitor config

**Comment by tzatwork** [comment]
Seconding this. I'm literally performing this work now to get jmx in prometheus.

**Comment by chukka** [comment]
@DDSloan96  @tzatwork  can you please provide more info on this ? is this needed for artifactory chart or any other chart ?
