### ISSUE TITLE
Feature: preStartCommand for primary and node separately.

### ISSUE THREAD

**Issue by zendril** [jfrog/charts#515]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE

**Version of Helm and Kubernetes**: 0.17.1 and k8s 1.15.3

**Which chart**: artifactory-ha

**What happened**: preStartCommand runs on both primary and member nodes.

**What you expected to happen**: Sometimes there are things that you only want to run on one or the other. So we would like to see: 
* Values.artifactory.primary.preStartCommand
* Values.artifactory.node.preStartCommand

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
I'll work to implement and raise PR as we are working with support right now on an issue this may be helpful in fixing.

**Comment by zendril** [comment]
@eldada @danielezer @arielkv Do you guys have a preference whether this run before, or after the existing Values.artifactory.preStartCommand?

**Comment by eldada** [comment]
Hi @zendril - this is a great idea and makes good sense!
I think it should run **after** the existing `artifactory.preStartCommand`.
Looking forward for the PR. Thx for helping!

**Comment by danielezer** [comment]
I agree with @eldada since I see this as a kind of ‘override’ to the regular preStartCommand. Thanks @zendril! Great idea!
