### ISSUE TITLE
Allow env to be sourced from secrets

### ISSUE THREAD

**Issue by zendril** [jfrog/charts#519]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**: 2.9 Helm, 1.15.3 Kubernetes

**Which chart**: artifactory-ha

**What happened**: The helm chart allows you to pass extra env vars, but they are just static values for the most part. 

**What you expected to happen**: I would like to have secrets mounted as env vars in the artifactory primary and member nodes.  This is possible like so: 
 https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables

**Anything else we need to know**: I want to do this as we are working with you guys on getting art-ha and access-federation working better in a k8s environment. One of the things we need to support is additional logback appenders (like the logstash appender to send things to kafka and EFK stack). I have most of that working except I need to get the password into the logback configuration, which it is able to read from env vars. 

So you can do something like this in the logback.xml:
`<producerConfig>ssl.keystore.password=${LOGA_KEYSTORE_SECRET}</producerConfig>` 

Need something like extraEnvironmentVariables but allows the value type to be set to not just 'value" but could also be something like 'valueFrom'.

**Comment by danielezer** [comment]
Nice Feature request @zendril. I think the best way would be to give you the option to provide the full env var declaration. That way you can use stuff like this as well - https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#configure-all-key-value-pairs-in-a-configmap-as-container-environment-variables.
This is also supported with secrets :) 

The only trick is that I'm having a hard time figuring out a name for that since `ExtraEnvironmentVariables` is already taken. I was thinking about something like `extraEnvironmentVariablesFullSpec` but it sounds weird to me. @eldada @zendril any naming suggestions?

**Comment by zendril** [comment]
Agree on the approach. 
Naming is always hard. 

Just thinking aloud.. why do we have to have 2 different sections?

What people currently put in is valid env section stuff

- name: "foo"
  value: "bar" 

as would be:

- name: SPECIAL_LEVEL_KEY
    valueFrom:
      configMapKeyRef:
        name: special-config
              key: SPECIAL_LEVEL

So can't we just take everything inside extraEnvironmentVariables and just tpl the whole thing inside the env section in the primary and node stateful set?

**Comment by danielezer** [comment]
@zendril no, that would not be possible because users now provide something like:
```
- foo: bar
```
and not:
```
- name: foo
  value: bar
```

we can't break compatibility, and that's why we need a new configuration option

**Comment by zendril** [comment]
I agree completely with not breaking backwards compatibility, but that isn't how we are using it today.


Here is an example from our config:

```
artifactory:
  license:
    dataKey: containerimages-na-test-1.license
  extraEnvironmentVariables:
    - name: CLUSTER_PREFIX
      value: "containerimages-na-test-cdc2-mt-t1"
    - name: CLUSTER
      value: "cdc2-mt-t1"
```

Perhaps I there is some magic helm/yaml magic going on that I'm not familiar with, but here is the code that is using those configs:

https://github.com/jfrog/charts/blob/master/stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml#L322-L325

```
      {{- range .Values.artifactory.extraEnvironmentVariables }}
        - name: {{ .name }}
          value: '{{ tpl .value $ }}'
      {{- end }}
```

Can you double check?

**Comment by danielezer** [comment]
Right @zendril, I missed that.
