### ISSUE TITLE
nginx fails with 'exec user process caused "operation not permitted"'

### ISSUE THREAD

**Issue by zendril** [jfrog/charts#532]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
2.9 and 1.15.3

**Which chart**:
artifactory-ha stable

**What happened**:
Starting nginx causes the pod to go into crashloop.
Pulling kubectl logs for the pod gives back:
```
standard_init_linux.go:178: exec user process caused "operation not permitted"
```

**How to reproduce it** (as minimally and precisely as possible):
set nginx.enabled: true

**Anything else we need to know**:

I notice that we are doing a straight call to nginx instead of calling the entrypoint-nginx.sh. 

https://github.com/jfrog/charts/blob/master/stable/artifactory-ha/templates/nginx-deployment.yaml#L62-L65

```
        command:
          - 'nginx'
          - '-g'
          - 'daemon off;'
```

I'm assuming that is because we have volumemounted in the configs needed.

When I run this container on docker manually I don't get that error.. only on the kubernetes cluster.

We have AquaSec and some other things on those clusters. Possible that they are preventing it from running?

**Comment by zendril** [comment]
Update: Looks like when I run it manually on docker it at least tries to start up, but I just don't have the configurations in place. So this is failing because I believe that nginx is requesting priv escalation which we have disabled on the clusters.

Any idea why nginx is doing this? Is there a version that doesn't require this?

**Comment by danielezer** [comment]
@zendril are you sure? I don't see anything regarding privilege escalation in the code... The only thing Nginx does which is sort of "over privileged" is bind to a port that's lower that 1024. But that's at the container level, so it shouldn't affect you..

**Comment by zendril** [comment]
Honestly I've lost the context on this one, and we are moving away from nginx ingress so I won't be able to test it anyways. I'm going to close this as a result.

**Comment by mister-red** [comment]
I ran into this recently using runAsNonRoot on the nginx deployment, as it is a security requirement on the cluster. We instead started to use the cluster ingress to get around this. Not to revive a necro thread, just for awareness that it's still out there.
