### ISSUE TITLE
Artifcatory chart install from HUB is failing 

### ISSUE THREAD

**Issue by laith-leo** [jfrog/charts#543]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Yes

**Version of Helm and Kubernetes**:
HELM 3.0.0 stable, Kubernetes 1.14.7 

**Which chart**:
artifactory/artifactory

**What happened**:
Unable to install the chart, I'm getting this error message:

```
# helm repo ls
NAME       	URL
artifactory	https://charts.jfrog.io

# helm install jfrog artifactory/artifactory
Error: values don't meet the specifications of the schema(s) in the following chart(s):
postgresql:
- postgresqlPassword: Invalid type. Expected: string, given: null
```

**What you expected to happen**:
Install the Jfrog Artifactory chart.

**How to reproduce it** (as minimally and precisely as possible):
It is producible right away.

**Anything else we need to know**:
I'm using MAC OSX Catalina 10.15.1 and use Docker for MAC (Docker Desktop 2.1.0.4) that runs Docker 19.03.4, K8s 1.14.7

**Comment by eldada** [comment]
@laith-leo - good catch. We'll fix it shortly.

**Comment by laith-leo** [comment]
It works now, thanks. Good to close this issue.
