### ISSUE TITLE
Artifactory federation

### ISSUE THREAD

**Issue by angegar** [jfrog/charts#550]
**Is this a request for help?**:

yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): don't know yet, but i would say it is normal behaviour causing troubles

**Version of Helm and Kubernetes**:

```
helm version
Client: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.12", GitCommit:"a8b52209ee172232b6db7a6e0ce2adc77458829f", GitTreeState:"clean", BuildDate:"2019-10-15T12:04:30Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
`artifactory-artifactory         24              Mon Nov 18 14:11:34 2019        DEPLOYED        artifactory-ha-1.1.12                   6.14.1          artifactory`
**What happened**:

**What you expected to happen**:

Federation between access service works

**How to reproduce it** (as minimally and precisely as possible):

Set up replication between an artifactory instance hosted on a VM and another one hosted in kubernetes

**Anything else we need to know**:

For artifactory hosted in kubernetes, i  think the service id change at each pod start thus after each upgrade. It implies the access federation need to be reconfigured but to activate the configuration we have to restart the service ;)

What i can observe in the access configuration file is  :

```
  inbound:
    service-id-mapping:
    - from: "jfrt@*"
      to: "jfrt@id1"
    - from: "jf-artifactory@remote_id"
      to: "jfrt@id1"
    - from: "jfrt@*"
      to: "jfrt@id2"
```

Can some help to have something more stable to enable access federation ?

**Comment by angegar** [comment]
Ok finally I manage to push the good configuration with the good service id. However i fear the nginx reverse proxy does not redirect the access trafic.

Can someone tell me if the  /access endpoint is exposed outside the kubernetes stack ?

**Comment by danielezer** [comment]
@angegar It should be exposed, yes. We expose the artifactory HTTP port, so any endpoint on that port should be accessible.

**Comment by shahiinn** [comment]
@angegar :  
/access endpoint doesn't seem to be exposed outside the stack. However, any request for the access service can come through the /artifcatory endpoint as we are enabling the cross-context functionality from the tomcat end. Can you let me know what is the exact issue you are encountering now?

**Comment by angegar** [comment]
Hi, 
I sorted out some months ago, but I used Artifactory replication + access federation to perform my migration. To be honest I don't exactly remind how set the access federation up but I made it worked following the documentation.
