### ISSUE TITLE
xray: readiness+liveness probes for analysis, indexer and persist STS fail with HTTP 403

### ISSUE THREAD

**Issue by titou10titou10** [jfrog/charts#553]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
helm version: v3.0.0
kubernetes version: v1.14.6+2e5ed54

**Which chart**:
jfrog/xray   v1.2.4  app:  v 2.10.7  

**What happened**:
fresh install without any external components (mongo..)
analysis, indexer and persist fail to start because the readiness probe returns  HTTP 403

**What you expected to happen**:
readiness and liveness probes works and so those 3 components are up and running

**How to reproduce it** (as minimally and precisely as possible):
do a fresh install of the chart

**Anything else we need to know**:
all other components start well (mongodb, postgresql, rabbitmq, server)
those 3 components seems to be healhty before before restarted by k8s because of the bad readiness probe...
k8s "events" from the persist component:

    kubectl describe pod xray-xray-persist-0

    Events:
      Type     Reason     Age                From                                       Message
      ----     ------     ----               ----                                       -------
      Normal   Scheduled  5m                 default-scheduler     Successfully assigned aa-artifactory/xray-xray-persist-0 to <ip masked>
      Normal   Pulled     5m                 kubelet, <ip masked>  Container image "alpine:3.8" already present on machine
      Normal   Created    5m                 kubelet, <ip masked>  Created container init-wait
      Normal   Started    5m                 kubelet, <ip masked>  Started container init-wait
      Warning  Unhealthy  17s (x5 over 57s)  kubelet, <ip masked>  Readiness probe failed: HTTP probe failed with statuscode: 403
      Normal   Pulled     14s (x2 over 2m)   kubelet, <ip masked>  Container image "docker.bintray.io/jfrog/xray-persist:2.10.7" already present on machine
      Warning  Unhealthy  14s (x3 over 34s)  kubelet, <ip masked>  Liveness probe failed: HTTP probe failed with statuscode: 403
      Normal   Killing    14s                kubelet, <ip masked>  Container xray-persist failed liveness probe, will be restarted
    ....

End of the logs in the pod for the persist component before its is killed:

    Version:  2.10.7
    Revision: f94bbb5
    Xray Home: '/var/opt/jfrog/xray/data'
    [16:28:17 UTC 2019/11/19] [INFO] (jfrog.com/xray/internal/startup.InitMicroServices:219) Starting persist@xray-xray-persist-0 micro service
    [16:29:17 UTC 2019/11/19] [INFO] (jfrog.com/xray/internal/workers.(*MonitoringWorker).runMonitorC:113) Running monitoring sampling cycle
    [16:29:17 UTC 2019/11/19] [INFO] (jfrog.com/xray/internal/workers.(*MonitoringWorker).PublishMsgToQueue:147) Monitoring worker id 1 publishing msg to exchange: trans.monitoringStatus

readiness/liveness probe from the persist statefulset 

    readinessProbe:
      httpGet:
        path: /debug/pprof/
        port: 7003
        scheme: HTTP
      initialDelaySeconds: 60
      timeoutSeconds: 1
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 10
    livenessProbe:
      httpGet:
        path: /debug/pprof/
        port: 7003
        scheme: HTTP
      initialDelaySeconds: 90
      timeoutSeconds: 1
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3

**Comment by eldada** [comment]
Thx @titou10titou10 . We'll look into this ASAP.

**Comment by eldada** [comment]
@titou10titou10 - please try the following:
1. Deploy
2. In the 90 secs before probes start, open a shell to the container in the pod
3. Run `ls -la /var/run/secrets/`
4. Run `ls -la /`
5. Share the output here

I tried reproducing, but it does not happen to me.

**Comment by titou10titou10** [comment]
ls -la /

    drwxr-xr-x.   1 root root   39 Nov 20 14:14 .
    drwxr-xr-x.   1 root root   39 Nov 20 14:14 ..
    drwxr-xr-x.   2 root root 4096 Oct 14 00:00 bin
    drwxr-xr-x.   2 root root    6 Jun 14  2018 boot
    drwxr-xr-x.   5 root root  360 Nov 20 14:14 dev
    drwxr-xr-x.   1 root root   19 Nov 20 14:14 etc
    drwxr-xr-x.   1 root root   18 Nov  7 15:53 home
    drwxr-xr-x.   9 root root  112 Nov 27  2014 lib
    drwxr-xr-x.   2 root root   34 Oct 14 00:00 lib64
    drwxr-xr-x.   2 root root    6 Oct 14 00:00 media
    drwxr-xr-x.   2 root root    6 Oct 14 00:00 mnt
    drwxr-xr-x.   1 root root   19 Nov  7 15:53 opt
    dr-xr-xr-x. 356 root root    0 Nov 20 14:14 proc
    drwx------.   2 root root   37 Oct 14 00:00 root
    drwxr-xr-x.   1 root root   21 Nov 20 14:14 run
    drwxr-xr-x.   2 root root 4096 Oct 14 00:00 sbin
    drwxr-xr-x.   2 root root    6 Oct 14 00:00 srv
    dr-xr-xr-x.  13 root root    0 Oct 22 13:44 sys
    drwxrwxrwt.   1 root root    6 Nov  7 15:53 tmp
    drwxr-xr-x.   1 root root   66 Oct 14 00:00 usr
    drwxr-xr-x.   1 root root   17 Oct 14 00:00 var
    
ls -la /var/run/secrets

    drwxr-xr-x. 4 root root 80 Nov 20 14:16 .
    drwxr-xr-x. 1 root root 21 Nov 20 14:16 ..
    drwxr-xr-x. 3 root root 60 Nov 20 14:16 kubernetes.io
    drwx------. 3 root root 60 Nov 20 14:16 rhsm

**Comment by eldada** [comment]
The pull request I have created (#559 ), should fix it.

**Comment by eldada** [comment]
@titou10titou10, can you please test the newly released chart and confirm the fix? 1.2.6

**Comment by titou10titou10** [comment]
Thanks for your express fix !!
But it does not work and this bug should be reopened
For analysis its' OK but for indexer and persist I think you set the XRAY_K8S_ENV=true env variable in the wrong container
You put the variable on an initcontainer and not on the container itself,,,

**Comment by eldada** [comment]
Oooops. That's embarrassing. Sorry!
Fix is on its way...

**Comment by eldada** [comment]
Can you confirm xray-1.2.7 resolves this?

**Comment by titou10titou10** [comment]
I...still don't know
The env variables seemto be at the right place but i have now another problem the "server" pod does not start:

Logs from the "init-wait" initcontainer:

    '/scripts/setup.sh' -> '/var/opt/jfrog/xray/data/setup.sh'
    Creating directories
    Waiting for Mongo...
    mongodb ok
    Waiting for Postgres...
    postgresql ok
    Waiting for Rabbit...
    rabbitmq ok
    Preparing Xray config (/var/opt/jfrog/xray/data/config/xray_config.yaml)
    Config exist. Backing it up...
    '/var/opt/jfrog/xray/data/config/xray_config.yaml' -> '/var/opt/jfrog/xray/data/config/xray_config.yaml-20191121-135724'
    '/scripts/xray_config.yaml' -> '/var/opt/jfrog/xray/data/config/xray_config.yaml'

Logs from the "xray-server" container:

    xray-server service container is starting...
    Exec: /opt/jfrog/xray-server/server  
    ServerLoadConfiguration: Error: Could not open "/var/opt/jfrog/xray/data/config/server_log4go_config.xml" for reading: open /var/opt/jfrog/xray/data/config/server_log4go_config.xml: no such file or directory

And indeed there is no`"server_log4go_config.xml"`file in the`"config"` dir:

From the PV:

    ls -la config/ 
    total 20
    drwxr-xr-x    2 10001200 10001200      4096 Nov 21 13:57 .
    drwxrwxrwx   16 10001200 10541         4096 Nov 21 13:57 ..
    -rw-r--r--    1 10001200 10001200       390 Nov 21 13:57 xray_config.yaml
    -rw-r--r--    1 10001200 10001200       408 Nov 21 13:50 xray_config.yaml-20191121-135002
    -rw-r--r--    1 10001200 10001200       408 Nov 21 13:57 xray_config.yaml-20191121-135724

**Comment by titou10titou10** [comment]
Got it to work !
So yes your fix solved my problem
The`"server_log4go_config.xml"` file not found problem was caused because I "erased" the`"xrayUserId`"and`"xrayGroupId"`variables
We are running in OpenShift and we try to not open permissions when it is not necessary

    common:
      xrayUserId: null
      xrayGroupId: null

Maybe it could be worth noting in the doc that you cannot do that..Or investigate why erasing those variables make the server pod fail..
Once again, many thanks
