### ISSUE TITLE
Postgres Password in Configmap/Secret Resetting

### ISSUE THREAD

**Issue by evannorstrand** [jfrog/charts#564]
Reference ticket #545  that was closed.

**Comment by evannorstrand** [comment]
@danieldrrivera - See below for the relevant section of the yaml file. Obviously FOO isn't our password, but it shows the format.

postgresql:
  postgresqlPassword: FOO

**Comment by danielezer** [comment]
@evannorstrand you have an indentation issue in your values file but I assume that’s because of the copy to github... which version of the chart are you currently using?

**Comment by danielezer** [comment]
@evannorstrand is this still an issue for you?

**Comment by danielezer** [comment]
@evannorstrand Have you made any progress with the above? Can I close this issue or is this still an issue for you?
