### ISSUE TITLE
Issue with DB Password consisting of '&'

### ISSUE THREAD

**Issue by dishameswania** [jfrog/charts#576]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: Latest

**Which chart**: Artifactory

**What happened**: External Postgres DB password with '&' - is populated wrongly in the db.properties file resulting in issue while starting up Artifactory with a password authentication failure message.

**What you expected to happen**: Passwords with special characters should also be accepted as they are in a normal installation.

**How to reproduce it** (as minimally and precisely as possible): helm install --name artifactory --set postgresql.enabled=false --set database.type=postgresql --set database.url='jdbc:postgresql://<DB_HOST>:<DB_PORT>/artifactory' --set database.user=artifactory --set database.password="**pass&word**"  jfrog/artifactory

**Anything else we need to know**: This password isn't working even if passed in double/single quotes, even with secrets.

**Comment by dishameswania** [comment]
This works with an escape character, i.e. if you use the --set command as per below:
--set database.password="pass\\&word"

**Comment by eldada** [comment]
Be aware of [helm open issue](https://github.com/helm/helm/issues/4030) regarding this limitation.

**Comment by eldada** [comment]
Closing as this is not related to our charts.
