### ISSUE TITLE
Add nginx pod (to enable tls not utilising Ingress)

### ISSUE THREAD

**Issue by lexual** [jfrog/charts#578]
**Is this a request for help?**: NO

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**: n/a

**Which chart**: Xray
**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

We are using xray helm chart to deploy xray.
We aren't able to utilise Ingress objects, and are looking to add an nginx pod
to handle tls instead (similar to the artifactory-ha chart)

1) Would you be interested in accepting nginx as an option to the helm chart (we may be able to provide a pull request)?

2) Is there any particular reason the artifactory-ha has its own nginx container vs using an upstream nginx container and/or helm chart?
Can you shine any light on customizations that exist in the nginx container from jfrog??

Thanks,

**Comment by eldada** [comment]
@lexual - I hope this answers:
1. Yes. It's totally acceptable. As we don't have any special config for it, it should be fairly simple.
2. Our custom nginx docker image is in `artifactory` and `artifactory-ha` for a few reasons:
  (a) Custom Docker specific reverse proxy config needed for Artifactory
  (b) Out of the box self signed TLS
        If you shell into the Nginx container, you can find the actual Dockefile inside to see our custom changes. `cat /docker/nginx-artifactory-pro/Dockerfile.nginx`.
  (c) Binding to port lower than 1024 with non root user
  (d) A few small other issues you can review

**Comment by lexual** [comment]
we'll park this for meantime. We have enabled nginx-ingress controller on our cluster for the time being.
