### ISSUE TITLE
Use s3 as datastore and NFS as working dir | Do not use PV

### ISSUE THREAD

**Issue by papovyr** [jfrog/charts#579]
hi,
I deploy artifactory to k8s (eks) with following command 

```
s3_bucket=mybucket387483
AWS_REGION=us-east-1
DB_HOST=artifactory.DNS.us-east-1.rds.amazonaws.com
DB_PORT=5432
DB_NAME=artifactory1
DB_USER=postgres
DB_PASSWORD=PASSFORDB
helm upgrade -i artifactory jfrog/artifactory \
        --set postgresql.enabled=false \
        --set database.type=postgresql \
        --set database.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME} \
        --set database.user=${DB_USER} \
        --set artifactory.license.secret=artifactory-license,artifactory.license.dataKey=art.lic \
        --set database.password=${DB_PASSWORD} \
        --set artifactory.persistence.type=aws-s3-v3 \
        --set artifactory.persistence.awsS3V3.region=${AWS_REGION} \
        --set artifactory.persistence.awsS3V3.bucketName=${s3_bucket} \
        --set artifactory.persistence.awsS3V3.testConnection=true \
        --set artifactory.masterKeySecretName=artifactory-master-key
```
After deploy i can access to artifactory (license is active ), 
I tryed to push files and that works as well
Checked binarystore.xml looks fine to me (Contains s3 info that i provided)
There is a IAM attached to instance and has access to s3

But there Is a 20 GB EBS volume (PV) attached, 

**What you expected to happen**:
Im expecting that all files will go to s3 and there will be no PV

**Version of Helm and Kubernetes**:
helm 3

Im actually looking to use S3 as backend storage and also mount `/var/opt/jfrog/artifactory` folder to EFS (In case of s3 storage will be unavailable ) so when i restart/delete/create deployment nothing will be lost

**Comment by eldada** [comment]
@papovyr - good one!
Yes. This can be set. Since `artifactory` is installed as a StatefulSet, we use the `volumeClaimTemplates` to create the default StorageClass PVC.
To change that, you need to pass the EFS PVC (that you create before) as an existing PVC.
`--set artifactory.persistence.existingClaim=<YOU PRE CREATED EFS PVC>`.

Does this answer your question?

**Comment by papovyr** [comment]
Thanks this will work
