### ISSUE TITLE
Add support for external PostgreSQL and ElasticSearch in Mission Control helm chart

### ISSUE THREAD

**Issue by joonfrog** [jfrog/charts#58]
FEATURE REQUEST

Add support to configure an external MongoDB and ElasticSearch for Mission Control Helm Chart

**Comment by eldada** [comment]
@joonfrog - there is no PostgreSQL in Mission Control (did you mean ElasticSearch?). Can you update this issue?
Also, please fill in the details.

**Comment by eldada** [comment]
@amithins - can you see if this is still relevant?

**Comment by amithins** [comment]
This support was added as part of #273 .
