### ISSUE TITLE
Would like to submit PR/MR to add custom ca-certs to Xray

### ISSUE THREAD

**Issue by evannorstrand** [jfrog/charts#580]
As the title states, I have made some helm chart changes to allow adding a single CA-Cert to xray. Can I please be given permissions to push my branch and submit a PR/MR?

I have an artifactory-pro-x license: erik@strategicmissionelements.com.

Respectfully,
Erik Van Norstrand

**Comment by danielezer** [comment]
Hey @evannorstrand, I see you already created a few PRs via a fork. Is this issue still relevant?
