### ISSUE TITLE
chart release and repo release map

### ISSUE THREAD

**Issue by yiwu1** [jfrog/charts#585]
Wondering how the chart version mapped with the source repo release, for if I unzip https://charts.jfrog.io/artifactory-ha-0.17.3.tgz, it is as following:
~/JFrog/artifactory-ha$ ls -ltr
total 176
-rwxr-xr-x 1 yiwu1 nogroup 35922 Oct 24 04:10 values.yaml
-rwxr-xr-x 1 yiwu1 nogroup   390 Oct 24 04:10 values-small.yaml
-rwxr-xr-x 1 yiwu1 nogroup   390 Oct 24 04:10 values-medium.yaml
-rwxr-xr-x 1 yiwu1 nogroup   392 Oct 24 04:10 values-large.yaml
-rwxr-xr-x 1 yiwu1 nogroup   146 Oct 24 04:10 requirements.yaml
-rwxr-xr-x 1 yiwu1 nogroup   241 Oct 24 04:10 requirements.lock
-rwxr-xr-x 1 yiwu1 nogroup  6690 Oct 24 04:10 ReverseProxyConfiguration.md
-rwxr-xr-x 1 yiwu1 nogroup 65738 Oct 24 04:10 README.md
-rwxr-xr-x 1 yiwu1 nogroup 11357 Oct 24 04:10 LICENSE
-rwxr-xr-x 1 yiwu1 nogroup   646 Oct 24 04:10 Chart.yaml
-rwxr-xr-x 1 yiwu1 nogroup 13609 Oct 24 04:10 CHANGELOG.md
drwxr-xr-x 2 yiwu1 nogroup  4096 Dec 10 23:57 templates
drwxr-xr-x 2 yiwu1 nogroup  4096 Dec 10 23:57 ci
drwxr-xr-x 3 yiwu1 nogroup  4096 Dec 10 23:57 charts

But if I clone the repo https://github.com/jfrog/charts.git, it gets stuff different.
$ git remote -v
origin	https://github.com/jfrog/charts.git (fetch)
origin	https://github.com/jfrog/charts.git (push)

Thanks
Yi

**Comment by eldada** [comment]
Can you explain better the problem you see? I don't understand your question...

**Comment by yiwu1** [comment]
Sorry for that, for example this version artifactory-ha-0.17.3 released here https://charts.jfrog.io/artifactory-ha-0.17.3.tgz, don't know this version is comming from which commit/branch of the resource repo https://github.com/jfrog/charts.git ? Thanks!

**Comment by eldada** [comment]
You are right @yiwu1 . We just commit with the app version change in the commit message. And we also don't tag.
I'll review the process internally and suggest improvements.

You can see the match between chart version and app version in the `CHANGELOG.md` of each chart.

**Comment by yiwu1** [comment]
Thanks @eldada .
