### ISSUE TITLE
Clarification on when require PersistentVolumeClaim in artifactory-ha

### ISSUE THREAD

**Issue by lexual** [jfrog/charts#591]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): QUESTION?! ;)

Regarding chart artifactory-ha.
We currently are using Google Cloud Buckets as our storage backend.
i.e. `artifactory-persistence.type=google-storage`

Our current setup does appear to have PersistentVolumeClaims associated with them.

Can we safely run without them?

Would setting `artifactory.persistence.enabled=false` do this?

Thanks ;)

**Version of Helm and Kubernetes**:

**Which chart**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by jfrog-aparicio** [comment]
> Would setting artifactory.persistence.enabled=false do this?

Short answer:
It would not be 100% safe. 

Long answer:

When working with an object store like S3 or Google storage, there is an eventual upload mechanism. This means when you upload something and Artifactory says upload succeded, it really just means it is stored on the local machine (in the persistent volume) and it will eventually make it to the object store (a matter of seconds). To the end-user, it does not matter, if something has not yet made it to the object store, it will be served from this eventual cache. This happens even if it is in the eventual cache of another machine. By default and for safety reasons, when you upload something, it is simultaneously put in two nodes' eventual cache. 

Knowing the above, the potential loss of data scenario occurs in the (somewhat unlikely) event that:
1. Files have just been uploaded and are in the eventual cache but not yet in the object store
2. Both of the pods that have copies die

In such a case, when Artifactory starts back up it will say it has those artifacts but it won't have the underlying binaries and this will result in an error if a user tries to download them.

**Comment by lexual** [comment]
very clear, thanks for the clarification.
