### ISSUE TITLE
Artifactory helm upgrade command fails with forbidden error

### ISSUE THREAD

**Issue by sumanmohan** [jfrog/charts#593]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm Version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}

kubernetes Version 
1.14

**Which chart**:
1.3.1

**What happened**:

Installed artifactory successfully by running below command  but when we run any upgrade commands it fails. 

Install command - 
```
helm install --name artifactory --set postgresql.postgresqlPassword=xxxx --set artifactory.node.replicaCount=1 --set artifactory.persistence.customBinarystoreXmlSecret=custom-binarystore --set artifactory.primary.persistence.existingClaim=true --set artifactory.node.persistence.existingClaim=true jfrog/artifactory-ha
```
Upgrade command - 
```
helm upgrade --install artifactory --set databaseUpgradeReady=no --set postgresql.postgresqlPassword=xxxx --set artifactory.persistence.customBinarystoreXmlSecret=custom-binarystore --set artifactory.node.replicaCount=2 jfrog/artifactory-ha
```

ERROR: 
```
UPGRADE FAILED
Error: StatefulSet.apps "artifactory-artifactory-ha-member" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden && StatefulSet.apps "artifactory-artifactory-ha-primary" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```

**What you expected to happen**:
Upgrade to be successful and node replica count to increase to 2 . 

**How to reproduce it** (as minimally and precisely as possible):
Install helm version 2.14.3 on EKS 1.14 and install artifactory with chart version 1.3.1 . Perform a basic instillation with one member node and try to upgrade the installation by adding another member node
**Anything else we need to know**:

**Comment by eldada** [comment]
Hi @sumanmohan .
It looks that you have a couple of issues with the upgrade command:
1. Missing the same 
```
  --set artifactory.primary.persistence.existingClaim=true \
  --set artifactory.node.persistence.existingClaim=true \
```
 as passed to the first `helm install` command.

2. You should set `--set databaseUpgradeReady=yes` to notify you are good for the upgrade if relevant.

Can you check and get back to us?

**Comment by sumanmohan** [comment]
Hi @eldada 
Thanks for your reply. We tried to run the commands as mentioned and we can see the upgrade command was executed but a secondary member node pod was not provisioned. We see the primary pod getting terminated and provisioned again. Also we see another nginx pod getting created. Not sure if this is expected? 

[ec2-user@ip-172-29-4-188 ~]$ kubectl get pods
NAME                                   READY   STATUS        RESTARTS   AGE
artifactory-artifactory-ha-member-0    1/1     Running       0          12m
artifactory-artifactory-ha-primary-0   1/1     Terminating   0          12m
artifactory-nginx-7795f55fdf-75whl     0/1     Running       0          6s
artifactory-nginx-79c5c7b974-lj6zh     1/1     Running       0          10m
artifactory-postgresql-0               1/1     Running       0          12m
tiller-deploy-676c6469d7-qpvh4         1/1     Running       0          8d


[ec2-user@ip-172-29-4-188 ~]$ kubectl get pods
NAME                                   READY   STATUS    RESTARTS   AGE
artifactory-artifactory-ha-member-0    1/1     Running   0          14m
artifactory-artifactory-ha-primary-0   0/1     Running   0          52s
artifactory-nginx-7795f55fdf-75whl     0/1     Running   0          94s
artifactory-nginx-79c5c7b974-lj6zh     1/1     Running   0          11m
artifactory-postgresql-0               1/1     Running   0          14m
tiller-deploy-676c6469d7-qpvh4         1/1     Running   0          8d

**Comment by sumanmohan** [comment]
This issue can be closed. We were able to proceed with the upgrade commands when we removed --set artifactory.primary.persistence.existingClaim=true --set artifactory.node.persistence.existingClaim=true

**Comment by eladh** [comment]
Hi @eldada 
We also getting the same issue trying to an existing helm chart in order to update artifactory.persistence.size

getting the following error:

> UPGRADE FAILED: StatefulSet.apps "artifactory-artifactory" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden


Best,
Elad.

**Comment by eldada** [comment]
@chukka - can you help here?

**Comment by chukka** [comment]
@eladh Looks like a very old issue , can you please raise this as a new issue and provide more details like chart versions (present and upgrading chart version and also share helm commands with values.yaml to debug further )

cc @eldada

**Comment by chukka** [comment]
Also, artifactory.persistence.size can't be changed via helm upgrade directly

Steps to be followed 

- edit PVC size
- delete statefulset
- update chart custom-values.yaml
- do helm upgrade

**Comment by eladh** [comment]
Hi @chukka , i would love to get more details regarding the process.
editing the pvc size resulting :
`error: persistentvolumeclaims "artifactory-volume-artifactory-artifactory-0" could not be patched: persistentvolumeclaims "artifactory-volume-artifactory-artifactory-0" is forbidden: only dynamically provisioned pvc can be resized and the storageclass that provisions the pvc must support resize`

**Comment by chukka** [comment]
yes please
