### ISSUE TITLE
Deployment failure on IBM kubernetes cluster with persistence volume true

### ISSUE THREAD

**Issue by akashpatel567** [jfrog/charts#598]
Hello,

I am using 8.2.4 version from https://charts.jfrog.io/ but not able to make it work when persistence volume is true.

It works when persistence volume is false. 

Note: Everytime I have cleaned the release and remove the pvc before the redeployment. Matched the password in artifactory and postgres container is same. Hardcoded the password but error remains same. 
Please let me know what could be possible solution to it.

**Error:**
 Role "artifactory" does not exist.
	Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"
] FATAL:  password authentication failed for user "artifactory"
DETAIL:  Role "artifactory" does not exist.

Thank You

**Comment by akashpatel567** [comment]
JFI, We are using IBM block storage.

**Comment by akashpatel567** [comment]
And as I mentioned on [#602](https://github.com/jfrog/charts/issues/602). in parallel to the solution to the problem it would be great if we can start supporting IBM cloud as well.

**Comment by akashpatel567** [comment]
@jainishshah17 could you please look into it. As I found you have worked on IBM cloud.

Thank You

**Comment by alexanderldavis** [comment]
Was there a resolution to this? I am running into the exact same error when trying to deploy on IBM k8s with PVCs. Thanks for any help!

**Comment by avivbl** [comment]
> Was there a resolution to this? I am running into the exact same error when trying to deploy on IBM k8s with PVCs. Thanks for any help!

@alexanderldavis Yes, I was able to reproduce and resolve it. Reproduced by installing the helm chart on a 'used' PVC. Then resolved it by creating the PVCs in advance, for example:

pvc.yaml:

```kind: PersistentVolumeClaim
apiVersion: v1
metadata:`
  name: claim1-block-bronze
  annotations:
    volume.beta.kubernetes.io/storage-class: "ibmc-block-bronze" # name of the storage class
  labels:
    billingType: "monthly" # optional params [hourly | monthly (default)]
spec:
  accessModes:
    - ReadWriteOnce # access mode
  resources:
    requests:
      storage: 10Gi #
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim2-block-bronze
  annotations:
    volume.beta.kubernetes.io/storage-class: "ibmc-block-bronze" # name of the storage class
  labels:
    billingType: "monthly" # optional params [hourly | monthly (default)]
spec:
  accessModes:
    - ReadWriteOnce # access mode
  resources:
    requests:
      storage: 10Gi #
```

Then:
`kubectl apply -f pvc.yaml`

Finally, I referenced these in the values.yaml:
```...
artifactory:
  name: artifactory
...
  persistence:
    mountPath: "/var/opt/jfrog/artifactory"
    enabled: true
    ## A manually managed Persistent Volume and Claim
    ## Requires persistence.enabled: true
    ## If defined, PVC must be created manually before volume will be bound
    existingClaim: claim1-block-bronze
...
postgresql:
  enabled: true
...
  persistence:
    enabled: true
    size: 50Gi
    existingClaim: claim2-block-bronze
```

By the way, I also needed to create a custom init container to sort out the permissions on the volume:
```
## Add custom init containers
  customInitContainers: |
    - name: "prepare-storage"
      image: "{{ .Values.initContainerImage }}"
      imagePullPolicy: "{{ .Values.artifactory.image.pullPolicy }}"
      command:
        - 'sh'
        - '-c'
      args:
        - chown -R {{ .Values.artifactory.uid }}:{{ .Values.artifactory.uid }} {{ .Values.artifactory.persistence.mountPath }}
      volumeMounts:
        - mountPath: "{{ .Values.artifactory.persistence.mountPath }}"
          name: artifactory-volume
      securityContext:
        runAsUser: 0```

**Comment by JfrogPrasanna** [comment]
Closing this assuming the recommendation has helped.
