### ISSUE TITLE
binarystore.xml missing content for ibm block storage

### ISSUE THREAD

**Issue by akashpatel567** [jfrog/charts#602]
Hello,

We are using IBM kubernetes services and with the charts listed on charts.jfrog.io in particularly I am using the version 8.2.4 doesn't have any information about IBM cloud block storage.

#values.yaml

`	
    ## Set the persistence storage type. This will apply the matching binarystore.xml to Artifactory config
    ## Supported types are:
    ## file-system (default)
    ## nfs
    ## google-storage
    ## aws-s3
    ## azure-blob
    type: file-system

    ## Use binarystoreXml to provide a custom binarystore.xml
    ## This can be a template or hardcoded.
    binarystoreXml: |

Could we please update the charts to support IBM cloud with persistence volume enabled
`

**Comment by eldada** [comment]
IBM block storage is S3 compatible, so you should use the S3 configuration for this.
