### ISSUE TITLE
Failed to pass resources requests and limits for most containers

### ISSUE THREAD

**Issue by yiwu1** [jfrog/charts#607]
Hi team,

When I pass values-xxx.yaml(-f) in latest mission-control chart to set resources requests and limits for my installation, only elasticsearch and missionControl container take effect for the resource spec, but all other containers like insightServer/insightExecutor/insightScheduler and all initContainers have empty resource with following spec :resources: {}. 

Resource will be inconsistent in the spec as following:
failed quota: high-qos-limit-requests: must specify limits.cpu,limits.memory,requests.cpu,requests.memory

Thanks
Yi

**Comment by eldada** [comment]
@yiwu1 - can you share your `values-xxx.yaml` file?

**Comment by yiwu1** [comment]
Here it is:
[values-small.yaml.zip](https://github.com/jfrog/charts/files/4051897/values-small.yaml.zip)

Thanks!

**Comment by danielezer** [comment]
Good catch @yiwu1, thanks for that. I created a PR #626 to address this issue
