### ISSUE TITLE
Feature [artifactory-ha]: Should allow artifactory.primary.replicaCount customization

### ISSUE THREAD

**Issue by planteman** [jfrog/charts#608]
**Is this a request for help?**:
No.
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

We need to have the primary StatefulSet template expose the replicaCount (like the member StatefulSet) so that we may configure the primary StatefulSet replicaCount from the values file.

While `member` has a values-override for the number of replicas, the primary is hardwired to use a `replicaCount = 1` setting.  When running in HA with 2 Artifactory pods, we must divide the licenses across the 2 StatefulSets, each with 1 replica.

This is problematic, as when an auto-scale event impacts the cluster, or while performing an Artifactory upgrade, the result is both StatefulSets processing the operation at the same time, and both the primary and member pods are rendered unavailable simultaneously.  This will result in downtime.

Of course, we can avoid this downtime without any code changes by applying the default 3 licenses for HA instead of 2.  However, this 33% cost increase compounds quickly when factoring in numerous Artifactory deployments that don't actually need more than 2 pods running, but must leverage HA to avoid interruptions in service when upgrading (or when the cluster auto-scales).

**Comment by eldada** [comment]
Hi @planteman . Artifactory app does not support multiple primary nodes. Only multiple members. This is a know limitation and we are already working on changing this architecture in the future.

**Comment by eldada** [comment]
As this is not supported, I'm closing this for now. Future support for such architecture is in development.

**Comment by djsly** [comment]
Can we keep open to track the status of the development ? 

Or can you refer to the issue we can follow.

**Comment by eldada** [comment]
Sure. I should have noted this before: https://www.jfrog.com/jira/browse/RTFACT-13461 is the issue tracking this. It is being actively worked on.

**Comment by djsly** [comment]
Any update on this ? @eldada

**Comment by eldada** [comment]
@djsly - It's planned to be released in one of the coming Artifactory minor versions. Stay tuned!

**Comment by djsly** [comment]
Thanks!  Will that be in the 6.X release as well ?

What is considered soon enough ? :)

**Comment by eldada** [comment]
It will **not** be part of 6.x.
As for timelines - I'm not sure. I'm not the one managing this 😉

**Comment by eldada** [comment]
> @djsly - It's planned to be released in one of the coming Artifactory minor versions. Stay tuned!

Correction - this is wrong. I don't have an exact estimate as work is still being done here 😟
