### ISSUE TITLE
Replicator internal port is not set by default

### ISSUE THREAD

**Issue by patbat95008** [jfrog/charts#614]
Is this a request for help?:
No

Is this a BUG REPORT or FEATURE REQUEST?  BUG REPORT

Describe in detail the feature/behavior/change you'd like to see.

https://github.com/jfrog/charts/blob/d8570470f69c4e541e1c2a12aea42178c17596c9/stable/artifactory-ha/templates/replicator-configmap.yaml#L14

The Helm client is looking in this location when the replicator.enabled = true value is used. From what I can tell, the nginx.internalPortReplicator is not set in the default values.yaml file. 

We should add the internalPortReplicator default value of 6061 to the values.yaml file, or reference a different internal value. Otherwise replicator won't start and won't produce any logged errors.

**Comment by eldada** [comment]
Yep. Good catch @patbat95008. This was missed in a previous change we did. Will fix this promptly.
