### ISSUE TITLE
TLS x509 name incorrect

### ISSUE THREAD

**Issue by res0nat0r** [jfrog/charts#618]
BUG REPORT:

**Version of Helm and Kubernetes**:

```
$ helm version
Client: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

`artifactory-ha`

**What happened**:

Trying to `docker login`  errors with an x509 invalid certificate.

```
$ docker login dns-entry-of-our-artifactory-elb.com
Username: admin
Password:
Error response from daemon: Get https://dns-entry-of-our-artifactory-elb.com/v2/: x509: certificate is valid for artifactory-ha.artifactory-ha, artifactory-ha.artifactory-ha.svc, not dns-entry-of-our-artifactory-elb.com
```

**What you expected to happen**:

Auth to the Artifactory docker repo without any errors.

**How to reproduce it** (as minimally and precisely as possible):

I have this setup in my helm chart:

```yaml
ingress:
  enabled: true
  defaultBackend:
    enabled: false
  # Used to create an Ingress record.
  hosts:
    - dns-entry-of-our-artifactory-elb.com
  path: /
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/proxy-body-size: "0"
    ingress.kubernetes.io/proxy-read-timeout: "600"
    ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/(v2)/token /artifactory/api/docker/null/v2/token;
      rewrite ^/(v2)/([^\/]*)/(.*) /artifactory/api/docker/$2/$1/$3;
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  labels: {}
  # traffic-type: external
  # traffic-type: internal
  tls:
    - secretName: artifactory-tls
      hosts:
        -  dns-entry-of-our-artifactory-elb.com
```

This seems to be ignoring any tls secret I have set with SSL certs and just defaulting to the helm templating service name.

I've also created a `artifactory-tls` secret with the cert/key per the documentation.

**Comment by eldada** [comment]
Hi @res0nat0r . Can you give the exact steps used to create the secret? The command for the key+certificate creation and creation of the `artifactory-tls`?

**Comment by res0nat0r** [comment]
Hi @eldada 

Sure, so I'm just testing via generating a self-signed cert:

```
openssl req \
       -newkey rsa:2048 -nodes -keyout domain.key \
       -x509 -days 365 -out domain.crt
```

Then I've created a new `artifactory-ha` namespace:

`kubectl create ns artifactory-ha`

Then created a tls secret:

`kubectl create secret tls artifactory-tls --cert=domain.crt --key=domain.key`

And then just installed the helm chart  with the snippet  shown above via:

`helm install --namespace artifactory-ha --name artifactory-ha .`

**Comment by eldada** [comment]
I think you also need to add the `-subj "CN=dns-entry-of-our-artifactory-elb.com"` to get it to be stamped with your domain name. See more explanation in https://stackoverflow.com/a/10176685/1300730 answer.

**Comment by res0nat0r** [comment]
Hi,

So I'm actually setting the CN via the prompts when the openssl command is running, example like below:

```
$ openssl req \
>        -newkey rsa:2048 -nodes -keyout domain.key \
>        -x509 -days 365 -out domain.crt
Generating a 2048 bit RSA private key
....+++
....................................................................+++
writing new private key to 'domain.key'
-----
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) []:
State or Province Name (full name) []:
Locality Name (eg, city) []:
Organization Name (eg, company) []:
Organizational Unit Name (eg, section) []:
Common Name (eg, fully qualified host name) []:artifactory.example.com
Email Address []:
```

It seems that the helm templating is just ignoring the `ingress.tls.hosts[]` config item, and seems to just be defaulting to the generic `artifactory-ha` type default service name, based on what I see below:

`Error response from daemon: Get https://dns-entry-of-our-artifactory-elb.com/v2/: x509: certificate is valid for artifactory-ha.artifactory-ha, artifactory-ha.artifactory-ha.svc, not dns-entry-of-our-artifactory-elb.com`

I'd think if the TLS items were being setup properly etc and the SSL cert was just incorrect, then the login error above would be related to some type of SSL issue, vs. just the generic `service.namespace.svc` type name I see above.

**Comment by chukka** [comment]
@res0nat0r just checking if this is still an issue ,  I'm marking this as closed, feel free to open if issue still exists
