### ISSUE TITLE
Please add a configuration variable for nginx server_name FQDN

### ISSUE THREAD

**Issue by sergevs** [jfrog/charts#624]
**Is this a request for help?**:
NO
---
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

Please introduce a separate variable for nginx server_name configuration.
Currently artifactory nginx can be configured using **.Values.nginx.artifactory_conf** configuration variable. Default values.yaml provides a configuration. However, for a proper setup, it's required to fully override it because default **.Values.nginx.artifactory_conf** has:
```
      server_name ~(?<repo>.+)\.{{ include "artifactory.fullname" . }} {{ include "artifactory.fullname" . }}
```
That means that it's almost impossible to assign a required server_name FQDN ( checked out definitions at **_helpers.tpl** )
The suggestion is to introduce a separate variable - as an instance **nginx.fqdn**, and use it at **nginx.artifactory_conf** default definition. Having that it will not be required to  fully override **nginx.artifactory_conf** default value in the order just to set correct nginx server_name, which in turn is required to correctly serve docker registry repositories.

**Comment by eldada** [comment]
Thx @sergevs . We'll look into it. Looks like a valid request.

**Comment by danielezer** [comment]
@sergevs You can use `ingress.hostname` even if you are not using ingress. If you look at the `.nginx.artifactoryConf`, you can this just under the line you posted:
```
      {{- range .Values.ingress.hosts -}}
        {{- if contains "." . -}}
          {{ "" | indent 0 }} ~(?<repo>.+)\.{{ . }}
        {{- end -}}
      {{- end -}};
```

This basically loops over the `ingress.hosts` list and adds an entry to `server_name` based on that.
Please try to set something like:
```
ingress:
  hosts:
    - my.host.name
    - my.other.host.name
```

Please let us know if that works :)

**Comment by sergevs** [comment]
Thank you. Well, seems using ingress.hosts produces a working configuration. I would recommend to update comments for it and give a hint that it provides additional nginx virtual server configuration even if ingress is not enabled.

**Comment by danielezer** [comment]
@sergevs Good point. We would be more than happy to merge a PR if you would suggest one :)
