### ISSUE TITLE
Add custom volumes for Distribution to add private CA certificates

### ISSUE THREAD

**Issue by erick-duran** [jfrog/charts#637]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
Kubernetes: 1.14
Helm: 3.0.3

**Which chart**:
Distribution

**What happened**:
Cannot get MC to communicate with Distribution via HTTPS due to private CA certificate. HTTP works.

**What you expected to happen**:
Link the Distribution service with Mission Control. There is no option to mount a custom volume with the certificate as in the other Helm charts.

**How to reproduce it** (as minimally and precisely as possible):
1. Deploy MC and distribution with HTTPS (a similar issue may present with self signed certs)
2. Try to link Distribution using HTTPS

**Anything else we need to know**:
I was able to add my private CA certificates to MC/Artifactory(HA)/Xray by adding a custom volume to `customVolumes`/`customVolumeMounts` and setting up a `preStartCommand` as in other issues posted here. However, this option is not available for the Distribution chart, would be helpful if something similar was implemented.

Since the cert is trusted by MC but not by Distribution, my thoughts are that MC can reach Distribution but Distribution cannot reach back.

As a side note, it would be useful to implement this consistently across all the services (couldn't find `preStartCommand` for Xray server/indexer, had to get into the container(s) and run the `keytool` command manually).

Thanks in advance!

**Comment by danielezer** [comment]
@erick-duran just an FYI, Xray is written in Go, so there's no need to import the certificate into with keytool. irregardless, I will add the `preStartCommand` feature

**Comment by erick-duran** [comment]
Merge? 😬

**Comment by danielezer** [comment]
@erick-duran Merged :)

**Comment by erick-duran** [comment]
Hello @danielezer,
I have deployed this and I was able to mount my certificate into the Distribution container, but looking at the logs seems that `keytool` is not adding the certificate to `cacerts`. Here is the output from the command logs (from `kubectl logs` from the Distribution container):

```
Running custom Distribution preStartCommand command
Warning: use -cacerts option to access cacerts keystore
Certificate was added to keystore
keytool error: java.io.FileNotFoundException: /java/jdk-11.0.2+9/lib/security/cacerts (Permission denied)
```

I tried doing a `docker exec` as `root` into the container to run the command manually, but I got the same error. Taking a look at the folder, this is the `ls` output:
```bash
root@distribution-0:/java/jdk-11.0.2+9/lib/security# ls -la
total 356
drwxr-xr-x    2 500      500             98 Jan  1  1970 .
drwxr-xr-x    6 500      500           4096 Jan  1  1970 ..
-rw-r--r--    1 500      500           1253 Jan  1  1970 blacklisted.certs
-rw-r--r--    1 500      500         102883 Jan  1  1970 cacerts
-rw-r--r--    1 500      500           8815 Jan  1  1970 default.policy
-rw-r--r--    1 500      500         234959 Jan  1  1970 public_suffix_list.dat
``` 
From the dates, looks like the file wasn't modified. So the file exists but for some reason not even `root` can modify it. Have any clue what I'm missing?

I used the same command that I used for the other services, as suggested in your template:
```bash
/java/jdk-11.0.2+9/bin/keytool -importcert -keystore /java/jdk-11.0.2+9/lib/security/cacerts -storepass changeit -file <mount-location> -alias <alias> -noprompt
```

And logs show that SSL handshake didn't succeed:
```
2020-02-14 22:40:15,214 [http-nio-8080-exec-7] [ERROR] (o.j.b.d.s.p.t.EdgeNodesServiceImpl:104) Failed getting platform services from Mission Control
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

**Side note**
Does it make sense to also implement these in the `distributor` container? All our Artifactory nodes will have certificates issued from the same private CA. Asking because I noticed you guys also include a `preStartCommand` with the `keytool` example there, but I no see custom volume or mount options. Not sure if the `distributor` container interacts directly with the services. 🤔

Thanks in advance.

**Comment by danielezer** [comment]
@erick-duran Did you do it the same way as you did with the other charts? i.e artifactory and jfmc?

**Comment by danielezer** [comment]
@erick-duran I see the same issue with mission control as well. Did you manage to import the certificate to the mission control keystore?

**Comment by erick-duran** [comment]
@danielezer,
Yes, I use the same command for all the charts. Just did a test deployment and `preStartCommand` on MC throws the same error for me:
```
$ kubectl logs -c mission-control pod/mission-control-0 
Running custom preStartCommand command
Warning: use -cacerts option to access cacerts keystore
Certificate was added to keystore
keytool error: java.io.FileNotFoundException: /java/jdk-11.0.2+9/lib/security/cacerts (Permission denied)
```
The difference is that for this I was able to `docker exec -itu root <container> bash` (from the host node) and perform the command with no errors:
```bash
root@mission-control-0:/# /java/jdk-11.0.2+9/bin/keytool -importcert -keystore /java/jdk-11.0.2+9/lib/security/cacerts -storepass changeit -file <cert-file> -alias <alias> -noprompt
Warning: use -cacerts option to access cacerts keystore
Certificate was added to keystore
```
And the `cacerts` file was indeed modified:
```bash
root@mission-control-0:/# ls -la /java/jdk-11.0.2+9/lib/security/
total 352
drwxr-xr-x    1 32185196 root            21 Jan  1  1970 .
drwxr-xr-x    1 32185196 root            22 Jan  1  1970 ..
-rw-r--r--    1 32185196 root          1253 Jan  1  1970 blacklisted.certs
-rw-r--r--    1 32185196 root        105184 Feb 16 18:41 cacerts
-rw-r--r--    1 32185196 root          8815 Jan  1  1970 default.policy
-rw-r--r--    1 32185196 root        234959 Jan  1  1970 public_suffix_list.dat
```
And the certificate was imported. So this is why MC is working for us in our final environment. 

Taking a look at the `distribution` container, I get `Permission denied` on `root` when performing almost any write action:
```bash
# docker exec -itu root <container> bash
bash: /home/.bashrc: Permission denied
root@distribution-0:/opt/jfrog/distribution-distribution# touch test                                                                                                                    
touch: test: Permission denied
```

And comparing `/java/jdk-11.0.2+9/lib/security/` to its MC counterpart, looks like files are owned by `500` instead of `root` or any other user, hence the `Permission denied`. 

Probably not a good practice but for sanity check trying to `chgrp` the file returns: `chgrp: cacerts: Operation not permitted`.

**Comment by danielezer** [comment]
Thanks, @erick-duran. We need to address this in the Docker image itself and not in the chart...
We will make sure to submit a fix and hopefully, it will be released soon

**Comment by danielezer** [comment]
@erick-duran I merged the pull request that added custom volumes to the distributor containers as well. Please notice that the `customVolumes` has moved to `common`.

**Comment by danielezer** [comment]
Closing this issue as I opened another, a more specific one, for the permissions issue
