### ISSUE TITLE
Helm upgrade error from v1.4.1 to v1.4.10 due to PodDisruptionBudget

### ISSUE THREAD

**Issue by erick-duran** [jfrog/charts#651]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report (?)

**Version of Helm and Kubernetes**:
Helm: 3.1.0
Kubernetes: 1.14

**Which chart**:
Artifactory HA

**What happened**:
Tried to perform an upgrade from chart v1.4.1 to v1.4.10 using the same values (working fine). Got the following error:
```bash
$ helm upgrade artifactory-ha jfrog/artifactory-ha -f values.yml
Error: UPGRADE FAILED: rendered manifests contain a new resource that already exists. Unable to continue with update: existing resource conflict: namespace: artifactory, name: artifactory-ha-nginx, existing_kind: policy/v1beta1, Kind=PodDisruptionBudget, new_kind: policy/v1beta1, Kind=PodDisruptionBudget
```

**What you expected to happen**:
Deploy with the new chart version.

**How to reproduce it** (as minimally and precisely as possible):
1. Deploy chart v1.4.1
2. Try to perform an upgrade to v1.4.10

**Anything else we need to know**:
Noticed that you guys added the PDB on chart v1.4.2:
https://github.com/jfrog/charts/commit/45ef7afd90b5fec33d5a31c1b3fccd6d8fa94aa4

And, actually, the PDB already exists in the deployment, hence the error:
```bash
$ kubectl get pdb
NAME                   MIN AVAILABLE   MAX UNAVAILABLE   ALLOWED DISRUPTIONS   AGE
artifactory-ha-nginx   0               N/A               1                     5d19h
artifactory-ha-node    1               N/A               1                     19d
```
Confirmation of chart version:
```bash
$ helm list
NAME          	NAMESPACE  	REVISION	UPDATED                             	STATUS  	CHART               	APP VERSION
artifactory-ha	artifactory	8       	2020-02-20 11:35:19.945976 -0800 PST	deployed	artifactory-ha-1.4.1	6.17.0   
```

What is the suggested approach to perform the upgrade?

**Comment by chukka** [comment]
@erick-duran Sorry for delayed response, is this still an issue  with latest (master branch ) charts ?   Can you please confirm

**Comment by erick-duran** [comment]
Hello @chukka,
Sorry for the delay. I will test this later this week and get back to you, we have been working with the Xray charts.

**Comment by chukka** [comment]
@erick-duran I'm marking this as closed . Feel free to reopen if this is still an issue
