### ISSUE TITLE
Helm chart support for Xray 3.2

### ISSUE THREAD

**Issue by russ-c** [jfrog/charts#652]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

Setting XRAY_VERSION to 3.2 when deploying Xray through Helm results in each of the pods failing to start. Errors look like :
`/bin/sh: 1: /opt/jfrog/xray-analysis/wrapper.sh: not found`

Using XRAY_VERSION=2.11.4 works fine.

**Version of Helm and Kubernetes**: (Deploying on GKE)

**Which chart**: xray-1.3.8

Looks like Xray 3.2 is not currently supported in the current helm template. Is there any work in progress to get 3.2 support?

Thanks.

**Comment by eldada** [comment]
Hi @russ-c . The current public chart does not support Xray 3.x.
There are many breaking changes so we are going to release a new chart with migration details. This release is planned for today, so stay tuned. It will be released to https://charts.jfrog.io first (sources to here will follow in the coming days).
