### ISSUE TITLE
Readme is broken on Helm Hub and Kubeapps Hub

### ISSUE THREAD

**Issue by SimonAlling** [jfrog/charts#657]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Which chart**:

`artifactory`

**What happened**:

`README.md` is broken on both [Helm Hub](https://hub.helm.sh/charts/jfrog/artifactory) and [Kubeapps Hub](https://hub.kubeapps.com/charts/jfrog/artifactory). For example, the giant table under _Configuration_ is practically illegible after `artifactory.masterKey`; and, under _Artifactory storage_, the AWS S3 shell script is broken such that `With explicit credentials` and `With using existing IAM role` are rendered as top-level headings instead of shell script comments, etc.

**What you expected to happen**:

I expected the readme to be fully legible at Helm Hub.

**How to reproduce it** (as minimally and precisely as possible):

Go to [the chart at Helm Hub](https://hub.helm.sh/charts/jfrog/artifactory) and Ctrl + F for `With explicit credentials` and `This key is generated only once and cannot be updated once created`.

I tried `helm pull`ing the chart and rendering `README.md` with [Grip](https://github.com/joeyespo/grip), and saw no obvious errors.

I don't know how to mimic Helm Hub's Markdown rendering locally.

**Anything else we need to know**:

[Markdownlint](https://github.com/markdownlint/markdownlint) recommends quite a lot of changes in `README.md`.

**Comment by SimonAlling** [comment]
Now that #658 is merged, I can confirm that it did the trick – with one exception: The configuration table had a different error, which should be fixed by #659. However, said PRs don't seem to affect [the latest version at Helm Hub (9.0.15)](https://hub.helm.sh/charts/jfrog/artifactory/9.0.15), and I don't know where to find that code.

**Comment by JfrogPrasanna** [comment]
@SimonAlling thank you. We have not merged the latest code with the latest helmHub packages. We will soon be doing. We will update  the  current GH readme to reflect it. Thanks for your patience.

**Comment by JfrogPrasanna** [comment]
@SimonAlling this is now fixed. and the latest is in this repo, free feel to check and contribute.
