### ISSUE TITLE
helm chart to build version 7.2.1 

### ISSUE THREAD

**Issue by mrafieee** [jfrog/charts#663]
Trying to provision a 7.2.1 Artifactory using helm chart it is not like it.

set: 
```
artifactory:
  image:
    version: 7.2.1
```

and received : 

```
error reading configuration from system.yaml : reading db properties failed: could not derive db properties from system yaml: Type: , Url: : Could not set db properties to application configuration: could not parse the jdbc url
goroutine 1 [running]:
runtime/debug.Stack(0x10, 0x10, 0xc000400740)
	/src/runtime/debug/stack.go:24 +0x9d
jfrog.com/metadata/common/log.(*standardLogger).Panicfc(0xc000080648, 0x14cbc40, 0xc000178420, 0x1293e62, 0x31, 0xc000400740, 0x1, 0x1)
	/src/jfrog.com/metadata/common/log/standard_logger.go:44 +0x6a
jfrog.com/metadata/services/common.(*configBearer).ValidateConfig(0xc000120460, 0x14cbc40, 0xc000178420, 0x14dbdc0, 0xc000080648)
	/src/jfrog.com/metadata/services/common/config_bearer.go:174 +0x245
main.main()
	/src/jfrog.com/metadata/metadata.go:24 +0x31f
panic: error reading configuration from system.yaml : reading db properties failed: could not derive db properties from system yaml: Type: , Url: : Could not set db properties to application configuration: could not parse the jdbc url
goroutine 1 [running]:
runtime/debug.Stack(0x10, 0x10, 0xc000400740)
	/src/runtime/debug/stack.go:24 +0x9d
jfrog.com/metadata/common/log.(*standardLogger).Panicfc(0xc000080648, 0x14cbc40, 0xc000178420, 0x1293e62, 0x31, 0xc000400740, 0x1, 0x1)
	/src/jfrog.com/metadata/common/log/standard_logger.go:44 +0x6a
jfrog.com/metadata/services/common.(*configBearer).ValidateConfig(0xc000120460, 0x14cbc40, 0xc000178420, 0x14dbdc0, 0xc000080648)
	/src/jfrog.com/metadata/services/common/config_bearer.go:174 +0x245
main.main()
	/src/jfrog.com/metadata/metadata.go:24 +0x31f
goroutine 1 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1(0xc0000fc380, 0x319)
	/pkg/mod/github.com/rs/zerolog@v1.17.2/log.go:338 +0x4f
github.com/rs/zerolog.(*Event).msg(0xc000525140, 0xc0000fc380, 0x319)
	/pkg/mod/github.com/rs/zerolog@v1.17.2/event.go:146 +0x186
github.com/rs/zerolog.(*Event).Msgf(0xc000525140, 0xc000665640, 0x34, 0xc0001cdb40, 0x2, 0x2)
	/pkg/mod/github.com/rs/zerolog@v1.17.2/event.go:126 +0x83
jfrog.com/metadata/common/log.(*standardLogger).logMessage(0xc000080648, 0x14cbc40, 0xc000178420, 0xc000525140, 0xc000665640, 0x34, 0xc0001cdb40, 0x2, 0x2)
	/src/jfrog.com/metadata/common/log/standard_logger.go:88 +0xbc
jfrog.com/metadata/common/log.(*standardLogger).Panicfc(0xc000080648, 0x14cbc40, 0xc000178420, 0x1293e62, 0x31, 0xc0001cdb40, 0x2, 0x2)
	/src/jfrog.com/metadata/common/log/standard_logger.go:45 +0x1df
jfrog.com/metadata/services/common.(*configBearer).ValidateConfig(0xc000120460, 0x14cbc40, 0xc000178420, 0x14dbdc0, 0xc000080648)
	/src/jfrog.com/metadata/services/common/config_bearer.go:174 +0x245
main.main()
	/src/jfrog.com/metadata/metadata.go:24 +0x31f
2020-03-09T19:29:21.136Z [jfrou] [FATAL] [                ] [bootstrap.go:92               ] [main                ] - Cluster join: Failed resolving join key: failed resolving 'shared.security.joinKey' key; file does not exist: /opt/jfrog/artifactory/var/etc/security/join.key

```

**Comment by farvour** [comment]
Is 7.2.1 even tested with the current Helm structure ecosystem?

**Comment by mrafieee** [comment]
> Is 7.2.1 even tested with the current Helm structure ecosystem?

not sure, there is no docs on how we should use the version attribute `artifactory.image.version` ! 
is version 7.x.x backward compatible? specially for thee database schema.

**Comment by farvour** [comment]
Based on the migration script they added I am going to say no.

**Comment by eldada** [comment]
Hi all. For installing the new 7.x Artifactory, you need to use the newest charts we released in the last few days. We also merged the sources for these charts just yesterday (March 11, 2020).
We had a couple of weeks of misalignment, that probably cause the error you had initially, that I think are now resolved.

Version 7.x is backward compatible application wise, but does require a proper upgrade to be run. Using helm, this means you'll have to upgrade with the new chart over the old one. Migration scripts take care of this one time migration, which is skipped in later upgrades.

Have a look at the [Artifactory Upgrade Notes](https://github.com/jfrog/charts/blob/master/stable/artifactory/UPGRADE_NOTES.md). There is a typo in the top title. It should be `Upgrade from 8.X to 9.X (Chart Versions)`.

**Comment by mrafieee** [comment]
@eldada Great thanks, It worked for me 👍

**Comment by angegar** [comment]
hello i am trying to deploy artifactory-ha chart version 2.2.9. My current artifactory installation is 6.18.1 and i am trying to upgrade to 7.3.2. The migration script started but failed with errors such as :

- error reading configuration from system.yaml : reading db properties failed: could not derive db properties from system yaml: Type: , Url: : Could not set db properties to application configuration: could not parse the jdbc url
goroutine 1 [running]:

- Failed initializing Home. Failed to init db properties:
- Failed initializing Artifactory context: Artifactory home not initialized.
- Cluster join: Failed resolving join key: failed resolving 'shared.security.joinKey' key; file does not exist: /opt/jfrog/artifactory/var/etc/security/join.key

What chart version did you use to fix your issue ?

**Comment by chukka** [comment]
@angegar Looks like you are running in to this issue
https://github.com/jfrog/charts/issues/677
Can you please refer this  
https://github.com/jfrog/charts/blob/master/stable/artifactory-ha/README.md#special-upgrade-notes-1

If you are using `32 hex` masterKey in 6.18.1 and using the same 32 hex masterKey in 7.3.2 (which is wrong)

**Solution** : Don't pass masterKey in 7.3.2 (during migration) -implies migration takes care of adding masterKey for you (recommended)

**Comment by angegar** [comment]
I see changes around db connection for non PosgreSQL.
I think the parameter host disappeared and now we have to use url only. Is it true ?

**Comment by angegar** [comment]
i remove the master key from the deployment, but i have the same result :(

If I force a new key is there a risk to desynchronize the database content with the file system one ?

**Comment by angegar** [comment]
I know an expert but I think those lines introduced multiple changes in the chart values file :

```
  database:
      {{- if .Values.postgresql.enabled }}
        type: postgresql
        url: "jdbc:postgresql://{{ .Release.Name }}-postgresql:{{ .Values.postgresql.service.port }}/{{ .Values.postgresql.postgresqlDatabase }}"
        host: ""
        driver: org.postgresql.Driver
        username: "{{ .Values.postgresql.postgresqlUsername }}"
      {{ else }}
        type: "{{ .Values.database.type }}"
        url: "{{ .Values.database.url }}"
        driver: "{{ .Values.database.driver }}"
        username: "{{ .Values.database.user }}"
      {{- end }}
```

Indeed the host parameter disappeared and a driver parameter must be set now. Probably due to those changes i receive the following error :

```
Caused by: java.lang.IllegalStateException: Mandatory database parameter 'database.driver' doesn't exist
        at org.jfrog.storage.DbProperties.assertMandatoryProperties(DbProperties.java:143)
        at org.jfrog.storage.DbProperties.<init>(DbProperties.java:32)
        ... 186 more
```

Previously i just started my container with : 

`--set artifactory.preStartCommand="wget -O /opt/jfrog/artifactory/tomcat/lib/mysql-connector-java-5.1.40.jar https://jcenter.bintray.com/mysql/mysql-connector-java/5.1.40/mysql-connector-java-5.1.40.jar"  \`

which no longer sounds be sufficent.

**Comment by angegar** [comment]
I receive the error : Caused by: java.sql.SQLException: Unable to load class: com.mysql.jdbc.Driver from ClassLoader:ParallelWebappClassLoader

I tried to configure the mysql driver following the doc, but without success. Any idea ?
