### ISSUE TITLE
Artifactory HA upgrade from 6.17.0 to 7.2.1  it keep stuck on init 4/5 on  migration-artifactory-ha and it is complaining about MASTER_KEY and JOIN_KEY.

### ISSUE THREAD

**Issue by mhamaydeh** [jfrog/charts#677]
**Is this a request for help?**: YES

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:

Helm : 2.16.1
Kubernetes : 1.14.10-gke.27

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.27", GitCommit:"145f9e21a4515947d6fb10819e5a336aff1b6959", GitTreeState:"clean", BuildDate:"2020-02-21T18:01:40Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
  
  artifactory-ha
  version: 2.0.30

**What happened**:
 we have a running artifactory Ha , version 6.17.0 . and we need to upgrade it to 7.2.1  . 
 when we apply the helm upgrade of the new version 7.2.1 helm chart version 2.0.30 , it keep stuck on init 4/5 of the primary node and one member node , 
 which is the  migration-artifactory-ha . 
 it complains about the master key and the join key . 
  Master key checksum mismatch. Aborting initialization. 
 [ERROR] [7bd3e3bbd7297186] [tifactoryHomeConfigListener:59] [ocalhost-startStop-1] - Failed initializing Home. Master key checksum mismatch
 [ERROR] [7bd3e3bbd7297186] [actoryContextConfigListener:82] [ocalhost-startStop-1] - Failed initializing Artifactory context: Artifactory home not initialized.

 join_key 
 Cluster join: Join key is missing. Pending for 15 seconds with 2m0s timeout

2020-03-14T01:07:36.121Z [jffe ] [ERROR] [ ] [ ] [main ] - Error: connect ECONNREFUSED 127.0.0.1:8046
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
2020-03-14T01:07:36.122Z [jffe ] [INFO ] [ ] [ ] [main ] - exit detected
2020-03-14T01:07:36.122Z [jffe ] [INFO ] [ ] [ ] [main ] - cleanup options : {"cleanup":true,"exit":true}
2020-03-14T01:07:36.122Z [jffe ] [INFO ] [ ] [ ] [main ] - doing clean
2020-03-14T01:07:36.122Z [jffe ] [INFO ] [ ] [ ] [main ] - unregistering from router
2020-03-14T01:07:36.122Z [jffe ] [INFO ] [ ] [ ] [main ] - client is already unregistered from router
2020-03-14T01:07:36.123Z [jffe ] [INFO ] [ ] [ ] [main ] - exiting app

 I'm passing the same master key that 6.17.0 is created with . 

 and I'm generating new join_key as the documentation says .

**What you expected to happen**:
 it expected to finish migration ,and start artifactory primary node with version 7.2.1 

**How to reproduce it** (as minimally and precisely as possible):
  Fresh installion of artifactory Ha 6.17.0 . 
  and then try to upgrade to artifactory ha version 7.2.1 

**Anything else we need to know**:
[log.txt](https://github.com/jfrog/charts/files/4338375/log.txt)

**Comment by mhamaydeh** [comment]
I'm passing the same master key that  6.17.0 is created with . 
and generated new key for join_key . 
I'm passing both with helm .

**Comment by chukka** [comment]
@mhamaydeh  Thanks for reporting this, Can you share know how master key was generated in 6.17.0 (did you explicitly generate  using `openssl rand -hex 32` and pass it while installing 6.17.0) ?

**Comment by mhamaydeh** [comment]
@chukka  thank you for your help . 
master_key is generated with   `openssl rand -hex 32 ` and stored in vault , and we pass it each time the same value  . 

join_key is generated  with `openssl rand -hex 16` and stored in vault as well , it was not exist in 6.17.0 so it is new value introduced with 7.x

**Comment by mhamaydeh** [comment]
@chukka  , still we are facing the same problem if you could please advice and help 

 we can't upgrade from artifactory HA 6.17.0 to 7.2.1 because of the following errors 

1- Master key checksum mismatch. Aborting initialization Failed initializing Access client: Cluster 
2- Service registry ping failed; context deadline exceeded. last error: Error while trying to connect to local router at address 'http://localhost:8046/access'
those errors in the log of the migration process  `migration-artifactory-ha`
We Manually generated and passing the same master key through helm chart on 6.17.0 and 7.2.1 .

port `8046`  is not exposed on `values.yaml` I'm not sure where we can change that ? 


Thanks

**Comment by chukka** [comment]
@mhamaydeh Thanks for the update , we are investigating this internally and will get back to soon

**Comment by chukka** [comment]
@mhamaydeh FYI, Fix is in PR - https://github.com/jfrog/charts/pull/701

**Comment by mhamaydeh** [comment]
@chukka  , thank you for the response , 
I have check the changes ,and test it out , still the same issue and the same errors  , 
Please check the log file on the container  `migration-artifactory-ha`

[migration-artifactory-ha.log](https://github.com/jfrog/charts/files/4359501/migration-artifactory-ha.log)

**Comment by chukka** [comment]
@mhamaydeh Can you share upgrade command output with debug and dry-run options 
For example   : add this at the end of helm upgrade  command `  --debug --dry-run ` ,
I would like see if you are passing masterKey in 7.x upgrade (which you shouldn't)

**Comment by mhamaydeh** [comment]
@chukka  , they are the same  values  , I'm using terraform with helm release for both charts , 6.17.0 and 7.2.1 
the master key value is pulled from Vault .  we generated it manually using `openssl rand -hex 32` and stored it in Vault . 
and I confirm that your changes  that you provide on #701 to trim the master key to 32 characters works fine , but it does not solve the problem,  I will try to add ` --debug --dry-run`

**Comment by mhamaydeh** [comment]
@chukka  
Hello again , i have created the following logs, the logs is formatted and trim some text from it  since it contain some secrets and sensitive data ,  Master key and Join Key are the same on all files . 
I'm attaching the following 
 1 - Terrafom plan for chart release  6.17.0   [terraform_6.17.0_release.log](https://github.com/jfrog/charts/files/4364004/terraform_6.17.0_release.log)
 2-  Helm release for chart version 6.17.0 [helm_release_6.17.0.log](https://github.com/jfrog/charts/files/4364003/helm_release_6.17.0.log)
 3-  Terrafom plan for  upgrade from chart 6.17.0 to 7.2.1  [terraform_7.2.1_release.log](https://github.com/jfrog/charts/files/4364005/terraform_7.2.1_release.log)
 4- Helm upgrade form chart 6.17.0 to 7.2.1  [helm_release_7.2.1.log](https://github.com/jfrog/charts/files/4364002/helm_release_7.2.1.log)
 5- Pod describe of the primary node of 7.2.1  [describe_pod_artifactory-artifactory-ha-primary-0.log](https://github.com/jfrog/charts/files/4364009/describe_pod_artifactory-artifactory-ha-primary-0.log)
 6- Log of the migration Container  `migration-artifactory-ha` in the primary pod [migration-artifactory-ha.log](https://github.com/jfrog/charts/files/4364001/migration-artifactory-ha.log)


Thank you .

**Comment by chukka** [comment]
Thanks @mhamaydeh Thanks for the logs
In your example , it seems you are using 32 hex masterKey in 6.17
`bda654a4b44e2de44d5d2bc9ab8aecfec4d5a2b2d0bfbbc78e534cf64b866719` and using the same 32 hex masterKey in 7.2.1 (which is wrong)
Now, You can do either of two things 
1. Don't pass masterKey in 7.2.1 (during migration) -implies migration takes care of adding masterKey for you 
or 
2. Pass trimmed masterKey  16 hex - `bda654a4b44e2de44d5d2bc9ab8aecfe` in 7.2.1

Please try and let us know the feedback

**Comment by chukka** [comment]
@mhamaydeh PR is merged, Please try above steps with latest charts(master)  or latest chart from https://charts.jfrog.io/  (artifactory-ha-2.0.35)

**Comment by mhamaydeh** [comment]
@chukka 
option 1 , works fine . 
1- Don't pass masterKey in 7.2.1 (during migration) -implies migration takes care of adding masterKey for you (recommended)

it pulled the master key from the database , which 32 hex .  
`bda654a4b44e2de44d5d2bc9ab8aecfec4d5a2b2d0bfbbc78e534cf64b866719`

Thank you

**Comment by chukka** [comment]
Thanks for the feedback , Marking this as issue closed :)
