### ISSUE TITLE
Adding Service account annotations breaks all the release

### ISSUE THREAD

**Issue by javier-ga** [jfrog/charts#680]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug

**Version of Helm and Kubernetes**:
helm version - v3.1.1
kubernetes: EKS 1.14

**Which chart**:
Artifactory and Artifactory-ha

**What happened**:
The `stable/artifactory/templates/artifactory-serviceaccount.yaml` template wrongly renders all the `values.yaml` content inside the ServiceAccount/metadata/annotations structure

**What you expected to happen**:
The service account should take only the annotations and not the whole `values.yaml` content

```diff
# stable/artifactory/templates/artifactory-serviceaccount.yaml
 {{- if .Values.serviceAccount.create }}
 apiVersion: v1
 kind: ServiceAccount
 metadata:
 {{- if .Values.serviceAccount.annotations }}
   annotations:
-{{ tpl (toYaml .) $ | indent 4 }}
+{{ tpl (toYaml .Values.serviceAccount.annotations) $ | indent 4 }}
 {{- end}}
   labels:

```

**How to reproduce it** (as minimally and precisely as possible):
Having a `values.yaml` as:

```yaml
serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::1233333333:role/EKS-artifactory-S3Role"
```
and then running helm as:
```bash
$ helm install --name artifactory -f values.yaml jfrog/artifactory
```

**Anything else we need to know**:
This is required to grant AWS permissions to a particular ServiceAccount without having to create key pairs - https://docs.aws.amazon.com/eks/latest/userguide/enable-iam-roles-for-service-accounts.html

**Comment by eldada** [comment]
Thanks @javier-ga . Good catch. Will provide a fix.
