### ISSUE TITLE
[Feature] Add NetworkPolicy to each chart to restrict traffic between pods

### ISSUE THREAD

**Issue by eldada** [jfrog/charts#69]
**Is this a request for help?**:

No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST:
To have better control and secure structure of traffic between each application's pods, every chart has to also deploy a NetworkPolicy descriptor with the matching rules.

- Deny all
- Allow traffic from pods in same namespace on application ports
- Allow traffic from external resources to public endpoint only

**Version of Helm and Kubernetes**:
Any

**Which chart**:
All

**Comment by jainishshah17** [comment]
@eldada Do we want to keep this open till we add this feature in all charts?

**Comment by eldada** [comment]
@jainishshah17 - Yes. I'll reopen this.
@zendril - Can you add this functionality in other charts?
