### ISSUE TITLE
Artifactory-OSS not honoring postgresql.enabled=false with Kubernetes 1.17

### ISSUE THREAD

**Issue by rafollett** [jfrog/charts#707]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: Helm 2.16.1, Kubernetes 1.17.3

**Which chart**: artifactory-oss

**What happened**: Running `helm install --name artifactory --set postgresql.enabled=false jfrog/artifactory-oss` still installs the postgresql pod and service.  

**What you expected to happen**: Expected it to default to derby, like jfrog/artifactory does and not install the pod. 

**How to reproduce it** (as minimally and precisely as possible):
Run `helm install --name artifactory --set postgresql.enabled=false jfrog/artifactory-oss` and see that it creates an artifactory-postgresql service and artifactory-posgresql-0 pod.

**Anything else we need to know**: If I try with an older Kubernetes (1.14 I believe) it works correctly.

**Comment by eldada** [comment]
Hi @rafollett. The `artifactory-oss` chart actually uses `artifactory` as a sub-chart, so you need to pass the configuration under the `artifactory` sub-chart key in the following format
```
helm install --name artifactory --set artifactory.postgresql.enabled=false jfrog/artifactory-oss
```

Looks like we need to fix some documentation on this. I will work on that. 
Try the above and let us know if it works for you.

**Comment by rafollett** [comment]
Yes, that command worked! Thank you!
