### ISSUE TITLE
Xray 3.2.0 Chart 3.0.22 Failed to connect to Google Cloud SQL ( POSTGRES_9_6)

### ISSUE THREAD

**Issue by mhamaydeh** [jfrog/charts#711]
**Is this a request for help?**: yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.31", GitCommit:"a757c52d8d65cf25a2891411b576fbe85734d327", GitTreeState:"clean", BuildDate:"2020-03-06T08:39:21Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
version: 3.0.22
appVersion: 3.2.0

**What happened**:
I'm trying deploy Xray with Terraform and Helm  . 
we are overriding the chart values to use Google Cloud SQL ( POSTGRES_9_6)
we are setting the following variables . 
postgresql.enabled = false 
database.url = "postgres://xray:changeme@host:5432/database?sslmode=disable"
database.user: xray
database.password: changeme

we are getting error in pod  (`xray-xray-server-0`    CrashLoopBackOff ) in container `xray-server`
`Failed to set Postgres statement timeout to 18000000: pq: password authentication failed`

**What you expected to happen**:
the xray server should connect to the database without any issue , 
in the previous chart (2.11.3) we was using the same setup  beside mongoDB and we didn't face any connectivity issues 

**How to reproduce it** (as minimally and precisely as possible):
deploy the xray 3.2.0 with Google Cloud SQL ( POSTGRES_9_6)

**Anything else we need to know**:
I'm attaching the log file  for  `kubectl logs xray-xray-server-0 -c xray-server`
[xray-server.log](https://github.com/jfrog/charts/files/4373711/xray-server.log)

**Comment by JfrogPrasanna** [comment]
@mhamaydeh Can you  try *without* user password in the db url?

This is what the system.yaml template has:
`   ## Example for postgresql
    #type: postgresql
    #driver: org.postgresql.Driver
    #url: jdbc:postgresql://<your db url, for example: localhost:5432>/artifactory
    #username: artifactory
    #password: password`

**Comment by mhamaydeh** [comment]
@JfrogPrasanna  , thank you for your help 
we was having 2 issues , and i guess the README need to be updated . 
1- the password was having `+` character . xray does not accept that   and does not give proper error 
2- the connection URL should be `postgres://host:port/databaseName?sslmode=disable`  , this need to be fixed in the Readme i guess 
and we need to pass the password and the user  as well  `database.user` and `database.password`

**Comment by JfrogPrasanna** [comment]
@mhamaydeh thank you - we will update this.

**Comment by JfrogPrasanna** [comment]
@mhamaydeh just to further update, the password having '+' works well when you pass them as database.password.
