### ISSUE TITLE
Artifactory 6.15.2 

### ISSUE THREAD

**Issue by angegar** [jfrog/charts#714]
**Is this a request for help?**:  yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): More like a bug

**Version of Helm and Kubernetes**: 
 
- Helm : 2.16.0
- Kubernetes : 1.15.9

**Which chart**: Artifactory-ha

**What happened**:
I would like to deploy the version 6.15.2 which contains a security patch. I tried with the chart version 1.2.4. During the deployment the master pod failed. The logs does not contain an error message but it display the java command help (java --help). It behaves like if the java command parameters where bad.

I try to run the 6.15.2 container in a my local docker host and it works. My assumption is there is a configuration file preventing the pod to correctly start with the new version.

**What you expected to happen**:
The pod running with the Artifactory version 6.15.2

**How to reproduce it** (as minimally and precisely as possible):

- Deploy the chart version 1.2.4
- Update the value file to use the image tag 6.15.2
- Deploy once again

**Anything else we need to know**:

Kubernetes stack deployed with Kops and hosted on AWS.
We use an AWS S3 storage. The cache is persisted on a 600GB  EBS disk.

**Comment by angegar** [comment]
If i edit the deployment with kubectl edit and if i remove the environment variable EXTRA_JAVA_OPTIONS, it works.

The options are : 

```
        - name: EXTRA_JAVA_OPTIONS
          value: |
            -Dartifactory.async.corePoolSize=16 -Xms4g -Xmx12g --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
```

**Comment by angegar** [comment]
If i remove the multi line syntax and use an inline one then it works.

The options --add-opens .... can be removed, it was added by mistake.

**Comment by cpasquini** [comment]
I am seeing this same issue with the 6.18.1 docker image. I've tried using both of these helm chart versions:
8.2.3
8.5.0

In my helm deployment I am not adding any of my own Java Options - these come directly from the docker image i presume.

I am seeing this error during startup:
```020-03-24T17:39:13.449015877Z 2020-03-24 17:39:13  [740 entrypoint-artifactory.sh] No extra certificates found
2020-03-24T17:39:13.455426404Z 2020-03-24 17:39:13  [745 entrypoint-artifactory.sh] Adding EXTRA_JAVA_OPTIONS if exist
2020-03-24T17:39:13.462725815Z 2020-03-24 17:39:13  [747 entrypoint-artifactory.sh] Adding EXTRA_JAVA_OPTIONS -Dartifactory.async.corePoolSize=8
2020-03-24T17:39:13.462743561Z 
2020-03-24T17:39:13.463414222Z '/opt/jfrog/artifactory/bin/artifactory.default' -> '/opt/jfrog/artifactory/bin/artifactory.default.origin'
2020-03-24T17:39:13.471631406Z 2020-03-24 17:39:13  [785 entrypoint-artifactory.sh] Setup done. Running Artifactory
2020-03-24T17:39:13.480526799Z /usr/bin/java
2020-03-24T17:39:13.575279912Z NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
2020-03-24T17:39:13.705998205Z Usage: java [options] <mainclass> [args...]```

**Comment by russ-c** [comment]
I'm seeing the same issue with Artifactory 6.16.2. JFrog, when will a fix be out?

**Comment by eldada** [comment]
Hi all. We actually released a fix for this in `artifactory-8.5.3` and `artifactory-ha-1.5.2` (we have a dedicated branch to keep supporting the Artifactory 6.x versions).
They include Artifactory app version 6.18.1 by default, but also work with older Artifactory versions (by setting `artifactory.image.version` to the desired version).
Try it out and provide some feedback.

**Comment by angegar** [comment]
I am deployed the chart version 1.5.2 with the image 6.15.2. For this deployment i set nginx.enable=false so that the nginx pdb should not be created, but it is. Indeed during another run of the same deployment I receive the error :

![image](https://user-images.githubusercontent.com/5628764/77514606-6f8e9400-6e77-11ea-8c80-e4f01e5148ee.png)

**Comment by eldada** [comment]
Yes. Seems there's a bug there that we fixed only on the latest `master` charts. I will submit a fix for it soon.

**Comment by eldada** [comment]
Pull request #717

**Comment by eldada** [comment]
```
artifactory-ha-1.5.3 released successfully!
```
Please confirm.

**Comment by cpasquini** [comment]
I've confirmed that in my deployment the 16.18.1 image is working with the 8.5.3 helm chart.  Thanks for the quick fix.

**Comment by eldada** [comment]
@angegar - can you let us know? I'm closing this issue. Reopen it if issue persists.

**Comment by angegar** [comment]
Indeed i deployed with chart version 1.5.2 with the image 6.15.2.
