### ISSUE TITLE
Add javaOpts.other to distribution chart

### ISSUE THREAD

**Issue by majwang** [jfrog/charts#726]
Is this a BUG REPORT or FEATURE REQUEST? (choose one):
Feature request

Version of Helm and Kubernetes:
All

Which chart:
Distribution

Description:
This is a feature request to add javaOpts.other to the distribution chart, just like there is in Artifactory. This is to be able to easily add java opts like to add a custom java keystore.

values.yaml:
javaOpts:
      other: 

Template:
{{- if $.Values.artifactory.javaOpts.other }}
            {{ $.Values.artifactory.javaOpts.other }}
          {{- end }}

**Comment by JfrogPrasanna** [comment]
@majwang Feel  free to raise a pull request, it will be the best way to make sure your feature requests gets in the fastest way.
