### ISSUE TITLE
Use secret for external MongoDB

### ISSUE THREAD

**Issue by Manojtuguru** [jfrog/charts#73]
**Is this a request for help?**:
FEATURE REQUEST
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
Helm: 2.9.1 K8s: 1.10.0

**Which chart**:
Xray

**What happened**:
[MONGODB_URL](https://github.com/jfrog/charts/blob/master/stable/xray/templates/xray-indexer-deployment.yaml#L48) is using variable instead of secret.

**What you expected to happen**:
Use secret for [MONGODB_URL](https://github.com/jfrog/charts/blob/master/stable/xray/templates/xray-indexer-deployment.yaml#L48)

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by jainishshah17** [comment]
@eldada We need to fix this in Xray as well. According to https://github.com/jfrog/charts/blob/master/stable/xray/templates/xray-indexer-deployment.yaml#L49 we are using ENV for it.

**Comment by jainishshah17** [comment]
@Manojtuguru Closing issue as PR is merged.
