### ISSUE TITLE
Unable to deploy artifactory-ha in AKS

### ISSUE THREAD

**Issue by vinayk833** [jfrog/charts#756]
**Is this a request for help?**: Yes

If this is a FEATURE REQUEST, please:  Yes
We are trying to  deploy artifactory-ha from the link  https://github.com/jfrog/charts/tree/master/stable/artifactory-ha. But we are not able to deploy as the primary pods is never ready and always get deleted. and we get this error in the logs.

accessJdbcHelperImpl': Invocation of init method failed; nested exception is java.lang.IllegalStateException: Could not initialize database: FATAL: password authentication failed for user "artifactory"   

Please note that we have tried deploying the helm using with and without generating master key, also we tried  deploying the helm chart with customized postgresql password also.
We are currently trying to deploy the artifactory-ha version 7.3.2. on Azure aks( eastus , Kubernetes version 1.16.7)
Moreover when we tried deploying the older version of artifactory-ha version 6.x from the link https://github.com/helm/charts/tree/master/stable/artifactory-ha . its working perfectly fine.
-->

**Version of Helm and Kubernetes**: helm version 3.1 kubernetes verson 1.16.7

**Which chart**:  https://charts.jfrog.io/  |  artifactory-ha-2.2.8.tgz 

**What you expected to happen**:
 succesfull deploy of artifactory ha using helm

**How to reproduce it** (as minimally and precisely as possible): 
follow the document "https://github.com/jfrog/charts/tree/master/stable/artifactory-ha"  on  Azure AKS

[logs_artifactory-ha-primary-0.txt](https://github.com/jfrog/charts/files/4426769/logs_artifactory-ha-primary-0.txt)

**Comment by gkollengode** [comment]
I have been able to recreate this on AWS EKS.  Looks like the issue is in the systemYAML section in the yaml here.  [https://github.com/jfrog/charts/blob/master/stable/mission-control/values.yaml#L349] The resulting system.yaml is missing the password and hence the auth failure 

Adding password: "{{ .Values.database.password }}" after that line seems to resolve the problem  for us at this time

**Comment by chukka** [comment]
@vinayk833 Sorry for delayed response , Looks like a password issue , to investigate and help you  further 
1. Can you try setting  postgresqlPassword as part of helm install by `--set postgresql.postgresqlPassword=xxx` (replace xxx with actual password you wish to pass)
2. Can you share output of command your helm install command with adding this extension at the end `--debug  --dry-run `

**Comment by vinayk833** [comment]
Hi @chukka ,

Apologies for late reply.
I have tried the suggestions given by you, but the results is the same. Also I attaching the logs generated during dry-run.
[dry_run.txt](https://github.com/jfrog/charts/files/4468370/dry_run.txt)
