### ISSUE TITLE
Xray chart 3.x secrets not working!

### ISSUE THREAD

**Issue by erick-duran** [jfrog/charts#758]
**Is this a request for help?**: yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
bug

**Version of Helm and Kubernetes**:
Helm: 3.1.0
Kubernetes: 1.14.9 (EKS)

**Which chart**:
Xray 3.0.27

**What happened**:
Tried to install Xray passing credentials as Kubernetes secrets, but got errors in services when trying to do so. Had to deploy passing the user/password directly.

**What you expected to happen**:
That the charts retrieved the secrets from Kubernetes by the secret resource.

**How to reproduce it** (as minimally and precisely as possible):
1. Install Xray chart 3.x with the default values, pass your credentials as secrets.
2. Xray server pod gets into Error status.

**Anything else we need to know**:
I tried passing the following secrets similar to how I do in other charts or previous versions. Secrets I tested:
- xray.masterKeySecretName (not an error, but you can see the default master key warning in the message after the chart install)
- database.secrets (causes error status in server pod, working if passed directly to the database user/password values).

After experiencing this, retried passing all values that have the secrets option directly and that worked fine.

Thanks in advance

**Comment by chukka** [comment]
Hi @erick-duran Thanks for the issue.This is a known bug for database secrets . Fix for this is currently work in progress.Will let you know once we fix this.

**Comment by nixel2007** [comment]
Looks like jcr chart has the same issue.

**Comment by chukka** [comment]
@nixel2007 Latest JCR chart - 2.1.5 will have secrets support , please try and let us know

**Comment by chukka** [comment]
Hi @erick-duran Can you please try latest xray chart - `3.0.28` which has support for DB secrets and share the feedback ?

**Comment by erick-duran** [comment]
Hello @chukka,
Thanks for this. I was able to use:
- `xray.joinKeySecretName`
- `database.secrets.user/password/url`

However, I couldn't use `rabbitmq-ha.existingPasswordSecret`. This resulted in the following errors from describing the `rabbitmq-ha` pod:
```
Warning  FailedMount    MountVolume.SetUp failed for volume "definitions" : references non-existent secret key: definitions.json

Warning  FailedMount   Unable to mount volumes for pod "xray-rabbitmq-ha-0_xray3(e1131b65-842c-11ea-812c-126a2963b5f9)": timeout expired waiting for volumes to attach or mount for pod "xray3"/"xray-rabbitmq-ha-0". list of unmounted volumes=[definitions]. list of unattached volumes=[data config configmap definitions xray-rabbitmq-ha-token-2nf26]
```
The secret was created with the `rabbitmq-password` key indicated in the comments. Any advice?

Also, I noticed that the `xray.masterKeySecretName` value works (I see the custom master key by `exec` into the pod and checking the key file), but it shows the warning that I'm using the default master key value ("`FFFFFFF...`"). Not a problem but rather a small bug. 🙂
