### ISSUE TITLE
artifactory-ha : DB Driver not found in Init Containers

### ISSUE THREAD

**Issue by angegar** [jfrog/charts#773]
**Is this a request for help?**:

Yes, this is probably a bug
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
 - Helm chart version 2.2.9
- Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.9", GitCommit:"2e808b7cb054ee242b68e62455323aa783991f03", GitTreeState:"clean", BuildDate:"2020-01-18T23:24:23Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
artifactory-ha

**What happened**:
I am migrating from artifactory 6.18.1 to the latest version in using the chart.  The last InitContainers (migration-artifactory-ha) fails with the error : 

```
2020-04-06T14:27:25.681Z [jfrt ] [ERROR] [92549b418c48f099] [o.j.c.d.TemporaryDBChannel:44 ] [ocalhost-startStop-2] - The DB driver for mysql was not found. Copy the relevant DB driver to '$JF_PRODUCT_HOME/var/bootstrap/artifactory/tomcat/lib'.
```

Indeed I am using the mysql database and i have to download the driver with 		--set artifactory.preStartCommand.

In the latest chart version this command is used only in the artifactory container (https://github.com/jfrog/charts/blob/82f615a4e26614620f2cd861e0a39c348b870049/stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml#L355) but not in the init container. The result is that the migration process fails.

**What you expected to happen**:

A smooth startup and migration from 6.18.1 to 7.3.2 ;)

**How to reproduce it** (as minimally and precisely as possible):

My previous configuration was 
- Use Helm chart version 1.5.3 
- Use the chart image version (6.18.1)

**Anything else we need to know**:
I will try to use customInitContainersBegin  to fix this issue.

**Comment by chukka** [comment]
Hi @angegar , Thanks for the PR, Let me investigate further and update  you soon

**Comment by angegar** [comment]
Thank you @chukka, I will test the change as soon as it will be released

**Comment by chukka** [comment]
@angegar Can you please try latest below Chart(s) 

- [x]  artifactory-9.2.8 
- [x] artifactory-ha-2.2.10 

Try preStartCommand in migration Init container as`artifactory.migration.preStartCommand` in values.yaml

**Comment by angegar** [comment]
Hummm,
My first try returned this error :


```
 copy-system-yaml:
    Container ID:
    Image:         busybox
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
      echo "Copy system.yaml to /var/opt/jfrog/artifactory/etc"; mkdir -p /var/opt/jfrog/artifactory/etc; mkdir -p /var/opt/jfrog/artifactory/etc/access/keys/trusted; cp -fv /tmp/etc/system.yaml /var/opt/jfrog/artifactory/etc/system.yaml; echo "Remove /var/opt/jfrog/artifactory/lost+found folder if exists"; rm -rfv /var/opt/jfrog/artifactory/lost+found; echo "Copy masterKey to /var/opt/jfrog/artifactory/etc/security"; mkdir -p /var/opt/jfrog/artifactory/etc/security; echo -n ${ARTIFACTORY_MASTER_KEY} > /var/opt/jfrog/artifactory/etc/security/master.key;

    State:          Waiting
      Reason:       ErrImagePull
    Ready:          False
    Restart Count:  0
    Environment:
      ARTIFACTORY_MASTER_KEY:  <set to the key 'master-key' in secret 'art-artifactory-ha'>  Optional: false
    Mounts:
      /tmp/etc/system.yaml from systemyaml (rw,path="system.yaml")
      /var/opt/jfrog/artifactory from volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from artifactory-svc-account-token-fdmgh (ro)
```

**Comment by angegar** [comment]
arfff my bad i overwrittent the initContainer image with busybox. Just commented it and try again.

**Comment by angegar** [comment]
Even with the good init container image i have this strange issue :


```
  Type     Reason       Age                    From                                   Message
  ----     ------       ----                   ----                                   -------
  Normal   Scheduled    11m                    default-scheduler                      Successfully assigned artifactory/art-artifactory-ha-primary-0 to ip-10-165-14-43.ec2.internal
  Warning  FailedMount  9m38s                  kubelet, ip-10-165-14-43.ec2.internal  Unable to mount volumes for pod "art-artifactory-ha-primary-0_artifactory(f3a5ff23-8482-4d37-85d0-a32cab683585)": timeout expired waiting for volumes to attach or mount for pod "artifactory"/"art-artifactory-ha-primary-0". list of unmounted volumes=[volume]. list of unattached volumes=[volume binarystore-xml artifactory-license migration-scripts installer-info tmp-plugins metrics clean-permissions clean-perm-repo systemyaml logback artifactory-svc-account-token-fdmgh]
  Normal   Pulled       9m25s                  kubelet, ip-10-165-14-43.ec2.internal  Container image "alpine:3.10" already present on machine
  Normal   Created      9m25s                  kubelet, ip-10-165-14-43.ec2.internal  Created container delete-db-properties
  Normal   Started      9m24s                  kubelet, ip-10-165-14-43.ec2.internal  Started container delete-db-properties
  Normal   Pulled       9m24s                  kubelet, ip-10-165-14-43.ec2.internal  Container image "alpine:3.10" already present on machine
  Normal   Started      9m24s                  kubelet, ip-10-165-14-43.ec2.internal  Started container remove-lost-found
  Normal   Created      9m24s                  kubelet, ip-10-165-14-43.ec2.internal  Created container remove-lost-found
  Normal   Pulling      8m13s (x3 over 9m23s)  kubelet, ip-10-165-14-43.ec2.internal  Pulling image "alpine:3.10"
  Warning  Failed       7m58s (x3 over 9m8s)   kubelet, ip-10-165-14-43.ec2.internal  Failed to pull image "alpine:3.10": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  Failed       7m58s (x3 over 9m8s)   kubelet, ip-10-165-14-43.ec2.internal  Error: ErrImagePull
  Warning  Failed       7m33s (x4 over 9m8s)   kubelet, ip-10-165-14-43.ec2.internal  Error: ImagePullBackOff
  Normal   BackOff      4m30s (x14 over 9m8s)  kubelet, ip-10-165-14-43.ec2.internal  Back-off pulling image "alpine:3.10"
```

**Comment by angegar** [comment]
With the chart 1.5.3, i don't have difficulties to download the image :

```
Events:
  Type     Reason     Age                   From                                   Message
  ----     ------     ----                  ----                                   -------
  Normal   Scheduled  6m11s                 default-scheduler                      Successfully assigned artifactory/art-artifactory-ha-primary-0 to ip-10-165-14-43.ec2.internal
  Normal   Pulled     6m1s                  kubelet, ip-10-165-14-43.ec2.internal  Container image "alpine:3.10" already present on machine
  Normal   Created    6m1s                  kubelet, ip-10-165-14-43.ec2.internal  Created container delete-db-properties
  Normal   Started    6m                    kubelet, ip-10-165-14-43.ec2.internal  Started container remove-lost-found
  Normal   Started    6m                    kubelet, ip-10-165-14-43.ec2.internal  Started container delete-db-properties
  Normal   Pulled     6m                    kubelet, ip-10-165-14-43.ec2.internal  Container image "alpine:3.10" already present on machine
  Normal   Created    6m                    kubelet, ip-10-165-14-43.ec2.internal  Created container remove-lost-found
  Normal   Started    5m59s                 kubelet, ip-10-165-14-43.ec2.internal  Started container access-bootstrap-creds
  Normal   Pulled     5m59s                 kubelet, ip-10-165-14-43.ec2.internal  Container image "alpine:3.10" already present on machine
  Normal   Created    5m59s                 kubelet, ip-10-165-14-43.ec2.internal  Created container access-bootstrap-creds
  Normal   Pulled     5m58s                 kubelet, ip-10-165-14-43.ec2.internal  Container image "alpine:3.10" already present on machine
  Normal   Created    5m58s                 kubelet, ip-10-165-14-43.ec2.internal  Created container wait-for-db
  Normal   Started    5m58s                 kubelet, ip-10-165-14-43.ec2.internal  Started container wait-for-db
  Normal   Pulled     5m57s                 kubelet, ip-10-165-14-43.ec2.internal  Container image "docker.bintray.io/jfrog/artifactory-pro:6.18.1" already present on machine
  Normal   Created    5m57s                 kubelet, ip-10-165-14-43.ec2.internal  Created container artifactory-ha
  Normal   Started    5m57s                 kubelet, ip-10-165-14-43.ec2.internal  Started container artifactory-ha
```


Is it possible that the docker pull error come from the chart ? I found it strange but that's an option.

**Comment by chukka** [comment]
@angegar I tried  fresh artifactory-9.2.8 without any errors - Can you retry and share feedback ?

**Comment by angegar** [comment]
We had a network issue thus the error above were not linked with the chart. I tried another run but i failed, I still not understand why. I am trying to apply it over a 1.5.3 to reproduce the condition I will have in production.

The first thing i noticed is that all the pod were deleted at the same time, thus there is an application downtime. Did you observe the same behavior ?

**Comment by angegar** [comment]
Just to highlight what i said, all the pods are deleted :

![image](https://user-images.githubusercontent.com/5628764/78970019-a4057f80-7b08-11ea-87b0-316b780b9eb0.png)


Can it be linked with one of  the command line options below  :

		--wait 
		--atomic 
		--cleanup-on-fail 
		--force 
		--reset-values 
		--timeout 2600 
		--version 2.2.11

**Comment by angegar** [comment]
I purged the artifactoy-ha deployment and re-run the 2.2.11 version. During the deployment i encounter :

```
11:30:43  [2020-04-10T09:30:43.471Z] INSTALL FAILED
11:30:43  [2020-04-10T09:30:43.471Z] PURGING CHART
11:30:43  [2020-04-10T09:30:43.471Z] Error: release art failed: Service "art-artifactory-ha" is invalid: spec.ports[1]: Duplicate value: core.ServicePort{Name:"", Protocol:"TCP", Port:8081, TargetPort:intstr.IntOrString{Type:0, IntVal:0, StrVal:""}, NodePort:0}
11:30:44  [2020-04-10T09:30:44.401Z] Successfully purged a chart!
11:30:44  [2020-04-10T09:30:44.402Z] Error: release art failed: Service "art-artifactory-ha" is invalid: spec.ports[1]: Duplicate value: core.ServicePort{Name:"", Protocol:"TCP", Port:8081, TargetPort:intstr.IntOrString{Type:0, IntVal:0, StrVal:""}, NodePort:0}
11:30:44  [2020-04-10T09:30:44.402Z] make: *** [makefile:31: upsert] Error 1
```

Do you have a such error with the artifactory-ha chart ?

**Comment by angegar** [comment]
I finally made progress. The good command to use in migration.prestartcommand is :

```
 migration:
    preStartCommand: "mkdir -p /opt/jfrog/artifactory/var/bootstrap/artifactory/tomcat/lib; wget -O /opt/jfrog/artifactory/var/bootstrap/artifactory/tomcat/lib/mysql-connector-java-5.1.40.jar"
```

I tried with the -x command but the container wget version does not support it.

**Comment by angegar** [comment]
Now i have the following error :

`art-artifactory-ha-primary-0   0/1     PostStartHookError: command '/bin/sh -c echo;`

@chukka , any idea about what happens.

**Comment by angegar** [comment]
Here are the logs if it can help :

![image](https://user-images.githubusercontent.com/5628764/79252359-c76e5880-7e81-11ea-86a0-2d70b1bec624.png)

**Comment by angegar** [comment]
I checked into the code, it appears that the postStart hook is using bin/sh whereas the container commands are using bin/bash, i don't think it is the root cause but that's a difference. 

Any case the culprit line seems to be ::https://github.com/jfrog/charts/blob/c3fd35b1d6405c1bfb8e145019ae9d1b388c8d0f/stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml#L372

**Comment by chukka** [comment]
@angegar I was about to pinpoint the same difference as you mentioned above.

Can you please try changing it from  `/bin/sh ` to `bin/bash` in artifactory-primary-statefulset.yaml  and artifactory-node-statefulset.yaml

if it works, please share the feedback,  I may want to provide a fix in the upcoming release

**Comment by angegar** [comment]
@chukka , i obtain the same result. I tried to modify the lifecyle prestart command but i always receive an exit code 126 which seems to mean the script does not have the permission to be executed.

Basically this sounds to be a permission issue during the script execution.

**Comment by angegar** [comment]
i tried to simplify the lifecycle hook but i have the same result. 
I tried with :

        lifecycle:
          postStart:
            exec:
              command:
              - /bin/bash
              - -c
              - ls

**Comment by chukka** [comment]
@angegar Thanks for the feedback ! Can you please raise this postStart  issue as an separate issue (since this issue is already closed)
