### ISSUE TITLE
helm chart versions for artifactory-ha 6.*

### ISSUE THREAD

**Issue by palko444** [jfrog/charts#816]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
helm: 3.1.2
k8s: v1.15.3

**Which chart**: artifactory-ha

**What happened**:
In changelog for artifactory-ha are missing versions 1.5.[0-3], but i can see these version in helm chart repositories via `helm search repo artifactory-ha --version 1.5.3`
Follow up question, will you still update charts for artifactory-ha as version 6 is still supported
https://www.jfrog.com/confluence/display/RTF6X/End+of+Life

**What you expected to happen**:
Update helm charts for version 6 until end of life

**How to reproduce it** (as minimally and precisely as possible): ---

**Anything else we need to know**: ---

**Comment by chukka** [comment]
@palko444 7.x Artifactory is maintained on  `master` branch and 
6.x Artifactory is supported and maintained under `pre-unified-platform` branch
Please refer for changelog:
https://github.com/jfrog/charts/blob/pre-unified-platform/stable/artifactory-ha/CHANGELOG.md

Closing this issue, Feel free to reopen the issue
