### ISSUE TITLE
Pod Disruption Budgets change removed

### ISSUE THREAD

**Issue by DNewt** [jfrog/charts#828]
Hey i made an issue awhile ago here https://github.com/jfrog/charts/issues/613
and made the pull request to fix it which got accepted here: https://github.com/jfrog/charts/pull/615

Changelog.md: https://github.com/jfrog/charts/blob/master/stable/artifactory-ha/CHANGELOG.md#142---jan-22-2020

This was accepted but it seems like the change has been overwritten in later chart versions.

The change was made in this Pull Request 
https://github.com/jfrog/charts/commit/8b9dd9fa1f63e08ebf7a8a3c0f77935821d23e3d#diff-c23b8769797f9447ddb7559242883cacL13
It removed the ability to define the target component for a pod disruption budget - this means you can't specifically target Artifactory rather than Nginx pods.

Not a hard change to fix - just wondering if this was done on purpose

**Is this a request for help?**:
Yep
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature?

If this is a FEATURE REQUEST, please:
  - Describe *in detail* the feature/behavior/change you'd like to see.
The previous change allowed us to specify that we want a certain amount of Artifactory pods up. Without this change, it puts Nginx Pods and Artifactory pods together - so if you say you want 50% of them up, you may end up with 0 Artifactory pods and 100% Nginx pods.

**Which chart**:
artifactory-ha

**Comment by chukka** [comment]
@DNewt Thanks for the detailed info, Are you referring to this single line change(addition of component) in stable/artifactory-ha/templates/artifactory-node-pdb.yaml file 
(https://github.com/jfrog/charts/pull/615/files#diff-c23b8769797f9447ddb7559242883cacR14) which was removed in latest charts ?

Also please confirm if this is related to https://github.com/jfrog/charts/issues/651 ?

Thanks

**Comment by shinji62** [comment]
@chukka We got the same issue and it's related to removed line that you are showing. Basically this avoid us to drain our kubernetes nodes because a pod have 2 pdb attach to it.

Can you please re-add the deleted line?

I don't think is related to the issue #651.

**Comment by chukka** [comment]
@shinji62 Fixed in latest charts - artifactory-ha-2.5.1, Please try and share feedback
