### ISSUE TITLE
XRAY chart xray-3.0.26 , APP version 3.2.3  failed fetching external topology from Access

### ISSUE THREAD

**Issue by mhamaydeh** [jfrog/charts#832]
**Is this a request for help?**: YES

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**Version of Helm and Kubernetes**:
Helm :
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}

Kubernetes: 
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.32", GitCommit:"f93c8851c566b682af18a7323472d2ef685176da", GitTreeState:"clean", BuildDate:"2020-03-07T00:38:31Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
version: 3.0.26
appVersion: 3.2.3

**What happened**:
Xray deployed successfully , after running for a while it keep giving errors 
2020-04-08T16:35:10.661Z [jfrou] [ERROR] [31406fc97d70c608] [external_topology.go:82       ] [main                ] - failed fetching external topology from Access:

and 
Error: Data sync from global database server has failed.

**What you expected to happen**:
xray to work fine , since the deployment went fine . 

**How to reproduce it** (as minimally and precisely as possible):
deploy artrifactory 7.2.1 (artifactory-ha-2.0.35)  and xray 3.2.3 (chart xray-3.0.26) on Kubernetes 

**Anything else we need to know**:
2020-04-08T16:34:54.931Z [jfrou] [ERROR] [16b504066ac4541a] [local_topology.go:112         ] [main                ] - periodic send heartbeat failed for 5 consecutive times. Last error: failed sending heartbeat information to Access: failed closing Access grpc client: rpc error: code = Unavailable desc = Service Unavailable: HTTP status code 503; transport: received the unexpected content-type "text/plain; charset=utf-8"
2020-04-08T16:34:55.667Z [jfrou] [ERROR] [31e5bb6d67af94b3] [external_topology.go:82       ] [main                ] - failed fetching external topology from Access:

**Comment by chukka** [comment]
@mhamaydeh Can you please share more logs of Xray  and Artifactory pods 
Also, Can you share xray.joinKey and xray.jfrogUrl passed for connecting xray to Artifactory?

**Comment by mhamaydeh** [comment]
@chukka thank you for the fast response , I'm afraid that i can't share those information's it is production environment ,  i need to setup dev environment  with dummy keys  first i guess .

**Comment by chukka** [comment]
@mhamaydeh  is this still an issue ? If not, please close this issue

**Comment by mhamaydeh** [comment]
@chukka it is still an issue . but we are moving to enterprise plus licence , i will close the ticket now , and see what we will get later .
