### ISSUE TITLE
404 error after upgrading chart from 7.18.3 to 8.4.7

### ISSUE THREAD

**Issue by wlmckeon** [jfrog/charts#835]
**Is this a request for help?**: yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
Helm: version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}

Kubernetes:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"c83d931fb9bece427bc63a02349755e0f8696d3e", GitTreeState:"clean", BuildDate:"2020-01-31T20:09:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**: 7.18.3 and 8.4.7

**What happened**:
After following the instructions pertaining found in README.md  for 8.4.7, the upgrade fails with a 404 error.
Message /artifactory/webapp/

Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

Looking into the logs there is a message about not being able to connect to postgreasql due to a password mismatch.  Also, there are two services running for postgresql after upgrade:  service/artifactory-postgresql and service/artifactory-postgresql-headless.  

**What you expected to happen**:
The artifactory instance to come back up after applying the new chart

**How to reproduce it** (as minimally and precisely as possible):
- Have artifactory running from chart 7.18.3 with pv/pvcs for both artifactory and the postgresql database.
  - Log onto artifactory and perform a full system export
  - Update artifactory instance with the following command:
  helm3 upgrade artifactory charts/8.4.7/ --set databaseUpgradeReady=yes -f values-8.4.7.yaml --timeout=60m0s

 - watch instances come back up and report no error from any of the K8s logs, but receive 404 error when attempting to go to the artifactory page.  Logging on the artifactory instance revels the password issue and the double postgresql services are noted.

**Anything else we need to know**:
I've attached my values file for 7.18.3 (values.yaml) and the values file I was using for 8.4.7 (values-8.4.7.yaml)
[artifactory_values.zip](https://github.com/jfrog/charts/files/4504683/artifactory_values.zip)

**Comment by chukka** [comment]
@wlmckeon I tried with steps documented in https://github.com/jfrog/charts/blob/master/stable/artifactory/UPGRADE_NOTES.md and tried upgrade from 7.18.3 to 8.4.7 with default values, it works as expected (able to login artifactory after upgrade.)

looks like you added ingress configuration in values , Can you please double check those values and follow the  instructions mentioned [here](https://github.com/jfrog/charts/blob/master/stable/artifactory/UPGRADE_NOTES.md)

**Comment by wlmckeon** [comment]
@chukka I followed the instructions in the link that you have posted and I still get the 404 error.  I have checked my ingress settings and there wasn't any issues that I noticed, but I did just disable the ingress to test if that was the issue.  I still get a 404 error, but this one is slightly different:
Message /artifactory

Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

I still see two versions of the postgresql service after the upgrade.  One headless and one not.  Is that expected?

**Comment by wlmckeon** [comment]
If I curl to the pods' endpoint with curl -LI http://<pod-ip>:8081
HTTP/1.1 200 OK
Accept-Ranges: bytes
ETag: W/"878-1578568769000"
Last-Modified: Thu, 09 Jan 2020 11:19:29 GMT
Content-Type: text/html
Content-Length: 878
Date: Tue, 21 Apr 2020 21:51:50 GMT

For more information.
When I curl to pods endpoint with /artifactory or /artfactory/webapps:
curl -LI http://<pod-id>:8081/artifactory
HTTP/1.1 404 Not Found
Content-Type: text/html;charset=utf-8
Content-Language: en
Transfer-Encoding: chunked
Date: Tue, 21 Apr 2020 21:53:16 GMT

**Comment by chukka** [comment]
@wlmckeon  is this still an issue now ? can you try upgrading to latest charts - 8.7.0 (Artifactory 6.20.0) ?

I'm closing this issue. Feel free to open if it doesn't solve with upgrade .
