### ISSUE TITLE
Docker 503 Error when trying to pull image

### ISSUE THREAD

**Issue by EvanMAmstutz** [jfrog/charts#836]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Version of Helm and Kubernetes**:
Helm 3 OpenShift 3.11

**Which chart**:
Artifactory-HA

**What happened**:
Receiving a 503 error when trying to pull an image from docker virtual repository. I can login to the repository but cannot pull an image.

**What you expected to happen**:
Pull an image from the remote repository without incident

**How to reproduce it** (as minimally and precisely as possible):
Run the helm chart with helm 3 from commit 42b781c0711e8f4ba4511e23de8ccd63274ce507 on OpenShift 3.11

**Anything else we need to know**:

**Comment by chukka** [comment]
@EvanMAmstutz Can you share more info to investigate further 

1. chart version
2. App version
3. Logs

**Comment by EvanMAmstutz** [comment]
version: 1.5.0
appVersion: 6.18.0
No logs appear when getting the 503

**Comment by chukka** [comment]
@EvanMAmstutz is this still an issue  ? Can you share all  logs  (access , artifactory ) to look into the issue .  

If it is not production instance, can you try upgrading to latest preunified chart (1.6.0) and app version (6.19.0) and see it works

**Comment by chukka** [comment]
@EvanMAmstutz I'm marking this issue as closed feel free to reopen if its still an issue
