### ISSUE TITLE
ConfigMaps for security.import.xml and artifactory.config.import.xml can't copy

### ISSUE THREAD

**Issue by sylus** [jfrog/charts#85]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug

**Version of Helm and Kubernetes**:

K8S: v1.10.6
Helm: v2.9.1

**Which chart**: Artifactory 7.6.1

**What happened**: ConfigMaps for security.import.xml and artifactory.config.import.xml can't copy.

```sh
  Type     Reason                  Age                From                                Message
  ----     ------                  ----               ----                                -------
  Normal   SuccessfulMountVolume   1m                 kubelet, k8s-linuxpool1-16822035-0  MountVolume.SetUp succeeded for volume "artifactory-license"
  Normal   SuccessfulMountVolume   1m                 kubelet, k8s-linuxpool1-16822035-0  MountVolume.SetUp succeeded for volume "bootstrap-config"
  Normal   Scheduled               1m                 default-scheduler                   Successfully assigned artifactory-artifactory-0 to k8s-linuxpool1-16822035-0
  Normal   SuccessfulMountVolume   1m                 kubelet, k8s-linuxpool1-16822035-0  MountVolume.SetUp succeeded for volume "artifactory-artifactory-token-27wwz"
  Normal   SuccessfulAttachVolume  1m                 attachdetach-controller             AttachVolume.Attach succeeded for volume "pvc-2d274fb1-d020-11e8-8166-000d3a4e189f"
  Normal   SuccessfulMountVolume   50s                kubelet, k8s-linuxpool1-16822035-0  MountVolume.SetUp succeeded for volume "pvc-2d274fb1-d020-11e8-8166-000d3a4e189f"
  Normal   Pulling                 49s                kubelet, k8s-linuxpool1-16822035-0  pulling image "alpine:3.6"
  Normal   Pulled                  49s                kubelet, k8s-linuxpool1-16822035-0  Successfully pulled image "alpine:3.6"
  Normal   Pulled                  48s                kubelet, k8s-linuxpool1-16822035-0  Successfully pulled image "alpine:3.6"
  Normal   Created                 48s                kubelet, k8s-linuxpool1-16822035-0  Created container
  Normal   Started                 48s                kubelet, k8s-linuxpool1-16822035-0  Started container
  Normal   Pulling                 48s                kubelet, k8s-linuxpool1-16822035-0  pulling image "alpine:3.6"
  Normal   Created                 47s                kubelet, k8s-linuxpool1-16822035-0  Created container
  Normal   Started                 47s                kubelet, k8s-linuxpool1-16822035-0  Started container
  Normal   Pulling                 11s (x2 over 47s)  kubelet, k8s-linuxpool1-16822035-0  pulling image "docker.bintray.io/jfrog/artifactory-pro:6.5.0"
  Normal   Killing                 11s                kubelet, k8s-linuxpool1-16822035-0  Killing container with id docker://artifactory:FailedPostStartHook
  Normal   Pulled                  10s (x2 over 46s)  kubelet, k8s-linuxpool1-16822035-0  Successfully pulled image "docker.bintray.io/jfrog/artifactory-pro:6.5.0"
  Normal   Created                 10s (x2 over 46s)  kubelet, k8s-linuxpool1-16822035-0  Created container
  Normal   Started                 10s (x2 over 46s)  kubelet, k8s-linuxpool1-16822035-0  Started container
  Warning  FailedPostStartHook     10s (x2 over 46s)  kubelet, k8s-linuxpool1-16822035-0  Exec lifecycle hook ([/bin/sh -c cp -Lrf /bootstrap/* /artifactory_extra_conf/;
]) for Container "artifactory" in Pod "artifactory-artifactory-0_monitoring(da526df6-d028-11e8-8166-000d3a4e189f)" failed - error: command '/bin/sh -c cp -Lrf /bootstrap/* /artifactory_extra_conf/;
' exited with 1: cp: cannot create regular file '/artifactory_extra_conf/artifactory.config.import.xml': Permission denied
cp: cannot create regular file '/artifactory_extra_conf/security.import.xml': Permission denied
, message: "cp: cannot create regular file '/artifactory_extra_conf/artifactory.config.import.xml': Permission denied\ncp: cannot create regular file '/artifactory_extra_conf/security.import.xml': Permission denied\n"
```

**What you expected to happen**: The copy to be successful.

**How to reproduce it** (as minimally and precisely as possible): Simply try to add in a custom configmap.

**Anything else we need to know**: N/A

**Comment by sylus** [comment]
@jainishshah17

**Comment by jainishshah17** [comment]
@sylus Can you provide details about storage. Are you using NFS/GCPersistentDisk/EBS?
Is this GKE/AKS/EKS?

**Comment by sylus** [comment]
Hey @jainishshah17 I am using Azure Disk on ACS Engine Kubernetes 1.11.3

**Comment by jainishshah17** [comment]
@sylus I found issue `artifactory_extra_conf` is not owned by artifactory user its owned by root. We will have to add some logic in entrypoint.sh to check and fix permission.

**Comment by sylus** [comment]
Ah great @jainishshah17 , would it help if i filed an official support ticket?

**Comment by eldada** [comment]
@sylus - no need. We are already working on a fix to this, so it will be included in one of the coming Artifactory releases.

**Comment by sylus** [comment]
Just seeing if there is any push on this as it is a blocking me from moving to a production cluster.

**Comment by jainishshah17** [comment]
@eldada Whats ETA for this?

**Comment by sylus** [comment]
@jainishshah17 think it makes sense if I grab the dockerfile template and just override it to support this? Is there a public repo where the docker templates exist? (right now I just exec into container and grab)

**Comment by jainishshah17** [comment]
@sylus Our dockerfiles are not public yet.

**Comment by 1aziz** [comment]
Is there any other temporary way to achieve this and copy configs, until the next release comes?

**Comment by jainishshah17** [comment]
@sylus @1aziz One alternative is to directly mount files to `artifactory_extra_conf `.

**Comment by nsabernierdev1** [comment]
also waiting for this fix

**Comment by eldada** [comment]
A new version of Artifactory is due to be released in the coming days. Will update and verify and update here once released.

**Comment by eldada** [comment]
Artifactory 6.6.X now released. @wilrnh , @nsabernierdev1 , @1aziz , @sylus - can you all test and see if this is resolved for you with latest chart?

**Comment by 1aziz** [comment]
> Artifactory 6.6.X now released. @wilrnh , @nsabernierdev1 , @1aziz , @sylus - can you all test and see if this is resolved for you with latest chart?

Unfortunately, not solved yet. I'm using the version 6.6.5 (PRO) and still have the same issue.

**Comment by eldada** [comment]
@1aziz - can you help with more details?
I just tried this with the latest Artifactory version and it worked as expected.
- Created a configMap with an xml
- Deploy Artifactory chart with passing `--set artifactory.configMapName=my-release-bootstrap-config`
Artifactory came up properly.

**Comment by 1aziz** [comment]
@eldada, the problem was from my side, apologies. I was trying it with **helm upgrade**, while the configs only get copied if the Artifactory instance gets re-deployed. 
I now confirm that the solution does work. Thanks for the release.

**Comment by eldada** [comment]
Thx for the quick confirmation!

**Comment by sylus** [comment]
Thanks amazing folks! :D
