### ISSUE TITLE
Common volume for router and other components in Xray chart

### ISSUE THREAD

**Issue by akashpatel567** [jfrog/charts#855]
Can we have a common volume option in the chart for router and other components for TLS certs update (DB and HTTPS connection).
As router and other components have different mount path. So, basically 2 common volume mount options to fix this issue.

We have a secret with bunch of cert files which we want to put in a location accessible to router and other components.

**Comment by chukka** [comment]
@akashpatel567  Can you please elaborate this feature request  with an example , Also update  xray chart version  you are currently using ?

**Comment by chukka** [comment]
@akashpatel567  I'm marking this as closed , Please feel to reopen /open a new feature request
