### ISSUE TITLE
[Mission control] add suppot of creating users/schema's when using external Database

### ISSUE THREAD

**Issue by mhamaydeh** [jfrog/charts#866]
**Is this a request for help?**:yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):FEATURE REQUEST

**Version of Helm and Kubernetes**:

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.32", GitCommit:"f93c8851c566b682af18a7323472d2ef685176da", GitTreeState:"clean", BuildDate:"2020-03-07T00:38:31Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:

version: 3.1.1
appVersion: 4.2.0

**What happened**:

when using external database , you need to create the schemas and users manually  . 
it will be great if that will be part of the chart  regardless if using Database  Internal or External 

**What you expected to happen**:
creation of  SQL users and schemas part of the chart  regardless if using  Internal or External  database 

**How to reproduce it** (as minimally and precisely as possible):
set up the chart with external database 

**Anything else we need to know**:

**Comment by erick-duran** [comment]
Thanks for posting this, we also ran into the same error when trying to deploy with an external DB, creating the users/schemas manually fixed the issue. We are also interested in this feature.

**Comment by mhamaydeh** [comment]
@erick-duran  tweak the chart to execute the database script in the statefulset init .

**Comment by chukka** [comment]
@mhamaydeh @erick-duran  This PR #1084 fix this issue

**Comment by erick-duran** [comment]
Thanks for the update @chukka.
