### ISSUE TITLE
artifactory-ha failure with customVolumes and customVolumesMounts

### ISSUE THREAD

**Issue by jmcfallargo** [jfrog/charts#895]
I started with a version of Artifactory that I deployed using the Helm chart about a year ago.  I took that configuration and began to try to deploy using the latest version and have hit multiple issues.

I took the example in the documentation for customVolumes, mounts, and copyOnEveryStartup from the documentation at : https://hub.helm.sh/charts/jfrog/artifactory-ha/2.4.6

Created a custom values.yaml using the example from the docs:

artifactory:
  ## Create a volume pointing to the config map with your configuration file
  customVolumes: |
    - name: logback-xml-configmap
      configMap:
        name: logback-xml-configmap
  customVolumeMounts: |
    - name: logback-xml-configmap
      mountPath: /tmp/artifactory-logback/
  copyOnEveryStartup:
    - source: /tmp/artifactory-logback/*
      target: etc/

Ran the helm command with debug enabled 
helm upgrade --install artifactory-ha --namespace artifactory-ha jfrog/artifactory-ha -f values.yaml --debug

`Error: YAML parse error on artifactory-ha/templates/artifactory-node-statefulset.yaml: error converting YAML to JSON: yaml: line 263: mapping values are not allowed in this context
helm.go:84: [debug] error converting YAML to JSON: yaml: line 263: mapping values are not allowed in this context
YAML parse error on artifactory-ha/templates/artifactory-node-statefulset.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
        /home/circleci/helm.sh/helm/pkg/releaseutil/manifest_sorter.go:146
helm.sh/helm/v3/pkg/releaseutil.SortManifests
        /home/circleci/helm.sh/helm/pkg/releaseutil/manifest_sorter.go:106
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
        /home/circleci/helm.sh/helm/pkg/action/action.go:159
helm.sh/helm/v3/pkg/action.(*Install).Run
        /home/circleci/helm.sh/helm/pkg/action/install.go:238
main.runInstall
        /home/circleci/helm.sh/helm/cmd/helm/install.go:229
main.newUpgradeCmd.func1
        /home/circleci/helm.sh/helm/cmd/helm/upgrade.go:104
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:83
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1357`

**Version of Helm and Kubernetes**:
Helm: v3.2.1
Kubernetes: 1.15.11-gke.12

**Which chart**:
jfrog/artifactory-ha

**What happened**:
Following the example, the helm deployment fails.
If I modify the Yaml from the example to remove the "Artifactory" - the helm install completes, but the custom volumes and mounts are missing.
Using this Yaml

  customVolumes: |
    - name: logback-xml-configmap
      configMap:
        name: logback-xml-configmap
  customVolumeMounts: |
    - name: logback-xml-configmap
      mountPath: /tmp/artifactory-logback/
  copyOnEveryStartup:
    - source: /tmp/artifactory-logback/*
      target: etc/

**What you expected to happen**:
I expect to be able to create customVolumeMounts and Volumes via a custom values.yml

**How to reproduce it** (as minimally and precisely as possible):
Follow the example in the documentation

**Anything else we need to know**:
I have tried multiple versions going back to version 1.2.4 without success.

**Comment by jmcfallargo** [comment]
Looks closely related to: https://github.com/jfrog/charts/issues/759

**Comment by chukka** [comment]
@jmcfallargo  can you share the values.yaml  (with customVolumes ) just to reproduce at my end .Looks like you are upgrading from previous chart version-Pls share previous chart version .  Also can you try installing a fresh (not upgrade and see it works)

**Comment by evannorstrand** [comment]
@chukka - this issue has been thoroughly documented in 759. The **FIX** has been defined. The regression just needs to be resolved.

**Comment by chukka** [comment]
@evannorstrand  #759 is not related to artifactory BTW, @jmcfallargo  If you are still facing  this issue , try latest chart `2.5.0` and share feddback

**Comment by chukka** [comment]
@evannorstrand  I'm marking this issue as closed, Feel free to reopen if you face any upgrade issues
