### ISSUE TITLE
[Proposal] Provide different values for small (default), medium & large deployments

### ISSUE THREAD

**Issue by ankushchadha** [jfrog/charts#9]
**What**
Ship 3 flavors of values.yaml so that a user (dev, SML customer) can pick the flavor of the file that's more relevant and is only exposed to a very minimum set of properties that they have to modify, versus the entire set. There is no need for the user to touch the main `values.yaml` file and instead they should only be modifying the relevant file that includes a very minimum set. And then pass the modular file via  -f custom-values-file option.
 

**Why**
Having a single `values.yaml` is too much especially for customers who are new to helm. Relevant details such compute, secret names are missed because they are hidden among 100s of key-value pairs. Plus these values are not optimized for their use case. Example: For a customer that runs 300 concurrent builds with 1GB payload, the default compute values are not enough. Or in case of Xray, the memory assigned to MongoDB should be atleast 6GB for staging and maybe 12GB for production. This would enhance the UX for our customers and even reduce the readme size.

**Comment by eldada** [comment]
I like it. Propose a pull request for one of the charts as an example and we'll use it as a discussion thread.

**Comment by ankushchadha** [comment]
Yes, @rimusz came up with this solution during our discussion with support about the pain points. We will start with a simpler chart (artifactory pro) and then expand it to other charts. That's a good idea.

**Comment by nimerb** [comment]
@eldada, @rimusz and @ankushchadha, we should consider adding the option of different values.yaml for staging and production use suggestion.

**Comment by rimusz** [comment]
we should have override files for staging and production which have only compute resources and maybe some other tweaks, no needs to duplicate the whole `values.yam` there, it would make harder to maintain.
