### ISSUE TITLE
Cannot docker push to an almost vanilla installation.

### ISSUE THREAD

**Issue by AlessandroEmm** [jfrog/charts#908]
**Is this a request for help?**:

yes

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Could be either. 

**Version of Helm and Kubernetes**:

Helm v3.1.2, OpenShift 4.3

**Which chart**:

jfrog/artifactory

**What happened**:

Cannot push to docker registry with the error (in the artifactory log) *Unsupported docker v2 repository request for xxxx* where xxx is the actual image name.

**What you expected to happen**:

The Push to work, docker login has worked but pushing results in
`65c62053e519: Retrying in 1 second 
771f555be0f4: Retrying in 1 second 
6a7fa7cf8c86: Retrying in 1 second 
133cd970782e: Retrying in 1 second 
15421e93d379: Retrying in 1 second 
0f68577f0b47: Waiting 
2218b66de68f: Waiting 
d2db7f1db0b6: Waiting 
e11909b739a8: Waiting 
e1c9043c84f5: Waiting 
d0828edd7233: Waiting 
unknown: Not Found`

**How to reproduce it** (as minimally and precisely as possible):

Installed via Helmchart without any further vars configured; replaced the ingress resource with a route to the nginx service.

**Anything else we need to know**:

From other issues here I guess the issue may be with generating the Nginx configuration.

**Comment by AlessandroEmm** [comment]
Nevermind, actually i was missing the repository key in the path. I was used to operate it with a reverse proxy and hence assumed to must be on the root path. Sorry for disturbing.

**Comment by chukka** [comment]
Closing this issue
