### ISSUE TITLE
helm chart has missing steps for configuring Artifactory with oracle

### ISSUE THREAD

**Issue by pavanvikas** [jfrog/charts#918]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):FEATURE REQUEST

**Version of Helm and Kubernetes**:
Kubernetes 1.12+

**Which chart**:

**What happened**:
As part of configuring Artifactory to use oracle, we need to install libaio Library and modify the system.yaml file accordingly. For detailed steps, please refer below JFrog wiki link:
https://www.jfrog.com/confluence/display/JFROG/Oracle#Oracle-ConfiguringArtifactorytouseOracle

**What you expected to happen**:
Helm chart documentation should have the steps to follow while configuring Artifactory with oracle.

**How to reproduce it** (as minimally and precisely as possible):
Please try to install Artifactory helm chart and integrate with oracle db, in metadata server log we could observe below error:

2020-05-27T11:16:32.7Z [jfmd ] [PANIC]][database_bearer.go:55         ] [main] - Could not initialize database (db config:<DB-HOST-Name>:<PORT-Number>}):
ORA-00000: DPI-1047: Cannot locate a 64-bit Oracle Client library: "libclntsh.so: cannot open shared object file: No such file or directory". See https://oracle.github.io/odpi/doc/installation.html#linux for help
error connecting to database. giving up
jfrog.com/metadata/services/common/db.(*databaseBearer).init
	/src/jfrog.com/metadata/services/common/db/database_bearer.go:91
jfrog.com/metadata/services/common/db.NewDatabaseBearer
	/src/jfrog.com/metadata/services/common/db/database_bearer.go:53
.....
**Anything else we need to know**:

**Comment by rahulsadanandan** [comment]
@pavanvikas 
can you try out with the below commands, you will have to download the oracle client library files, libaio and extract them to tomcat lib folder. Also it is important to set LD_LIBRARY_PATH env variable.
```bash
helm3 upgrade --install artifactory \
--set postgresql.enabled=false \
--set artifactory.preStartCommand="mkdir -p /opt/jfrog/artifactory/var/bootstrap/artifactory/tomcat/lib; cd /opt/jfrog/artifactory/var/bootstrap/artifactory/tomcat/lib && wget -O instantclient-basic-linux.x64-19.6.0.0.0dbru.zip https://download.oracle.com/otn_software/linux/instantclient/19600/instantclient-basic-linux.x64-19.6.0.0.0dbru.zip && unzip -jn instantclient-basic-linux.x64-19.6.0.0.0dbru.zip && wget -O libaio1_0.3.110-3_amd64.deb http://ftp.br.debian.org/debian/pool/main/liba/libaio/libaio1_0.3.110-3_amd64.deb &&  dpkg-deb -x libaio1_0.3.110-3_amd64.deb . && cp lib/x86_64-linux-gnu/* ." \
--set database.type=oracle \
--set database.driver=oracle.jdbc.OracleDriver \
--set database.url=${DB_URL} \
--set database.user=${DB_USER} \
--set database.password=${DB_PASSWORD} \
--set artifactory.extraEnvironmentVariables\[0\].name=LD_LIBRARY_PATH \
--set artifactory.extraEnvironmentVariables\[0\].value=/opt/jfrog/artifactory/var/bootstrap/artifactory/tomcat/lib \
--namespace art jfrog/artifactory
```

I have tested with oracle 12c.
