### ISSUE TITLE
Deployment of OSS Chart fails due to "Readiness probe failed"

### ISSUE THREAD

**Issue by egulatee** [jfrog/charts#961]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
`helm version
`

`version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
`

`kubectl version
`

`Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
`

**Which chart**:

`artifactory              	artifactory	1       	2020-06-19 20:14:56.288021 -0400 EDT	deployed	artifactory-oss-2.3.1	7.5.7      
`

**What happened**:
`Events:
  Type     Reason     Age                 From               Message
  ----     ------     ----                ----               -------
  Normal   Scheduled  <unknown>           default-scheduler  Successfully assigned artifactory/artifactory-artifactory-0 to nuc9036
  Normal   Pulled     11m                 kubelet, nuc9036   Container image "alpine:3.11" already present on machine
  Normal   Created    11m                 kubelet, nuc9036   Created container delete-db-properties
  Normal   Started    11m                 kubelet, nuc9036   Started container delete-db-properties
  Normal   Started    11m                 kubelet, nuc9036   Started container remove-lost-found
  Normal   Created    11m                 kubelet, nuc9036   Created container remove-lost-found
  Normal   Pulled     11m                 kubelet, nuc9036   Container image "alpine:3.11" already present on machine
  Normal   Pulled     11m                 kubelet, nuc9036   Container image "alpine:3.11" already present on machine
  Normal   Created    11m                 kubelet, nuc9036   Created container copy-system-yaml
  Normal   Started    11m                 kubelet, nuc9036   Started container copy-system-yaml
  Normal   Started    11m                 kubelet, nuc9036   Started container wait-for-db
  Normal   Created    11m                 kubelet, nuc9036   Created container wait-for-db
  Normal   Pulled     11m                 kubelet, nuc9036   Container image "alpine:3.11" already present on machine
  Normal   Pulled     11m                 kubelet, nuc9036   Container image "docker.bintray.io/jfrog/artifactory-oss:7.5.7" already present on machine
  Normal   Created    11m                 kubelet, nuc9036   Created container migration-artifactory
  Normal   Started    11m                 kubelet, nuc9036   Started container migration-artifactory
  Normal   Pulled     11m                 kubelet, nuc9036   Container image "docker.bintray.io/jfrog/artifactory-oss:7.5.7" already present on machine
  Normal   Created    11m                 kubelet, nuc9036   Created container artifactory
  Normal   Started    11m                 kubelet, nuc9036   Started container artifactory
  Warning  Unhealthy  52s (x45 over 10m)  kubelet, nuc9036   Readiness probe failed: Get http://10.233.112.32:8082/router/api/v1/system/health: dial tcp 10.233.112.32:8082: connect: connection refused
`

`
NAMESPACE        NAME                                                READY   STATUS             RESTARTS   AGE
artifactory      artifactory-artifactory-0                           0/1     Running            2          12m
artifactory      artifactory-artifactory-nginx-fc6ccccff-fpqtx       0/1     CrashLoopBackOff   9          26m
artifactory      artifactory-postgresql-0                            1/1     Running            0          26m
`

**What you expected to happen**:

The artifactory (non oss) Chart does complete and bring up Artifactory.

**How to reproduce it** (as minimally and precisely as possible):
`
helm repo add jfrog https://charts.jfrog.io
kubectl create ns artifactory
helm upgrade --install artifactory --namespace artifactory jfrog/artifactory-oss
`

**Anything else we need to know**:
`
kubectl get pvc -A
NAMESPACE     NAME                                           STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
artifactory   artifactory-volume-artifactory-artifactory-0   Bound    pvc-c113a404-75cb-4823-bb88-04f3aa1ca221   20Gi       RWO            rook-ceph-block   41m
artifactory   data-artifactory-postgresql-0                  Bound    pvc-c2157ac1-e701-4c4a-a86b-92a8fa934bc9   50Gi       RWO            rook-ceph-block   41m
harbor
`

**Comment by chukka** [comment]
@egulatee Can you please share reproducible steps  ? is this on fresh install ?

**Comment by chukka** [comment]
@egulatee Following up on the reproducible steps !

**Comment by egulatee** [comment]
@chukka 
The steps are as follows:

`helm repo add jfrog https://charts.jfrog.io kubectl create ns artifactory helm upgrade --install artifactory --namespace artifactory jfrog/artifactory-oss
`

**Comment by chukka** [comment]
Thanks
