### ISSUE TITLE
Add support of specifying resources for initContainers in nginx deployment and Artifactory statefulset

### ISSUE THREAD

**Issue by pedromctech** [jfrog/charts#962]
**Is this a request for help?**:

No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

**Version of Helm and Kubernetes**:

Kubernetes v1.16.8
Helm v3.2.3

**Which chart**:

Artifactory Version 9.5.3

**What happened**:

When a `ResourceQuota` is configured in the namespace, pods are not deployed because resources requests and limits must be specified.

**What you expected to happen**:

To be able to configure resources request and limits for init containers through `values.yaml` file.

**How to reproduce it** (as minimally and precisely as possible):

Configure a `ResourceQuota` with CPU and memory request and limits and install the Helm Chart.

**Anything else we need to know**:

**Comment by DasJayYa** [comment]
Looking at the other InitContainers, they are using the init resource but for the Nginx Deployment.

`        resources:
{{ toYaml .Values.initContainers.resources | indent 10 }}`
