### ISSUE TITLE
OSS deployment fails due to failing Readiness Probe

### ISSUE THREAD

**Issue by rgbrizzlehizzle** [jfrog/charts#97]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug

**Version of Helm and Kubernetes**: 2.11.0 and 1.9.7-gke.6

**Which chart**: jfrog/artifactory

**What happened**: 

When attempting to pass in the custom docker image to use artifactory oss, the Readiness Probe fails repeatedly due to a 404

I initially launched this chart with the default settings other than switching docker image to oss

`helm install --set artifactory.image.repository="docker.bintray.io/jfrog/artifactory-oss" jfrog/artifactory`

at which point I looked at the pod details and saw 

> Warning  Unhealthy 3m17s (x2 over 3m26s)  kubelet, gke-prod-cluster-default-pool  Readiness probe failed: HTTP probe failed with statuscode: 404

Wanting to dive a little deeper before passing the issue over to you guys, I then turned off the readiness probe, launched the service and port forwarded the pod's 8081 port to my localhost and was able to hit the base port, at which point it looks like artifactory attempts to forward my request to /artifactory which in turn also results in a 404

**What you expected to happen**: Readiness probe to succeed

**How to reproduce it** (as minimally and precisely as possible): 

`helm install --set artifactory.image.repository="docker.bintray.io/jfrog/artifactory-oss" jfrog/artifactory`

**Comment by jainishshah17** [comment]
@rgbrizzlehizzle Can you provide more details about your K8S environment?

**Comment by eldada** [comment]
@rgbrizzlehizzle - is this still happening? If not, can you close this?
