### ISSUE TITLE
Artifactory installs one container as opposed to the several listed in the system architecture diagram

### ISSUE THREAD

**Issue by chook** [jfrog/charts#983]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature Request

**Version of Helm and Kubernetes**:
```
$ helm version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}`

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:41:00Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.36", GitCommit:"34a615f32e9a0c9e97cdb9f749adb392758349a6", GitTreeState:"clean", BuildDate:"2020-04-06T16:33:17Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

```
**Which chart**: artifactory 

**What happened**: As opposed to xray/mission control, where the pod contains several containers, it seems artifactory brings 2 pods (artifactory / artifactory-nginx) where the artifactory-artifactory-0 pod contains only 1 container, the artifactory server. 

**What you expected to happen**: I expect the pod to contains all services (UI, router, access, MDS, event) as described in https://www.jfrog.com/confluence/display/JFROG/System+Architecture

**How to reproduce it** (as minimally and precisely as possible): Install artifactory using helm 

**Anything else we need to know**: no

**Comment by eldada** [comment]
Hi @chook . Your observation is correct. This was a deliberate decision mostly for simplicity and backward compatibility for users of the Artifactory Docker image (which is very popular).
We are looking into adding (optional) support for deploying as separate containers for K8s. This is still under a general idea. The benefits for separate containers are great, but business continuity and backward compatibility are very important in this case.
I hope this answers your question.

**Comment by chook** [comment]
It does! thanks for the quick and verbose response!
