### ISSUE TITLE
[artifactory-ha] chart for user defined plugins does not seem to work with artifactory 7

### ISSUE THREAD

**Issue by kpirateone** [jfrog/charts#985]
**Is this a request for help?**:
yes?
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT 

**Version of Helm and Kubernetes**:
Helm 3 / Kubernetes v1.16

**Which chart**:
Artifactory HA

**What happened**:
user defined plugins via configuration by .Values.artifactory.userPluginSecrets does not load plugin in artifactory 7.  The chart creates the secret.  The secret is mounted and files are copied from the mount point to /tmp/plugins via the helm created deployments.  However it seems like the Artifactory 7 /entrypoint-artifactory.sh script does not load plugins from this location.

**What you expected to happen**:
i expected to have defined plugin loaded.  when using Artifactory 6 and associated chart, the chart does a similar process in crating the secret and copying plugin files to /tmp/plugins.   The Artifactory 6 /entrypoint-artifactory.sh has specific code to pull the plugins from the /tmp/plugins location and copy it to the correct location to load the plugins.  It's as if the plugin support in the chart has not been modified to work with Artifactory 7 which no longer loads plugins from /tmp/plugins.

**How to reproduce it** (as minimally and precisely as possible):
configure a userPluginSecret as described in the chart README.  run Artifactory-HA

**Anything else we need to know**:

**Comment by chukka** [comment]
@kpirateone Thanks for reporting . Can you please provide with reproducible steps (helm commands used - will help)

**Comment by kpirateone** [comment]
we set the user plugin secret in the chart values

```
  ## List of secrets for Artifactory user plugins.
  ## One Secret per plugin's files.
  userPluginSecrets:
    - devx-repo-plugin
```

and run a `helm template` followed by a `kubectl apply -f <template target dir>`
