### ISSUE TITLE
[Distribution]  Cloud Memorystore instead of Redis in Kubernetes

### ISSUE THREAD

**Issue by mhamaydeh** [jfrog/charts#987]
**Is this a request for help?**: YES
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**:
Helm:
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

Kubernetes:

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.37", GitCommit:"34a615f32e9a0c9e97cdb9f749adb392758349a6", GitTreeState:"clean", BuildDate:"2020-04-10T21:17:01Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
distribution
version: 5.1.3
appVersion: 2.2.0

**What happened**:

In the current chart , Redis will be deployed  in Kubernetes . and we need to use  Cloud Memorystore instead .

**What you expected to happen**:

To be able to provide the Cloud Memorystore connection instead of deploying it Kubernetes .

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by mhamaydeh** [comment]
I have got an answer from Jfrog that it is not supported to replace Redis at this point , 
but the helm chart is pointing to a depreciated version of Redis .

**Comment by chukka** [comment]
@mhamaydeh we are planning to update redis to latest `6.0.5` in the coming release

**Comment by chukka** [comment]
@mhamaydeh  can you please mark this issue as closed ?

**Comment by mhamaydeh** [comment]
@chukka  Thank you
