### ISSUE TITLE
Tomcat artifactory.access.client.max.connections

### ISSUE THREAD

**Issue by bo-tu** [jfrog/charts#993]
**Sorry if this feature already exists, I think the way this was managed has changed in Artifactory 7.x**

**Is this a request for help?:**
Yes

This is a
**Feature Request**

I would like to be able to update the Tomcat values for **artifactory.access.client.max.connections**.

As recommended in this document: https://jfrog.com/knowledge-base/how-do-i-tune-artifactory-for-heavy-loads/ it needs to be tuned for heavy loads as below,

Important: When modifying the Access maxThreads, it is required to update the $JFROG_HOME/artifactory/var/etc/artifactory/artifactory.system.properties file with:
artifactory.access.client.max.connections = <VALUE>

**Which chart:**
artifactory-ha

**Comment by KierranM** [comment]
Could this potentially be implemented the same way `asyncCorePool` is currently?

i.e around [here](https://github.com/jfrog/charts/blob/master/stable/artifactory-ha/values.yaml#L452-L454) add something like:

```
{{- with .Values.artifactory.primary.javaOpts }}
        -Dartifactory.async.corePoolSize={{ .corePoolSize }}
{{- if .accessClientMaxConnections }}
        -Dartifactory.access.client.max.connections={{ .accessClientMaxConnections }}
{{- end }}
```
